-- Leg Ulcers Article Content and MCQs
-- Article ID: bc19fc77-d567-4ab9-9ec8-8f3aadaaa387

INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 'introduction', 1, 'Introduction', 'Leg ulcers are chronic wounds of the lower extremity that fail to heal within expected timeframes. They represent a significant healthcare burden. Main types: Venous (70%), Arterial (10-15%), Mixed (10-15%), Diabetic/neuropathic, and other causes. Accurate diagnosis of etiology is essential for appropriate management.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 'content', 2, 'Types and Characteristics', 'VENOUS ULCERS: Location - medial malleolus (gaiter area). Shallow, irregular margins, granulating base, moderate exudate. Associated signs: varicose veins, hemosiderin staining, lipodermatosclerosis, edema. ABI >0.8. ARTERIAL ULCERS: Location - toes, heel, pressure points. Deep, punched-out margins, pale/necrotic base, minimal exudate. Associated: absent pulses, cold limb, claudication, rest pain. ABI <0.5. DIABETIC/NEUROPATHIC: Location - plantar surface, pressure points. Painless, surrounded by callus. Associated: loss of protective sensation, Charcot deformity.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 'content', 3, 'Assessment and ABI', 'CLINICAL ASSESSMENT: History (duration, pain, comorbidities), Location and appearance, Pulse examination, Sensory testing. ANKLE-BRACHIAL INDEX (ABI): Ratio of ankle to brachial systolic BP. >0.9 Normal, 0.8-0.9 Mild PAD, 0.5-0.8 Moderate PAD, <0.5 Severe PAD. Interpretation: ABI >0.8 = safe for compression. ABI <0.5 = likely arterial ulcer, refer vascular. ABI >1.3 = falsely elevated (calcified vessels in diabetes).'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 'content', 4, 'Management', 'VENOUS ULCERS: Compression therapy (gold standard) - multilayer bandaging 40mmHg at ankle. Leg elevation. Wound care with appropriate dressings. Treat underlying venous disease. ARTERIAL ULCERS: Revascularization (angioplasty/bypass) is definitive. No compression. Wound care, pain management. DIABETIC ULCERS: Offloading (total contact cast), Debridement, Infection control, Optimize glycemic control. GENERAL: Debridement of devitalized tissue, Moist wound healing, Treat infection if present.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 'key_points', 5, 'Key Points', '1. Venous ulcers are most common (70%). 2. Venous ulcers occur at medial malleolus. 3. Arterial ulcers occur at toes/heel with punched-out margins. 4. ABI <0.5 suggests arterial disease. 5. ABI >0.8 allows compression therapy. 6. Compression is gold standard for venous ulcers. 7. Compression contraindicated in arterial disease. 8. Diabetic ulcers need offloading and debridement. 9. ABI >1.3 may be falsely elevated. 10. Treat underlying cause for definitive healing.');

-- Leg Ulcers Self-Assessment Questions
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 1, 'Most common type of leg ulcer is:', 'Arterial', 'Venous', 'Diabetic', 'Traumatic', 'Malignant', 'B', 'Venous ulcers account for 70% of leg ulcers.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 2, 'Venous ulcers typically occur at:', 'Toes', 'Heel', 'Medial malleolus', 'Dorsum of foot', 'Plantar surface', 'C', 'Venous ulcers occur at medial malleolus (gaiter area).'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 3, 'Arterial ulcer characteristics include:', 'Shallow with granulation', 'Deep with punched-out margins', 'Painless with callus', 'Located at medial malleolus', 'Heavy exudate', 'B', 'Arterial ulcers are deep with punched-out margins.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 4, 'Normal ABI is:', '>0.9', '0.5-0.8', '<0.5', '0.3-0.5', '<0.3', 'A', 'Normal ABI is greater than 0.9.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 5, 'ABI safe for compression therapy is:', '>0.8', '<0.5', '<0.3', '>1.5', '0.3-0.5', 'A', 'ABI >0.8 is safe for compression.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 6, 'Gold standard treatment for venous ulcers:', 'Revascularization', 'Compression therapy', 'Antibiotics', 'Skin grafting', 'Amputation', 'B', 'Compression therapy is gold standard for venous ulcers.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 7, 'Compression is contraindicated when ABI is:', '>0.9', '>0.8', '<0.5', '>1.0', '0.8-0.9', 'C', 'Compression contraindicated when ABI <0.5 (arterial disease).'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 8, 'Hemosiderin staining is associated with:', 'Arterial ulcers', 'Venous ulcers', 'Diabetic ulcers', 'Pressure ulcers', 'Malignant ulcers', 'B', 'Hemosiderin staining is a sign of chronic venous insufficiency.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 9, 'Diabetic ulcer key treatment is:', 'Compression', 'Offloading', 'Elevation only', 'Heat therapy', 'Massage', 'B', 'Diabetic ulcers require offloading (total contact cast).'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 10, 'ABI >1.3 suggests:', 'Normal circulation', 'Severe PAD', 'Falsely elevated due to calcification', 'Venous disease', 'Neuropathy', 'C', 'ABI >1.3 is falsely elevated due to calcified vessels.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 11, 'Rest pain suggests:', 'Venous disease', 'Severe arterial disease', 'Neuropathy', 'Infection', 'Lymphedema', 'B', 'Rest pain is a sign of severe arterial disease.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 12, 'Lipodermatosclerosis is associated with:', 'Arterial ulcers', 'Venous ulcers', 'Diabetic ulcers', 'Pressure ulcers', 'Traumatic ulcers', 'B', 'Lipodermatosclerosis is fibrosis from chronic venous insufficiency.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 13, 'Arterial ulcer definitive treatment is:', 'Compression', 'Revascularization', 'Elevation', 'Dressings only', 'Antibiotics', 'B', 'Revascularization is definitive for arterial ulcers.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 14, 'Compression bandage pressure at ankle:', '10 mmHg', '20 mmHg', '40 mmHg', '60 mmHg', '80 mmHg', 'C', 'Compression therapy provides about 40 mmHg at ankle.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 15, 'Neuropathic ulcers are typically:', 'Very painful', 'Painless', 'Located at malleolus', 'Associated with edema', 'Deep to bone', 'B', 'Neuropathic ulcers are painless due to sensory loss.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 16, 'Charcot joint is associated with:', 'Venous disease', 'Arterial disease', 'Diabetic neuropathy', 'Rheumatoid arthritis', 'Gout', 'C', 'Charcot joint is a complication of diabetic neuropathy.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 17, 'Claudication indicates:', 'Venous insufficiency', 'Peripheral arterial disease', 'DVT', 'Cellulitis', 'Lymphedema', 'B', 'Claudication is pain on walking from PAD.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 18, 'Moist wound healing is:', 'Outdated concept', 'Promotes faster healing', 'Increases infection', 'Only for burns', 'Contraindicated in ulcers', 'B', 'Moist wound healing promotes epithelialization.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 19, 'Total contact cast is used for:', 'Venous ulcers', 'Arterial ulcers', 'Diabetic plantar ulcers', 'Pressure ulcers', 'Burn wounds', 'C', 'TCC provides offloading for diabetic plantar ulcers.'),
('bc19fc77-d567-4ab9-9ec8-8f3aadaaa387'::uuid, 20, 'Mixed ulcer with ABI 0.6 should:', 'Receive full compression', 'Receive modified compression with vascular referral', 'Have no compression', 'Be amputated', 'Receive antibiotics only', 'B', 'ABI 0.6 allows modified compression with vascular input.');
