-- Intraoperative Monitoring Article Content and MCQs
-- Article ID: a8f44503-5bcf-4a0f-9b88-f667d94ab31e

INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 'introduction', 1, 'Introduction', 'Intraoperative monitoring ensures patient safety during anesthesia and surgery. Goals: Detect physiological derangements early, Guide anesthetic and surgical management, Prevent complications. Monitoring levels: Basic (ASA standard), Advanced (invasive hemodynamics), Specialized (neuromonitoring). The ASA mandates minimum monitoring standards.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 'content', 2, 'ASA Standard Monitors', 'OXYGENATION: Pulse oximetry (SpO2) - mandatory. Inspired oxygen analyzer (FiO2). Adequate lighting to assess color. VENTILATION: Capnography (ETCO2) - mandatory for GA with ETT. Observation of chest rise. Disconnect alarm on ventilator. CIRCULATION: Continuous ECG - mandatory. Blood pressure every 5 minutes minimum. Heart rate (from ECG or pulse ox). TEMPERATURE: Available for all cases, measured when clinically indicated. ANESTHESIOLOGIST: Continuous presence of qualified personnel.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 'content', 3, 'Advanced Monitoring', 'ARTERIAL LINE: Continuous BP, ABG sampling. Indications: hemodynamic instability, major surgery, controlled hypotension. Sites: radial, femoral, dorsalis pedis. CENTRAL VENOUS CATHETER: CVP measurement, large volume access, vasopressor infusion. Sites: internal jugular, subclavian, femoral. Normal CVP 5-10 cmH2O. PULMONARY ARTERY CATHETER: Cardiac output, PCWP, mixed venous oxygen. Indications: severe cardiac disease, major vascular surgery. TRANSESOPHAGEAL ECHO: Real-time cardiac function, volume status.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 'content', 4, 'Specific Monitors', 'CAPNOGRAPHY (ETCO2): Normal 35-45 mmHg. Confirms ETT placement. Detects: circuit disconnection, esophageal intubation, hypoventilation, cardiac arrest (sudden drop). NEUROMUSCULAR MONITORING: Train-of-four (TOF) stimulation. Monitors muscle relaxant effect. TOF ratio >0.9 for extubation. DEPTH OF ANESTHESIA: BIS monitor (0-100 scale). Target 40-60 for general anesthesia. Prevents awareness. URINE OUTPUT: Foley catheter for long cases. Target >0.5 ml/kg/hr.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 'content', 5, 'Interpretation and Response', 'HYPOTENSION: Check depth, blood loss, cardiac function, anaphylaxis. Treat cause, consider fluids/vasopressors. HYPOXEMIA: Check ETT position, circuit, FiO2, ventilation. Consider bronchospasm, aspiration, pneumothorax. ETCO2 CHANGES: Sudden decrease - disconnection, cardiac arrest, PE. Gradual decrease - hyperventilation, hypothermia. Increase - hypoventilation, MH, CO2 absorption. ARRHYTHMIAS: Correct hypoxia, electrolytes, depth. Consider surgical stimulation.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 'key_points', 6, 'Key Points', '1. ASA mandates minimum monitoring standards. 2. Pulse oximetry is mandatory. 3. ETCO2 confirms ETT placement. 4. BP measured every 5 minutes minimum. 5. Normal ETCO2 35-45 mmHg. 6. Normal CVP 5-10 cmH2O. 7. TOF ratio >0.9 for safe extubation. 8. BIS 40-60 for adequate anesthesia depth. 9. Urine output target >0.5 ml/kg/hr. 10. Continuous qualified personnel presence required.');

-- Intraoperative Monitoring Self-Assessment Questions
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 1, 'Which monitor is mandatory for general anesthesia:', 'Arterial line', 'CVP', 'Pulse oximetry', 'BIS monitor', 'PA catheter', 'C', 'Pulse oximetry is an ASA mandatory standard.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 2, 'Normal ETCO2 range is:', '20-30 mmHg', '35-45 mmHg', '50-60 mmHg', '60-70 mmHg', '25-35 mmHg', 'B', 'Normal ETCO2 is 35-45 mmHg.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 3, 'ETCO2 confirms:', 'Adequate oxygenation', 'ETT in trachea', 'Blood pressure', 'Heart rate', 'Temperature', 'B', 'ETCO2 confirms tracheal intubation.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 4, 'Normal CVP is:', '0-3 cmH2O', '5-10 cmH2O', '15-20 cmH2O', '25-30 cmH2O', '20-25 cmH2O', 'B', 'Normal CVP is 5-10 cmH2O.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 5, 'BP should be measured every:', '1 minute', '3 minutes', '5 minutes', '10 minutes', '15 minutes', 'C', 'BP measured every 5 minutes minimum.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 6, 'TOF ratio for safe extubation is:', '>0.5', '>0.7', '>0.9', '>0.3', '>0.1', 'C', 'TOF ratio >0.9 indicates adequate reversal.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 7, 'BIS target for general anesthesia is:', '0-20', '20-40', '40-60', '60-80', '80-100', 'C', 'BIS 40-60 for adequate anesthesia depth.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 8, 'Sudden drop in ETCO2 suggests:', 'Hyperventilation', 'Circuit disconnection', 'Hypoventilation', 'Fever', 'Light anesthesia', 'B', 'Sudden ETCO2 drop suggests disconnection or cardiac arrest.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 9, 'Urine output target is:', '>0.1 ml/kg/hr', '>0.5 ml/kg/hr', '>1.0 ml/kg/hr', '>2.0 ml/kg/hr', '>0.3 ml/kg/hr', 'B', 'Target urine output >0.5 ml/kg/hr.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 10, 'Most common arterial line site:', 'Femoral', 'Brachial', 'Radial', 'Dorsalis pedis', 'Axillary', 'C', 'Radial artery is most common site.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 11, 'CVP line used for:', 'ABG sampling', 'Vasopressor infusion', 'Cardiac output', 'Oxygen measurement', 'Temperature', 'B', 'CVP line for central access and vasopressors.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 12, 'Rising ETCO2 may indicate:', 'Cardiac arrest', 'Malignant hyperthermia', 'Hypovolemia', 'Bronchospasm', 'PE', 'B', 'Rising ETCO2 suggests MH or hypoventilation.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 13, 'Train-of-four monitors:', 'Anesthesia depth', 'Neuromuscular blockade', 'Oxygenation', 'Ventilation', 'Temperature', 'B', 'TOF monitors muscle relaxant effect.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 14, 'BIS monitor prevents:', 'Hypotension', 'Hypoxia', 'Intraoperative awareness', 'Hypothermia', 'Arrhythmias', 'C', 'BIS monitors depth to prevent awareness.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 15, 'ASA mandates continuous presence of:', 'Surgeon', 'Qualified anesthesia personnel', 'Nurse', 'Perfusionist', 'Technician', 'B', 'Qualified anesthesia personnel must be continuously present.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 16, 'TEE provides information on:', 'Oxygenation', 'Cardiac function', 'Neuromuscular status', 'Temperature', 'Blood glucose', 'B', 'TEE assesses cardiac function and volume.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 17, 'Esophageal intubation shows on capnography:', 'Normal waveform', 'Absent or minimal CO2', 'High ETCO2', 'Irregular waveform', 'Slowly rising baseline', 'B', 'Esophageal intubation shows absent ETCO2.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 18, 'PA catheter measures:', 'CVP only', 'Cardiac output and PCWP', 'Arterial BP', 'SpO2', 'Urine output', 'B', 'PA catheter measures CO, PCWP, and SvO2.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 19, 'Preferred site for CVP line:', 'External jugular', 'Internal jugular', 'Subclavian', 'Femoral', 'Antecubital', 'B', 'Internal jugular is preferred site.'),
('a8f44503-5bcf-4a0f-9b88-f667d94ab31e'::uuid, 20, 'Low SpO2 with adequate ventilation suggests:', 'Normal', 'V/Q mismatch', 'Hyperventilation', 'Light anesthesia', 'Full muscle relaxation', 'B', 'Low SpO2 despite ventilation suggests V/Q mismatch or shunt.');
