-- Fracture Management Article Content and MCQs
-- Article ID: fe04f125-5e92-4ec7-99ef-998ed5092231

INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 'introduction', 1, 'Introduction', 'A fracture is a break in bone continuity. Causes: Trauma (direct/indirect), Stress (repetitive), Pathological (abnormal bone). Classification by pattern: Transverse, Oblique, Spiral, Comminuted, Segmental. By skin integrity: Closed (simple), Open (compound). Management goals: Reduce, Hold, Rehabilitate.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 'content', 2, 'Assessment', 'HISTORY: Mechanism, time, symptoms, comorbidities. EXAMINATION: Look - swelling, deformity, wounds, skin color. Feel - tenderness, crepitus, pulses, sensation. Move - active then passive, joint above and below. INVESTIGATIONS: X-ray - 2 views, joint above and below. CT - complex fractures. MRI - stress fractures, soft tissue. OPEN FRACTURE CLASSIFICATION (Gustilo-Anderson): Type I - <1cm wound. Type II - 1-10cm wound. Type IIIA - >10cm, adequate soft tissue. Type IIIB - bone exposure, requires flap. Type IIIC - vascular injury.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 'content', 3, 'Treatment Principles', 'REDUCTION: Closed - manipulation under anesthesia. Open - surgical. Acceptable alignment varies by bone/age. IMMOBILIZATION: Cast/splint, Traction (skin/skeletal), External fixation, Internal fixation (plates, screws, nails). REHABILITATION: Early mobilization, Physiotherapy, Prevent stiffness and muscle wasting. AO PRINCIPLES: 1. Anatomical reduction 2. Stable fixation 3. Preservation of blood supply 4. Early mobilization.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 'content', 4, 'Complications', 'IMMEDIATE: Vascular injury, Nerve injury, Visceral injury, Haemorrhage. EARLY: Compartment syndrome (5 Ps: Pain, Pallor, Pulselessness, Paresthesia, Paralysis), Fat embolism, DVT/PE, Infection (open fractures). LATE: Delayed union (healing slower than expected), Non-union (failure to heal - atrophic/hypertrophic), Malunion (heals in poor position), Stiffness, Complex regional pain syndrome, Avascular necrosis, Osteoarthritis.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 'content', 5, 'Fracture Healing', 'STAGES: 1. Hematoma (0-5 days) 2. Inflammation and cellular proliferation 3. Soft callus (2-3 weeks) 4. Hard callus (3-4 months) 5. Remodeling (months to years). FACTORS AFFECTING HEALING: Blood supply, Stability, Infection, Patient factors (age, nutrition, smoking, DM). TIME TO UNION: Upper limb 6-8 weeks, Lower limb 12-16 weeks. Children heal faster.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 'key_points', 6, 'Key Points', '1. X-ray: 2 views, joint above and below. 2. Open fracture is surgical emergency. 3. Gustilo IIIC has vascular injury. 4. Compartment syndrome: 5 Ps. 5. AO principles for internal fixation. 6. Soft callus forms at 2-3 weeks. 7. Non-union = failure to heal. 8. Malunion = heals in wrong position. 9. Lower limb heals in 12-16 weeks. 10. Reduce, Hold, Rehabilitate.');

-- Fracture Management Self-Assessment Questions
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 1, 'X-ray for fracture should include:', '1 view only', '2 views, same joint', '2 views, joint above and below', 'CT always', 'MRI always', 'C', 'X-ray: 2 views, joint above and below.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 2, 'Gustilo Type IIIC open fracture has:', 'Wound <1cm', 'Wound 1-10cm', 'Bone exposure needing flap', 'Vascular injury', 'No soft tissue damage', 'D', 'Type IIIC has vascular injury requiring repair.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 3, 'Compartment syndrome classic signs are:', '4 As', '5 Ps', '6 Cs', '3 Ds', '4 Fs', 'B', '5 Ps: Pain, Pallor, Pulselessness, Paresthesia, Paralysis.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 4, 'Soft callus forms at:', '0-5 days', '2-3 weeks', '3-4 months', '6 months', '1 year', 'B', 'Soft callus forms at 2-3 weeks.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 5, 'Non-union means:', 'Faster healing', 'Slower healing', 'Failure to heal', 'Heals in wrong position', 'Infection', 'C', 'Non-union is failure to heal.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 6, 'Malunion means:', 'Failure to heal', 'Slower healing', 'Heals in poor position', 'Excessive callus', 'Infection', 'C', 'Malunion is healing in poor position.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 7, 'Lower limb fracture heals in:', '2-4 weeks', '6-8 weeks', '12-16 weeks', '6 months', '1 year', 'C', 'Lower limb heals in 12-16 weeks.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 8, 'AO principles include:', 'Delayed mobilization', 'Preservation of blood supply', 'Minimal fixation', 'Non-anatomical reduction', 'External fixation only', 'B', 'AO includes preservation of blood supply.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 9, 'Open fracture is:', 'Medical emergency', 'Surgical emergency', 'Not urgent', 'Treated conservatively', 'Outpatient management', 'B', 'Open fracture is surgical emergency.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 10, 'Pathological fracture occurs in:', 'Normal bone', 'Abnormal bone', 'Only in elderly', 'Only in children', 'Stress injury', 'B', 'Pathological fracture occurs in abnormal bone.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 11, 'Spiral fracture results from:', 'Direct blow', 'Twisting force', 'Compression', 'Distraction', 'Repeated stress', 'B', 'Spiral fracture from rotational/twisting force.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 12, 'Comminuted fracture has:', '2 fragments', '3 or more fragments', 'Butterfly fragment', 'Single transverse line', 'No displacement', 'B', 'Comminuted has 3 or more fragments.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 13, 'Fat embolism occurs after fracture of:', 'Phalanx', 'Clavicle', 'Long bone/pelvis', 'Scaphoid', 'Vertebra', 'C', 'Fat embolism from long bone/pelvis fractures.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 14, 'Delayed union is:', 'Normal healing', 'Slower than expected healing', 'Failure to heal', 'Healing in wrong position', 'Immediate complication', 'B', 'Delayed union is slower than expected healing.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 15, 'Children''s fractures heal:', 'Slower', 'Same rate', 'Faster', 'Never', 'Only with surgery', 'C', 'Children heal faster due to periosteal activity.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 16, 'Skeletal traction uses:', 'Skin strapping', 'Pin through bone', 'Cast only', 'Splint only', 'Compression bandage', 'B', 'Skeletal traction uses pin through bone.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 17, 'Avascular necrosis commonly affects:', 'Shaft of femur', 'Femoral head', 'Tibial shaft', 'Radius shaft', 'Humeral shaft', 'B', 'AVN commonly affects femoral head.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 18, 'First priority in open fracture is:', 'X-ray', 'Debridement and antibiotics', 'Immediate fixation', 'Cast application', 'Observation', 'B', 'Debridement, washout, and antibiotics are priority.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 19, 'Hematoma stage of healing is:', '0-5 days', '2-3 weeks', '3-4 months', '6 months', '1 year', 'A', 'Hematoma forms in first 0-5 days.'),
('fe04f125-5e92-4ec7-99ef-998ed5092231'::uuid, 20, 'Treatment principle is:', 'Reduce, Hold, Rehabilitate', 'Fix, Cast, Wait', 'Operate, Immobilize, Discharge', 'Reduce, Wait, Move', 'Cast, Rest, Review', 'A', 'Reduce, Hold, Rehabilitate is the principle.');
