-- Sutures and Surgical Instruments Article Content and MCQs
-- Article ID: 38387cb8-3265-42cc-b0c2-cb05afc822b3

INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 'introduction', 1, 'Introduction', 'Sutures are materials used to hold tissues together. Instruments are tools for surgical procedures. Knowledge of both is essential for any surgeon. Sutures classified by: Absorbability (absorbable/non-absorbable), Structure (monofilament/multifilament), Origin (natural/synthetic). Instruments classified by function: Cutting, Grasping, Clamping, Retracting, Suturing.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 'content', 2, 'Absorbable Sutures', 'NATURAL: Plain catgut - absorbed 7-10 days. Chromic catgut - absorbed 21-28 days. From sheep/bovine intestine. Rarely used now. SYNTHETIC: Polyglycolic acid (Dexon) - absorbed 60-90 days. Polyglactin 910 (Vicryl) - absorbed 56-70 days, braided. Poliglecaprone (Monocryl) - absorbed 90-120 days, monofilament. Polydioxanone (PDS) - absorbed 180-210 days, monofilament, longest lasting absorbable. USE: Internal sutures, bowel anastomosis, subcutaneous closure.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 'content', 3, 'Non-Absorbable Sutures', 'NATURAL: Silk - braided, easy handling, tissue reactive. Cotton - rarely used. SYNTHETIC: Nylon (Ethilon) - monofilament, skin closure, low reactivity. Polypropylene (Prolene) - monofilament, vascular surgery, least reactive. Polyester (Ethibond) - braided, cardiac surgery. Steel wire - strongest, sternotomy closure. USE: Skin closure, vascular anastomosis, hernia repair, permanent fixation. SUTURE SIZE: Larger number = smaller diameter. 2-0 > 3-0 > 4-0. Skin: 3-0 to 5-0. Face: 5-0 to 6-0. Fascia: 0 to 1.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 'content', 4, 'Surgical Instruments', 'CUTTING: Scalpel (handles 3, 4; blades 10, 11, 15, 20, 22), Scissors (Mayo, Metzenbaum). GRASPING: Forceps - toothed (tissue), non-toothed (dressing). CLAMPING: Hemostats (mosquito, Kelly, Kocher), Bowel clamps (Babcock - atraumatic, Allis - traumatic). RETRACTORS: Handheld (Langenbeck, Army-Navy), Self-retaining (Balfour, Finochietto). NEEDLE HOLDERS: Mayo-Hegar, Castroviejo (microsurgery). SUCTION: Yankauer, Poole. SPECIAL: Diathermy, Harmonic scalpel, Ligasure.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 'content', 5, 'Surgical Needles', 'NEEDLE TYPES: Round body - atraumatic, for bowel, peritoneum, vessels. Cutting - triangular, for skin, fascia. Reverse cutting - skin, less tissue cut-through. Taper cut - combination. NEEDLE SHAPES: 1/4 circle - eye surgery. 3/8 circle - most common. 1/2 circle - deep cavities. 5/8 circle - pelvis. Straight - skin, rarely. NEEDLE ATTACHMENT: Swaged (eyeless) - suture attached, atraumatic. Eyed - threaded manually.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 'key_points', 6, 'Key Points', '1. Vicryl is braided absorbable. 2. Prolene is least reactive. 3. PDS lasts longest of absorbables. 4. Round body needle for bowel. 5. Cutting needle for skin. 6. 3/8 circle most common shape. 7. Babcock is atraumatic. 8. Allis is traumatic. 9. Larger suture number = smaller diameter. 10. Metzenbaum for delicate tissue dissection.');

-- Sutures and Instruments Self-Assessment Questions
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 1, 'Vicryl is:', 'Non-absorbable monofilament', 'Absorbable braided', 'Non-absorbable braided', 'Natural absorbable', 'Steel wire', 'B', 'Vicryl is absorbable braided synthetic.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 2, 'Least reactive suture is:', 'Silk', 'Catgut', 'Polypropylene', 'Vicryl', 'Cotton', 'C', 'Polypropylene (Prolene) is least reactive.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 3, 'Longest lasting absorbable suture is:', 'Catgut', 'Vicryl', 'Monocryl', 'PDS', 'Dexon', 'D', 'PDS lasts 180-210 days.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 4, 'Round body needle is used for:', 'Skin', 'Fascia', 'Bowel', 'Tendon', 'Nail bed', 'C', 'Round body needle for bowel - atraumatic.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 5, 'Cutting needle is used for:', 'Bowel', 'Vessels', 'Skin', 'Peritoneum', 'Nerve', 'C', 'Cutting needle for skin and fascia.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 6, 'Most common needle shape is:', '1/4 circle', '3/8 circle', '1/2 circle', '5/8 circle', 'Straight', 'B', '3/8 circle is most commonly used.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 7, 'Babcock clamp is:', 'Traumatic', 'Atraumatic', 'For vessels only', 'For bone', 'Cutting', 'B', 'Babcock is atraumatic bowel clamp.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 8, 'Allis clamp is:', 'Atraumatic', 'Traumatic', 'For vessels', 'Self-retaining', 'Non-locking', 'B', 'Allis has teeth - traumatic.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 9, 'Suture 4-0 compared to 3-0 is:', 'Thicker', 'Thinner', 'Same', 'Stronger', 'Longer', 'B', 'Larger number = smaller diameter.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 10, 'Metzenbaum scissors are for:', 'Cutting sutures', 'Heavy tissue', 'Delicate dissection', 'Bone cutting', 'Wire cutting', 'C', 'Metzenbaum for delicate tissue dissection.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 11, 'Mayo scissors are for:', 'Delicate tissue', 'Fascia and heavy tissue', 'Sutures only', 'Eye surgery', 'Nerve dissection', 'B', 'Mayo scissors for fascia and heavy tissue.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 12, 'Prolene is used for:', 'Bowel anastomosis', 'Vascular surgery', 'Subcutaneous closure', 'Muscle closure', 'Catgut alternative', 'B', 'Prolene for vascular surgery - non-absorbable.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 13, 'Silk suture is:', 'Absorbable', 'Non-absorbable', 'Synthetic', 'Monofilament', 'Least reactive', 'B', 'Silk is non-absorbable natural.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 14, 'Chromic catgut is absorbed in:', '7-10 days', '21-28 days', '60 days', '90 days', '180 days', 'B', 'Chromic catgut absorbed in 21-28 days.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 15, 'Swaged needle means:', 'Has eye for threading', 'Suture pre-attached', 'Is curved', 'Is straight', 'Has cutting edge', 'B', 'Swaged = suture pre-attached to needle.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 16, 'Balfour retractor is:', 'Handheld', 'Self-retaining', 'For chest', 'Vascular clamp', 'Needle holder', 'B', 'Balfour is self-retaining abdominal retractor.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 17, 'Face sutures typically use:', '0-1', '2-0', '3-0', '5-0 to 6-0', '1-2', 'D', 'Face needs fine sutures: 5-0 to 6-0.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 18, 'Langenbeck is a:', 'Clamp', 'Retractor', 'Needle holder', 'Scissors', 'Forceps', 'B', 'Langenbeck is handheld retractor.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 19, 'Monocryl is:', 'Non-absorbable', 'Absorbable monofilament', 'Braided', 'Natural', 'For vascular', 'B', 'Monocryl is absorbable monofilament.'),
('38387cb8-3265-42cc-b0c2-cb05afc822b3'::uuid, 20, 'Yankauer is used for:', 'Cutting', 'Suturing', 'Suction', 'Retraction', 'Clamping', 'C', 'Yankauer is suction device.');
