-- ============================================================================
-- BATCH 25: Additional CPR - Clinical Scenario Questions (Questions ~960-1000)
-- Topic: Clinical scenarios for resuscitation decision-making
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- CARDIAC ARREST RECOGNITION SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 58-year-old man suddenly collapses in the hospital corridor. He is unresponsive to your voice and gentle shaking. You check for breathing and notice only occasional gasping. His carotid pulse is absent after 10 seconds of checking. What is your IMMEDIATE next action?',
'Wait for the crash cart to arrive',
'Begin chest compressions immediately while calling for help',
'Perform a 12-lead ECG first',
'Administer IV adrenaline',
'Attempt defibrillation without CPR',
'B',
'In witnessed cardiac arrest with no pulse and agonal breathing (which is NOT effective breathing), immediate high-quality chest compressions are the priority. Call for help simultaneously. Do not delay CPR for equipment. Agonal gasps occur in up to 40% of cardiac arrests.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'You are the first responder to find a 45-year-old woman collapsed in a shopping mall. She is unresponsive with no normal breathing. You are alone with no AED nearby. What is the correct sequence of actions?',
'Start CPR for 2 minutes, then call emergency services',
'Call emergency services (or send someone), then immediately begin CPR at 30:2 ratio',
'Open airway first and give 5 rescue breaths',
'Check blood glucose level first',
'Wait for paramedics to arrive',
'B',
'For adult cardiac arrest, activate emergency response immediately (phone on speaker), then begin CPR 30:2. In adults, cardiac arrest is usually cardiac in origin, so early defibrillation is critical - call first. Continuous chest compressions are the priority.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 3-year-old child is pulled from a swimming pool. He is unresponsive with no breathing. You are a single healthcare provider. What should you do FIRST?',
'Call for help immediately before any intervention',
'Give 5 initial rescue breaths, then start CPR for 2 minutes before calling for help',
'Start chest compressions only',
'Perform abdominal thrusts for drowning',
'Check blood pressure',
'B',
'In pediatric arrest (especially drowning - asphyxial cause), hypoxia is the primary problem. Give 5 rescue breaths first, then 1 minute of CPR (or 2 minutes if alone) before leaving to call for help. This differs from adult protocol.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During ward rounds, a 70-year-old post-MI patient suddenly becomes unresponsive. The monitor shows a flat line. Before starting CPR, what must you verify?',
'That the patient has a DNR order',
'That leads are properly connected and gain is adequate (rule out technical issues)',
'That the patient is definitely dead',
'That the family is present',
'That blood tests are current',
'B',
'Asystole on monitor requires verification - check leads are connected, gain is adequate, and check in another lead. True asystole should show no electrical activity in multiple leads. Technical issues are common. However, do not delay CPR if clinically in arrest.',
'medium', 'application'),

-- CHEST COMPRESSION SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'You are performing CPR on a 65-year-old man. After 2 minutes, you notice you are becoming fatigued and your compression depth is decreasing. The arrest team has just arrived. What should you do?',
'Continue compressions as you started the resuscitation',
'Switch with another team member to maintain high-quality compressions',
'Take a short break to recover',
'Reduce compression rate to conserve energy',
'Stop CPR until the defibrillator is ready',
'B',
'Rescuer fatigue significantly reduces compression quality after 1-2 minutes even when rescuer does not feel tired. Rotate compressors every 2 minutes (or every 5 cycles of 30:2) to maintain adequate depth and rate. Minimize interruptions during switch.',
'easy', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During CPR on an adult patient, the end-tidal CO2 monitor shows readings consistently below 10 mmHg. What does this indicate and what action should you take?',
'CPR is effective, continue current technique',
'Compression quality is inadequate - ensure proper depth, rate, and complete recoil',
'The patient has ROSC, stop CPR',
'Ventilation is excessive, reduce breath rate',
'The monitor is malfunctioning',
'B',
'ETCO2 less than 10 mmHg during CPR indicates poor cardiac output from compressions. Ensure compressions are 5-6cm deep, rate 100-120/min, complete chest recoil, and minimize interruptions. ETCO2 greater than 20 mmHg suggests better perfusion. Sudden rise to greater than 40 may indicate ROSC.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old obese man (BMI 42) is in cardiac arrest on a soft hospital bed. CPR has been ongoing but seems ineffective. What modification would MOST improve compression effectiveness?',
'Compress faster than 120/min',
'Place a backboard under the patient or move to floor',
'Use both hands stacked higher on sternum',
'Have two people compress simultaneously',
'Reduce compression depth for obese patients',
'B',
'Soft surfaces reduce compression effectiveness as energy is absorbed by mattress. Place a CPR backboard under patient or move to floor/hard surface. For obese patients, ensure adequate depth (may require more force), proper hand position remains lower sternum.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'You are performing CPR on a pregnant woman at 32 weeks gestation who collapsed from suspected amniotic fluid embolism. How should you modify your technique?',
'No modification needed, standard CPR',
'Manually displace uterus to the left or tilt patient 15-30 degrees left',
'Perform compressions on the right side of chest',
'Avoid chest compressions due to pregnancy',
'Compress at a slower rate',
'B',
'In pregnant patients beyond 20 weeks, the gravid uterus compresses the IVC, reducing venous return. Manual left uterine displacement (preferred) or left lateral tilt (15-30 degrees) improves venous return. Compressions may need to be slightly higher on sternum.',
'hard', 'application'),

-- DEFIBRILLATION SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 62-year-old man collapses with witnessed VF arrest. An AED arrives within 2 minutes. The AED advises a shock. What is the correct sequence?',
'Give 3 stacked shocks, then start CPR',
'Clear patient, deliver ONE shock, immediately resume CPR for 2 minutes before rhythm check',
'Check pulse first, then shock if VF persists',
'Start CPR for 2 minutes before first shock',
'Shock only if pulse is present',
'B',
'Current guidelines: Single shock strategy. After shock, immediately resume CPR for 2 minutes (do not stop to check rhythm/pulse). Rhythm check only after 2 minutes of CPR. Early defibrillation in witnessed VF (within 3-5 min) gives best outcomes.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During resuscitation, the monitor shows fine VF that looks almost like asystole. You have already delivered 3 shocks with ongoing CPR. What strategy might improve defibrillation success?',
'Continue shocking at same energy',
'Give adrenaline and continue CPR to "coarsen" VF before next shock attempt',
'Increase ventilation rate',
'Stop resuscitation as fine VF is not shockable',
'Decrease shock energy',
'B',
'Fine VF has lower defibrillation success. Continue good CPR (improves myocardial oxygenation) and give adrenaline. This may convert fine VF to coarse VF which is more amenable to successful defibrillation. Do not treat fine VF as asystole - it remains shockable.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient in VF arrest has a transdermal medication patch on the anterior chest where you need to place a defibrillator pad. What should you do?',
'Place pad directly over the patch',
'Remove the patch, wipe the area, then apply the pad',
'Use a different pad position',
'Reduce the shock energy',
'Avoid defibrillation until patch effect wears off',
'B',
'Medication patches can block energy delivery and may cause burns or explosion. Remove patch, wipe residue from skin, then apply pad. Also check for implanted devices (pacemaker/ICD) and place pads at least 8cm away.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient with an ICD in the left pectoral region goes into cardiac arrest. The ICD has delivered one shock but the patient remains in VF. How should you manage external defibrillation?',
'Do not defibrillate - the ICD will manage it',
'Place pads at least 8cm from the device and defibrillate normally',
'Place pads directly over the ICD for best effect',
'Wait for the ICD to deliver more shocks',
'Remove the ICD before defibrillating',
'B',
'External defibrillation is safe and necessary if ICD fails. Place pads at least 8cm from implanted device to avoid damage and ensure current path through heart. AP position may be preferred. Proceed with standard ALS algorithm.',
'medium', 'application'),

-- DRUG ADMINISTRATION SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'You are managing a cardiac arrest with a shockable rhythm (VF). After the first shock and 2 minutes of CPR, the rhythm is still VF. After the second shock, the rhythm remains VF. When should you administer the first dose of adrenaline?',
'Immediately after the first shock',
'After the third shock, during CPR',
'Only if rhythm becomes non-shockable',
'After 10 minutes of resuscitation',
'Adrenaline is not used in VF',
'B',
'In shockable rhythms: First adrenaline after 3rd shock. Amiodarone also given after 3rd shock (300mg), with second dose (150mg) after 5th shock. In non-shockable rhythms, give adrenaline as soon as IV/IO access obtained.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient is in PEA arrest with a heart rate of 30/min on the monitor but no palpable pulse. You have given 3 doses of adrenaline. What additional intervention should you consider?',
'Atropine is no longer recommended in cardiac arrest',
'Electrical pacing',
'Immediate thoracotomy',
'Calcium gluconate routinely',
'Stop resuscitation',
'A',
'Atropine is no longer recommended in cardiac arrest per ALS guidelines. For PEA, focus on reversible causes (4Hs and 4Ts). If organized electrical activity with rate, continue CPR while treating reversible causes. Pacing unlikely to help without output.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During resuscitation, the team struggles to obtain IV access in a patient with VF arrest. One minute has passed. What is the most appropriate alternative access route?',
'Intramuscular injection',
'Intraosseous (IO) access',
'Subcutaneous injection',
'Sublingual medication',
'Endotracheal drug administration as first alternative',
'B',
'IO access is first-line alternative to IV. Can be established in seconds, allows all resuscitation drugs and fluids. Common sites: proximal tibia, proximal humerus. Endotracheal route is no longer recommended due to unpredictable absorption.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 68-year-old man has been in VF arrest for 12 minutes despite 3 shocks and adrenaline. After the 3rd shock, you administered amiodarone 300mg IV. The rhythm is still VF after the 5th shock. What is the next antiarrhythmic step?',
'Give another 300mg amiodarone',
'Give amiodarone 150mg IV',
'Switch to lidocaine 100mg',
'No further antiarrhythmics indicated',
'Give magnesium sulphate',
'B',
'After initial 300mg amiodarone (post-3rd shock in refractory VF/pVT), a second dose of 150mg can be given after the 5th shock. Lidocaine (1mg/kg) is alternative if amiodarone unavailable. Magnesium for torsades de pointes or hypomagnesemia.',
'hard', 'application'),

-- REVERSIBLE CAUSES SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 35-year-old IV drug user presents in PEA arrest. On examination, neck veins are distended, heart sounds are muffled, and there is electrical alternans on the monitor. CPR is ongoing. What is the most likely reversible cause and urgent intervention?',
'Tension pneumothorax - needle decompression',
'Cardiac tamponade - pericardiocentesis',
'Pulmonary embolism - thrombolysis',
'Hypovolemia - IV fluids',
'Hypoxia - increase oxygen',
'B',
'Beck triad (distended neck veins, muffled heart sounds, hypotension) with electrical alternans suggests cardiac tamponade. In IV drug users, consider infective endocarditis. Emergency pericardiocentesis or thoracotomy during CPR may be lifesaving.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 22-year-old asthmatic is brought in after cardiac arrest at home. She is in PEA arrest. On examination, there is no air entry on the right side, the trachea is deviated to the left, and the right chest is hyper-resonant. What intervention is required immediately during CPR?',
'Chest X-ray before any intervention',
'Needle decompression of right chest followed by chest drain',
'Intubation only',
'Increase ventilation pressure',
'CT chest',
'B',
'Clinical signs of tension pneumothorax (absent breath sounds, hyper-resonance, tracheal deviation away from affected side) require immediate needle decompression (2nd intercostal space midclavicular line or 4th/5th ICS anterior axillary line) followed by chest drain.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 72-year-old woman on warfarin for atrial fibrillation is in PEA arrest following a fall and head injury 3 days ago. Her INR is 6.8. Head CT shows large subdural hematoma. During resuscitation, what specific treatment should be administered?',
'Continue standard CPR only',
'Prothrombin complex concentrate (PCC) and IV vitamin K for warfarin reversal',
'Fresh frozen plasma only',
'Tranexamic acid only',
'Platelet transfusion',
'B',
'Coagulopathy from warfarin with major bleeding requires urgent reversal. PCC (25-50 units/kg) provides immediate reversal, plus IV vitamin K (5-10mg) for sustained effect. FFP is slower and requires larger volume. Addresses the reversible cause.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A dialysis patient is brought to ED in cardiac arrest. The ECG shows very tall peaked T waves, widened QRS, and sine wave pattern. CPR is ongoing. What is the FIRST drug you should administer?',
'Adrenaline 1mg',
'Calcium chloride 10ml of 10% solution IV',
'Amiodarone 300mg',
'Sodium bicarbonate',
'Insulin and dextrose',
'B',
'ECG shows severe hyperkalemia (peaked T waves, wide QRS, sine wave). Calcium is cardioprotective and should be given immediately (stabilizes myocardium within minutes). Follow with insulin/dextrose, salbutamol, and sodium bicarbonate. Dialysis if available.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient found unresponsive in a house fire is in cardiac arrest. SpO2 reads 100% but the patient is cyanosed. What is the likely diagnosis and specific treatment?',
'Equipment malfunction - use different monitor',
'Carbon monoxide poisoning - give 100% oxygen and consider hyperbaric oxygen',
'Methemoglobinemia - give methylene blue',
'Cyanide poisoning - give hydroxocobalamin',
'Normal finding in arrest',
'B',
'House fire exposure suggests CO poisoning. SpO2 falsely reads normal as it cannot distinguish carboxyhemoglobin. Give high-flow 100% O2 to displace CO (reduces half-life from 4-6 hours to 1 hour). Hyperbaric oxygen if available. Also consider cyanide from smoke.',
'hard', 'application'),

-- POST-RESUSCITATION SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'After 15 minutes of CPR, a 60-year-old man achieves ROSC. His BP is 85/50, HR 110, and he remains unconscious with GCS 3. What is the MOST important next step in his management?',
'Immediate coronary angiography for all patients',
'Secure airway, optimize oxygenation (SpO2 94-98%), and avoid hypotension (MAP greater than 65)',
'Immediate therapeutic hypothermia to 32 degrees',
'High-dose adrenaline infusion',
'Neurological prognostication immediately',
'B',
'Post-ROSC priorities: Airway management (intubate if GCS low), avoid hypoxia AND hyperoxia (target SpO2 94-98%), avoid hypotension (MAP greater than 65, may need vasopressors), treat cause (consider coronary angiography if STEMI or suspected cardiac cause).',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'Following successful resuscitation from VF arrest, a 55-year-old man remains comatose. His 12-lead ECG shows ST elevation in leads V1-V4. What is the recommended management?',
'Wait for the patient to wake up before any intervention',
'Immediate coronary angiography and PCI regardless of coma',
'Thrombolysis only as the patient cannot consent',
'CT head first to exclude stroke',
'Delay angiography until neurological prognosis is clear',
'B',
'STEMI post-cardiac arrest is indication for emergent coronary angiography and PCI regardless of neurological status. Coma is not a contraindication. Early revascularization improves outcomes. Combined with targeted temperature management.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 48-year-old woman has ROSC after VF arrest. She remains unresponsive. Her temperature is 37.8 degrees C. Blood glucose is 15 mmol/L. What temperature and glucose targets should you aim for?',
'No specific targets needed',
'Target temperature 32-36 degrees C and blood glucose less than 10 mmol/L, avoiding hypoglycemia',
'Allow fever as it is protective',
'Target blood glucose less than 4 mmol/L',
'Target temperature greater than 38 degrees C',
'B',
'Post-ROSC: Targeted temperature management (32-36 degrees C for at least 24 hours) for comatose patients. Avoid fever. Maintain blood glucose 7.8-10 mmol/L (avoid both hyper- and hypoglycemia). Continuous monitoring required.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A family asks about neurological prognosis for their 65-year-old father who remains comatose 24 hours after cardiac arrest and successful resuscitation. What should you tell them?',
'Prognosis is certainly poor if not awake by 24 hours',
'Accurate prognostication should be delayed at least 72 hours, and longer if sedation was used',
'Brain death should be declared at 48 hours',
'Full recovery is guaranteed if ROSC achieved',
'MRI at 24 hours gives definitive prognosis',
'B',
'Neurological prognostication should be delayed at least 72 hours post-ROSC (longer if sedatives given or hypothermia used). Use multimodal approach: clinical exam, EEG, somatosensory evoked potentials, biomarkers, imaging. No single test is definitive.',
'medium', 'application'),

-- SPECIAL SITUATIONS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 28-year-old construction worker is in cardiac arrest after electrocution from a high-voltage power line. The scene is now safe. What special considerations apply?',
'Standard CPR only',
'Higher incidence of VF, trauma assessment, may need prolonged resuscitation',
'Electrocution never causes VF',
'CPR is contraindicated after electrocution',
'Avoid defibrillation',
'B',
'Electrical injury: Higher incidence of VF (especially high voltage AC). Associated trauma common (falls, tetanic muscle contractions). May have burns. Consider spinal injury. Young patients may survive prolonged resuscitation - more aggressive approach warranted.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 35-year-old woman is found unresponsive after suspected opioid overdose. She has a pulse of 50/min but is not breathing. What is the appropriate management?',
'Full CPR as this is cardiac arrest',
'Bag-mask ventilation with oxygen and administer naloxone 400mcg IV/IM/IN',
'Chest compressions only',
'Wait for her to start breathing',
'Intubate immediately',
'B',
'This is respiratory arrest (has pulse, not breathing), not cardiac arrest. Priority is ventilation. Give high-flow oxygen via bag-mask. Naloxone 400mcg IV/IM/intranasal, repeat every 2-3 minutes. Monitor closely as naloxone wears off faster than most opioids.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A swimmer is pulled from cold water (water temperature 10 degrees C). He has been submerged for approximately 15 minutes. He is pulseless and not breathing. His core temperature is 28 degrees C. What is your approach?',
'Declare death as submersion greater than 10 minutes is not survivable',
'Initiate CPR and continue until core temperature is at least 32 degrees C or rewarming fails',
'Standard resuscitation for 20 minutes only',
'Do not attempt resuscitation in hypothermia',
'Warm the patient before starting CPR',
'B',
'Hypothermic cardiac arrest: "No one is dead until warm and dead." Hypothermia is protective. Continue CPR until core temp at least 32 degrees C. Limit defibrillation attempts until warmer. May require ECMO/cardiopulmonary bypass for rewarming. Remarkable survival reported.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old man with terminal metastatic cancer has a witnessed VF arrest in hospital. His notes document a DNACPR (Do Not Attempt CPR) order signed yesterday. What should you do?',
'Start CPR as VF is reversible',
'Respect the DNACPR decision and do not attempt resuscitation',
'Ask family permission to override',
'Start CPR until a senior doctor confirms the order',
'Only do chest compressions, not defibrillation',
'B',
'A valid DNACPR order should be respected. It represents the patient informed decision (or best interests decision). Provide comfort care and support for family. DNACPR does not mean withholding other treatments or care.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'You are leading a resuscitation that has been ongoing for 40 minutes with no ROSC despite optimal CPR, multiple shocks for recurrent VF, and all reversible causes addressed. The patient is a 78-year-old with multiple comorbidities. When is it appropriate to consider stopping?',
'Continue indefinitely as long as VF persists',
'After 20 minutes',
'Consider stopping when reversible causes treated, no ROSC, and team agrees further resuscitation is futile',
'Only a consultant can decide',
'Stop immediately at 30 minutes',
'C',
'Stopping resuscitation is a clinical judgment. Consider: duration (usually greater than 20-30 min without ROSC), rhythm (asystole worse prognosis), reversible causes addressed, patient factors (age, comorbidities, quality of life), and team consensus. No absolute time limit.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During resuscitation of a patient in asystole, a junior doctor asks why you are not giving atropine as he was taught this previously. What is the correct response?',
'Atropine is still indicated, give 3mg IV',
'Atropine is no longer recommended in cardiac arrest - focus on adrenaline and reversible causes',
'Atropine is only for VF',
'Give atropine via endotracheal tube',
'Atropine should be given every 3 minutes',
'B',
'Atropine was removed from cardiac arrest algorithms (since 2010) as evidence showed no benefit in asystole or PEA. Focus on high-quality CPR, adrenaline every 3-5 minutes, and identifying/treating reversible causes.',
'medium', 'knowledge'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A hospital cardiac arrest call is made. When you arrive, there are 8 people around the bed with several trying to help simultaneously. What is your priority as team leader?',
'Join in with chest compressions',
'Organize the team with clear roles, ensure high-quality CPR, and maintain situation awareness',
'Let everyone continue as they are',
'Send most people away immediately',
'Focus only on drug administration',
'B',
'Effective team leadership is critical. Assign clear roles (compressions, airway, access/drugs, scribe), ensure closed-loop communication, monitor CPR quality, maintain 30-second rhythm checks, and coordinate interventions. Too many uncoordinated helpers reduce quality.',
'medium', 'application');
