-- ============================================================================
-- BATCH 26: Additional Shock - Clinical Scenario Questions (Questions 992-1035)
-- Topic: Clinical scenarios for shock recognition and management
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- HYPOVOLEMIC SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 25-year-old motorcyclist is brought to ED after a road traffic accident. BP is 80/50 mmHg, HR 130/min, RR 28/min, cold clammy extremities, and altered consciousness. He is pale with visible deformity of the left femur. Estimated blood loss is 2 liters. What class of hemorrhagic shock is this and what is the initial fluid of choice?',
'Class I shock - give oral fluids',
'Class III shock - give crystalloid and prepare for blood transfusion',
'Class II shock - observation only',
'Class IV shock - give vasopressors first',
'Not hemorrhagic shock - give antibiotics',
'B',
'Class III hemorrhage (30-40% blood volume loss, 1.5-2L): Tachycardia (greater than 120), hypotension, decreased urine output, anxiety/confusion. Initial resuscitation with warm crystalloid (NS or Ringer lactate), but likely needs blood products. Activate massive transfusion protocol.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old woman presents with severe vomiting and diarrhea for 3 days. She is lethargic with dry mucous membranes, sunken eyes, and skin tenting. BP 85/60 mmHg, HR 118/min, urine output minimal. Her serum sodium is 155 mEq/L. What is the most appropriate initial management?',
'Immediate blood transfusion',
'Aggressive isotonic crystalloid resuscitation with monitoring of sodium correction rate',
'Hypertonic saline',
'Vasopressor infusion',
'Oral rehydration only',
'B',
'Hypovolemic shock from GI losses with hypernatremic dehydration. Initial resuscitation with isotonic crystalloid (NS). Correct sodium slowly (less than 10-12 mEq/L per 24 hours) to avoid cerebral edema. Monitor urine output, mental status, and electrolytes.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old man post-abdominal surgery has BP 95/65 mmHg, HR 105/min, decreased urine output. His Hb drops from 12 to 8 g/dL over 6 hours. Abdominal drains show minimal output. What is the most likely diagnosis and next step?',
'Septic shock - start antibiotics',
'Intra-abdominal hemorrhage - return to OR for re-exploration',
'Cardiogenic shock - give inotropes',
'Anaphylaxis - give adrenaline',
'Normal postoperative course - observe',
'B',
'Dropping hemoglobin with hemodynamic compromise post-surgery suggests intra-abdominal hemorrhage. Minimal drain output does not exclude bleeding (may be loculated or drains blocked). Urgent return to OR for exploration and hemostasis.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old man on warfarin presents with melena for 2 days. He is pale, diaphoretic, BP 75/45 mmHg, HR 125/min. His INR is 5.2. What is the priority management sequence?',
'Endoscopy first to identify bleeding source',
'Secure large-bore IV access, transfuse blood products, reverse anticoagulation, then endoscopy',
'Give IV vitamin K and wait 24 hours',
'Start vasopressors immediately',
'Discharge with oral iron',
'B',
'Hemorrhagic shock from GI bleeding with supratherapeutic anticoagulation. Priorities: IV access (2 large-bore), resuscitation with crystalloid and blood products (type O negative if severe, then cross-matched), reverse warfarin with PCC and vitamin K, urgent endoscopy.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient with Class IV hemorrhagic shock receives 6 units of packed RBCs rapidly. He develops hypotension, coagulopathy with oozing from IV sites, and hypothermia (34 degrees C). What complication has developed and how should it be managed?',
'Transfusion reaction - stop blood',
'Lethal triad (hypothermia, acidosis, coagulopathy) - damage control resuscitation with balanced transfusion, warming, and permissive hypotension',
'Fluid overload - give diuretics',
'Anaphylaxis - give adrenaline',
'DIC from sepsis - give antibiotics',
'B',
'Lethal triad of trauma: hypothermia, acidosis, coagulopathy. Management: Damage control surgery, balanced transfusion (1:1:1 PRBC:FFP:platelets), active warming, avoid excessive crystalloid, permissive hypotension (target SBP 80-90 until bleeding controlled).',
'hard', 'application'),

-- CARDIOGENIC SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old man presents with crushing chest pain for 2 hours. ECG shows ST elevation in leads V1-V4. BP is 80/55 mmHg, HR 110/min, with bilateral lung crackles and JVP elevated to angle of jaw. What is the diagnosis and immediate management?',
'Pulmonary embolism - give thrombolysis',
'Cardiogenic shock from anterior STEMI - emergent PCI, avoid excessive fluids, consider inotropes',
'Hypovolemic shock - give 2L crystalloid',
'Tension pneumothorax - needle decompression',
'Septic shock - start antibiotics',
'B',
'Anterior STEMI with cardiogenic shock (hypotension, pulmonary edema, elevated JVP). Treatment: Emergent coronary angiography and PCI (primary treatment), judicious fluid use, inotropic support (dobutamine or noradrenaline), consider IABP or mechanical support.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 72-year-old woman 3 days post-MI suddenly develops severe dyspnea and a new loud pansystolic murmur at the left sternal edge. BP drops to 75/50 mmHg with pulmonary edema. What is the most likely complication and definitive management?',
'Mitral stenosis - balloon valvuloplasty',
'Ventricular septal rupture - urgent surgical repair',
'Aortic stenosis - TAVI',
'Pulmonary embolism - thrombolysis',
'Pericardial effusion - pericardiocentesis',
'B',
'New harsh pansystolic murmur 3-5 days post-MI suggests ventricular septal rupture (mechanical complication). IABP for stabilization, inotropes, but definitive treatment is urgent surgical repair. High mortality without surgery.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old man on chemotherapy presents with dyspnea. BP 85/palpable, HR 120/min, JVP markedly elevated, heart sounds are muffled. There is pulsus paradoxus of 20 mmHg. ECG shows low voltage and electrical alternans. What is the diagnosis and urgent intervention?',
'Tension pneumothorax - chest drain',
'Cardiac tamponade - urgent pericardiocentesis',
'Massive PE - thrombolysis',
'Cardiomyopathy - beta blockers',
'Aortic dissection - surgery',
'B',
'Beck triad (hypotension, elevated JVP, muffled heart sounds) with pulsus paradoxus and electrical alternans indicates cardiac tamponade. In oncology patient, consider malignant effusion. Urgent echo-guided pericardiocentesis or surgical window.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in cardiogenic shock post-MI is started on dobutamine infusion. His BP improves from 75/50 to 95/60 mmHg but he develops rapid atrial fibrillation with HR 150/min. What adjustment should be made?',
'Increase dobutamine dose',
'Reduce dobutamine, consider adding noradrenaline for pressure support while controlling rate',
'Stop all treatment',
'Add adrenaline',
'Immediate cardioversion',
'B',
'Dobutamine increases heart rate (beta-1 effect) and can trigger arrhythmias. In new AF with fast rate, reduce dobutamine dose, consider noradrenaline (less chronotropic effect) for pressure support, and rate control with caution (avoid negative inotropes in cardiogenic shock).',
'hard', 'application'),

-- DISTRIBUTIVE SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old woman develops fever (39.5 C), BP 75/40 mmHg, HR 125/min, and confusion 2 days after cholecystectomy. Her skin is warm and flushed. WBC is 18,000 with left shift, lactate 5.2 mmol/L. What is the diagnosis and initial management priority?',
'Cardiogenic shock - dobutamine',
'Septic shock - IV fluids, blood cultures, and broad-spectrum antibiotics within 1 hour',
'Hemorrhagic shock - blood transfusion',
'Anaphylaxis - adrenaline',
'Neurogenic shock - vasopressors',
'B',
'Septic shock: Fever, hypotension despite warm peripheries (vasodilation), tachycardia, elevated lactate, source (post-surgical). Sepsis 6: Blood cultures, lactate, IV antibiotics within 1 hour, IV fluid bolus, urine output monitoring, oxygen. Consider biliary leak.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 68-year-old man with urosepsis has received 3L of crystalloid. His BP remains 80/50 mmHg, HR 115/min, lactate 4.5 mmol/L. CVP is 14 mmHg. Antibiotics have been given. What is the next step in management?',
'Continue aggressive fluid resuscitation',
'Start noradrenaline infusion as first-line vasopressor',
'Give blood transfusion',
'Start dobutamine',
'Immediate hemodialysis',
'B',
'Fluid-refractory septic shock (hypotension despite adequate volume resuscitation indicated by elevated CVP). First-line vasopressor is noradrenaline. Target MAP greater than 65 mmHg. Consider central line for vasopressor administration and monitoring.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient on high-dose noradrenaline for septic shock still has MAP of 55 mmHg. Echo shows hyperdynamic left ventricle. Cortisol level is 8 mcg/dL. What additional treatment should be considered?',
'Increase noradrenaline further',
'Add vasopressin and consider hydrocortisone for relative adrenal insufficiency',
'Start adrenaline as sole agent',
'Stop all vasopressors',
'Blood transfusion',
'B',
'Refractory septic shock with low cortisol suggests relative adrenal insufficiency. Add vasopressin (0.03 units/min) as second-line vasopressor. Hydrocortisone 200mg/day may improve vasopressor responsiveness in refractory shock.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'Minutes after receiving IV penicillin, a 30-year-old woman develops facial swelling, widespread urticaria, wheeze, BP 70/40 mmHg, and tachycardia. What is the FIRST drug to administer?',
'IV hydrocortisone',
'IM adrenaline 0.5mg (1:1000) into anterolateral thigh',
'IV chlorpheniramine',
'Nebulized salbutamol',
'IV fluids only',
'B',
'Anaphylactic shock: Adrenaline is FIRST-LINE and lifesaving. Give 0.5mg (0.5ml of 1:1000) IM into anterolateral thigh. Repeat every 5 minutes if needed. Also give IV fluids, antihistamines, and steroids, but adrenaline is priority. Remove trigger.',
'easy', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with anaphylaxis has received 3 doses of IM adrenaline but remains severely hypotensive (BP 60/30 mmHg). What is the next step?',
'Give more IM adrenaline indefinitely',
'Start IV adrenaline infusion and call for expert help (ICU/anesthesia)',
'Give IV bolus of 1mg adrenaline',
'Stop adrenaline and give steroids only',
'Proceed directly to cardiac massage',
'B',
'Refractory anaphylaxis: If 3 doses of IM adrenaline fail, start IV adrenaline infusion (dilute solution, titrated). Call for expert help. Ensure adequate IV fluids. Large IV bolus (1mg) is for cardiac arrest only and is dangerous in patient with output.',
'hard', 'application'),

-- NEUROGENIC SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 22-year-old diver sustains a cervical spine injury. He has flaccid paralysis below C5, BP 70/45 mmHg, HR 50/min, and warm dry skin below the level of injury. What type of shock is this and how does it differ from hypovolemic shock?',
'Hypovolemic shock - cold peripheries expected',
'Neurogenic shock - hypotension with bradycardia and warm peripheries due to loss of sympathetic tone',
'Cardiogenic shock - will have elevated JVP',
'Septic shock - will have fever',
'Obstructive shock - will have distended neck veins',
'B',
'Neurogenic shock: Loss of sympathetic tone causes vasodilation (warm peripheries) and bradycardia (unopposed vagal tone). Unlike hypovolemic shock which has tachycardia and cold, clammy skin. Treatment: Fluids cautiously and vasopressors with chronotropic effect.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with T4 spinal cord injury has neurogenic shock with BP 75/50 and HR 48/min. After 1.5L of crystalloid, BP is 80/55 and HR 52/min. What vasopressor would be most appropriate?',
'Pure vasopressor like phenylephrine',
'Noradrenaline or dopamine (have both alpha and beta effects)',
'Dobutamine (primarily beta effect)',
'Adrenaline at high dose',
'No vasopressor needed',
'B',
'Neurogenic shock: Need agent with both vasoconstrictor (alpha) and chronotropic (beta) effects due to bradycardia. Noradrenaline is first choice. Dopamine also useful. Pure alpha agents like phenylephrine may worsen bradycardia reflexively.',
'hard', 'application'),

-- OBSTRUCTIVE SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old woman 7 days post-hip replacement suddenly becomes severely dyspneic with chest pain. BP 80/50 mmHg, HR 130/min, JVP elevated, clear lungs. She is cyanosed. SpO2 82% on room air. What is the most likely diagnosis and immediate action?',
'Pneumonia - start antibiotics',
'Massive pulmonary embolism - give oxygen, fluid bolus, consider thrombolysis',
'Cardiogenic shock - give diuretics',
'Tension pneumothorax - needle decompression',
'COPD exacerbation - nebulizers',
'B',
'Massive PE: Risk factor (post-orthopedic surgery), acute dyspnea, hypoxia, hypotension, elevated JVP with clear lungs (RV failure). Give oxygen, cautious fluids (500ml), consider thrombolysis for hemodynamic instability. Echo shows RV dilation.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with confirmed massive PE and shock (BP 75/50, HR 135) is not improving with supportive care. Thrombolysis is being considered. What are contraindications that would preclude systemic thrombolysis?',
'Recent MI is a contraindication',
'Recent hemorrhagic stroke, active bleeding, or recent major surgery are absolute contraindications',
'Pregnancy is an absolute contraindication',
'Age over 75 is an absolute contraindication',
'There are no contraindications in shock',
'B',
'Thrombolysis contraindications: Absolute - hemorrhagic stroke ever, ischemic stroke within 6 months, active bleeding, recent major surgery/trauma, bleeding diathesis. Relative - pregnancy, recent MI, severe hypertension. In life-threatening PE, benefits may outweigh risks.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 19-year-old man with asthma is brought in after a severe attack. He is unconscious, cyanosed, with no air entry on left side and tracheal deviation to right. BP is 70/palpable, HR 140/min. The left hemithorax is hyper-resonant. What must be done IMMEDIATELY?',
'Obtain chest X-ray',
'Needle decompression of left chest in 2nd intercostal space midclavicular line',
'Intubation first',
'IV steroids and bronchodilators',
'Wait for senior review',
'B',
'Clinical tension pneumothorax (tracheal deviation away, absent breath sounds, hyper-resonance, shock). Do NOT wait for X-ray - immediate needle decompression followed by chest drain. Life-threatening emergency, clinical diagnosis sufficient.',
'easy', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'After needle decompression for tension pneumothorax, there is a rush of air and the patient BP improves from 70/palpable to 95/60 mmHg. What is the next step?',
'Needle decompression is definitive - observe only',
'Insert intercostal chest drain on the same side',
'Remove the needle',
'Repeat needle decompression on opposite side',
'Discharge patient',
'B',
'Needle decompression is temporizing only. Must be followed by intercostal chest drain (typically 28-32 Fr in 4th/5th intercostal space, anterior axillary line) for definitive management. Connect to underwater seal. CXR to confirm position and lung expansion.',
'medium', 'application'),

-- SHOCK MONITORING AND ENDPOINTS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient is being resuscitated for hemorrhagic shock. Which of the following is the BEST indicator that tissue perfusion is improving?',
'Blood pressure returning to 120/80 mmHg',
'Lactate clearance and improving base deficit',
'Heart rate normalizing',
'Warm peripheries',
'Normal respiratory rate',
'B',
'Lactate clearance (fall of greater than 10-20% per 2 hours) and improving base deficit are best markers of adequate resuscitation and tissue perfusion. BP and HR can be compensated or affected by medications. Lactate reflects tissue oxygen debt.',
'medium', 'comprehension'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old man in septic shock has been resuscitated with fluids and noradrenaline. MAP is 70 mmHg. His CVP is 16 mmHg but urine output remains less than 0.3 ml/kg/hr and lactate is 5 mmol/L. What does this suggest about further fluid administration?',
'Give more aggressive fluid boluses',
'Patient may be fluid-replete; further fluids may not help and could cause harm',
'Stop all fluids immediately',
'CVP is not useful in shock',
'Only give albumin from now on',
'B',
'Elevated CVP with persistent hypoperfusion suggests patient is volume-replete but tissue perfusion is still inadequate. Further fluids may cause pulmonary edema without benefit. Focus on vasopressor optimization, consider inotropes, and investigate source control.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in hemorrhagic shock has received 6 units of PRBC. She now has diffuse oozing from wound edges and IV sites, with platelets of 45,000, INR 2.1, and fibrinogen 0.8 g/L. What blood product strategy is indicated?',
'More packed red blood cells only',
'Balanced transfusion with FFP, platelets, and cryoprecipitate for fibrinogen',
'Stop transfusion due to reaction',
'Give recombinant factor VIIa as first line',
'Tranexamic acid only',
'B',
'Dilutional coagulopathy and consumption. Need balanced resuscitation: FFP for clotting factors (INR greater than 1.5), platelets (less than 50,000 with bleeding), cryoprecipitate for fibrinogen (less than 1.5 g/L). Tranexamic acid as adjunct. Warm products.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 40-year-old woman with ruptured ectopic pregnancy and hemorrhagic shock requires emergency surgery. Her blood type is not yet available. What blood product should be transfused immediately?',
'Wait for type and screen results',
'O negative packed red blood cells',
'O positive packed red blood cells',
'Type-specific uncrossmatched blood',
'Crystalloid only until blood type available',
'B',
'O negative is universal donor for RBCs (no A, B, or D antigens). Use in life-threatening emergencies when blood type unknown. For women of childbearing age, O negative is essential to avoid Rh sensitization. Switch to type-specific when available.',
'easy', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient in septic shock has been on escalating doses of noradrenaline for 12 hours. You notice mottled skin on his knees and toes are becoming dusky. Lactate is rising despite MAP of 65 mmHg. What does this indicate?',
'Noradrenaline is working well',
'Peripheral vasoconstriction from high-dose vasopressors causing tissue hypoperfusion - consider adding vasopressin or inotrope',
'Normal finding in elderly',
'Allergic reaction to noradrenaline',
'Need higher doses of noradrenaline',
'B',
'Mottling and digital ischemia suggest excessive peripheral vasoconstriction. High-dose noradrenaline (greater than 0.5 mcg/kg/min) associated with worse outcomes. Consider adding vasopressin (catecholamine-sparing), dobutamine if low cardiac output, and reassess source control.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 28-year-old woman is brought in after a bee sting. She has widespread urticaria but BP is 110/70 and she is not wheezing. An hour later, her BP drops to 80/50 with increasing dyspnea. What phenomenon is this and what is the management?',
'Initial treatment failure - use different antihistamine',
'Biphasic anaphylaxis - give IM adrenaline again and observe for at least 6-12 hours',
'Separate allergic reaction',
'Vasovagal syncope',
'Cardiogenic shock from myocarditis',
'B',
'Biphasic anaphylaxis: Recurrence of symptoms hours after initial resolution without re-exposure (occurs in 1-20% of cases). Treat with adrenaline again. This is why anaphylaxis patients should be observed for at least 6-12 hours, longer if severe.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A known drug abuser is found unconscious with BP 60/40 mmHg, HR 45/min, pinpoint pupils, and respiratory rate of 6/min. Naloxone has been given with improved consciousness but he remains hypotensive with warm peripheries. What additional cause of shock should be considered?',
'Opioid overdose only - give more naloxone',
'Sepsis from IV drug use (endocarditis, abscess) - check for fever, murmurs, injection sites',
'Cardiogenic shock from MI',
'Anaphylaxis from drugs',
'Neurogenic shock from fall',
'B',
'IV drug users at high risk for sepsis from infected injection sites, endocarditis, and abscesses. After addressing opioid toxicity, persistently low BP with warm peripheries suggests distributive (septic) shock. Examine for stigmata of endocarditis, track marks, abscesses.',
'hard', 'application'),

-- PEDIATRIC SHOCK SCENARIO
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 2-year-old child presents with 3 days of diarrhea. He is lethargic, has sunken eyes, dry mucous membranes, and reduced skin turgor. His HR is 160/min, BP 70/40 mmHg, and capillary refill time is 5 seconds. What is the fluid bolus volume and preferred fluid?',
'10 ml/kg of 5% dextrose',
'20 ml/kg of isotonic crystalloid (0.9% saline or Ringer lactate) given over 5-10 minutes',
'50 ml/kg of 0.45% saline',
'5 ml/kg of colloid',
'100 ml/kg over 1 hour',
'B',
'Pediatric shock: Give 20 ml/kg bolus of isotonic crystalloid rapidly (over 5-10 minutes if septic shock, can be over 10-20 minutes if dehydration). Reassess and repeat if needed. Avoid hypotonic fluids (risk of hyponatremia). Dextrose only if hypoglycemic.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'After three 20 ml/kg fluid boluses, a child in septic shock still has poor perfusion with weak pulses and BP 60/40 mmHg. Oxygen is being given and antibiotics administered. What is the next step?',
'Give more fluid boluses',
'Start vasoactive infusion (adrenaline or noradrenaline) - this is fluid-refractory shock',
'Intubate immediately',
'Give blood transfusion',
'Observe for response',
'B',
'Fluid-refractory shock in children: After 40-60 ml/kg of fluid without response, start vasoactive support. Adrenaline or noradrenaline peripheral initially if central access delayed. Consider early intubation but be aware that positive pressure ventilation can worsen shock.',
'hard', 'application');
