-- ============================================================================
-- BATCH 27: Blood and Blood Products - Clinical Scenario Questions (~1020-1060)
-- Topic: Transfusion decisions, reactions, and complications in clinical settings
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- TRANSFUSION DECISION SCENARIOS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old man with stable coronary artery disease is admitted for elective knee replacement. Pre-operative Hb is 8.5 g/dL. He is asymptomatic with no chest pain or dyspnea. What is the most appropriate management?',
'Transfuse 2 units PRBC immediately to reach Hb of 10 g/dL',
'Investigate cause of anemia and consider IV iron; transfusion may not be necessary if asymptomatic',
'Cancel surgery until Hb normalizes spontaneously',
'Transfuse 4 units to achieve Hb of 12 g/dL',
'Proceed with surgery without any intervention',
'B',
'Restrictive transfusion strategy: In stable patients, transfusion trigger of 7-8 g/dL is safe. Pre-operative anemia should be investigated and treated (iron deficiency common). IV iron can raise Hb without transfusion risks. Symptomatic anemia different threshold.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old woman with acute coronary syndrome has Hb of 7.8 g/dL. She complains of increasing chest pain and dyspnea. ECG shows dynamic ST changes. What transfusion threshold is appropriate?',
'Transfuse at Hb less than 7 g/dL only',
'Consider transfusion to maintain Hb above 8-9 g/dL in active cardiac ischemia',
'No transfusion needed regardless of symptoms',
'Transfuse to Hb greater than 12 g/dL',
'Only transfuse if Hb less than 5 g/dL',
'B',
'In acute coronary syndrome, higher transfusion threshold (8-9 g/dL) may be appropriate, especially if symptomatic. Anemia increases myocardial oxygen demand. Balance transfusion risks vs benefits. Liberal strategy debated but reasonable in active ischemia.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A 25-year-old woman is having massive postpartum hemorrhage with estimated blood loss of 2.5 liters. She is group A Rh-negative. Type-specific blood will take 15 minutes. She is hypotensive (BP 70/40). What should you transfuse now?',
'Wait for type-specific blood',
'O negative packed red blood cells',
'O positive packed red blood cells',
'Whole blood of any type',
'Crystalloid only until blood available',
'B',
'Life-threatening hemorrhage with no time for typing: O negative RBCs (universal donor, Rh-negative important for childbearing women to avoid sensitization). Switch to type-specific when available. Activate massive transfusion protocol.',
'easy', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'During a massive transfusion, the patient has received 8 units of PRBCs. Labs show platelets 42,000/uL, INR 1.9, fibrinogen 1.0 g/L. He is actively bleeding from surgical site. What blood products are needed?',
'More PRBCs only',
'Platelets, FFP, and cryoprecipitate to correct coagulopathy',
'FFP only',
'Cryoprecipitate only',
'Stop transfusion and observe',
'B',
'Dilutional and consumptive coagulopathy with active bleeding. Need: Platelets (target greater than 50,000 with active bleeding), FFP (INR greater than 1.5), cryoprecipitate (fibrinogen less than 1.5 g/L). Balanced 1:1:1 ratio improves outcomes in massive transfusion.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient requiring massive transfusion has received blood products via a rapid infuser. He develops hypotension, widened QRS on monitor, and muscle weakness. Core temperature is 35.5 degrees C. What is the most likely cause?',
'Transfusion reaction',
'Hypocalcemia from citrate toxicity - give IV calcium gluconate',
'Hyperkalemia from stored blood',
'Air embolism',
'Anaphylaxis',
'B',
'Citrate toxicity: Citrate anticoagulant in blood products binds calcium. With rapid/massive transfusion, citrate accumulates faster than liver can metabolize. Causes hypocalcemia (prolonged QT, tetany, hypotension). Give IV calcium gluconate 10ml of 10%.',
'hard', 'application'),

-- TRANSFUSION REACTION SCENARIOS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'Fifteen minutes into a blood transfusion, a patient develops fever (38.8 degrees C from baseline 37.2 degrees C), rigors, and lower back pain. BP has dropped from 120/80 to 85/55 mmHg. Urine appears dark red. What is the most likely diagnosis?',
'Febrile non-hemolytic reaction',
'Acute hemolytic transfusion reaction - stop transfusion immediately',
'Bacterial contamination',
'Allergic reaction',
'TRALI',
'B',
'Classic triad of acute hemolytic reaction: Fever, flank/back pain, dark urine (hemoglobinuria). Caused by ABO incompatibility. STOP transfusion, maintain IV access, send samples to blood bank, support BP, maintain urine output to prevent renal failure. Medical emergency.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'After stopping the transfusion for suspected acute hemolytic reaction, what investigations should be performed urgently?',
'No investigations needed',
'Direct antiglobulin test (DAT), repeat blood typing, plasma hemoglobin, urinalysis, and renal function',
'Chest X-ray only',
'CT scan of abdomen',
'Blood cultures only',
'B',
'Investigate hemolytic reaction: DAT (direct Coombs test) positive, check blood bag vs patient ID/blood type, plasma free hemoglobin (pink plasma), urine hemoglobin, renal function, bilirubin, LDH, haptoglobin (decreased). Report to blood bank.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient develops rigors and temperature rises to 38.5 degrees C (from 37 degrees C baseline) during transfusion, but BP is stable and there is no back pain or dark urine. What is the most likely diagnosis and management?',
'Acute hemolytic reaction - stop transfusion permanently',
'Febrile non-hemolytic transfusion reaction - pause transfusion, give antipyretics, may resume if improves',
'TRALI - give steroids',
'Anaphylaxis - give adrenaline',
'Normal response to transfusion',
'B',
'FNHTR: Fever (greater than 1 degree C rise) and/or rigors without hemolysis. Caused by cytokines or WBC antibodies. Pause transfusion, give paracetamol. If symptoms resolve and no hemolysis suspected, may resume slowly. Consider leukoreduced products in future.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'During a platelet transfusion, a patient develops urticaria and pruritus but no dyspnea, hypotension, or angioedema. What is the appropriate action?',
'Stop transfusion and never transfuse again',
'Pause transfusion, give antihistamine, and resume if symptoms resolve',
'Give adrenaline immediately',
'Continue transfusion regardless',
'Give steroids and cancel future transfusions',
'B',
'Mild allergic reaction: Urticaria/itching without anaphylaxis. Pause transfusion, give antihistamine (chlorpheniramine/diphenhydramine). If symptoms resolve, may resume. Premedicate with antihistamine for future transfusions. Washed products if recurrent.',
'easy', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'Five minutes into transfusion, a patient develops stridor, facial angioedema, bronchospasm, and BP drops to 70/40 mmHg. He has IgA deficiency. What is the diagnosis and treatment?',
'FNHTR - give paracetamol',
'Anaphylactic transfusion reaction - stop transfusion, give IM adrenaline, manage as anaphylaxis',
'TRALI - give oxygen only',
'Bacterial contamination - give antibiotics',
'Volume overload - give diuretics',
'B',
'Anaphylactic transfusion reaction: Severe allergic reaction, may occur in IgA-deficient patients with anti-IgA antibodies. Stop transfusion, give IM adrenaline 0.5mg, IV fluids, antihistamines, steroids. Future: IgA-deficient donor products or washed products.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'During transfusion of a platelet unit, a patient suddenly develops high fever (40 degrees C), rigors, vomiting, and becomes hypotensive. The platelet bag appears cloudy with unusual discoloration. What is the most likely diagnosis?',
'Febrile non-hemolytic reaction',
'Bacterial contamination of blood product - stop transfusion, blood cultures, IV antibiotics',
'TRALI',
'Allergic reaction',
'Citrate toxicity',
'B',
'Bacterial contamination: High fever, septic picture, rapid onset. Platelets stored at room temperature are higher risk. Stop transfusion, send bag and patient blood cultures, start broad-spectrum IV antibiotics (cover gram-positives and gram-negatives). Notify blood bank.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'Two hours after completing a transfusion, a patient develops acute respiratory distress with SpO2 82%, bilateral lung infiltrates on CXR, but no elevated JVP or signs of fluid overload. BNP is normal. What is the diagnosis?',
'Cardiogenic pulmonary edema - give diuretics',
'Transfusion-related acute lung injury (TRALI) - supportive care with oxygen, possible ventilation',
'TACO (transfusion-associated circulatory overload)',
'Pneumonia - give antibiotics',
'Pulmonary embolism',
'B',
'TRALI: Non-cardiogenic pulmonary edema within 6 hours of transfusion. Bilateral infiltrates, hypoxia, no evidence of volume overload (normal BNP, no elevated JVP). Supportive treatment with oxygen, may need mechanical ventilation. Usually resolves 48-96 hours.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient with heart failure receives 2 units of PRBCs. Shortly after, she develops dyspnea, elevated JVP, bilateral crackles, and pink frothy sputum. BNP is markedly elevated. What is the diagnosis and management?',
'TRALI - supportive care only',
'TACO (transfusion-associated circulatory overload) - stop transfusion, sit upright, oxygen, diuretics',
'Allergic reaction - antihistamines',
'Acute hemolytic reaction',
'Bacterial sepsis',
'B',
'TACO: Volume overload in susceptible patients (elderly, cardiac/renal disease). Elevated JVP, pulmonary edema, elevated BNP differentiates from TRALI. Management: Stop transfusion, upright positioning, oxygen, IV diuretics. Transfuse slowly with diuretic cover in future.',
'medium', 'application'),

-- SPECIAL TRANSFUSION SCENARIOS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A Jehovah Witness patient with GI bleeding has Hb of 5 g/dL and is hypotensive. She adamantly refuses blood transfusion but accepts iron and EPO. She is fully competent. What is the appropriate management?',
'Transfuse as it is an emergency',
'Respect her refusal, maximize non-blood alternatives: IV iron, EPO, minimize blood loss, cell salvage if acceptable',
'Obtain court order to transfuse',
'Discharge patient',
'Only transfuse if she becomes unconscious',
'B',
'Competent adult patients have right to refuse treatment including blood. Document discussion, maximize alternatives: high-dose IV iron (ferric carboxymaltose), EPO, minimize blood draws, cell salvage if acceptable to patient, hemostatic agents, meticulous surgical technique.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient requiring chronic transfusions for beta-thalassemia major has received over 30 units of blood. He now has elevated liver enzymes and serum ferritin of 3500 ng/mL. What complication has developed and how is it managed?',
'Viral hepatitis - antiviral therapy',
'Transfusion iron overload (hemosiderosis) - iron chelation therapy (deferasirox or deferoxamine)',
'Alloimmunization - extended matching',
'GVHD - steroids',
'Citrate toxicity - calcium',
'B',
'Iron overload: Each unit of RBCs contains 200-250mg iron. Body has no excretion mechanism. Leads to liver, cardiac, endocrine damage. Ferritin greater than 1000 indicates overload. Chelation: Deferoxamine (IV/SC), deferasirox (oral), deferiprone. Monitor ferritin and organ function.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with sickle cell disease has received multiple transfusions. Her latest crossmatch shows she has developed antibodies to C, E, and Kell antigens, making compatible blood difficult to find. What preventive strategy should have been used?',
'Transfuse any compatible blood',
'Extended phenotype matching (Rh and Kell antigen matching) from the beginning',
'Leukoreduction only',
'Irradiated blood only',
'Washed red cells only',
'B',
'Alloimmunization: Common in chronically transfused patients (sickle cell, thalassemia). Prevention: Extended antigen matching for Rh (C, c, E, e) and Kell antigens from the start. Once alloimmunized, finding compatible blood becomes increasingly difficult.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A bone marrow transplant patient requires platelet transfusion. To prevent transfusion-associated graft-versus-host disease (TA-GVHD), what modification should be made to the blood product?',
'Leukoreduction',
'Irradiation of blood products',
'Washing',
'Volume reduction',
'CMV-negative products',
'B',
'TA-GVHD: Donor lymphocytes attack immunocompromised recipient. Almost always fatal. Irradiation (25-50 Gy) inactivates donor lymphocytes. Required for: BMT patients, congenital immunodeficiency, HLA-matched products, directed donations from relatives, Hodgkin lymphoma.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A pregnant woman at 28 weeks is Rh-negative and her partner is Rh-positive. Routine antibody screen is negative. What should be given and why?',
'No intervention needed until delivery',
'Anti-D immunoglobulin (Rho-GAM) at 28 weeks to prevent Rh sensitization',
'Transfuse with Rh-positive blood',
'Induce delivery early',
'Give steroids for fetal lung maturity',
'B',
'Routine antenatal anti-D prophylaxis at 28 weeks (some protocols also at 34 weeks) prevents Rh sensitization from fetomaternal hemorrhage. Given to all Rh-negative women with Rh-positive or unknown partner. Also after sensitizing events (amniocentesis, trauma, delivery).',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient receiving chemotherapy has a positive CMV IgG. He requires platelet transfusion. What type of platelet product should be used?',
'CMV-negative platelets only',
'Standard leukoreduced platelets are acceptable as patient is already CMV-seropositive',
'Non-leukoreduced platelets',
'Irradiated only',
'Washed platelets',
'B',
'CMV-seronegative products are reserved for CMV-seronegative recipients at risk (BMT, pregnant women, premature infants). CMV-seropositive patients already infected, so standard leukoreduced products acceptable (leukoreduction reduces CMV risk significantly).',
'hard', 'application'),

-- FFP AND COAGULATION SCENARIOS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient on warfarin for mechanical heart valve has INR of 8.5 with no bleeding. What is the appropriate management?',
'Give FFP immediately',
'Hold warfarin and give oral vitamin K 1-2.5mg; recheck INR in 24 hours',
'Give prothrombin complex concentrate',
'Give vitamin K 10mg IV immediately',
'No intervention needed',
'B',
'INR greater than 9 without bleeding: Hold warfarin, give low-dose oral vitamin K (1-2.5mg). IV vitamin K reserved for bleeding or very high INR. FFP/PCC reserved for serious bleeding. High-dose vitamin K can make re-anticoagulation difficult in valve patients.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient on warfarin (INR 4.2) presents with large intracerebral hemorrhage. What is the most appropriate reversal strategy?',
'FFP 4 units only',
'4-factor PCC plus IV vitamin K 10mg for immediate and sustained reversal',
'Oral vitamin K and observe',
'Hold warfarin and wait',
'Tranexamic acid only',
'B',
'Life-threatening bleeding on warfarin: 4-factor PCC (25-50 units/kg) provides immediate reversal (minutes) plus IV vitamin K 10mg for sustained reversal (takes 6-12 hours for effect). PCC preferred over FFP (faster, smaller volume, more complete reversal).',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient on dabigatran presents with major GI bleeding. Last dose was 4 hours ago. Standard coagulation tests are unhelpful. What reversal agent is available?',
'FFP',
'Idarucizumab (Praxbind) - specific reversal agent for dabigatran',
'Vitamin K',
'PCC (limited effectiveness)',
'No reversal agent exists',
'B',
'Idarucizumab: Specific reversal agent for dabigatran (direct thrombin inhibitor). Monoclonal antibody fragment. Give 5g IV for immediate reversal. For factor Xa inhibitors (rivaroxaban, apixaban), andexanet alfa is specific reversal; PCC can be used if unavailable.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with hemophilia A (factor VIII deficiency) presents with hemarthrosis of the knee after minor trauma. His baseline factor VIII is 2%. What is the target factor level and treatment?',
'Target 100% - give massive transfusion',
'Target 40-60% - give factor VIII concentrate',
'Give FFP only',
'Give platelets',
'Give cryoprecipitate only',
'B',
'Hemophilia A hemarthrosis: Target factor VIII 40-60% for joint bleeds. Give recombinant or plasma-derived factor VIII concentrate. Calculate dose: (target % - baseline %) x weight(kg) x 0.5 = units required. Repeat q12h as needed. RICE, avoid aspiration.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A 10-year-old boy with hemophilia A needs emergency appendectomy. His factor VIII level is less than 1%. What perioperative factor replacement is required?',
'No replacement needed for minor surgery',
'Pre-operative factor VIII to achieve 80-100%, maintain above 50% for 7-10 days post-op',
'Give FFP throughout surgery',
'Give cryoprecipitate once',
'Wait until bleeding occurs to treat',
'B',
'Major surgery in severe hemophilia: Pre-op factor level 80-100%. Maintain greater than 50% for 7-10 days (major surgery) or 3-5 days (minor). Requires repeated dosing or continuous infusion. Involve hematology. Monitor factor levels and for inhibitor development.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A woman with von Willebrand disease type 1 needs dental extraction. What treatment options should be considered?',
'No treatment needed',
'DDAVP (desmopressin) trial, may also use tranexamic acid as adjunct',
'Factor VIII concentrate',
'Platelet transfusion',
'Whole blood transfusion',
'B',
'VWD type 1: DDAVP releases stored vWF and factor VIII (give 0.3 mcg/kg IV/SC or intranasal). Do test dose to confirm response. Tranexamic acid helps as adjunct. For more severe disease or non-responders, vWF-containing factor concentrate.',
'medium', 'application'),

-- PLATELET TRANSFUSION SCENARIOS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with acute leukemia has platelet count of 8,000/uL after chemotherapy. She has no bleeding and needs lumbar puncture for intrathecal chemotherapy. What is the appropriate platelet threshold?',
'Transfuse if less than 20,000',
'Transfuse to achieve platelets greater than 50,000 before lumbar puncture',
'No transfusion needed',
'Transfuse to greater than 100,000',
'Transfuse only if active bleeding',
'B',
'Platelet thresholds: Prophylactic (no bleeding) - 10,000. Minor procedures (LP, central line) - greater than 50,000. Major surgery - greater than 50,000, neurosurgery greater than 100,000. Transfuse 1 pooled unit (4-6 random donor) or 1 apheresis unit.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient received platelet transfusion but repeat count 1 hour later shows no increment (pre: 12,000, post: 14,000). He has had multiple prior transfusions. What is the likely cause and solution?',
'Incorrect platelet dose',
'Platelet refractoriness likely from HLA alloimmunization - use HLA-matched platelets',
'Platelets were expired',
'Patient does not need platelets',
'Give more platelets from same donor',
'B',
'Platelet refractoriness: Poor increment after transfusion. Immune causes: HLA antibodies (from prior transfusions/pregnancy). Solution: HLA-matched or crossmatch-compatible platelets. Non-immune causes: Fever, sepsis, splenomegaly, DIC, medications - treat underlying cause.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with immune thrombocytopenic purpura (ITP) has platelet count of 5,000/uL with mucosal bleeding. Should platelets be transfused?',
'Never transfuse in ITP',
'Yes, transfuse for life-threatening or serious bleeding along with ITP-specific therapy',
'Only if count less than 1,000',
'Platelets make ITP worse',
'Transfuse only with steroids',
'B',
'ITP with serious bleeding: Platelets can be transfused despite autoimmune destruction. They may be consumed rapidly but can provide temporary hemostasis. Give alongside ITP therapy (IVIG, steroids, TPO agonists). For minor bleeding, treat ITP without transfusion.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient develops heparin-induced thrombocytopenia (HIT) with platelet count dropping from 180,000 to 55,000 and new DVT. What is the management regarding platelet transfusion?',
'Transfuse platelets to prevent bleeding',
'Avoid platelet transfusion; stop all heparin and anticoagulate with non-heparin agent',
'Continue heparin and add platelets',
'No specific treatment needed',
'Give low molecular weight heparin instead',
'B',
'HIT: Prothrombotic condition. Stop ALL heparin (including flushes). Anticoagulate with non-heparin agent (argatroban, fondaparinux, DOACs). Avoid platelet transfusion as it may worsen thrombosis. Do not wait for confirmatory tests before treating.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient with severe bleeding has received 10 units of PRBCs. Point-of-care testing shows severely prolonged clotting times and fibrinogen of 0.6 g/L despite 4 units of FFP. What additional product is needed?',
'More FFP',
'Cryoprecipitate to increase fibrinogen',
'More PRBCs',
'Platelets only',
'Vitamin K',
'B',
'Cryoprecipitate: Rich source of fibrinogen, factor VIII, vWF, factor XIII. Give when fibrinogen less than 1.5 g/L (or 2 g/L in massive bleeding). Each pool (10 units) raises fibrinogen by 0.5-1 g/L. FFP contains less concentrated fibrinogen.',
'medium', 'application');
