-- ============================================================================
-- BATCH 28: Fluid and Electrolytes - Clinical Scenario Questions (~1050-1090)
-- Topic: Clinical scenarios for fluid/electrolyte management
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- HYPONATREMIA SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old woman on thiazide diuretic presents with confusion and lethargy. Serum sodium is 118 mEq/L. She had a seizure in the ambulance. Urine osmolality is 500 mOsm/kg, urine sodium 45 mEq/L. What is the immediate management?',
'Fluid restriction',
'Hypertonic saline (3%) to raise sodium by 1-2 mEq/L/hour until symptoms resolve, then slower correction',
'Normal saline rapid bolus',
'Demeclocycline',
'Observation only',
'B',
'Severe symptomatic hyponatremia with seizures is an emergency. Give 3% saline 100-150ml bolus to rapidly raise sodium 4-6 mEq/L to stop seizures. Then slow correction (less than 8-10 mEq/24h total) to avoid osmotic demyelination syndrome.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with SIADH from lung cancer has chronic hyponatremia (Na 124 mEq/L) with mild fatigue but no severe symptoms. What is the appropriate first-line treatment?',
'Hypertonic saline immediately',
'Fluid restriction to 800-1000 ml/day',
'IV normal saline',
'Diuretics',
'No treatment needed',
'B',
'Chronic asymptomatic SIADH: Fluid restriction is first-line. Restrict to 800-1000 ml/day (or 500ml below urine output). If refractory, consider salt tablets, loop diuretics, demeclocycline, or vaptans. Avoid rapid correction in chronic hyponatremia.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old man with heart failure on furosemide has sodium of 128 mEq/L. He has peripheral edema, elevated JVP, and ascites. His urine sodium is 8 mEq/L. What is the underlying mechanism and treatment?',
'SIADH - fluid restrict only',
'Hypervolemic hyponatremia - treat underlying heart failure with diuretics and sodium/water restriction',
'Hypovolemic hyponatremia - give saline',
'Pseudohyponatremia - no treatment',
'Adrenal insufficiency - give steroids',
'B',
'Hypervolemic hyponatremia (CHF, cirrhosis, nephrotic syndrome): Total body sodium increased but water more so. Low urine sodium (less than 10) reflects avid renal retention. Treat underlying condition, diuretics, fluid/sodium restriction. Not SIADH.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A marathon runner collapses at the finish line with confusion. He drank large amounts of water during the race. Sodium is 122 mEq/L, he is euvolemic on exam. What is the likely cause and concern about treatment?',
'Dehydration - give IV fluids',
'Exercise-associated hyponatremia from excess water intake - risk of overcorrection with fluid restriction',
'Heat stroke - cool the patient',
'Hyperglycemia - check glucose',
'Rhabdomyolysis',
'B',
'Exercise-associated hyponatremia: Excess free water intake during exercise. Often euvolemic or hypervolemic. May self-correct rapidly with fluid restriction (arginine vasopressin suppresses, kidneys excrete water). Monitor sodium closely to avoid overcorrection.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'During treatment of severe hyponatremia, a patient sodium rises from 108 to 120 mEq/L in 12 hours. What complication are you concerned about and what should you do?',
'Cerebral edema - give more hypertonic saline',
'Osmotic demyelination syndrome - lower sodium with desmopressin and D5W, aim for slower correction',
'Cardiac arrhythmia - give potassium',
'Pulmonary edema - give diuretics',
'No concern with this rate',
'B',
'Overcorrection (greater than 8-10 mEq/L in 24 hours) risks osmotic demyelination syndrome (central pontine myelinolysis). Re-lower sodium using desmopressin (prevents water excretion) and D5W infusion. Target correction 6-8 mEq/L per day in chronic cases.',
'hard', 'application'),

-- HYPERNATREMIA SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'An 80-year-old nursing home resident is brought in with altered consciousness. Sodium is 162 mEq/L, BUN/creatinine elevated. She is lethargic with dry mucous membranes and decreased skin turgor. What fluid should be given?',
'Hypertonic saline',
'Hypotonic fluids (D5W or 0.45% saline) after initial resuscitation with isotonic saline if hemodynamically unstable',
'3% saline',
'Lactated Ringer only',
'Oral water only',
'B',
'Hypernatremia with hypovolemia: First stabilize with isotonic saline if hypotensive. Then correct free water deficit with hypotonic fluids (D5W, 0.45% saline). Correct slowly: no more than 10-12 mEq/L per day to avoid cerebral edema.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A neurosurgical patient develops polyuria (6L/day) and sodium rises from 140 to 158 mEq/L over 48 hours. Urine is very dilute (osmolality 80 mOsm/kg). What is the diagnosis and treatment?',
'SIADH - fluid restrict',
'Central diabetes insipidus - give desmopressin (DDAVP) and replace free water',
'Diabetes mellitus - insulin',
'Psychogenic polydipsia',
'Cerebral salt wasting',
'B',
'Central DI: ADH deficiency (post-neurosurgery, head trauma). Dilute urine despite hyperosmolar serum. Treatment: DDAVP (intranasal or IV) replaces ADH, plus free water replacement. Calculate free water deficit and replace over 48-72 hours.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with sodium of 168 mEq/L has been hypernatremic for 5 days. You calculate a free water deficit of 5 liters. What is the safest rate of correction?',
'Replace all 5 liters over 6 hours',
'Replace over 48-72 hours, lowering sodium no more than 10-12 mEq/L per day',
'Replace over 2 hours',
'No need to replace deficit',
'Give hypertonic saline',
'B',
'Chronic hypernatremia: Brain adapts by generating idiogenic osmoles. Rapid correction causes cerebral edema. Correct no faster than 10-12 mEq/L per day. Replace deficit over 48-72 hours. Monitor sodium frequently (every 4-6 hours initially).',
'hard', 'application'),

-- HYPOKALEMIA SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with repeated vomiting presents with muscle weakness. Potassium is 2.4 mEq/L, magnesium 1.2 mg/dL. ECG shows U waves and flattened T waves. What is the treatment priority?',
'Potassium replacement orally only',
'IV potassium replacement AND magnesium replacement (hypokalemia resistant to correction if Mg low)',
'Calcium replacement',
'Sodium bicarbonate',
'Observation',
'B',
'Severe hypokalemia with ECG changes: IV potassium needed (max 10-20 mEq/hr peripherally, 40 mEq/hr central with monitoring). Magnesium must also be replaced - hypokalemia is refractory to treatment if magnesium is low. Replace both simultaneously.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient on digoxin for atrial fibrillation develops nausea and visual disturbances. Potassium is 2.9 mEq/L. ECG shows new ventricular ectopics. What is the concern and management priority?',
'Normal digoxin effect - continue medication',
'Hypokalemia precipitating digoxin toxicity - stop digoxin, replace potassium, monitor',
'Hyperkalemia - give calcium',
'Stroke - CT head',
'Myocardial infarction - cath lab',
'B',
'Hypokalemia potentiates digoxin toxicity (both affect Na/K-ATPase). Stop digoxin, aggressively replace potassium, cardiac monitoring. Digibind for severe toxicity with arrhythmias. Digoxin level may be normal but toxicity present if potassium low.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic hypokalemia (K 2.8 mEq/L) also has metabolic alkalosis and hypertension. He is not on diuretics. Blood pressure is 170/100. What condition should be suspected?',
'Diuretic abuse',
'Primary hyperaldosteronism (Conn syndrome) - check aldosterone and renin levels',
'Renal tubular acidosis',
'Addison disease',
'Gitelman syndrome',
'B',
'Hypokalemia + hypertension + metabolic alkalosis suggests mineralocorticoid excess. Primary hyperaldosteronism: high aldosterone, suppressed renin. Check aldosterone-to-renin ratio. Other causes: Cushing syndrome, renovascular disease, licorice.',
'hard', 'application'),

-- HYPERKALEMIA SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A dialysis patient presents with weakness. Potassium is 7.2 mEq/L. ECG shows peaked T waves, widened QRS, and loss of P waves. What is the immediate first-line treatment?',
'IV insulin and glucose',
'IV calcium gluconate 10ml of 10% to stabilize the myocardium',
'Oral kayexalate',
'Nebulized salbutamol only',
'Emergency dialysis before any treatment',
'B',
'ECG changes in hyperkalemia are life-threatening. Calcium gluconate is given FIRST - it does not lower potassium but stabilizes cardiac membrane within 1-3 minutes. Then give treatments to shift K into cells (insulin/glucose, salbutamol) and remove K (dialysis, kayexalate).',
'easy', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'After giving calcium gluconate for hyperkalemia (K 7.0), what treatments shift potassium into cells?',
'Calcium gluconate shifts potassium',
'Insulin with glucose and nebulized salbutamol',
'Furosemide',
'Sodium polystyrene sulfonate (kayexalate)',
'Hemodialysis',
'B',
'Shift K intracellularly: Insulin 10 units with 25g glucose (works in 15-30 min, lasts 4-6 hours), nebulized salbutamol 10-20mg (works in 30 min). Bicarbonate if acidotic. These are temporizing - still need to remove potassium from body (dialysis, resins, diuretics).',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with potassium of 6.2 mEq/L has a normal ECG. He has chronic kidney disease stage 4 and mild metabolic acidosis. What is the treatment approach?',
'Emergency dialysis',
'Remove exacerbating factors, dietary restriction, consider oral potassium binders; recheck K; dialysis if refractory',
'No treatment needed with normal ECG',
'IV calcium gluconate immediately',
'Hypertonic saline',
'B',
'Moderate hyperkalemia without ECG changes: Stop offending drugs (ACEi, ARB, K-sparing diuretics, NSAIDs), restrict dietary K, consider oral binders (calcium resonium, patiromer), loop diuretics if volume tolerated. Treat acidosis. Recheck and dialysis if refractory.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A sample shows potassium of 6.8 mEq/L but the patient is completely asymptomatic with normal ECG. The blood was drawn with difficulty. What should you consider?',
'Treat immediately regardless',
'Pseudohyperkalemia from hemolysis - redraw sample carefully and recheck',
'The ECG must be wrong',
'Patient has adapted',
'This is impossible',
'B',
'Pseudohyperkalemia: Falsely elevated K from in-vitro hemolysis (difficult draw, tourniquets, fist clenching, delayed processing). If clinical picture inconsistent, redraw sample carefully (no tourniquet, no clenching, process promptly). Confirms spurious result.',
'easy', 'application'),

-- METABOLIC ACIDOSIS SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient presents with vomiting, abdominal pain, and Kussmaul breathing. Labs show pH 7.15, HCO3 8 mEq/L, glucose 450 mg/dL, ketones positive. Sodium 130, chloride 98. What is the anion gap and diagnosis?',
'Normal anion gap acidosis - diarrhea',
'High anion gap metabolic acidosis (AG = 24) - diabetic ketoacidosis',
'Respiratory acidosis',
'Metabolic alkalosis',
'Normal acid-base status',
'B',
'Anion gap = Na - (Cl + HCO3) = 130 - (98 + 8) = 24 (elevated, normal 8-12). DKA: High AG acidosis from ketoacids. Treatment: IV fluids, insulin infusion, potassium replacement, monitor glucose and AG for resolution.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient in DKA has initial potassium of 5.8 mEq/L but is clinically depleted (total body K deficit). After starting insulin, what do you expect and how should you manage?',
'Potassium will rise further - do not supplement',
'Potassium will drop rapidly as insulin drives K into cells - add K to IV fluids once level below 5.3 and urine output confirmed',
'No change in potassium expected',
'Give more insulin to lower K faster',
'Give calcium for elevated K',
'B',
'DKA: Initial K may be normal/high despite total body depletion (acidosis shifts K out of cells). Insulin drives K back into cells, causing rapid drop. Add 20-40 mEq KCl per liter once K less than 5.3 and patient urinating. Monitor closely.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic diarrhea has pH 7.28, HCO3 14 mEq/L, normal anion gap, and potassium 2.8 mEq/L. What type of acidosis is this and what is the mechanism?',
'High anion gap acidosis from lactate',
'Normal anion gap (hyperchloremic) metabolic acidosis from GI bicarbonate loss',
'Respiratory acidosis',
'Metabolic alkalosis',
'Mixed disorder',
'B',
'Non-anion gap metabolic acidosis: Loss of bicarbonate (diarrhea, RTA, ureterosigmoidostomy) or failure to excrete acid. GI losses of HCO3-rich fluid with compensatory Cl retention. Treatment: Treat underlying cause, replace bicarbonate and potassium.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient has pH 7.10, lactate 12 mmol/L, and BP 70/40. What is the primary treatment for this lactic acidosis?',
'Sodium bicarbonate infusion',
'Treat the underlying cause (restore tissue perfusion with fluids and vasopressors)',
'Hemodialysis',
'Mechanical ventilation',
'Thiamine infusion',
'B',
'Type A lactic acidosis from tissue hypoperfusion. Treatment is restoring perfusion (fluids, vasopressors, inotropes). Bicarbonate controversial and may worsen outcomes - consider only if pH less than 7.0 and hemodynamically unstable. Find and treat source.',
'medium', 'application'),

-- METABOLIC ALKALOSIS SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with prolonged NG suction has pH 7.52, HCO3 38 mEq/L, potassium 2.6 mEq/L, chloride 88 mEq/L. What is the diagnosis and treatment?',
'Respiratory alkalosis - sedate patient',
'Chloride-responsive metabolic alkalosis - give normal saline with potassium chloride',
'Primary hyperaldosteronism',
'Milk-alkali syndrome',
'No treatment needed',
'B',
'Contraction alkalosis from gastric losses (HCl loss). Chloride-responsive: Urine Cl less than 20 mEq/L. Treatment: Volume repletion with NS (provides chloride), potassium chloride replacement. Kidneys will excrete excess HCO3 once volume and Cl restored.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with resistant hypertension and hypokalemia has metabolic alkalosis. Urine chloride is 45 mEq/L and does not respond to saline. What is the likely cause?',
'Vomiting',
'Chloride-resistant alkalosis from mineralocorticoid excess (hyperaldosteronism, Cushing)',
'Diuretic use',
'Bartter syndrome',
'Antacid abuse',
'B',
'Chloride-resistant metabolic alkalosis (urine Cl greater than 20 mEq/L, does not respond to saline): Usually from mineralocorticoid excess. Evaluate for primary hyperaldosteronism (ARR), Cushing, Liddle syndrome. Treat underlying cause. Potassium-sparing diuretics may help.',
'hard', 'application'),

-- FLUID THERAPY SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A 70 kg man is admitted for elective bowel surgery. He is nil by mouth. What is his approximate daily maintenance fluid requirement?',
'1000 ml/day',
'2500-3000 ml/day (approximately 30-35 ml/kg/day or 4-2-1 rule)',
'5000 ml/day',
'500 ml/day',
'No fluids needed if NPO for surgery',
'B',
'Maintenance fluid: 4-2-1 rule (4ml/kg for first 10kg + 2ml/kg for next 10kg + 1ml/kg for remaining) gives approximately 2500ml/day for 70kg. Or 30-35ml/kg/day. Adjust for fever, GI losses, renal function. Also need Na 1-2 mEq/kg, K 1 mEq/kg, glucose.',
'easy', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A postoperative patient has been receiving 3L of 0.9% saline daily for 4 days. He now has peripheral edema and labs show sodium 148 mEq/L and chloride 115 mEq/L. What has happened?',
'Normal postoperative response',
'Hyperchloremic hypernatremia from excessive normal saline - switch to balanced crystalloid or hypotonic fluid',
'Heart failure',
'Renal failure',
'SIADH',
'B',
'Excessive 0.9% saline: NS has 154 mEq/L each of Na and Cl (supra-physiological). Can cause hyperchloremia, hypernatremia, and normal AG metabolic acidosis. Balanced crystalloids (Ringer lactate, Plasmalyte) are more physiological for maintenance.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A septic patient has received 4 liters of crystalloid but remains hypotensive. Bedside ultrasound shows good LV function and IVC is collapsing with respiration. What does this suggest?',
'Patient is volume overloaded - give diuretics',
'Patient is still fluid-responsive - give more fluid before vasopressors',
'Start vasopressors immediately without more fluid',
'Patient needs inotropes',
'Ultrasound is not useful here',
'B',
'Collapsing IVC with respiration suggests hypovolemia and fluid responsiveness. Continue fluid resuscitation. Non-collapsing IVC suggests euvolemia or overload. Dynamic assessments (IVC, pulse pressure variation) help guide fluid therapy beyond initial resuscitation.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient requiring large volume resuscitation is receiving Ringer lactate. He also has liver failure. Is there a concern with lactate-containing fluids?',
'Lactate will accumulate causing acidosis',
'Lactate in balanced crystalloids is metabolized to bicarbonate and does not worsen lactic acidosis; it is safe in liver disease',
'Never use Ringer lactate in liver failure',
'Switch to normal saline for liver failure',
'Use dextrose instead',
'B',
'Lactate in Ringer lactate (28 mM) is metabolized to bicarbonate (has alkalinizing effect, opposite of causing acidosis). Even in liver failure, extrahepatic metabolism occurs. Studies show balanced crystalloids safe in liver disease. May actually be preferred over NS.',
'hard', 'comprehension'),

-- CALCIUM DISORDERS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient post-thyroidectomy develops perioral numbness, carpopedal spasm, and positive Chvostek sign. Calcium is 6.8 mg/dL. What is the diagnosis and treatment?',
'Hyperparathyroidism - surgery',
'Symptomatic hypocalcemia - IV calcium gluconate 10ml of 10% slowly with cardiac monitoring',
'Hypercalcemia - IV fluids',
'Tetanus - immunization',
'Anxiety - reassurance',
'B',
'Post-thyroidectomy hypocalcemia (parathyroid damage or hungry bone syndrome). Symptomatic hypocalcemia: Give IV calcium gluconate 10ml of 10% over 10 minutes with cardiac monitoring (can cause arrhythmias). Follow with calcium infusion or oral calcium plus vitamin D.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with metastatic lung cancer presents with confusion, constipation, and polyuria. Calcium is 14.2 mg/dL. What is the initial management?',
'Oral calcium supplements',
'Aggressive IV saline hydration followed by IV bisphosphonate',
'Calcitonin only',
'Steroids immediately',
'Dialysis',
'B',
'Severe hypercalcemia: IV saline hydration first (restore volume, increase urinary calcium excretion). Then IV bisphosphonate (zoledronic acid or pamidronate - takes 2-4 days for effect). Calcitonin (rapid but transient effect). Loop diuretics only after euvolemia.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient has hypocalcemia that is not responding to IV calcium replacement. Magnesium is 1.0 mg/dL (low). Why is this important?',
'Magnesium has no relation to calcium',
'Hypomagnesemia causes PTH resistance and impairs PTH secretion - must correct Mg for Ca to normalize',
'Need higher doses of calcium',
'Give phosphorus instead',
'Check vitamin D only',
'B',
'Hypomagnesemia causes refractory hypocalcemia: Impairs PTH secretion and causes PTH resistance at target organs. Must replace magnesium for calcium to normalize. Common in malnutrition, alcoholism, GI losses, certain medications.',
'hard', 'comprehension'),

-- PHOSPHATE DISORDERS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A malnourished alcoholic patient is started on TPN feeding. On day 3, he develops weakness, respiratory failure, and seizures. Phosphate is 0.8 mg/dL, potassium 2.6 mEq/L. What syndrome is this?',
'Alcohol withdrawal',
'Refeeding syndrome with severe hypophosphatemia',
'Wernicke encephalopathy',
'DKA',
'Hepatic encephalopathy',
'B',
'Refeeding syndrome: Insulin surge from carbohydrate refeeding shifts phosphate (and K, Mg) into cells. Severe hypophosphatemia causes respiratory failure, cardiac dysfunction, rhabdomyolysis, seizures. Prevent by starting feeds slowly and replacing electrolytes first.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with CKD stage 5 has phosphate of 8.5 mg/dL and calcium of 8.2 mg/dL. PTH is markedly elevated. What is the diagnosis and management approach?',
'Primary hyperparathyroidism - surgery',
'Secondary hyperparathyroidism from CKD - phosphate binders, vitamin D analogs, dietary restriction, dialysis',
'Hypophosphatemia - give phosphate',
'Hypoparathyroidism - give PTH',
'No treatment needed',
'B',
'CKD-MBD: Kidney cannot excrete phosphate or activate vitamin D. High phosphate, low calcium, and very high PTH (secondary hyperparathyroidism). Management: Phosphate binders (calcium-free preferred), dietary restriction, active vitamin D, calcimimetics, adequate dialysis.',
'hard', 'application');
