-- ============================================================================
-- BATCH 29: Leg Ulcers - Clinical Scenario Questions (~1080-1120)
-- Topic: Diagnosis and management of different ulcer types
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- VENOUS ULCER SCENARIOS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old obese woman presents with a painless ulcer above the medial malleolus. She has visible varicose veins, brownish skin discoloration around the ankle, and ankle swelling worse at the end of the day. The ulcer has irregular edges with sloping borders and granulation tissue at the base. What is the most likely diagnosis?',
'Arterial ulcer',
'Venous ulcer',
'Diabetic neuropathic ulcer',
'Malignant ulcer',
'Pressure ulcer',
'B',
'Classic venous ulcer: Gaiter area location (medial malleolus), shallow with irregular sloping edges, surrounding lipodermatosclerosis (hemosiderin staining), varicose veins, edema, usually painless or mild pain relieved by elevation.',
'easy', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a venous ulcer has an ABPI of 0.95. You want to initiate compression therapy. What compression level and system would be most appropriate?',
'No compression - ABPI is too low',
'Multi-layer high compression bandaging (40 mmHg at ankle)',
'Light compression only (10-15 mmHg)',
'Compression is contraindicated in venous ulcers',
'Only elastic stockings without bandaging',
'B',
'ABPI greater than 0.8 allows full compression. Multi-layer high compression (40 mmHg at ankle, graduated to lower pressure at calf) is gold standard for venous ulcers. Reduces edema, improves venous return, promotes healing. Compression is cornerstone of venous ulcer treatment.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a large venous ulcer has an ABPI of 0.6 on the affected leg. She has significant edema. How should you modify the treatment plan?',
'Apply full high compression as usual',
'Use reduced compression (modified compression 20-30 mmHg) with specialist vascular input',
'No compression at all - treat as purely arterial',
'Apply high compression to the other leg only',
'Immediate bypass surgery',
'B',
'Mixed arterial-venous disease (ABPI 0.5-0.8): Reduced/modified compression with close monitoring. Below 0.5, compression is contraindicated. Needs vascular assessment. Balance between managing venous disease without compromising arterial perfusion.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 58-year-old man has recurrent venous ulcers despite good compression compliance. Duplex scan shows saphenofemoral junction incompetence. What intervention may reduce ulcer recurrence?',
'Compression alone is sufficient',
'Superficial venous ablation (endovenous laser or radiofrequency) or surgery',
'Deep vein bypass',
'Amputation',
'Long-term antibiotics',
'B',
'EVRA trial: Early endovenous ablation of superficial venous reflux plus compression heals venous ulcers faster and reduces recurrence compared to compression alone. Treat underlying venous reflux - endovenous thermal ablation, foam sclerotherapy, or surgery.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a healing venous ulcer asks what she can do to prevent recurrence after the ulcer heals. What is the most important long-term measure?',
'Nothing after healing',
'Lifelong graduated compression stockings (Class 2, 25-35 mmHg)',
'Antibiotics prophylaxis',
'Monthly wound dressings',
'Strict bed rest',
'B',
'Compression stockings are essential for preventing venous ulcer recurrence. Class 2 (25-35 mmHg) below-knee stockings. Replace every 6 months. Also: leg elevation, exercise, weight management, treat underlying reflux. Without compression, 70% recur within 1 year.',
'medium', 'application'),

-- ARTERIAL ULCER SCENARIOS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 72-year-old male smoker with diabetes presents with a painful ulcer on his lateral ankle extending to the foot dorsum. The pain is worse at night and relieved by hanging the leg over the bed. The foot is cool with absent pedal pulses. The ulcer has a punched-out appearance with pale base. What is the diagnosis?',
'Venous ulcer',
'Arterial (ischemic) ulcer',
'Neuropathic ulcer',
'Vasculitic ulcer',
'Pyoderma gangrenosum',
'B',
'Arterial ulcer: Distal location (toes, lateral foot, pressure areas), punched-out edges, pale/necrotic base, painful (worse with elevation, better with dependency due to gravity-assisted perfusion), cool foot, absent pulses. History of smoking, diabetes, claudication.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'The patient with suspected arterial ulcer has an ABPI of 0.4. What is the interpretation and next management step?',
'Normal - proceed with compression',
'Severe peripheral arterial disease - urgent vascular referral for revascularization assessment',
'Mild disease - optimize risk factors only',
'ABPI not useful in diabetics',
'Start compression therapy',
'B',
'ABPI less than 0.5 indicates severe PAD with high risk of limb loss. Urgent vascular referral needed. Will require arterial imaging (duplex, CTA, or angiography) and consideration of revascularization (angioplasty/stenting or bypass surgery). Compression contraindicated.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with critical limb ischemia has rest pain and tissue loss. Angiography shows occluded superficial femoral artery with reconstitution at the popliteal level and patent tibial vessels. What revascularization option is preferred?',
'Conservative management only',
'Surgical bypass (fem-pop) or endovascular angioplasty/stenting depending on anatomy and patient factors',
'Primary amputation',
'Sympathectomy',
'Compression therapy',
'B',
'Revascularization essential for limb salvage in CLI. Options: Endovascular (angioplasty with or without stent) or surgical bypass. BASIL trial suggests similar outcomes. Decision based on anatomy, conduit availability (saphenous vein), comorbidities, life expectancy.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient has undergone successful angioplasty for an arterial ulcer. Despite improved blood flow, what additional measures are essential for healing and prevention?',
'No further treatment needed after revascularization',
'Risk factor modification: smoking cessation, antiplatelet therapy, statin, diabetes control, wound care',
'Start compression therapy',
'Immediate weight bearing',
'Prophylactic amputation',
'B',
'Post-revascularization: Continue best medical therapy - smoking cessation (critical), antiplatelet (aspirin/clopidogrel), high-dose statin, glycemic control, BP management. Wound care continues. Surveillance for restenosis. Revascularization may fail without risk factor control.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 75-year-old with multiple comorbidities has unreconstructable arterial disease with an ischemic ulcer and dry gangrene of the little toe. He is not fit for surgery. What is the palliative management approach?',
'Aggressive surgical debridement',
'Keep dry gangrene dry, pain control, allow autoamputation if possible, wound care for ulcer',
'High-dose antibiotics',
'Wet-to-dry dressings',
'Immediate above-knee amputation',
'B',
'Unreconstructable CLI with poor surgical candidacy: Palliative approach. Dry gangrene - keep dry, allow mummification and autoamputation if stable. Pain management (may need opioids). Wound care for wet areas. Amputation only if infection spreading or intractable pain.',
'hard', 'application'),

-- DIABETIC FOOT ULCER SCENARIOS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old diabetic with peripheral neuropathy presents with a painless ulcer on the plantar surface of the first metatarsal head. He has a warm foot with bounding pulses and reduced sensation to monofilament. The ulcer has thick callus at the edges. What is the primary cause of this ulcer?',
'Venous insufficiency',
'Neuropathic ulcer from repetitive pressure on insensate foot',
'Pure arterial disease',
'Vasculitis',
'Trauma only',
'B',
'Neuropathic diabetic foot ulcer: Plantar location at pressure points, painless (due to sensory neuropathy), surrounded by callus, warm foot with bounding pulses (unless concomitant PAD). Motor neuropathy causes deformity, autonomic causes dry cracked skin.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'The diabetic foot ulcer above is classified as Wagner Grade 2. What does this mean?',
'Superficial ulcer only',
'Deep ulcer penetrating to tendon, capsule, or bone',
'Localized gangrene',
'Extensive gangrene',
'Healed ulcer',
'B',
'Wagner classification: Grade 0 - pre-ulcer, Grade 1 - superficial, Grade 2 - deep (to tendon/bone), Grade 3 - abscess/osteomyelitis, Grade 4 - localized gangrene, Grade 5 - extensive gangrene. Grade 2 needs debridement and possibly imaging for bone involvement.',
'medium', 'knowledge'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient has a foot ulcer with probe-to-bone test positive. The foot is erythematous and swollen. ESR is 85 mm/hr. What diagnosis must be excluded and how?',
'Gout - check uric acid',
'Osteomyelitis - obtain MRI of the foot',
'DVT - duplex scan',
'Cellulitis only - treat with antibiotics',
'Charcot foot - immobilize only',
'B',
'Positive probe-to-bone test (probe reaches bone through ulcer) has high specificity for osteomyelitis. MRI is most sensitive imaging. Also consider bone biopsy for culture. Prolonged antibiotics (6+ weeks) and may need surgical debridement. X-ray may be normal early.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the most important aspect of managing a diabetic neuropathic foot ulcer to promote healing?',
'Topical antibiotics',
'Offloading (total contact cast or removable cast walker)',
'Soaking the foot daily',
'Debridement only',
'Compression bandaging',
'B',
'Offloading is critical - removes repetitive pressure on insensate foot. Total contact cast (gold standard) distributes pressure. Removable cast walkers acceptable if worn consistently. Also: debridement of callus, moist wound environment, infection control, glucose optimization.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A diabetic presents with a swollen, red, hot foot but no pain. He cannot recall any injury. X-ray shows fragmentation and dislocation of the midfoot bones. There is no ulcer. What is the diagnosis?',
'Gout',
'Acute Charcot neuroarthropathy',
'Osteomyelitis',
'Cellulitis',
'DVT',
'B',
'Acute Charcot foot: Painless (neuropathy) inflammation with bony destruction. Hot, red, swollen foot without systemic illness. X-ray may show fragmentation, subluxation, collapse. Management: Non-weight bearing, total contact casting until acute phase resolves. May need surgery for deformity.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient with a chronic heel ulcer has failed conservative management for 6 months. MRI confirms osteomyelitis of the calcaneus. ABPI is 0.8. What is the recommended management?',
'Continue antibiotics indefinitely',
'Partial calcanectomy (surgical debridement of infected bone) with culture-directed antibiotics',
'Below-knee amputation',
'Conservative treatment only',
'Revascularization first',
'B',
'Chronic diabetic foot osteomyelitis not responding to conservative treatment (antibiotics plus offloading plus wound care) needs surgical debridement of infected bone. Obtain bone cultures for directed antibiotics. Partial calcanectomy can salvage heel. Adequate vascularity needed for healing.',
'hard', 'application'),

-- MIXED AND SPECIAL ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient has features of both venous disease (varicose veins, hemosiderin staining) and arterial disease (absent foot pulses, thin shiny skin). ABPI is 0.65. How should this mixed aetiology ulcer be managed?',
'Full high compression',
'Reduced/modified compression with vascular input; consider revascularization if possible',
'No compression and no revascularization',
'Surgery for varicose veins first',
'Primary amputation',
'B',
'Mixed arterial-venous ulcers: Need balanced approach. Reduced compression (20-30 mmHg or less) with careful monitoring. Vascular assessment for potential revascularization. Treat arterial component to improve healing. Close supervision essential.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old woman presents with extremely painful leg ulcers that started as pustules. The ulcers have violaceous undermined edges and the borders are irregular. She has inflammatory bowel disease. What is the likely diagnosis?',
'Venous ulcer',
'Pyoderma gangrenosum',
'Arterial ulcer',
'Vasculitis',
'Squamous cell carcinoma',
'B',
'Pyoderma gangrenosum: Painful ulcer with violaceous undermined edges, often starts as pustule. Associated with IBD, rheumatoid arthritis, hematological malignancy. Pathergy phenomenon (worsens with debridement). Treatment: Immunosuppression (steroids, ciclosporin), not surgery.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old patient has a non-healing leg ulcer for 18 months despite appropriate treatment. The edges are raised and rolled, and there is an exophytic mass growing from the ulcer base. What should you do?',
'Continue current treatment',
'Biopsy the ulcer edge and base to exclude malignant transformation (Marjolin ulcer)',
'Apply more compression',
'Increase debridement',
'Discharge from clinic',
'B',
'Marjolin ulcer: Malignant transformation (usually SCC) in chronic wounds or scars. Suspect in: non-healing ulcer despite treatment, raised/rolled edges, exophytic growth, bleeding. Biopsy essential. Treatment: Wide excision with or without skin grafting, lymph node assessment.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with rheumatoid arthritis on methotrexate develops multiple small painful ulcers on the lower legs with surrounding purpura. The ulcers are punched out and symmetric. What is the likely cause?',
'Venous insufficiency',
'Vasculitic ulcers secondary to rheumatoid arthritis',
'Arterial disease',
'Methotrexate toxicity',
'Pyoderma gangrenosum',
'B',
'Vasculitic ulcers: Small vessel vasculitis causes punched-out painful ulcers with purpura/palpable purpura. Associated with RA, SLE, other connective tissue diseases. Treatment: Immunosuppression for underlying disease. May need biopsy for diagnosis.',
'hard', 'application'),

-- WOUND ASSESSMENT AND CARE
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'When assessing a leg ulcer, what findings in the wound bed would concern you about infection requiring systemic antibiotics?',
'Granulation tissue',
'Increased pain, wound deterioration, surrounding cellulitis, purulent discharge, fever',
'Slough present',
'Mild exudate',
'Epithelialization at edges',
'B',
'Signs of wound infection requiring antibiotics: Increased/new pain, wound deterioration, spreading cellulitis, purulent malodorous discharge, systemic signs (fever, elevated WBC). Colonization is normal - treat clinical infection, not swab results. Deep tissue culture most reliable.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A venous ulcer has significant slough and necrotic tissue. There is no clinical infection. What debridement method is most appropriate?',
'Leave the necrotic tissue as protection',
'Sharp debridement followed by autolytic debridement with appropriate dressings',
'Surgical debridement under general anesthesia',
'Enzymatic debridement only',
'Mechanical debridement with wet-to-dry dressings',
'B',
'Debridement promotes healing by removing barriers. Sharp debridement (with scalpel/curette) is effective and quick. Maintain with autolytic debridement (moist dressings) or larval therapy. In venous ulcers, formal surgical debridement rarely needed. Arterial ulcers - debridement only after vascular assessment.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'For a venous leg ulcer with moderate exudate and healthy granulation tissue, what type of dressing is most appropriate?',
'Dry gauze',
'Foam dressing or hydrofiber under compression',
'Hydrocolloid (may not handle high exudate)',
'Paraffin gauze',
'No dressing needed',
'B',
'Moderate exudate: Foam dressings or hydrofibers absorb exudate while maintaining moist wound environment. Apply under compression. Hydrocolloids suitable for low exudate. Match dressing to wound characteristics (exudate level, infection status, wound bed tissue type).',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A large venous ulcer (15cm x 10cm) has been present for 2 years with minimal healing despite optimal compression. Vascular surgery has treated superficial reflux. What surgical option may accelerate healing?',
'Amputation',
'Split-thickness skin grafting once wound bed prepared',
'Venous bypass surgery',
'Fasciotomy',
'Bone grafting',
'B',
'Large venous ulcers (greater than 10cm2) or prolonged duration may benefit from skin grafting to accelerate healing once wound bed is prepared (healthy granulation, no infection). Pinch grafts or split-thickness skin grafts. Compression must continue post-grafting.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a healing arterial ulcer post-revascularization asks about dressing choice. The ulcer is dry with minimal exudate. What dressing principle applies?',
'Keep the wound dry',
'Maintain moist wound environment with hydrogel or hydrocolloid',
'Wet-to-dry gauze',
'Leave open to air',
'Compression bandaging',
'B',
'Moist wound healing promotes epithelialization. For dry wounds, hydrogels add moisture. Low exudate - hydrocolloids maintain moisture. Avoid drying the wound. Exception: Dry gangrene in unreconstructable disease - keep dry to mummify.',
'medium', 'application'),

-- HOLISTIC MANAGEMENT
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 75-year-old with a painful venous ulcer is becoming socially isolated due to embarrassment about odor and leakage. How should this be addressed as part of comprehensive care?',
'Focus only on wound healing',
'Address quality of life: charcoal dressings for odor, absorbent dressings, adequate analgesia, psychological support, leg club participation',
'Tell patient to stay home',
'Increase compression only',
'Prescribe antidepressants',
'B',
'Holistic ulcer care: Quality of life is crucial. Manage odor (charcoal dressings, antimicrobials, frequent dressing changes), exudate (absorbent dressings, compression), pain (analgesia), psychosocial impact (patient groups, counseling). Chronic ulcers significantly impact mental health.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient with a healed neuropathic ulcer asks how to prevent recurrence. What advice is most important?',
'Avoid any walking',
'Daily foot inspection, protective footwear (custom orthotics if deformity), podiatry follow-up, optimize glucose control',
'Wear tight shoes to protect feet',
'Apply moisturizer inside shoes',
'No specific precautions needed after healing',
'B',
'Prevention of diabetic foot ulcer recurrence: Daily foot inspection (patient or carer), never walk barefoot, appropriate footwear (fitted, accommodative, protective), regular podiatry, treat calluses, optimize glycemic control, vascular assessment. 50% recur within 5 years without intervention.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'You are developing a leg ulcer service. What multidisciplinary team members should be involved for comprehensive care?',
'Only nurses',
'Vascular surgeon, diabetes specialist, tissue viability nurse, podiatrist, dermatologist, pain team, orthotist',
'GP only',
'Wound care company representative',
'Pharmacist only',
'B',
'MDT leg ulcer care: Tissue viability/wound care nurses (regular management), vascular surgeon (arterial disease, venous intervention), diabetologist (diabetes optimization), podiatrist (offloading, callus), dermatologist (unusual ulcers), pain team, orthotist (footwear). Improves outcomes.',
'easy', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old woman has a chronic venous ulcer not healing despite 6 months of optimal treatment. Biopsy has excluded malignancy. What advanced therapy might be considered?',
'Amputation',
'Negative pressure wound therapy (NPWT), bioengineered skin substitutes, or hyperbaric oxygen',
'Higher compression',
'Systemic steroids',
'No further options exist',
'B',
'Non-healing ulcers despite optimal standard care: Consider advanced therapies - NPWT (VAC therapy), bioengineered skin substitutes (Apligraf, Dermagraft), growth factors, hyperbaric oxygen (especially diabetic). Ensure underlying cause addressed first.',
'hard', 'application');
