-- ============================================================================
-- BATCH 30: Fracture Management - Clinical Scenario Questions (~1109-1150)
-- Topic: Clinical scenarios for fracture assessment and management
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- FRACTURE ASSESSMENT SCENARIOS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 25-year-old motorcyclist is brought to ED after a high-speed crash. His left lower leg is angulated with an open wound and bone visible. He has severe pain, the foot is pale, and no dorsalis pedis pulse is palpable. What is the priority management?',
'Obtain X-rays before any intervention',
'Reduce the fracture immediately to restore limb perfusion, cover wound, and urgent orthopedic/vascular input',
'Apply a full cast',
'Give antibiotics and wait for OR availability',
'Discharge with analgesia',
'B',
'Open fracture with vascular compromise is limb-threatening emergency. Gross reduction to restore alignment may restore perfusion (gentle traction and realignment). Cover wound with saline-soaked sterile dressing, IV antibiotics, tetanus prophylaxis, urgent surgery.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'In the above patient with an open tibial fracture, what antibiotic regimen should be administered and when?',
'Antibiotics can wait until OR',
'IV cefazolin (or co-amoxiclav) within 1 hour of injury, add gentamicin for severe contamination',
'Oral antibiotics only',
'Antibiotics only needed if infection develops',
'Topical antibiotics to wound',
'B',
'Open fracture antibiotics: Start within 1 hour (reduces infection significantly). Standard: Cefazolin or co-amoxiclav (covers skin flora). Add aminoglycoside for severe contamination or Gustilo III. Add penicillin or metronidazole for farm/fecal contamination. Continue until wound closure.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 10-year-old boy falls from a tree onto his outstretched hand. His elbow is swollen and held in flexion. There is no pulse at the wrist, and the hand is pale with delayed capillary refill. X-ray shows a displaced supracondylar fracture. What is the most urgent concern?',
'Nerve injury only',
'Brachial artery injury causing limb-threatening ischemia - urgent reduction needed',
'Elbow dislocation',
'Growth plate damage only',
'Forearm fracture',
'B',
'Supracondylar fracture with absent pulse: Brachial artery injury (entrapment or spasm) is surgical emergency. Gentle reduction may restore pulse. If pulse does not return after reduction, urgent vascular exploration. Associated median/anterior interosseous nerve injury also common.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'After reduction of a supracondylar fracture, the child now has a palpable radial pulse, but you notice he cannot make an "OK" sign (thumb and index finger pinch). What nerve is likely injured and what is its prognosis?',
'Radial nerve - needs urgent repair',
'Anterior interosseous nerve (branch of median) - usually neuropraxia, most recover spontaneously',
'Ulnar nerve',
'Musculocutaneous nerve',
'Axillary nerve',
'B',
'Anterior interosseous nerve (motor branch of median): Cannot flex thumb IP (FPL) and index DIP (FDP) - "OK sign" weakness. Usually neuropraxia from swelling/traction during injury. Most recover over weeks to months. Observe initially; surgical exploration if no recovery by 3 months.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old man sustains a closed tibial shaft fracture from a football tackle. Four hours later, he develops excruciating pain in the leg despite analgesia. The leg is tense and swollen. Pain increases with passive toe extension. Pulses are present. What is the diagnosis and treatment?',
'Deep vein thrombosis - anticoagulate',
'Acute compartment syndrome - emergency fasciotomy',
'Fracture needs better reduction',
'Infection developing - give antibiotics',
'Normal postoperative swelling',
'B',
'Compartment syndrome: Pain out of proportion, pain on passive stretch, tense compartment. Pulses often preserved until late. Diagnose clinically (or measure compartment pressure greater than 30 mmHg or delta P less than 30). Emergency fasciotomy required within 6 hours to prevent permanent damage.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What happens if compartment syndrome is not treated within 6-8 hours?',
'Complete recovery expected',
'Muscle necrosis leading to Volkmann ischemic contracture, rhabdomyolysis, possible amputation',
'Self-resolving condition',
'Only sensory loss',
'Infection develops',
'B',
'Untreated compartment syndrome: Muscle necrosis within 6-8 hours. Results in Volkmann ischemic contracture (forearm) or similar fixed deformity. Rhabdomyolysis can cause renal failure. May require amputation. Prevention through timely fasciotomy is critical.',
'medium', 'knowledge'),

-- SPECIFIC FRACTURE SCENARIOS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old woman trips and falls on her outstretched hand. Her wrist is deformed with a "dinner fork" appearance. X-ray shows a dorsally displaced, angulated distal radius fracture. What is this fracture called?',
'Smith fracture',
'Colles fracture',
'Barton fracture',
'Galeazzi fracture',
'Monteggia fracture',
'B',
'Colles fracture: Distal radius fracture with dorsal displacement and angulation, creating "dinner fork" deformity. Common in osteoporotic elderly from fall on outstretched hand. Treatment: Reduction and casting for stable fractures, fixation for unstable.',
'easy', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 30-year-old falls off a motorcycle and lands on his flexed wrist. X-ray shows a distal radius fracture with volar (palmar) displacement. What is this fracture and what is the risk with inadequate reduction?',
'Colles fracture - carpal tunnel syndrome risk',
'Smith fracture (reverse Colles) - volar displacement can compress median nerve',
'Scaphoid fracture',
'Lunate dislocation',
'Bennett fracture',
'B',
'Smith fracture: Distal radius fracture with volar displacement (garden spade deformity). Caused by fall on flexed wrist. Unstable, often requires surgical fixation. Volar displacement can stretch/compress median nerve. Different mechanism and displacement direction from Colles.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 22-year-old punches a wall and presents with pain and swelling over the dorsum of the hand. X-ray shows a fracture of the 5th metacarpal neck with volar angulation. What is this fracture and acceptable angulation?',
'Bennett fracture - no angulation acceptable',
'Boxer fracture - up to 40-50 degrees angulation acceptable for 5th metacarpal',
'Rolando fracture',
'Mallet finger',
'Jersey finger',
'B',
'Boxer fracture: 5th metacarpal neck fracture from punching. More angulation tolerated in 4th/5th MC (30-50 degrees) due to greater CMC joint mobility. Less tolerance in 2nd/3rd MC. Treatment: Buddy taping or ulnar gutter splint. Surgery if rotation, severe angulation, or 2nd/3rd MC.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A young man falls on his hand and has anatomical snuffbox tenderness but initial X-rays are normal. He is treated with a thumb spica cast. What fracture is suspected and why is this approach taken?',
'Colles fracture - missed on X-ray',
'Scaphoid fracture - treat as fracture until proven otherwise due to AVN risk',
'Triquetral fracture',
'Hamate fracture',
'No fracture if X-ray normal',
'B',
'Clinical scaphoid fracture (snuffbox tenderness, scaphoid tubercle tenderness, pain on axial compression of thumb) with negative X-ray: Up to 20% of scaphoid fractures occult initially. Immobilize and repeat imaging (X-ray or MRI) at 10-14 days. AVN risk warrants this approach.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'The patient above returns in 2 weeks with persistent snuffbox tenderness. Repeat X-ray shows a fracture through the scaphoid waist with some displacement. What is the recommended treatment and concern?',
'Continue cast immobilization only',
'Surgical fixation (headless compression screw) due to displacement and high nonunion/AVN risk',
'No treatment needed',
'Physiotherapy',
'Wrist fusion',
'B',
'Displaced scaphoid waist fracture: High risk of nonunion and AVN (blood supply enters distally - proximal pole at highest risk). Surgical fixation with headless compression screw (Herbert screw) recommended. Union rates better with surgery than casting for displaced fractures.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A child falls from a climbing frame. X-ray shows a fracture through the distal radial growth plate with a triangular metaphyseal fragment. According to Salter-Harris classification, what type is this?',
'Salter-Harris Type I',
'Salter-Harris Type II (most common type)',
'Salter-Harris Type III',
'Salter-Harris Type IV',
'Salter-Harris Type V',
'B',
'Salter-Harris II (SALTR: II=Above): Fracture through growth plate with metaphyseal fragment (Thurston-Holland fragment). Most common type (75%). Usually good prognosis. Types III-V involve epiphysis and have higher risk of growth disturbance.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 7-year-old has a displaced Salter-Harris Type IV fracture of the distal tibia. Why does this require anatomical reduction and likely surgical fixation?',
'Type IV fractures always need surgery',
'Fracture crosses growth plate and articular surface - malunion causes both growth arrest and arthritis',
'To prevent infection',
'For cosmetic reasons',
'Type IV fractures do not need reduction',
'B',
'Salter-Harris Type IV: Through metaphysis, physis, and epiphysis into joint. Requires anatomical reduction to prevent: 1) Growth arrest from physeal bar formation, 2) Post-traumatic arthritis from articular incongruity. Usually needs ORIF. Follow up for growth disturbance.',
'hard', 'application'),

-- HIP FRACTURE SCENARIOS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'An 82-year-old woman with dementia falls in her nursing home. She has leg shortening and external rotation, and cannot weight bear. X-ray shows a displaced intracapsular neck of femur fracture. What is the recommended surgical treatment?',
'Internal fixation with cannulated screws',
'Hemiarthroplasty (partial hip replacement)',
'Conservative management - bed rest',
'Total hip replacement',
'External fixation',
'B',
'Displaced intracapsular NOF in elderly with limited mobility/cognitive impairment: Hemiarthroplasty (replace femoral head, keep native acetabulum). Lower dislocation risk than THR, shorter surgery. For mobile, cognitively intact elderly: consider THR (better function, lower reoperation).',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old active man falls from a ladder and sustains a displaced intracapsular neck of femur fracture. What is the preferred surgical management?',
'Hemiarthroplasty',
'Internal fixation (screw or plate) to preserve native hip - younger patients need joint-saving approach',
'Total hip replacement',
'Conservative management',
'Amputation',
'B',
'Displaced intracapsular NOF in young/middle-aged: Attempt fixation (cannulated screws or sliding hip screw) to preserve native hip despite AVN risk (10-30%). If AVN develops, can do THR later. THR in young patients has limited lifespan and revision challenges.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'An 85-year-old woman presents with a painful right hip after a fall. X-ray shows an intertrochanteric (extracapsular) hip fracture. What is the recommended fixation device?',
'Cannulated screws',
'Dynamic hip screw (DHS/sliding hip screw) or intramedullary nail',
'Hemiarthroplasty',
'Total hip replacement',
'Cast immobilization',
'B',
'Extracapsular (intertrochanteric) fractures: Good blood supply, AVN rare. Treatment: Internal fixation with dynamic/sliding hip screw or cephalomedullary nail (for unstable/subtrochanteric patterns). Not hemiarthroplasty (femoral head blood supply intact). Early mobilization.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A hip fracture patient is medically optimized and scheduled for surgery. According to best practice guidelines, what is the target time from admission to surgery?',
'Within 1 week',
'Within 36 hours if medically stable',
'No specific timeframe',
'Within 24 hours regardless of medical status',
'Wait until fully ambulatory',
'B',
'Hip fracture surgery timing: Target within 36 hours of admission (NICE, BOAST guidelines). Earlier surgery associated with reduced mortality, complications, and length of stay. Only delay if medical optimization needed (e.g., anticoagulation reversal, cardiac stabilization).',
'easy', 'knowledge'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A hip fracture patient develops acute confusion on post-operative day 2. What are the most common causes to consider?',
'Normal post-operative course',
'Delirium from pain, infection, constipation, urinary retention, medications, hypoxia',
'Stroke',
'New dementia diagnosis',
'Anesthetic awareness',
'B',
'Post-operative delirium common in elderly: Check for pain (undertreated), infection (UTI, pneumonia, wound), constipation, urinary retention, medications (opioids, anticholinergics), metabolic (hypoxia, hyponatremia, renal failure). Treat underlying cause, provide orientation, avoid restraints.',
'medium', 'application'),

-- ANKLE AND FOOT FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 35-year-old man twists his ankle playing football. Examination shows significant swelling over the lateral malleolus with inability to weight bear. When should an X-ray be obtained based on Ottawa Ankle Rules?',
'X-ray for all ankle injuries',
'X-ray indicated: bone tenderness at posterior edge of lateral malleolus and inability to weight bear for 4 steps',
'Never X-ray ankle sprains',
'X-ray only if gross deformity',
'X-ray based on patient request',
'B',
'Ottawa Ankle Rules: X-ray ankle if bone tenderness at posterior 6cm of lateral or medial malleolus, OR inability to weight bear immediately and in ED for 4 steps. High sensitivity for fractures, reduces unnecessary X-rays. Also rules for midfoot (Ottawa Foot Rules).',
'easy', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'X-ray shows a Weber B ankle fracture (fibula fracture at level of syndesmosis) with medial clear space widening suggesting deltoid ligament injury. How does this change management?',
'Treat as simple fracture with cast',
'Unstable injury - requires surgical fixation with ORIF and syndesmosis stabilization if unstable',
'Treat with strapping only',
'No treatment needed',
'Immediate weight bearing',
'B',
'Weber B with medial injury (widened medial clear space greater than 4mm): Indicates unstable injury (bimalleolar equivalent). Requires ORIF of fibula. Stress test or MRI for syndesmosis injury - may need syndesmosis fixation. Simple Weber B without medial injury may be stable and cast-treatable.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient steps in a hole and sustains a twisting injury. X-ray shows a fracture of the base of the 5th metatarsal (Jones fracture zone). He is a professional athlete. What treatment gives fastest return to sport?',
'Cast immobilization for 6-8 weeks',
'Intramedullary screw fixation',
'No treatment needed',
'Physical therapy only',
'Amputation',
'B',
'Jones fracture (metaphyseal-diaphyseal junction of 5th MT): Poor blood supply, high nonunion with conservative treatment. Athletes benefit from intramedullary screw fixation - faster healing, earlier return to sport. Avulsion fractures of 5th MT (tuberosity) heal well with conservative treatment.',
'hard', 'application'),

-- FRACTURE HEALING SCENARIOS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A tibial shaft fracture was treated with intramedullary nailing. At 6 months, the patient still has pain at the fracture site. X-ray shows persistent fracture line with sclerotic edges. What is the diagnosis?',
'Normal healing',
'Nonunion - likely requires revision surgery',
'Delayed union',
'Malunion',
'Infection only',
'B',
'Nonunion: Fracture healing has stopped (typically defined as no progress for 3 months after expected healing time). Sclerotic, sealed bone ends. Types: Hypertrophic (adequate blood supply, need stability) vs atrophic (poor blood supply, need biology). Treatment: Revision surgery, bone grafting.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'The nonunion in the above patient shows abundant callus around the fracture site but persistent instability. What type of nonunion is this and what treatment principle applies?',
'Atrophic nonunion - needs bone graft',
'Hypertrophic nonunion - needs improved fixation stability',
'Infected nonunion - needs antibiotics',
'Normal healing',
'Pathological fracture',
'B',
'Hypertrophic nonunion: Adequate blood supply (shown by callus), but inadequate stability prevents healing. Treatment: Exchange nailing with larger nail, plate fixation, or external fixation. Bone graft not usually needed (biology intact). Contrast with atrophic - poor blood supply, needs bone graft.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a tibial fracture develops increasing pain, swelling, and wound drainage 3 weeks post-operatively. Blood tests show elevated WBC, CRP, and ESR. X-ray shows early periosteal reaction. What is the concern?',
'Normal healing',
'Deep surgical site infection/osteomyelitis - needs surgical debridement and IV antibiotics',
'DVT',
'Compartment syndrome',
'Nonunion',
'B',
'Post-operative infection/osteomyelitis: Increasing pain, wound drainage, systemic inflammation (elevated WBC, CRP, ESR). Early X-ray may be normal or show periosteal reaction. Treatment: Surgical debridement (retain or remove implant based on stability), culture-directed IV antibiotics, possible suppression or staged reconstruction.',
'medium', 'application'),

-- SPECIAL FRACTURE CONSIDERATIONS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 68-year-old woman sustains a vertebral compression fracture from minor trauma. She has no neurological deficit. DEXA scan shows T-score of -3.0. What medical treatment is important in addition to fracture management?',
'No additional treatment needed',
'Osteoporosis treatment: Calcium, vitamin D, and bisphosphonate or denosumab',
'Steroids',
'Chemotherapy',
'Hormone replacement only',
'B',
'Fragility fracture = diagnose and treat osteoporosis. T-score less than -2.5 = osteoporosis. Treatment: Calcium (1g/day), vitamin D (800-1000IU), and anti-resorptive therapy (bisphosphonate like alendronate/zoledronic acid, or denosumab). Reduces future fracture risk by 50%.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 50-year-old man has a femur fracture through a lytic bone lesion with no history of trauma. He has a history of lung cancer. What type of fracture is this and what is the management approach?',
'Simple traumatic fracture - standard fixation',
'Pathological fracture through bone metastasis - staging, stabilization for pain/function, oncology involvement',
'Stress fracture',
'Osteoporotic fracture',
'Normal variant',
'B',
'Pathological fracture through metastasis: Stabilization for pain relief, function, and quality of life (intramedullary nailing, plate, or prosthesis). Oncology assessment for systemic treatment. Prognosis guides surgical approach. Common sources: Lung, breast, prostate, kidney, thyroid.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient on long-term bisphosphonates for osteoporosis presents with thigh pain. X-ray shows lateral cortical thickening and a transverse femoral shaft fracture with "beaking." What is this condition?',
'Typical osteoporotic fracture',
'Atypical femoral fracture associated with bisphosphonates',
'Stress fracture',
'Pathological fracture',
'Traumatic fracture',
'B',
'Atypical femoral fracture: Associated with long-term bisphosphonate (greater than 5 years). Transverse or short oblique subtrochanteric/shaft fracture, lateral cortical beaking, minimal/no trauma. Prodromal thigh pain. Stop bisphosphonate, surgical fixation. Check contralateral femur.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A young athlete develops gradual onset anterior shin pain that worsens with running. X-ray is initially normal. MRI shows a stress reaction in the tibia. How should this be managed?',
'Continue training through pain',
'Relative rest, modify activity, gradual return to sport when pain-free',
'Immediate surgery',
'Full cast immobilization',
'Ignore as X-ray is normal',
'B',
'Stress fracture/reaction: Overuse injury. Modify activity (relative rest, cross-training with non-impact activity), address risk factors (training errors, footwear, nutrition, female athlete triad). Gradual return to sport when pain-free. Some high-risk sites (anterior tibia, femoral neck) may need surgery.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A polytrauma patient has bilateral femur fractures and respiratory distress 24 hours after injury. He develops petechial rash, confusion, and hypoxia. What syndrome is this?',
'Pulmonary embolism',
'Fat embolism syndrome',
'ARDS only',
'Pneumonia',
'Cardiogenic shock',
'B',
'Fat embolism syndrome: Classic triad - respiratory distress, neurological dysfunction, petechial rash (chest, axillae, conjunctivae). Occurs 24-72 hours post long bone/pelvic fracture. Treatment: Supportive (oxygen, fluids, consider mechanical ventilation). Early fracture fixation may reduce incidence.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'After a tibial plateau fracture is fixed, the patient develops calf pain and swelling 5 days post-operatively. What complication must be excluded and how?',
'Compartment syndrome - measure pressures',
'Deep vein thrombosis - D-dimer and duplex ultrasound',
'Infection - wound inspection',
'Arterial injury - angiogram',
'Fracture displacement - X-ray',
'B',
'DVT: Common after lower limb trauma/surgery. Calf pain, swelling, warmth. Diagnose with D-dimer (if low probability) and/or duplex ultrasound. Treatment: Anticoagulation. Prevention: Mechanical prophylaxis and chemical prophylaxis (LMWH) for high-risk patients.',
'medium', 'application');
