-- ============================================================================
-- BATCH 31: Urethral Catheterization - Clinical Scenario Questions (~1139-1175)
-- Topic: Clinical scenarios for catheter management and complications
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- INDICATIONS AND DECISION-MAKING
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A 75-year-old man presents to ED with severe lower abdominal pain and inability to void for 12 hours. His bladder is palpable to the umbilicus and he is in distress. What is the diagnosis and immediate management?',
'Constipation - give laxatives',
'Acute urinary retention - insert urethral catheter',
'Appendicitis - urgent surgery',
'Bowel obstruction - NG tube',
'Urinary tract infection - antibiotics only',
'B',
'Acute urinary retention: Sudden inability to void with painful distended bladder. Emergency management: Urethral catheterization to decompress bladder. Record residual volume. Investigate underlying cause (BPH most common in elderly men). Consider alpha-blocker trial.',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'After catheterizing the patient above, 1800ml of urine drains immediately. His BP drops from 150/90 to 100/60 mmHg. What has happened and how should it be managed?',
'Catheter malfunction',
'Post-obstructive diuresis and hypotension - give IV fluids, monitor urine output and electrolytes closely',
'Sepsis - give antibiotics',
'Allergic reaction to catheter',
'Normal finding - no action needed',
'B',
'Post-obstructive diuresis: After relief of chronic/high-volume obstruction, kidneys may produce large volumes of dilute urine. Can cause dehydration and electrolyte imbalance. Monitor urine output, replace fluids appropriately (typically 50-75% of output), check electrolytes regularly.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old woman is admitted for elective hip replacement. The surgeon requests a catheter "for theatre." According to catheter care guidelines, what approach minimizes CAUTI risk?',
'Insert the night before surgery',
'Insert in theatre, remove within 24 hours post-op when mobile, or use intermittent catheterization',
'Keep catheter for the entire hospital stay',
'Insert a week before surgery',
'Use catheter only if patient requests',
'B',
'CAUTI prevention: Avoid catheter if possible, use alternatives (intermittent catheterization, bladder scanner). If needed, insert aseptically in theatre, remove as soon as possible (within 24-48 hours for surgical patients). Duration is the main risk factor for CAUTI.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'An 80-year-old nursing home resident with advanced dementia and pressure ulcers has urinary incontinence. The family requests a catheter for "easier nursing care." What is the appropriate response?',
'Insert long-term catheter as requested',
'Discuss alternatives - incontinence pads, scheduled toileting; catheter only if wound healing requires dry area',
'Insert catheter to measure output',
'Refuse any catheter under any circumstances',
'Insert catheter for infection prevention',
'B',
'Incontinence alone is NOT an indication for catheterization. Catheters increase UTI risk, do not improve outcomes for incontinence. Alternatives: Pads, scheduled toileting, condom catheters. May be indicated if sacral wounds need protection from urine contamination - time-limited use.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A critically ill septic patient in ICU is oliguric. The medical team wants to accurately monitor urine output. What type of catheter system is most appropriate?',
'Standard Foley with leg bag',
'Foley catheter with hourly urometer and closed drainage system',
'Intermittent catheterization every 6 hours',
'Condom catheter',
'Suprapubic catheter',
'B',
'ICU urinary monitoring: Foley catheter with closed drainage system and urometer for accurate hourly output measurement. Keep closed system, use aseptic technique for samples, avoid bag-breaking. Assess need daily and remove when close monitoring no longer required.',
'easy', 'application'),

-- TECHNIQUE AND TROUBLESHOOTING
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'While catheterizing a 70-year-old man with BPH, you meet resistance at the level of the prostate. The catheter will not advance. What should you do?',
'Force the catheter through',
'Apply steady gentle pressure, ask patient to relax, try larger catheter tip (Coude/Tiemann), or call urology',
'Abandon the procedure and wait',
'Insert a smaller catheter quickly',
'Inflate the balloon to anchor it',
'B',
'Prostatic resistance: Have patient take deep breaths, relax pelvic floor. Apply steady gentle pressure. Try Coude-tip (curved tip) catheter which navigates prostatic urethra better. If still fails, do not force - risk false passage. Call urology for difficult catheter or suprapubic approach.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'During catheterization of a male patient, you successfully insert the catheter to the hub but no urine drains. The patient says he voided 30 minutes ago. What should you do?',
'Remove and reinsert immediately',
'Flush with sterile saline to confirm position, consider the catheter may be in a diverticulum or bladder is empty',
'Inflate balloon anyway',
'Insert a larger catheter',
'Document failed procedure',
'B',
'No urine flow: May be in urethral diverticulum, bladder genuinely empty, or kinked. Flush gently with sterile saline - if flushes easily and returns, catheter is in bladder. May need bladder scan to check volume. Avoid inflating balloon without confirmation of position.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'You are catheterizing a female patient but cannot visualize the urethral meatus. It appears to be within the vaginal introitus. What technique may help?',
'Use a larger speculum',
'Palpate for the urethral meatus anterior to vaginal opening, use good lighting, consider catheterization from above',
'Insert catheter into vagina repeatedly',
'Skip catheterization',
'Have patient stand up',
'B',
'Female urethral meatus may be difficult to visualize (especially elderly, obese). Located anterior to vaginal opening. Use good lighting, positioning (frog-leg), labial retraction. Meatus may be retracted proximally - palpate for it. If catheter enters vagina, leave it as a marker and use new catheter.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with a urethral catheter in situ has a catheter that is not draining despite adequate intake. The drainage bag is below bladder level. What should you do?',
'Immediately remove and replace catheter',
'Flush catheter with sterile saline to check patency and dislodge any debris/clot',
'Increase oral fluids',
'Ignore and monitor',
'Clamp the catheter',
'B',
'Blocked catheter: Flush gently with sterile saline (30-50ml) to dislodge debris, blood clots, sediment. If flushes freely and urine drains, maintain with increased fluids. If cannot flush or recurrent blocking, may need catheter change. Consider bladder washouts if mucus/debris problem.',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old man involved in RTA has blood at the urethral meatus, a high-riding prostate on rectal exam, and perineal bruising. He needs urinary drainage. What is the appropriate approach?',
'Insert urethral catheter immediately',
'Avoid urethral catheterization - urology consultation for suprapubic catheter or flexible cystoscopy',
'Insert larger catheter to tamponade bleeding',
'Use intermittent catheterization',
'Wait and observe',
'B',
'Urethral injury signs: Blood at meatus, high-riding prostate, perineal/scrotal hematoma, inability to void. Urethral catheterization contraindicated - may convert partial to complete disruption. Needs urology for retrograde urethrogram and suprapubic catheter if urethral injury confirmed.',
'hard', 'application'),

-- CATHETER-ASSOCIATED COMPLICATIONS
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with an indwelling catheter for 5 days develops fever (38.5 C), suprapubic tenderness, and cloudy urine. Blood tests show elevated WBC and CRP. What is the diagnosis and management?',
'Simple asymptomatic bacteriuria - no treatment',
'Catheter-associated UTI - obtain culture, change catheter, start empiric antibiotics',
'Routine catheter change - no treatment',
'Normal catheter finding',
'Sepsis from another source',
'B',
'CAUTI: Symptomatic UTI in catheterized patient (fever, suprapubic pain, systemic signs). Change catheter before collecting culture (biofilm on old catheter gives false results). Start empiric antibiotics (cover gram-negatives), adjust based on culture. Do not treat asymptomatic bacteriuria.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A routine urine sample from a catheterized patient shows bacteria greater than 10^5 CFU/ml but the patient is afebrile with no urinary symptoms. How should this be managed?',
'Start antibiotics immediately',
'No treatment required - this is asymptomatic bacteriuria, which is expected with catheters',
'Change catheter and repeat culture',
'Remove catheter and treat',
'Admit to hospital',
'B',
'Asymptomatic bacteriuria: Universal in long-term catheterized patients. Treatment does NOT reduce complications but promotes resistance. Only treat symptomatic CAUTI. Exception: Before urological procedures - treat to prevent bacteremia.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A male patient has had an indwelling catheter for 3 weeks. He now has purulent urethral discharge and swelling at the penile shaft. The catheter is anchored to the thigh. What complication has occurred?',
'Normal catheter reaction',
'Urethral erosion or pressure injury from improper catheter securement',
'STI',
'Allergic reaction',
'Catheter migration',
'B',
'Urethral erosion: Catheter pressing on urethra (especially if not properly secured allowing movement). Can cause stricture, fistula. Prevention: Proper securement (secure to abdomen in males to prevent penoscrotal angle pressure), use appropriate size, consider suprapubic for long-term.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with a long-term catheter develops recurrent encrustation and blockage. Urine culture grows Proteus mirabilis. What is the significance and management strategy?',
'Change to smaller catheter',
'Proteus produces urease causing alkaline urine and strite stones/encrustation - increase fluids, consider catheter washouts, treat symptomatically',
'Normal finding - ignore',
'Change to latex catheter',
'Continuous antibiotics',
'B',
'Proteus mirabilis: Urease-producing organism causing alkaline urine (pH greater than 7). Leads to struvite crystal formation and catheter encrustation. Management: Increase fluids, acidifying agents may help, regular catheter changes before blocking, citric acid washouts. Treat only symptomatic infection.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A nurse calls because a patient catheter balloon will not deflate when attempting to remove it. What techniques can be tried?',
'Cut the catheter shaft',
'Try aspiration with syringe, leave syringe attached without plunger, try cutting inflation port; if fails, urology can puncture balloon suprapubically',
'Pull the catheter out with force',
'Leave catheter in permanently',
'Insert another catheter alongside',
'B',
'Non-deflating balloon: Try 10ml syringe aspiration (sometimes valves stick). Leave syringe attached without plunger (passive drainage). Cut the inflation arm distal to port (allows passive deflation). If still fails, urology can pass needle suprapubically to puncture balloon. Never pull with balloon inflated.',
'medium', 'application'),

-- SPECIAL POPULATIONS
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A 5-year-old boy needs catheterization for surgery. What catheter size is appropriate and what special considerations apply?',
'Use adult size (16Fr)',
'Use pediatric size (6-8Fr for child this age), gentle technique, consider sedation/distraction',
'Same technique as adults',
'Catheterization contraindicated in children',
'12Fr is minimum size for any age',
'B',
'Pediatric catheterization: Size based on age/weight (approximately age/2 + 8 = Fr size for formula, but typically 6-8Fr for 5-year-old). Smaller balloon (3-5ml). Gentle technique with age-appropriate explanation. Topical anesthetic gel. May need parental presence or sedation.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A 28-week pregnant woman in preterm labor requires urinary drainage. What considerations are important for catheterization in pregnancy?',
'Standard technique unchanged',
'Modified positioning, gentle technique, uterus may compress bladder; be aware of physiological changes',
'Catheterization contraindicated in pregnancy',
'Use largest catheter available',
'Only suprapubic allowed',
'B',
'Pregnancy catheterization: Modified lithotomy or lateral positioning for comfort. Gravid uterus compresses bladder (smaller capacity). Physiological hydronephrosis of pregnancy is normal. Gentle technique. May need leg support help. Infection risk higher in pregnancy.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic urinary retention due to neurogenic bladder from spinal cord injury is being discharged. What long-term bladder management option preserves renal function best?',
'Long-term indwelling catheter',
'Clean intermittent self-catheterization (CISC)',
'Permanent suprapubic catheter',
'No intervention needed',
'Condom catheter only',
'B',
'CISC (clean intermittent self-catheterization): Gold standard for neurogenic bladder. Lower UTI rates than indwelling catheters. Preserves renal function by preventing high bladder pressures. Patient empowerment. Requires adequate hand function and motivation. Typically 4-6 times daily.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'An elderly man with dementia and chronic retention is not a candidate for CISC. He has failed multiple urethral catheter trials. What alternative is most appropriate for long-term management?',
'Continue urethral catheter indefinitely',
'Suprapubic catheter',
'Condom catheter with retention',
'Surgical bladder removal',
'No urinary management',
'B',
'Suprapubic catheter: When long-term catheter needed and urethral route problematic (recurrent urethral trauma, urethral stricture, patient preference, urethral complications). Lower urethral complication rate, easier care for carers, better for sexual function. Still carries CAUTI risk.',
'medium', 'application'),

-- CATHETER TRIALS AND REMOVAL
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A 72-year-old man with acute urinary retention from BPH has been catheterized for 3 days and started on tamsulosin. When should a trial without catheter (TWOC) be attempted?',
'Immediately upon presentation',
'After 2-3 days of alpha-blocker treatment, with bladder scan and voiding assessment planned',
'After 6 months',
'Never - catheter is permanent',
'Only after surgery',
'B',
'TWOC for BPH retention: Start alpha-blocker (tamsulosin/alfuzosin) for 2-3 days before trial. Remove catheter (morning often preferred). Monitor voiding and post-void residual by bladder scan. Success rate 50-70% with alpha-blocker pre-treatment. If fails, may need TURP.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient had a catheter for 2 days. It is removed and she does not void for 6 hours but has no discomfort. Bladder scan shows 180ml. What is the appropriate management?',
'Reinsert catheter immediately',
'Encourage fluids and mobilization, rescan in 2-4 hours - residual is not concerning yet',
'Discharge home',
'Start antibiotics',
'Emergency urology referral',
'B',
'Post catheter removal: Give patient 6-8 hours to void. Bladder volume less than 300ml without discomfort can observe. Encourage fluids, mobilization, privacy. Rescan if not voiding. Reinsert if greater than 500ml with discomfort or greater than 800ml regardless. One failed TWOC - try again in 48-72 hours.',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient who had a catheter for urinary retention has failed two TWOC attempts despite alpha-blocker therapy. He is symptomatic with LUTS affecting quality of life. What is the next step?',
'Third TWOC attempt',
'Urology referral for consideration of TURP or other BPH surgery',
'Long-term catheter as only option',
'Stop all medications',
'Reassurance only',
'B',
'Failed TWOC (especially twice): Need definitive treatment if BPH is the cause. TURP (transurethral resection of prostate) is gold standard. Alternatives: laser prostatectomy, prostatic urethral lift, water vapor thermal therapy. Long-term catheter if unfit for surgery.',
'medium', 'application'),

-- CATHETER SELECTION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'An ICU patient needs a catheter to monitor output after major surgery. He has no history of urological problems. What catheter size and type is most appropriate?',
'Largest available (24Fr) for best drainage',
'12-14Fr standard Foley with 10ml balloon and temperature sensing if needed',
'6Fr pediatric catheter',
'8Fr catheter',
'3-way irrigation catheter',
'B',
'Standard adult male: 12-14Fr (female 12Fr often sufficient). Larger is NOT better - causes more trauma and does not improve drainage. 10ml balloon standard. Temperature-sensing catheter in ICU helpful for continuous core temperature. 3-way only if irrigation needed (hematuria, post-TURP).',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with post-TURP bleeding needs continuous bladder irrigation. What type of catheter is required?',
'Standard 2-way Foley catheter',
'3-way irrigation catheter (e.g., 22-24Fr with 30ml balloon)',
'Intermittent catheterization',
'Suprapubic catheter',
'Condom catheter',
'B',
'Post-TURP bleeding: 3-way catheter for continuous bladder irrigation. Larger size (20-24Fr) to allow clot passage. 30ml balloon helps hemostasis. Three lumens: Drainage, irrigation inflow, balloon. Irrigate with normal saline until effluent clear.',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with known urethral stricture has chronic retention. A standard Foley will not pass. What specialized catheter might help?',
'Larger Foley catheter',
'Coude (Tiemann) catheter with curved tip, or consider urological input for dilators or suprapubic',
'Smaller gauge with more force',
'Pediatric feeding tube',
'No catheter possible for this patient',
'B',
'Urethral stricture: Coude catheter (curved tip, angled 30-45 degrees) may negotiate stricture. Follower/guide-wire techniques. If fails, urology may use dilators, flexible cystoscopy-guided catheterization, or suprapubic catheter. Never force - causes false passage.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient needs a long-term catheter (expected duration more than 3 months). The standard latex catheter is causing frequent reactions and blocking. What catheter material should be considered?',
'Continue latex',
'Silicone catheter (more biocompatible, less encrustation)',
'PVC catheter',
'Red rubber catheter',
'Latex with more frequent changes',
'B',
'Long-term catheterization (greater than 28 days): Silicone catheters preferred - more biocompatible, less allergenic, less encrustation. Can remain in place longer (up to 12 weeks). Hydrogel-coated options also available. Avoid latex for known latex allergy or long-term use.',
'medium', 'application'),

-- DOCUMENTATION AND GOVERNANCE
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What should be documented following urethral catheterization?',
'No documentation needed',
'Date/time, indication, catheter type/size, balloon volume, residual volume, any difficulties, and planned review date',
'Just catheter size',
'Only if complications occur',
'Document in nursing notes only',
'B',
'Catheter documentation: Date and time inserted, indication, catheter type/size/batch number, balloon volume, residual urine volume, any difficulties, name of person inserting, and planned review/removal date. Daily reassessment of need. Reduces CAUTI and ensures appropriate care.',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'An audit shows high CAUTI rates on your ward. What bundle of interventions would most effectively reduce catheter-associated infections?',
'Prophylactic antibiotics for all catheterized patients',
'CAUTI prevention bundle: Avoid unnecessary catheters, aseptic insertion, closed drainage system, daily review for removal, maintain unobstructed flow',
'Routine catheter changes every 3 days',
'Bladder washouts for all patients',
'Higher strength antiseptic use',
'B',
'CAUTI prevention bundle: Avoid catheter if alternatives exist. Aseptic insertion technique. Closed sterile drainage system. Maintain unobstructed urine flow (bag below bladder, no kinks). Daily assessment of ongoing need. Prompt removal. Hand hygiene. These reduce CAUTI by 30-60%.',
'medium', 'application');
