-- Article 37: Benign Breast Diseases
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d0000037-0000-0000-0000-000000000037'::uuid, 'introduction', 1, 'Introduction to Benign Breast Diseases', 'Benign breast conditions are extremely common, affecting up to 50% of women during their lifetime. They encompass a spectrum of disorders including fibrocystic changes, fibroadenomas, breast cysts, mastitis, and nipple discharge. Understanding these conditions is essential to differentiate from malignancy and provide appropriate management. ANDI (Aberrations of Normal Development and Involution) classification provides a framework understanding benign breast disease as deviations from normal breast physiology.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 'content', 2, 'Classification and Common Conditions', 'ANDI CLASSIFICATION: Normal processes become aberrations and may progress to disease states. Development phase (15-25 years): fibroadenoma. Cyclical changes (25-40 years): mastalgia, nodularity. Involution (35-55 years): cysts, duct ectasia, sclerosing adenosis.

FIBROADENOMA: Most common breast lump in women under 30. Well-circumscribed, mobile (breast mouse), firm, non-tender. Arises from complete lobule (stromal and epithelial). Giant fibroadenoma is greater than 5cm. Phyllodes tumor is rare, may be malignant, requires wide excision. Management: observation if typical; excision if greater than 3cm, growing, or patient preference.

BREAST CYSTS: Common in 35-50 age group. May be solitary or multiple. Present as smooth, tense lumps that may be tender. Diagnosed and treated by aspiration - clear or green fluid, disappearance of lump, no bloody aspirate. No further action if these criteria met. Recurrent cysts may need excision.

FIBROCYSTIC CHANGE: Most common cause of breast lumps. Includes fibrosis, cysts, adenosis, epithelial hyperplasia. Presents with cyclical mastalgia, nodularity, and lumpiness. Management is reassurance, supportive bra, evening primrose oil, danazol for severe cases.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 'content', 3, 'Breast Infections and Nipple Conditions', 'LACTATIONAL MASTITIS: Staphylococcus aureus most common. Presents with painful, red, swollen breast with fever. Treat with flucloxacillin and continue breastfeeding. Abscess requires drainage - ultrasound-guided aspiration or surgical incision.

NON-LACTATIONAL MASTITIS: Periductal mastitis (smokers), granulomatous mastitis, tuberculosis. Periductal mastitis associated with nipple piercing and smoking - often anaerobic bacteria. May lead to mammary duct fistula.

BREAST ABSCESS: Lactational - peripheral location; non-lactational - periareolar location. US-guided aspiration first-line; surgical drainage if fails or large abscess. Always exclude inflammatory carcinoma in non-lactational abscess.

NIPPLE DISCHARGE: Physiological (bilateral, multiple ducts), pathological (unilateral, single duct, spontaneous). Milky - galactorrhea (prolactinoma). Green or brown - duct ectasia. Bloody - papilloma, carcinoma (requires investigation). Serous - fibrocystic change.

FAT NECROSIS: History of trauma or surgery. Firm, irregular mass mimicking carcinoma. Oil cyst on mammogram. Core biopsy confirms diagnosis. No treatment needed.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 'content', 4, 'Investigation and Triple Assessment', 'TRIPLE ASSESSMENT: Clinical examination, imaging (mammogram plus ultrasound), and tissue diagnosis (cytology or histology). All three components must be concordant.

IMAGING: Under 35 years - ultrasound first (dense breast tissue). Over 35 years - mammogram plus or minus ultrasound. MRI for implant assessment, BRCA screening, occult primary.

TISSUE DIAGNOSIS: Fine needle aspiration cytology (FNAC) - C1-C5 grading. Core biopsy - provides histology, preferred for solid lesions. B1-B5 grading. Vacuum-assisted biopsy for microcalcifications.

GRADING SYSTEMS: C1 or B1 - inadequate; C2 or B2 - benign; C3 or B3 - atypical, probably benign; C4 or B4 - suspicious; C5 or B5 - malignant.

HIGH-RISK LESIONS: Atypical ductal hyperplasia (ADH), atypical lobular hyperplasia (ALH), lobular carcinoma in situ (LCIS), radial scar, papillary lesions. Require excision biopsy and surveillance.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'Fibroadenoma is mobile breast mouse - common under 30. Cyst aspiration: clear fluid plus lump disappears plus no mass equals no further action. Bloody nipple discharge requires investigation - papilloma or carcinoma. Lactational mastitis - continue breastfeeding. Non-lactational abscess - always exclude inflammatory carcinoma. Fat necrosis mimics carcinoma - history of trauma. Triple assessment is mandatory for any breast lump.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 'key_points', 6, 'Key Points Summary', 'ANDI framework explains benign breast disease as aberrations of normal development and involution. Fibroadenoma: mobile, firm, well-circumscribed lump in young women. Cyst: aspirate, reassure if criteria met. Fibrocystic change is most common cause of breast lumps. Lactational mastitis: Staph aureus, flucloxacillin, continue breastfeeding. Periductal mastitis associated with smoking. Bloody discharge: papilloma most common cause. Triple assessment for all breast lumps.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d0000037-0000-0000-0000-000000000037'::uuid, 1, 'Most common breast lump in women under 30 is:', 'Breast cyst', 'Fibroadenoma', 'Breast cancer', 'Fat necrosis', 'Lipoma', 'B', 'Fibroadenoma is the most common breast lump in women under 30 years of age.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 2, 'Characteristic feature of fibroadenoma is:', 'Fixed to skin', 'Highly mobile (breast mouse)', 'Nipple discharge', 'Skin dimpling', 'Axillary lymphadenopathy', 'B', 'Fibroadenoma is characteristically highly mobile, earning the nickname breast mouse.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 3, 'After cyst aspiration, no further action is needed if:', 'Fluid is bloody', 'Lump remains', 'Fluid is clear, lump disappears, no residual mass', 'Patient is young', 'Cyst is large', 'C', 'Successful cyst aspiration criteria: clear fluid, complete disappearance of lump, no residual mass.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 4, 'Lactational mastitis is most commonly caused by:', 'E. coli', 'Staphylococcus aureus', 'Streptococcus', 'Pseudomonas', 'Candida', 'B', 'Staphylococcus aureus is the most common organism in lactational mastitis.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 5, 'Management of lactational mastitis includes:', 'Stop breastfeeding immediately', 'Continue breastfeeding and give antibiotics', 'Immediate surgery', 'Observation only', 'Warm compresses only', 'B', 'Continue breastfeeding helps drain the breast. Flucloxacillin is the antibiotic of choice.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 6, 'Periductal mastitis is associated with:', 'Pregnancy', 'Smoking', 'Diabetes', 'Old age', 'Obesity', 'B', 'Periductal mastitis is strongly associated with smoking and nipple piercing.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 7, 'Bloody nipple discharge in a single duct suggests:', 'Duct ectasia', 'Fibrocystic change', 'Intraductal papilloma or carcinoma', 'Galactorrhea', 'Normal physiology', 'C', 'Unilateral single-duct bloody discharge requires investigation for papilloma or carcinoma.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 8, 'Triple assessment includes all EXCEPT:', 'Clinical examination', 'Imaging', 'Blood tests', 'Tissue diagnosis', 'Core biopsy', 'C', 'Triple assessment consists of clinical examination, imaging, and tissue diagnosis. Blood tests are not part of triple assessment.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 9, 'First imaging modality in women under 35 is:', 'Mammogram', 'Ultrasound', 'MRI', 'CT scan', 'PET scan', 'B', 'Ultrasound is preferred in women under 35 due to dense breast tissue making mammography less effective.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 10, 'C5 on cytology grading means:', 'Inadequate sample', 'Benign', 'Atypical', 'Suspicious', 'Malignant', 'E', 'C5 indicates malignant cells on fine needle aspiration cytology.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 11, 'Fat necrosis typically has a history of:', 'Infection', 'Trauma or surgery', 'Pregnancy', 'Smoking', 'Diabetes', 'B', 'Fat necrosis usually follows trauma or previous breast surgery.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 12, 'Phyllodes tumor management is:', 'Observation', 'Wide local excision', 'Lumpectomy only', 'Antibiotics', 'Aspiration', 'B', 'Phyllodes tumor requires wide local excision due to risk of malignancy and local recurrence.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 13, 'Milky nipple discharge is associated with:', 'Breast cancer', 'Prolactinoma', 'Duct ectasia', 'Papilloma', 'Fat necrosis', 'B', 'Galactorrhea (milky discharge) suggests hyperprolactinemia, often from pituitary adenoma.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 14, 'ANDI stands for:', 'Abnormal Nipple Duct Inflammation', 'Aberrations of Normal Development and Involution', 'Atypical Nodular Ductal Involvement', 'Advanced Neoplastic Disease Index', 'Acute Non-specific Ductal Infection', 'B', 'ANDI - Aberrations of Normal Development and Involution - framework for benign breast disease.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 15, 'Green-brown nipple discharge suggests:', 'Carcinoma', 'Duct ectasia', 'Papilloma', 'Mastitis', 'Galactorrhea', 'B', 'Green or brown cheesy discharge is characteristic of mammary duct ectasia.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 16, 'Non-lactational breast abscess location is typically:', 'Upper outer quadrant', 'Periareolar', 'Axillary tail', 'Lower inner quadrant', 'Retromammary', 'B', 'Non-lactational abscesses are typically periareolar, related to periductal mastitis.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 17, 'Breast cysts are most common in which age group?', '15-25 years', '25-35 years', '35-50 years', 'Over 60 years', 'Under 15 years', 'C', 'Breast cysts are most common in the 35-50 age group as part of involution.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 18, 'Core biopsy result B2 indicates:', 'Inadequate sample', 'Benign', 'Atypical', 'Suspicious', 'Malignant', 'B', 'B2 on core biopsy grading indicates a benign lesion.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 19, 'High-risk lesions requiring excision include all EXCEPT:', 'Atypical ductal hyperplasia', 'Lobular carcinoma in situ', 'Simple fibroadenoma', 'Radial scar', 'Papillary lesions', 'C', 'Simple fibroadenoma is not a high-risk lesion. ADH, LCIS, radial scar, and papillary lesions require excision.'),
('d0000037-0000-0000-0000-000000000037'::uuid, 20, 'In non-lactational breast abscess, one should always exclude:', 'Pregnancy', 'Inflammatory carcinoma', 'Tuberculosis', 'Diabetes', 'Lymphoma', 'B', 'Always exclude inflammatory breast carcinoma in non-lactational abscess, especially if not responding to treatment.');
