-- Article 38: Benign Thyroid Diseases
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d0000038-0000-0000-0000-000000000038'::uuid, 'introduction', 1, 'Introduction to Benign Thyroid Diseases', 'Benign thyroid conditions are common surgical presentations including goiter, thyroid nodules, thyroiditis, and hyperthyroidism. The thyroid gland is highly vascular and located in close proximity to critical structures including the recurrent laryngeal nerve and parathyroid glands. Understanding thyroid anatomy, physiology, and pathology is essential for safe surgical management. Evaluation includes clinical assessment, thyroid function tests, imaging, and tissue diagnosis to exclude malignancy.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 'content', 2, 'Goiter and Thyroid Nodules', 'GOITER CLASSIFICATION: Simple (diffuse), multinodular, or toxic. Endemic goiter due to iodine deficiency. Sporadic goiter may be colloid or multinodular. Retrosternal goiter can cause tracheal compression and venous obstruction.

MULTINODULAR GOITER (MNG): Most common cause of thyroid enlargement. May be non-toxic or toxic (Plummer disease). Presents as asymmetric thyroid enlargement with multiple palpable nodules. Complications include tracheal compression, dysphagia, hemorrhage into cyst, and malignancy (1-5%). Pemberton sign - facial plethora and JVD on arm elevation indicates retrosternal extension.

THYROID NODULES: Very common (4-7% palpable, 50% on ultrasound). Most are benign. Risk factors for malignancy include: age extremes, male sex, history of radiation, rapid growth, fixation, lymphadenopathy, family history of thyroid cancer or MEN syndrome.

EVALUATION: TSH first. If low TSH - thyroid scan (hot nodule rarely malignant). If normal or high TSH - ultrasound plus or minus FNAC. Ultrasound features suggesting malignancy: hypoechoic, microcalcifications, irregular margins, taller than wide, increased vascularity.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 'content', 3, 'Hyperthyroidism and Thyroiditis', 'GRAVES DISEASE: Autoimmune hyperthyroidism with TSH receptor antibodies. Features include diffuse goiter, ophthalmopathy, pretibial myxedema, acropachy. Treatment options: antithyroid drugs (carbimazole, propylthiouracil), radioactive iodine, or surgery. Thyroidectomy indicated for large goiter, ophthalmopathy, pregnancy planning, or patient preference.

TOXIC MULTINODULAR GOITER: Hyperthyroidism in elderly with MNG. No ophthalmopathy. Radioiodine uptake is patchy.

TOXIC ADENOMA: Single autonomous nodule producing excess thyroid hormone. Hot nodule on scan. Treat with surgery or radioiodine.

THYROIDITIS: Hashimoto (chronic lymphocytic) - autoimmune, may cause hypothyroidism, goitrous initially. De Quervain (subacute) - painful, viral, self-limiting. Riedel thyroiditis - rare, fibrosing, woody hard, may mimic carcinoma.

PREOPERATIVE PREPARATION: Patients must be euthyroid before surgery. Antithyroid drugs for 6-8 weeks. Lugol iodine for 10 days preoperatively reduces vascularity in Graves. Beta-blockers for symptom control.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 'content', 4, 'Surgical Management', 'INDICATIONS FOR THYROIDECTOMY: Compressive symptoms, suspected malignancy, cosmesis, hyperthyroidism refractory to medical therapy, retrosternal goiter, patient preference.

SURGICAL OPTIONS: Hemithyroidectomy (lobectomy plus isthmusectomy), subtotal thyroidectomy (rarely used now), near-total thyroidectomy, total thyroidectomy. For benign disease, hemithyroidectomy may suffice; bilateral disease requires total thyroidectomy.

COMPLICATIONS: Hemorrhage and airway compromise (emergency - open wound at bedside), recurrent laryngeal nerve injury (hoarseness - unilateral; stridor - bilateral), superior laryngeal nerve injury (voice fatigue, loss of high pitch), hypoparathyroidism (transient or permanent hypocalcemia), thyroid storm, wound infection, hypothyroidism.

RECURRENT LARYNGEAL NERVE: Runs in tracheoesophageal groove. Right nerve more variable, may be non-recurrent. Identify and preserve during dissection. Intraoperative nerve monitoring may be used.

PARATHYROID PRESERVATION: Usually 4 parathyroids. Preserve with blood supply or autotransplant if devascularized. Check calcium levels postoperatively.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'TSH is the first test for thyroid nodule evaluation. Hot nodules on scan are rarely malignant. FNAC indicated for cold or ultrasound-suspicious nodules. Patients must be euthyroid before surgery. Lugol iodine reduces vascularity in Graves disease. Always identify RLN during surgery. Check calcium postoperatively - numbness and tingling may indicate hypocalcemia. Pemberton sign indicates retrosternal extension.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 'key_points', 6, 'Key Points Summary', 'Multinodular goiter is the most common cause of thyroid enlargement. Malignancy risk factors: age extremes, male, radiation history, rapid growth, fixation. Graves disease: diffuse goiter with ophthalmopathy. Antithyroid drugs render patient euthyroid before surgery. Major complications: RLN injury, hypoparathyroidism, hemorrhage. Bleeding after thyroidectomy is an emergency - open wound at bedside. Check serum calcium postoperatively.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d0000038-0000-0000-0000-000000000038'::uuid, 1, 'Most common cause of thyroid enlargement is:', 'Thyroid cancer', 'Multinodular goiter', 'Graves disease', 'Thyroiditis', 'Solitary nodule', 'B', 'Multinodular goiter is the most common cause of thyroid enlargement.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 2, 'First investigation for a thyroid nodule is:', 'Ultrasound', 'TSH level', 'Thyroid scan', 'FNAC', 'CT scan', 'B', 'TSH is the first test. If suppressed, proceed to thyroid scan; if normal or elevated, proceed to ultrasound.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 3, 'Hot nodule on thyroid scan indicates:', 'High malignancy risk', 'Low malignancy risk (functioning nodule)', 'Thyroiditis', 'Parathyroid adenoma', 'Lymphoma', 'B', 'Hot (functioning) nodules are rarely malignant as they produce thyroid hormone.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 4, 'Pemberton sign indicates:', 'Hyperthyroidism', 'Retrosternal goiter extension', 'Thyroid cancer', 'Hypothyroidism', 'Thyroiditis', 'B', 'Pemberton sign (facial plethora and JVD on arm elevation) indicates retrosternal goiter.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 5, 'Features of Graves disease include all EXCEPT:', 'Diffuse goiter', 'Exophthalmos', 'Multinodular goiter', 'Pretibial myxedema', 'TSH receptor antibodies', 'C', 'Graves disease causes diffuse goiter, not multinodular goiter.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 6, 'Lugol iodine before thyroidectomy is used to:', 'Increase thyroid function', 'Reduce thyroid vascularity', 'Kill cancer cells', 'Improve wound healing', 'Prevent infection', 'B', 'Lugol iodine given 10 days preoperatively reduces thyroid vascularity and size.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 7, 'Unilateral recurrent laryngeal nerve injury causes:', 'Stridor', 'Hoarseness', 'Complete voice loss', 'Dysphagia', 'Aspiration only', 'B', 'Unilateral RLN injury causes hoarseness. Bilateral injury causes stridor due to vocal cord paralysis.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 8, 'Postoperative hypocalcemia after thyroidectomy is due to:', 'Thyroid hormone deficiency', 'Hypoparathyroidism', 'Blood loss', 'Infection', 'Medication effect', 'B', 'Hypocalcemia results from inadvertent removal or devascularization of parathyroid glands.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 9, 'Signs of postoperative hypocalcemia include:', 'Fever', 'Perioral tingling and Chvostek sign', 'Hoarseness', 'Neck swelling', 'Dyspnea', 'B', 'Hypocalcemia presents with perioral tingling, numbness, Chvostek and Trousseau signs.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 10, 'Management of post-thyroidectomy neck hematoma with stridor is:', 'IV steroids', 'Immediate wound opening at bedside', 'Observation', 'Antibiotics', 'CT scan first', 'B', 'Post-thyroidectomy hematoma causing airway compromise is emergency - open wound at bedside immediately.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 11, 'Ultrasound features suspicious for thyroid malignancy include all EXCEPT:', 'Microcalcifications', 'Hypoechoic nodule', 'Purely cystic nodule', 'Irregular margins', 'Taller than wide shape', 'C', 'Purely cystic nodules are almost always benign. Solid, hypoechoic, calcified lesions are suspicious.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 12, 'De Quervain thyroiditis is characterized by:', 'Autoimmune destruction', 'Painful thyroid, viral etiology, self-limiting', 'Woody hard thyroid', 'Suppurative infection', 'Iodine deficiency', 'B', 'De Quervain (subacute) thyroiditis is painful, viral, and self-limiting with elevated ESR.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 13, 'Hashimoto thyroiditis is:', 'Acute bacterial infection', 'Chronic autoimmune thyroiditis', 'Viral infection', 'Fibrosing thyroiditis', 'Malignancy', 'B', 'Hashimoto is chronic lymphocytic (autoimmune) thyroiditis, may lead to hypothyroidism.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 14, 'The recurrent laryngeal nerve runs in the:', 'Anterior triangle', 'Tracheoesophageal groove', 'Strap muscles', 'Carotid sheath', 'Thyroid isthmus', 'B', 'The RLN runs in the tracheoesophageal groove, posterior to the thyroid lobe.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 15, 'Superior laryngeal nerve injury results in:', 'Stridor', 'Loss of high-pitched voice and voice fatigue', 'Complete aphonia', 'Dysphagia', 'Neck weakness', 'B', 'External branch of SLN supplies cricothyroid. Injury causes voice fatigue and loss of high pitch.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 16, 'Before thyroidectomy for hyperthyroidism, patient should be:', 'Hypothyroid', 'Euthyroid', 'On no medication', 'Hyperthyroid', 'Fasting', 'B', 'Patients must be rendered euthyroid with antithyroid drugs before surgery to prevent thyroid storm.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 17, 'Thyroid nodule risk factors for malignancy include all EXCEPT:', 'Young age', 'Female gender', 'Radiation exposure', 'Rapid growth', 'Family history of MEN', 'B', 'Male gender increases malignancy risk. Other factors include age extremes, radiation, rapid growth, MEN family history.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 18, 'Toxic adenoma appears on thyroid scan as:', 'Cold nodule', 'Hot nodule with suppressed surrounding tissue', 'Diffuse uptake', 'No uptake', 'Patchy uptake', 'B', 'Toxic adenoma is a hot nodule that produces excess hormone and suppresses surrounding normal thyroid tissue.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 19, 'Riedel thyroiditis is characterized by:', 'Viral infection', 'Fibrosing process with woody hard thyroid', 'Autoimmune destruction', 'Hot nodule', 'Cystic degeneration', 'B', 'Riedel thyroiditis is rare fibrosing thyroiditis causing woody hard thyroid that may mimic carcinoma.'),
('d0000038-0000-0000-0000-000000000038'::uuid, 20, 'Number of parathyroid glands typically present is:', '2', '3', '4', '5', '6', 'C', 'There are typically 4 parathyroid glands - 2 superior and 2 inferior.');
