-- Article 39: External Hernias
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d0000039-0000-0000-0000-000000000039'::uuid, 'introduction', 1, 'Introduction to External Hernias', 'A hernia is defined as an abnormal protrusion of an organ or tissue through a defect in the surrounding walls. External hernias include inguinal (direct and indirect), femoral, umbilical, incisional, and epigastric hernias. Groin hernias (inguinal and femoral) are the most common, with inguinal hernias accounting for 75% of all abdominal wall hernias. Understanding anatomy and surgical management is essential for preventing complications including incarceration and strangulation.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 'content', 2, 'Inguinal Hernias', 'ANATOMY: Inguinal canal contains spermatic cord in males, round ligament in females. Boundaries: anterior (external oblique aponeurosis), posterior (transversalis fascia, conjoint tendon medially), superior (internal oblique and transversus muscles), inferior (inguinal ligament). Deep ring is in transversalis fascia; superficial ring in external oblique aponeurosis.

INDIRECT INGUINAL HERNIA: Passes through deep inguinal ring, lateral to inferior epigastric vessels. Most common type in all ages and both sexes. Congenital (patent processus vaginalis) or acquired. May descend into scrotum. Covered by all three spermatic fasciae.

DIRECT INGUINAL HERNIA: Passes through Hesselbach triangle (posterior wall), medial to inferior epigastric vessels. Acquired, more common in elderly. Does not descend into scrotum. Less likely to strangulate due to wide neck.

HESSELBACH TRIANGLE: Medial border - rectus muscle; lateral border - inferior epigastric vessels; inferior border - inguinal ligament.

CLINICAL FEATURES: Groin swelling, cough impulse, reducibility. Differentiate from femoral hernia (below and lateral to pubic tubercle), varicocele, undescended testis, lymph nodes, lipoma of cord.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 'content', 3, 'Other Abdominal Hernias', 'FEMORAL HERNIA: Through femoral canal, below and lateral to pubic tubercle. More common in women but inguinal still more common in women than femoral. High risk of strangulation due to narrow neck. Femoral ring boundaries: anterior (inguinal ligament), posterior (pectineal ligament), medial (lacunar ligament), lateral (femoral vein).

UMBILICAL HERNIA: Congenital (children) - most close spontaneously by age 2-4. Adult (para-umbilical) - acquired, more common in obese, multiparous women, ascites. May incarcerate omentum or bowel.

INCISIONAL HERNIA: Through previous surgical incision. Risk factors: wound infection, obesity, steroid use, malnutrition, midline vertical incisions, emergency surgery. Contains all layers except skin. May be large with loss of domain.

EPIGASTRIC HERNIA: Through linea alba above umbilicus. Contains preperitoneal fat, rarely bowel. Often multiple.

SPIGELIAN HERNIA: Through spigelian fascia at lateral border of rectus. Interparietal, often difficult to diagnose clinically. Ultrasound or CT helpful.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 'content', 4, 'Surgical Management', 'GENERAL PRINCIPLES: Elective repair recommended for all symptomatic hernias. Emergency surgery for incarcerated or strangulated hernias. Open or laparoscopic approaches available.

OPEN INGUINAL HERNIA REPAIR: Bassini repair (historical - posterior wall reinforcement), Shouldice repair (multilayer posterior wall), Lichtenstein tension-free mesh repair (gold standard open technique). Mesh repair has lowest recurrence rate.

LAPAROSCOPIC REPAIR: TAPP (transabdominal preperitoneal) - enters peritoneal cavity, dissects preperitoneal space. TEP (totally extraperitoneal) - does not enter peritoneal cavity. Advantages: bilateral repair, reduced postoperative pain, faster recovery. Disadvantages: general anesthesia, higher cost, learning curve.

FEMORAL HERNIA REPAIR: Low approach (Lockwood), high approach (McEvedy), inguinal approach (Lotheissen). All involve opening the canal and mesh repair.

COMPLICATIONS OF REPAIR: Seroma or hematoma, wound infection, chronic pain (inguinodynia), recurrence, testicular atrophy (ischemia), nerve injury (ilioinguinal, iliohypogastric, genital branch of genitofemoral).'),
('d0000039-0000-0000-0000-000000000039'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'Inguinal hernia is above and medial to pubic tubercle; femoral is below and lateral. Indirect hernia passes lateral to inferior epigastric vessels through deep ring. Direct hernia passes medial to inferior epigastric vessels through Hesselbach triangle. Femoral hernias have highest strangulation risk. Lichtenstein tension-free mesh repair is gold standard for open inguinal repair. Always examine opposite groin and scrotum.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 'key_points', 6, 'Key Points Summary', 'Inguinal hernias are most common (75% of all hernias). Indirect inguinal is most common type overall. Direct hernias rarely strangulate. Femoral hernias have high strangulation risk and are more common in women. Lichtenstein mesh repair has lowest recurrence rate. Emergency surgery for strangulated hernia. Chronic groin pain (inguinodynia) is common complication. Hesselbach triangle: rectus, inferior epigastrics, inguinal ligament.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d0000039-0000-0000-0000-000000000039'::uuid, 1, 'Most common type of external hernia is:', 'Femoral', 'Indirect inguinal', 'Direct inguinal', 'Umbilical', 'Incisional', 'B', 'Indirect inguinal hernia is the most common type, accounting for about 55% of all hernias.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 2, 'Indirect inguinal hernia passes:', 'Medial to inferior epigastric vessels', 'Lateral to inferior epigastric vessels', 'Through Hesselbach triangle', 'Through femoral canal', 'Through linea alba', 'B', 'Indirect inguinal hernia passes through the deep ring, lateral to the inferior epigastric vessels.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 3, 'Boundaries of Hesselbach triangle include all EXCEPT:', 'Rectus muscle medially', 'Inferior epigastric vessels laterally', 'Inguinal ligament inferiorly', 'External oblique superiorly', 'All are correct boundaries', 'D', 'Hesselbach triangle: medial (rectus), lateral (inferior epigastrics), inferior (inguinal ligament). External oblique is not a boundary.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 4, 'Femoral hernia is located:', 'Above and medial to pubic tubercle', 'Below and lateral to pubic tubercle', 'At umbilicus', 'In the flank', 'At the costal margin', 'B', 'Femoral hernia emerges below and lateral to the pubic tubercle, distinguishing it from inguinal hernia.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 5, 'Which hernia has the highest risk of strangulation?', 'Direct inguinal', 'Indirect inguinal', 'Femoral', 'Umbilical', 'Epigastric', 'C', 'Femoral hernia has the highest strangulation risk due to its narrow, rigid neck.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 6, 'Gold standard open inguinal hernia repair is:', 'Bassini repair', 'Shouldice repair', 'Lichtenstein tension-free mesh repair', 'McVay repair', 'Halsted repair', 'C', 'Lichtenstein tension-free mesh repair is the gold standard with lowest recurrence rates.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 7, 'Direct inguinal hernia rarely strangulates because:', 'It contains only omentum', 'It has a wide neck', 'It is congenital', 'It is covered by mesh', 'It is small', 'B', 'Direct hernias have a wide neck through the posterior wall defect, making strangulation uncommon.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 8, 'TAPP in laparoscopic hernia repair stands for:', 'Total anterior peritoneal procedure', 'Transabdominal preperitoneal', 'Transhernial advanced peritoneal patch', 'Tension-free anterior posterior procedure', 'Total abdominal primary procedure', 'B', 'TAPP - Transabdominal Preperitoneal approach enters the peritoneal cavity to access preperitoneal space.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 9, 'Risk factors for incisional hernia include all EXCEPT:', 'Wound infection', 'Obesity', 'Transverse incision', 'Steroid use', 'Malnutrition', 'C', 'Transverse incisions have lower incisional hernia rates. Vertical midline incisions have higher risk.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 10, 'Congenital indirect inguinal hernia is due to:', 'Weak transversalis fascia', 'Patent processus vaginalis', 'Damaged inguinal ligament', 'Absent conjoint tendon', 'Wide deep ring', 'B', 'Congenital indirect inguinal hernia results from failure of processus vaginalis to obliterate.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 11, 'Umbilical hernia in children usually:', 'Requires urgent surgery', 'Closes spontaneously by age 2-4 years', 'Is always symptomatic', 'Contains bowel', 'Strangulates frequently', 'B', 'Childhood umbilical hernias usually close spontaneously by age 2-4. Surgery if persists beyond age 4-5.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 12, 'The deep inguinal ring is a defect in:', 'External oblique aponeurosis', 'Internal oblique', 'Transversalis fascia', 'Conjoint tendon', 'Inguinal ligament', 'C', 'The deep inguinal ring is an opening in the transversalis fascia.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 13, 'Femoral ring medial border is formed by:', 'Femoral vein', 'Inguinal ligament', 'Lacunar ligament', 'Pectineal ligament', 'Femoral artery', 'C', 'Lacunar (Gimbernat) ligament forms the medial border of the femoral ring.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 14, 'In strangulated hernia, the first priority is:', 'CT scan', 'Ultrasound', 'Emergency surgery', 'Attempted reduction', 'Observation', 'C', 'Strangulated hernia requires emergency surgery to prevent bowel necrosis and perforation.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 15, 'Inguinodynia after hernia repair is caused by:', 'Mesh infection', 'Nerve entrapment or injury', 'Recurrence', 'Testicular atrophy', 'Seroma', 'B', 'Chronic groin pain (inguinodynia) is commonly due to ilioinguinal or iliohypogastric nerve injury.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 16, 'Spigelian hernia occurs through:', 'Umbilicus', 'Linea alba', 'Lateral border of rectus at semilunar line', 'Inguinal canal', 'Obturator foramen', 'C', 'Spigelian hernia occurs through the spigelian fascia at the lateral border of the rectus muscle.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 17, 'Pantaloon hernia is:', 'Recurrent hernia', 'Combined direct and indirect hernia', 'Femoral and inguinal together', 'Bilateral inguinal hernia', 'Incarcerated hernia', 'B', 'Pantaloon hernia has both direct and indirect components straddling the inferior epigastric vessels.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 18, 'TEP approach in laparoscopic hernia repair:', 'Enters peritoneal cavity', 'Does not enter peritoneal cavity', 'Uses larger mesh', 'Is done under local anesthesia', 'Has higher recurrence', 'B', 'TEP (Totally Extraperitoneal) approach does not enter the peritoneal cavity.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 19, 'Contents of inguinal canal in males include all EXCEPT:', 'Vas deferens', 'Testicular artery', 'Ilioinguinal nerve', 'Ovarian ligament', 'Genital branch of genitofemoral nerve', 'D', 'The ovarian ligament is found in females. In males, the round ligament equivalent does not exist.'),
('d0000039-0000-0000-0000-000000000039'::uuid, 20, 'Richter hernia involves:', 'Entire bowel circumference', 'Only antimesenteric border of bowel', 'Omentum only', 'Bladder', 'Appendix', 'B', 'Richter hernia involves only part of the bowel wall (antimesenteric border), not the entire circumference.');
