-- ============================================================================
-- BATCH 32: Intraoperative Monitoring - Clinical Scenario Questions
-- Topic: Clinical scenarios for perioperative monitoring and response
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- CARDIOVASCULAR MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During a laparotomy, the ECG monitor shows sudden onset ST elevation in leads II, III, aVF with hypotension (BP 75/50). SpO2 is 94%. What is most likely occurring and what is immediate action?',
'Normal surgical stress response',
'Intraoperative inferior MI - inform surgeon, consider stopping surgery, call cardiology, prepare for PCI if hemodynamically unstable',
'Artifact from diathermy',
'Hypovolemia only',
'Ventilator malfunction',
'B',
'Intraoperative MI: ST elevation with hemodynamic compromise during surgery. Inferior MI (II, III, aVF) indicates RCA territory. Management: Inform surgeon, may need to complete or abort surgery urgently, treat hemodynamic instability, aspirin if not contraindicated, urgent cardiology consultation, consider primary PCI.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient under general anesthesia has gradual BP decline from 120/80 to 85/55 over 20 minutes. HR is 85, SpO2 98%, EtCO2 normal. Surgical field shows minimal blood loss. What is the most likely cause?',
'Massive hemorrhage',
'Anesthetic-induced vasodilation or relative hypovolemia - give fluid bolus, consider vasopressor',
'Pulmonary embolism',
'Cardiac arrest',
'Equipment malfunction',
'B',
'Intraoperative hypotension without obvious bleeding: Anesthetic agents cause vasodilation and myocardial depression. May also have relative hypovolemia (NPO status, third spacing). Management: Fluid challenge (crystalloid bolus), vasopressor if needed (phenylephrine/ephedrine), check depth of anesthesia.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'The arterial line trace during surgery shows a damped waveform with reduced pulse pressure. What should be checked first?',
'Change the transducer immediately',
'Check for air bubbles, clot, kink, or loose connections in the arterial line system',
'Ignore it - BP cuff is more accurate',
'Start inotropes',
'Call for crash cart',
'B',
'Damped arterial line: Reduced pulse pressure, slurred upstroke. Causes: Air bubble in line, partial clot at catheter tip, kink in tubing, loose connection, catheter against vessel wall. Check and flush system. If cannot correct, use non-invasive BP while troubleshooting.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During laparoscopic surgery, the surgeon insufflates CO2 and the patient develops sudden bradycardia (HR drops from 72 to 38) and hypotension. What is the mechanism and management?',
'Vagal response to peritoneal stretch - reduce insufflation pressure, atropine if severe, inform surgeon',
'Anaphylaxis',
'Pulmonary embolism',
'Hemorrhage',
'Anesthetic overdose',
'A',
'Vagal response in laparoscopy: Peritoneal stretch from insufflation stimulates vagus nerve causing bradycardia and hypotension. Management: Reduce intra-abdominal pressure, give atropine (0.6mg IV) for bradycardia, give fluids, consider glycopyrrolate. Usually transient.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient with pacemaker is undergoing bowel surgery. The ECG shows pacemaker spikes but with intermittent failure to capture. The surgeon is using monopolar diathermy near the pacemaker generator. What action is needed?',
'Continue surgery unchanged',
'Request surgeon switch to bipolar diathermy, keep diathermy away from generator, ensure magnet available to switch to asynchronous mode',
'Remove the pacemaker',
'Stop surgery immediately',
'Ignore - artifact only',
'B',
'Pacemaker and diathermy: Monopolar diathermy can inhibit pacemaker sensing or cause inappropriate triggering. Management: Use bipolar when possible, keep ground pad away from generator, brief bursts of diathermy, have magnet available (converts to asynchronous mode). Pre-op pacemaker check and post-op recheck.',
'hard', 'application'),

-- RESPIRATORY MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During laparoscopic surgery, SpO2 suddenly drops from 99% to 88% and EtCO2 falls from 35 to 15 mmHg. HR increases to 120 and BP drops to 70/40. What is the most likely diagnosis?',
'Bronchospasm',
'CO2 embolism - decompress abdomen immediately, left lateral and head down position, supportive care',
'Pulmonary edema',
'ETT dislodgement',
'Pneumothorax',
'B',
'CO2 embolism in laparoscopy: CO2 enters venous circulation through open vessel. Causes sudden desaturation, hypotension, decreased EtCO2 (paradoxically - air lock in heart prevents CO2 reaching lungs). Management: Stop insufflation, release pneumoperitoneum, left lateral Trendelenburg, 100% O2, CPR if arrest.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'EtCO2 waveform shows a gradually rising baseline with normal plateau. SpO2 is 99%, RR is 12. What does this indicate?',
'Normal waveform',
'CO2 rebreathing - check soda lime exhaustion, increase fresh gas flow, check circuit for leak',
'Hypoventilation',
'Bronchospasm',
'Cardiac arrest',
'B',
'Rising CO2 baseline (baseline not returning to zero): Indicates rebreathing of CO2. Causes: Exhausted soda lime (color change), inadequate fresh gas flow in Mapleson circuits, incompetent expiratory valve. Check and replace soda lime, increase FGF if needed.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient on mechanical ventilation during surgery shows peak airway pressures increasing from 22 to 45 cmH2O over 10 minutes. SpO2 dropping to 92%. What should be checked and in what order?',
'Call for portable X-ray first',
'Hand ventilate to assess compliance, check ETT position and suction, auscultate for bronchospasm/pneumothorax, consider tension pneumothorax',
'Increase the ventilator rate',
'Deepen anesthesia only',
'Continue monitoring',
'B',
'Rising airway pressures: Systematic approach - disconnect from ventilator and hand ventilate. If easy to ventilate = ventilator issue. If difficult: Patient issue (bronchospasm, secretions, pneumothorax, endobronchial intubation). Check ETT depth, suction, auscultate, consider bronchodilator or needle decompression if tension pneumothorax.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During prone positioning for spinal surgery, SpO2 drops from 99% to 94% shortly after turning. EtCO2 and airway pressures are unchanged. What is the likely cause?',
'ETT displacement',
'Reduced chest compliance and atelectasis from prone position - accept if stable, optimize positioning',
'Cardiac arrest',
'Anesthetic overdose',
'Equipment failure',
'B',
'Prone position desaturation: Reduced chest wall compliance, dependent atelectasis, altered V/Q matching. Mild desaturation common and often acceptable if stable. Ensure proper padding (chest rolls/Wilson frame), optimize head position (avoid ETT kinking), may need to increase FiO2. Watch for pressure injuries.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'EtCO2 shows a "shark fin" pattern (slurred upstroke, no clear plateau). SpO2 is 95%. What does this indicate and what should be done?',
'Normal variant',
'Bronchospasm or airway obstruction - give bronchodilators, check ETT, deepen anesthesia if light',
'Hypovolemia',
'Cardiac tamponade',
'Normal for laparoscopic surgery',
'B',
'Shark fin capnograph: Slurred phase II (upstroke), absent or sloped phase III (plateau). Indicates obstructive pattern - bronchospasm, COPD, partial airway obstruction, kinked ETT. Management: Beta-2 agonist (salbutamol), deepen anesthesia (volatile agents bronchodilate), check ETT.',
'medium', 'application'),

-- TEMPERATURE MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A young muscular patient undergoing appendectomy develops massively increased EtCO2 (from 35 to 80), temperature rising from 36.5 to 39°C in 20 minutes, muscle rigidity, and tachycardia. What is the diagnosis?',
'Sepsis',
'Malignant hyperthermia - STOP volatile anesthetics, give dantrolene, hyperventilate with 100% O2, cool patient',
'Thyroid storm',
'Neuroleptic malignant syndrome',
'Overactive warming blanket',
'B',
'Malignant hyperthermia: Hypermetabolic crisis triggered by volatiles/succinylcholine. Signs: Rapidly rising EtCO2, hyperthermia, muscle rigidity, tachycardia, acidosis. Management: STOP trigger agents, give dantrolene 2.5mg/kg IV, 100% O2 with high flows, active cooling, treat hyperkalemia. Get MH kit.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'After 3 hours of abdominal surgery, the patient''s core temperature is 34.5°C despite the operating room being warm. What are the consequences and what should be done?',
'Hypothermia is protective - no intervention needed',
'Perioperative hypothermia - use forced air warming, warm IV fluids; prevents coagulopathy, wound infection, cardiac events',
'This is normal',
'Only treat if temperature less than 32°C',
'Stop surgery immediately',
'B',
'Perioperative hypothermia (less than 36°C): Increases bleeding (coagulopathy), wound infection, cardiac events, prolongs recovery. Prevention/treatment: Forced air warming blankets, warm IV fluids, warm irrigation, maintain room temperature. Target normothermia (greater than 36°C).',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'Post-operatively, a patient who was hypothermic (34°C) at end of surgery starts shivering in recovery. What is the significance and management?',
'Normal - cover with blankets only',
'Shivering greatly increases O2 consumption (200-400%) - warm actively, consider meperidine, ensure adequate oxygenation',
'Sign of sepsis - give antibiotics',
'Indicates emergence delirium',
'No significance',
'B',
'Post-operative shivering: Thermoregulatory response to hypothermia. Increases metabolic rate and O2 consumption by 200-400%, dangerous in cardiac patients. Management: Active warming (forced air), supplemental O2, meperidine 25mg IV (reduces shivering threshold), clonidine also effective.',
'medium', 'application'),

-- URINE OUTPUT MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During a 4-hour operation, the patient has only produced 50ml of urine (12.5ml/hr). BP has been stable at 110/70. What should be considered?',
'Normal for surgery',
'Oliguria - check for hypovolemia (give fluid challenge), consider diuretics only if fluid replete, rule out obstruction',
'Renal failure - dialysis',
'Ignore if BP normal',
'Administer furosemide immediately',
'B',
'Intraoperative oliguria (less than 0.5ml/kg/hr): Usually prerenal (hypovolemia, anesthetic-induced vasodilation). First give fluid challenge (250-500ml crystalloid). Check catheter patent. Furosemide only if fluid replete and CVP adequate. Consider vasopressor if vasodilated. Avoid nephrotoxins.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing TURP suddenly produces 3L of dilute urine over 1 hour. Serum sodium drops from 140 to 118 mEq/L. He becomes confused and has seizures. What has occurred?',
'Normal diuresis',
'TURP syndrome (dilutional hyponatremia from glycine irrigation absorption) - stop surgery, give hypertonic saline for seizures, supportive care',
'Diabetes insipidus',
'Acute kidney injury',
'Diuretic overdose',
'B',
'TURP syndrome: Absorption of hypotonic glycine irrigation fluid during TURP. Causes dilutional hyponatremia, fluid overload. Severe: confusion, seizures, blindness (glycine toxicity). Treatment: Stop surgery, furosemide, hypertonic saline (3%) carefully for symptomatic hyponatremia. Modern bipolar TURP uses saline - less risk.',
'hard', 'application'),

-- NEUROMUSCULAR MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'At the end of surgery, train-of-four (TOF) monitoring shows TOF ratio of 0.6. The surgeon wants to extubate. What should be done?',
'Extubate immediately',
'Residual paralysis - give reversal agent (neostigmine/sugammadex), wait for TOF ratio greater than 0.9 before extubation',
'Continue ventilation indefinitely',
'Give more muscle relaxant',
'TOF monitoring unreliable - ignore',
'B',
'TOF ratio less than 0.9: Clinically significant residual paralysis. Risk of aspiration, hypoxia, respiratory failure. Must reverse: Neostigmine (with glycopyrrolate) if TOF 2+ twitches, or sugammadex for rocuronium/vecuronium. Wait for TOF greater than 0.9, sustained head lift 5 seconds, adequate tidal volumes before extubation.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient given succinylcholine for rapid sequence induction does not relax after 15 minutes (TOF shows 0 twitches). What condition should be suspected?',
'Normal duration of action',
'Pseudocholinesterase deficiency - continue ventilation, sedate, wait for metabolism (may take hours), do not give more relaxant',
'Resistance to relaxants',
'Monitor malfunction',
'Give more succinylcholine',
'B',
'Pseudocholinesterase (plasma cholinesterase) deficiency: Inherited condition causing prolonged succinylcholine effect (hours instead of minutes). Management: Continue ventilation, adequate sedation, do not give anticholinesterases (make it worse), wait for metabolism. Fresh frozen plasma may help. Test patient and family later.',
'hard', 'application'),

-- BLOOD LOSS AND FLUID MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, an arterial blood gas shows Hb 7.2 g/dL (was 12 pre-op). BP is 95/60, HR 115. What is the transfusion trigger and action?',
'Wait until Hb less than 5',
'Transfuse PRBCs - symptomatic anemia with hemodynamic compromise despite Hb greater than 7, aim for Hb 7-9 in most patients',
'Hb 7 is acceptable - do not transfuse',
'Transfuse to Hb 12',
'Give IV iron',
'B',
'Intraoperative transfusion: Trigger depends on clinical status. General threshold 7-8 g/dL for stable patients. Transfuse if symptomatic (tachycardia, hypotension, poor tissue oxygenation despite fluids) regardless of number. Higher threshold (9-10) for cardiac patients. Type and crossmatch, use blood warmers.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'The CVP reading during surgery is 2 mmHg (was 8 pre-op). BP is 85/50. What does this indicate and what is the management?',
'Normal finding',
'Hypovolemia - give fluid challenge, consider blood if bleeding, reassess CVP response',
'Fluid overload',
'Cardiac tamponade',
'Equipment malfunction',
'B',
'Low CVP with hypotension: Suggests hypovolemia (blood loss, third spacing, inadequate replacement). Give fluid challenge (250ml crystalloid) and assess response. If CVP rises appropriately with BP improvement = volume responsive. If CVP rises without BP improvement = consider cardiac cause or vasopressor.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient receiving massive transfusion develops hypotension despite blood replacement. ECG shows peaked T waves. Core temp is 33°C. What electrolyte abnormality is likely?',
'Hyponatremia',
'Hyperkalemia from cold stored blood - give calcium, correct hypothermia, check and treat potassium',
'Hypocalcemia only',
'Hypernatremia',
'Hypomagnesemia',
'B',
'Massive transfusion complications: Hyperkalemia (K+ leaks from stored RBCs, worse with cold blood), hypocalcemia (citrate binds Ca2+), hypothermia, coagulopathy. Peaked T waves suggest hyperkalemia. Treat with calcium gluconate (also treats hypocalcemia), warm blood, check electrolytes frequently.',
'hard', 'application'),

-- DEPTH OF ANESTHESIA
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, the BIS (bispectral index) monitor shows a value of 75. What does this indicate?',
'Adequate anesthesia',
'Light anesthesia with risk of awareness - increase anesthetic depth, target BIS 40-60',
'Too deep anesthesia',
'Patient awake',
'Equipment error',
'B',
'BIS monitoring: 40-60 = adequate surgical anesthesia, less than 40 = deep anesthesia, greater than 60 = light/risk of awareness, greater than 80 = awake or light sedation. BIS 75 indicates inadequate depth with awareness risk. Increase volatile or IV anesthetic. Useful in TIVA and paralyzed patients.',
'easy', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A paralyzed patient under TIVA (total intravenous anesthesia) suddenly develops tachycardia (HR 110), hypertension (BP 160/100), and lacrimation. BIS has risen from 45 to 70. What is occurring?',
'Normal surgical stress',
'Signs of light anesthesia/awareness - deepen anesthesia immediately, increase propofol/opioid infusion',
'Malignant hyperthermia',
'Allergic reaction',
'Pheochromocytoma crisis',
'B',
'Intraoperative awareness signs: In paralyzed patients, cannot move so watch for autonomic signs - tachycardia, hypertension, sweating, lacrimation. BIS rise confirms light anesthesia. Give bolus of propofol/opioid and increase infusion rates. Post-op: acknowledge patient experience, offer psychological support.',
'medium', 'application'),

-- EQUIPMENT ALARMS AND RESPONSE
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'The ventilator alarm sounds for "high pressure." Peak pressure is 48 cmH2O. The patient is moving despite appearing to be under adequate anesthesia. What should be done?',
'Increase muscle relaxant',
'Patient may be light - deepen anesthesia before giving more relaxant, hand ventilate to assess',
'Turn off alarm',
'Continue unchanged',
'Perform cricothyroidotomy',
'B',
'High pressure from patient movement: "Bucking" on the ETT often indicates light anesthesia. Do not just paralyze - this masks the problem and risks awareness. Deepen anesthesia first (bolus of propofol or increase volatile). Then assess need for muscle relaxant. Hand ventilate briefly to assess compliance.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'The pulse oximeter shows SpO2 of 85% but the waveform is irregular and the patient appears pink with good air entry. BP and EtCO2 are normal. What is most likely?',
'True hypoxemia',
'Probe artifact (movement, poor perfusion, diathermy, nail polish) - check probe position, try different site',
'Carbon monoxide poisoning',
'Methemoglobinemia',
'Cyanosis',
'B',
'Pulse oximetry artifact: If reading inconsistent with clinical picture (pink patient, good ventilation, normal EtCO2), suspect artifact. Check probe position, finger perfusion, movement, diathermy interference, nail polish. Try different site (earlobe). Confirm with ABG if concerned.',
'easy', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, the anesthetic machine fails completely. All monitors go blank. What is immediate priority?',
'Wait for biomedical engineering',
'Hand ventilate with self-inflating bag (Ambu) on 100% O2, inform surgeon, call for backup equipment',
'Try to restart machine',
'Continue surgery without monitoring',
'Wake patient immediately',
'B',
'Anesthetic machine failure: Priority is ventilation and oxygenation. Every theatre must have self-inflating bag (Ambu) with O2 source as backup. Hand ventilate, inform surgeon (may need to pause), call for backup equipment/anesthetist. Clinical monitoring (color, chest movement, pulse) until monitors restored.',
'easy', 'application'),

-- POSITIONING COMPLICATIONS
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'Post-operatively, a patient who had 6-hour surgery in Lloyd-Davies position cannot dorsiflex his foot or feel the lateral leg. What has likely occurred?',
'Stroke',
'Common peroneal nerve injury from leg holder pressure - examine, document, refer physiotherapy, usually recovers',
'Spinal cord injury',
'DVT',
'Compartment syndrome',
'B',
'Common peroneal nerve palsy: Injury at fibular neck from leg stirrup/holder pressure. Presents with foot drop (cannot dorsiflex) and lateral leg numbness. Prevention: Padding at fibular neck, avoid extreme flexion/external rotation, time limits on positioning. Most recover with conservative management.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During steep Trendelenburg position for robotic pelvic surgery, the EtCO2 rises from 35 to 48 and airway pressures increase. What is the explanation?',
'Pneumothorax',
'Abdominal contents pushing on diaphragm reducing lung compliance - increase tidal volume/RR, accept higher EtCO2 if hemodynamically stable',
'CO2 embolism',
'Bronchospasm',
'Hyperventilation',
'B',
'Trendelenburg effects: Abdominal contents push diaphragm cephalad, reducing FRC and lung compliance. Increased airway pressures, potential atelectasis. Accept permissive hypercapnia if patient stable. May need higher ventilatory pressures. Also causes facial/airway edema - check before extubation.',
'medium', 'application');
