-- Article 40: Benign Colorectal Diseases
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d2000040-0000-0000-0000-000000000040'::uuid, 'introduction', 1, 'Introduction to Benign Colorectal Diseases', 'Benign colorectal conditions are common surgical presentations including diverticular disease, colonic polyps, inflammatory bowel disease, and intestinal obstruction. The colon absorbs water and electrolytes, stores feces, and facilitates defecation. Understanding colonic anatomy, physiology, and common pathologies is essential for surgical management. Blood supply is from superior and inferior mesenteric arteries with watershed areas prone to ischemia.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 'content', 2, 'Diverticular Disease', 'DEFINITIONS: Diverticulum is outpouching of bowel wall. True diverticulum contains all layers; false (pseudo) diverticulum contains only mucosa and submucosa. Colonic diverticula are false, pulsion type. Diverticulosis is presence of diverticula. Diverticular disease is symptomatic diverticulosis. Diverticulitis is inflammation of diverticula.

EPIDEMIOLOGY: Increases with age - over 50% by age 60. Most common in sigmoid colon in Western populations. Associated with low-fiber diet.

COMPLICATIONS: Diverticulitis (inflammation), abscess formation, perforation, peritonitis, fistula (colovesical most common in males), stricture, hemorrhage (usually painless, from right-sided diverticula).

HINCHEY CLASSIFICATION (Diverticulitis): Stage I - pericolic abscess; Stage II - pelvic abscess; Stage III - purulent peritonitis; Stage IV - fecal peritonitis.

MANAGEMENT: Uncomplicated diverticulitis - antibiotics, clear liquids, bowel rest. Complicated (abscess over 4cm) - CT-guided drainage. Recurrent or complicated - elective sigmoid resection. Emergency - Hartmann procedure (sigmoid resection with end colostomy) or primary anastomosis with or without diverting stoma.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 'content', 3, 'Colonic Polyps and Polyposis Syndromes', 'POLYP TYPES: Neoplastic (adenomas - tubular, villous, tubulovillous) and non-neoplastic (hyperplastic, inflammatory, hamartomatous).

ADENOMATOUS POLYPS: Premalignant. Malignancy risk increases with size (over 1cm), villous histology, and high-grade dysplasia. Adenoma-carcinoma sequence is basis for screening colonoscopy.

FAMILIAL ADENOMATOUS POLYPOSIS (FAP): Autosomal dominant, APC gene mutation on chromosome 5. Hundreds to thousands of polyps by teenage years. 100% cancer risk if untreated. Treatment: prophylactic colectomy (total colectomy with ileorectal anastomosis or proctocolectomy with IPAA). Extra-colonic manifestations: desmoid tumors, osteomas, CHRPE (congenital hypertrophy of retinal pigment epithelium).

HEREDITARY NON-POLYPOSIS COLORECTAL CANCER (HNPCC/Lynch Syndrome): Autosomal dominant, mismatch repair gene mutations (MLH1, MSH2, MSH6, PMS2). Right-sided cancers, younger age. Amsterdam criteria for diagnosis. Increased risk of endometrial, ovarian, and other cancers.

PEUTZ-JEGHERS SYNDROME: Hamartomatous polyps plus mucocutaneous pigmentation. Autosomal dominant, STK11 mutation. Increased cancer risk. Polyps may cause intussusception.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 'content', 4, 'Inflammatory Bowel Disease', 'ULCERATIVE COLITIS (UC): Mucosal inflammation, continuous from rectum. Bloody diarrhea, urgency, tenesmus. Backwash ileitis may occur. Complications: toxic megacolon, perforation, massive hemorrhage. Cancer risk increases with duration and extent. Extraintestinal: primary sclerosing cholangitis, pyoderma gangrenosum, erythema nodosum, uveitis. Surgery curative: proctocolectomy with IPAA (pouch).

CROHN DISEASE: Transmural inflammation, skip lesions, any part of GI tract (terminal ileum most common). Diarrhea, abdominal pain, weight loss. Complications: strictures, fistulae (enteroenteric, enterocutaneous, perianal), abscess, malabsorption. Cobblestone mucosa, creeping fat. Surgery not curative - resect only for complications. Preserve bowel length.

DISTINGUISHING FEATURES: UC - continuous, rectum always involved, pseudopolyps, crypt abscesses. Crohn - skip lesions, transmural, granulomas, fistulae, terminal ileum.

TOXIC MEGACOLON: Colonic dilation over 6cm with systemic toxicity. Medical emergency. Initial management: IV fluids, steroids, antibiotics, bowel rest, NGT decompression. Surgery if no improvement in 24-72 hours or perforation.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'Diverticulitis is left-sided appendicitis. Painless lower GI bleeding suggests right-sided diverticular bleed. Fistula to bladder causes pneumaturia and fecaluria. FAP has 100% cancer risk - prophylactic colectomy needed. Lynch syndrome causes right-sided cancers at younger age. UC is cured by surgery; Crohn is not. Toxic megacolon: over 6cm dilation with toxicity.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 'key_points', 6, 'Key Points Summary', 'Colonic diverticula are false (pulsion) type. Diverticulitis most common in sigmoid. Hinchey classification grades diverticulitis severity. Adenoma-carcinoma sequence underlies colorectal screening. FAP: APC gene, chromosome 5, 100% cancer risk. Lynch syndrome: mismatch repair genes, right-sided cancers. UC: mucosal, continuous; Crohn: transmural, skip lesions. Toxic megacolon is medical emergency requiring close monitoring.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d2000040-0000-0000-0000-000000000040'::uuid, 1, 'Colonic diverticula are classified as:', 'True diverticula', 'False (pseudo) diverticula', 'Traction diverticula', 'Congenital diverticula', 'Malignant diverticula', 'B', 'Colonic diverticula are false or pseudo-diverticula containing only mucosa and submucosa, not the full bowel wall.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 2, 'Most common site for diverticular disease in Western population is:', 'Cecum', 'Ascending colon', 'Transverse colon', 'Sigmoid colon', 'Rectum', 'D', 'Sigmoid colon is the most common site for diverticulosis in Western populations.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 3, 'Hinchey stage III diverticulitis refers to:', 'Pericolic abscess', 'Pelvic abscess', 'Purulent peritonitis', 'Fecal peritonitis', 'Stricture', 'C', 'Hinchey III is purulent peritonitis from perforated diverticulitis.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 4, 'Most common fistula in diverticular disease in males is:', 'Colocutaneous', 'Colovaginal', 'Colovesical', 'Coloenteric', 'Colonic stricture', 'C', 'Colovesical fistula is most common in males (bladder). In females post-hysterectomy, colovaginal is common.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 5, 'Familial adenomatous polyposis is caused by mutation in:', 'MLH1 gene', 'APC gene on chromosome 5', 'BRCA gene', 'p53 gene', 'RET gene', 'B', 'FAP is caused by APC (adenomatous polyposis coli) gene mutation on chromosome 5.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 6, 'Untreated FAP has colorectal cancer risk of:', '25%', '50%', '75%', '100%', '10%', 'D', 'FAP has 100% lifetime risk of colorectal cancer if not treated with prophylactic colectomy.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 7, 'Lynch syndrome is associated with mutations in:', 'APC gene', 'Mismatch repair genes', 'BRCA genes', 'RB gene', 'NF1 gene', 'B', 'Lynch syndrome (HNPCC) is caused by mutations in DNA mismatch repair genes (MLH1, MSH2, MSH6, PMS2).'),
('d2000040-0000-0000-0000-000000000040'::uuid, 8, 'Villous adenoma has highest malignancy risk because:', 'It is largest', 'It has more dysplastic tissue', 'It is most common', 'It bleeds more', 'It is symptomatic', 'B', 'Villous adenomas have highest proportion of dysplastic epithelium and therefore highest malignancy risk.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 9, 'Which feature distinguishes Crohn disease from ulcerative colitis?', 'Bloody diarrhea', 'Skip lesions and transmural inflammation', 'Rectal involvement', 'Pseudopolyps', 'Continuous inflammation', 'B', 'Crohn disease has skip lesions and transmural inflammation; UC is continuous and mucosal only.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 10, 'Primary sclerosing cholangitis is associated with:', 'Crohn disease', 'Ulcerative colitis', 'Diverticulitis', 'FAP', 'Lynch syndrome', 'B', 'Primary sclerosing cholangitis is an extraintestinal manifestation strongly associated with ulcerative colitis.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 11, 'Toxic megacolon is defined as colonic dilation greater than:', '3 cm', '4 cm', '5 cm', '6 cm', '8 cm', 'D', 'Toxic megacolon is transverse colon dilation greater than 6 cm with systemic toxicity.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 12, 'Surgery for ulcerative colitis is:', 'Palliative only', 'Curative', 'Contraindicated', 'Rarely needed', 'Always emergency', 'B', 'Proctocolectomy is curative for UC as the disease is limited to the colon and rectum.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 13, 'Surgery for Crohn disease should:', 'Remove all affected bowel', 'Be as extensive as possible', 'Preserve bowel length and treat complications only', 'Always include proctectomy', 'Be avoided at all costs', 'C', 'Crohn surgery should preserve bowel to prevent short bowel syndrome; resect only for complications.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 14, 'Peutz-Jeghers syndrome is characterized by:', 'Adenomatous polyps', 'Hamartomatous polyps with mucocutaneous pigmentation', 'Lymphomatous polyps', 'No polyps', 'Hyperplastic polyps only', 'B', 'Peutz-Jeghers has hamartomatous polyps and characteristic mucocutaneous (lip, buccal) pigmentation.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 15, 'Hartmann procedure involves:', 'Total colectomy', 'Sigmoid resection with end colostomy and rectal stump', 'Right hemicolectomy', 'Proctocolectomy', 'Appendectomy', 'B', 'Hartmann procedure: sigmoid resection with end colostomy (proximal) and rectal stump closure (distal).'),
('d2000040-0000-0000-0000-000000000040'::uuid, 16, 'Painless massive lower GI bleeding in diverticular disease usually originates from:', 'Sigmoid colon', 'Descending colon', 'Right colon', 'Rectum', 'Transverse colon', 'C', 'Diverticular bleeding is typically from right-sided diverticula, painless and self-limiting in 80%.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 17, 'Adenoma malignancy risk increases with all EXCEPT:', 'Size over 1 cm', 'Villous histology', 'Left-sided location', 'High-grade dysplasia', 'Multiple polyps', 'C', 'Location does not significantly affect malignancy risk. Size, villous features, and dysplasia are key factors.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 18, 'Extra-colonic manifestation of FAP includes:', 'Primary sclerosing cholangitis', 'Desmoid tumors', 'Pyoderma gangrenosum', 'Erythema nodosum', 'Uveitis', 'B', 'FAP extra-colonic features: desmoid tumors, osteomas, epidermoid cysts, CHRPE, thyroid and brain tumors.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 19, 'IPAA stands for:', 'Ileal pouch anal anastomosis', 'Internal peritoneal abdominal approach', 'Ileo-peritoneal arterial anastomosis', 'Inferior pelvic area assessment', 'Intestinal perforation acute appendicitis', 'A', 'IPAA - Ileal Pouch Anal Anastomosis, the restorative procedure after proctocolectomy.'),
('d2000040-0000-0000-0000-000000000040'::uuid, 20, 'Creeping fat is a characteristic feature of:', 'Ulcerative colitis', 'Crohn disease', 'Diverticulitis', 'Colorectal cancer', 'Ischemic colitis', 'B', 'Creeping fat (mesenteric fat wrapping around bowel) is characteristic of Crohn disease.');
