-- Article 42: Gallstones and Biliary Diseases
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d2000042-0000-0000-0000-000000000042'::uuid, 'introduction', 1, 'Introduction to Gallstones and Biliary Diseases', 'Gallstone disease (cholelithiasis) is one of the most common digestive disorders, affecting 10-15% of the adult population. The gallbladder stores and concentrates bile produced by the liver. Gallstones form when bile becomes supersaturated with cholesterol or bilirubin. Complications include acute cholecystitis, choledocholithiasis, cholangitis, gallstone pancreatitis, and rarely gallbladder carcinoma. Laparoscopic cholecystectomy is the gold standard treatment for symptomatic gallstones.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 'content', 2, 'Gallstone Types and Risk Factors', 'GALLSTONE TYPES: Cholesterol stones (80%) - yellow-green, radiolucent. Pigment stones (20%) - brown or black. Black pigment stones associated with hemolysis (sickle cell, spherocytosis) and cirrhosis. Brown pigment stones associated with biliary infection and stasis.

RISK FACTORS (5 Fs): Female, Forty, Fat (obesity), Fertile (multiparity), Fair (Caucasian). Additional: rapid weight loss, diabetes, oral contraceptives, TPN, ileal disease or resection, cirrhosis.

NATURAL HISTORY: 80% of gallstones are asymptomatic. Annual risk of developing symptoms is 1-2%. Once symptomatic, 50% will have recurrent symptoms or complications.

BILIARY COLIC: Episodic RUQ or epigastric pain after fatty meals. Pain is steady, not colicky despite the name. Lasts 30 minutes to several hours. No fever or leukocytosis. Ultrasound shows gallstones, normal gallbladder wall.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 'content', 3, 'Acute Cholecystitis and Complications', 'ACUTE CHOLECYSTITIS: Inflammation due to cystic duct obstruction by stone. Presents with RUQ pain, fever, leukocytosis. Murphy sign positive (inspiratory arrest during RUQ palpation). Ultrasound shows gallstones, thickened wall greater than 3mm, pericholecystic fluid, positive sonographic Murphy sign.

MANAGEMENT: NPO, IV fluids, analgesia, IV antibiotics. Early laparoscopic cholecystectomy (within 72 hours) is recommended. Tokyo Guidelines grade severity.

COMPLICATIONS: Empyema (pus in gallbladder), gangrene, perforation, emphysematous cholecystitis (gas-forming organisms - surgical emergency), Mirizzi syndrome (stone in cystic duct compressing CBD).

CHOLEDOCHOLITHIASIS: Stones in common bile duct. May be primary or secondary (passed from gallbladder). Presents with jaundice, RUQ pain, abnormal LFTs. Ultrasound may show dilated CBD (greater than 6mm or greater than 10mm post-cholecystectomy). MRCP or EUS for diagnosis. ERCP for stone extraction.

ACUTE CHOLANGITIS: Infection of biliary tree. Charcot triad: fever/rigors, jaundice, RUQ pain. Severe: Reynolds pentad adds hypotension and confusion. Emergency biliary drainage (ERCP preferred) plus antibiotics. Organisms: E. coli, Klebsiella, Enterococcus.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 'content', 4, 'Surgical Management', 'LAPAROSCOPIC CHOLECYSTECTOMY: Gold standard for symptomatic gallstones. Critical View of Safety: Hepatocystic triangle cleared, two structures (cystic duct and artery) seen entering gallbladder, lower third of gallbladder separated from liver. This reduces bile duct injury.

INDICATIONS: Symptomatic gallstones, acute cholecystitis, gallstone pancreatitis, porcelain gallbladder (cancer risk), large polyps greater than 10mm.

CONTRAINDICATIONS (relative): Severe cardiopulmonary disease, coagulopathy, previous extensive upper abdominal surgery, gallbladder carcinoma.

CONVERSION TO OPEN: Rate 5-10%. Indications: unclear anatomy, uncontrolled bleeding, bile duct injury, dense adhesions.

BILE DUCT INJURY: Serious complication (0.1-0.6%). Strasberg classification. Type E injuries are most severe (transection). Management depends on timing and type - immediate repair by hepatobiliary surgeon, ERCP for leaks, hepaticojejunostomy for strictures.

INTRAOPERATIVE CHOLANGIOGRAPHY: Selective or routine. Identifies CBD stones and anatomy. Alternative: laparoscopic ultrasound.

GALLSTONE PANCREATITIS: Caused by stone passing through ampulla. Mild cases: cholecystectomy during same admission. ERCP if cholangitis or persistent CBD stone. Recurrence risk without cholecystectomy is 30-50% within 6 weeks.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'Murphy sign is positive in cholecystitis, not in biliary colic. Early cholecystectomy (within 72 hours) is safe and recommended. Critical View of Safety prevents bile duct injury. Charcot triad for cholangitis - Reynolds pentad for severe. ERCP is both diagnostic and therapeutic for CBD stones. Porcelain gallbladder is a cancer risk - needs cholecystectomy.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 'key_points', 6, 'Key Points Summary', 'Cholesterol stones are most common (80%). Risk factors: 5 Fs (Female, Forty, Fat, Fertile, Fair). 80% of gallstones are asymptomatic. Acute cholecystitis: RUQ pain, fever, positive Murphy sign. Early lap chole within 72 hours is recommended. CBD stones: jaundice, dilated duct, ERCP for extraction. Cholangitis: Charcot triad, emergency biliary drainage. Bile duct injury: Critical View of Safety prevents this complication.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d2000042-0000-0000-0000-000000000042'::uuid, 1, 'Most common type of gallstone is:', 'Pigment stone', 'Cholesterol stone', 'Calcium carbonate stone', 'Mixed stone equally', 'Uric acid stone', 'B', 'Cholesterol stones account for approximately 80% of gallstones in Western populations.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 2, 'Black pigment stones are associated with:', 'Obesity', 'Hemolytic conditions', 'High cholesterol diet', 'Pregnancy', 'Diabetes', 'B', 'Black pigment stones are associated with hemolysis (sickle cell disease, hereditary spherocytosis) and cirrhosis.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 3, 'Murphy sign is positive in:', 'Biliary colic', 'Acute cholecystitis', 'Choledocholithiasis', 'Hepatitis', 'Peptic ulcer', 'B', 'Murphy sign (inspiratory arrest during RUQ palpation) is positive in acute cholecystitis due to inflamed gallbladder.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 4, 'Ultrasound finding of gallbladder wall thickness greater than 3mm suggests:', 'Normal gallbladder', 'Acute cholecystitis', 'Gallbladder polyp', 'Choledocholithiasis', 'Biliary colic', 'B', 'Wall thickness greater than 3mm is a sign of acute cholecystitis along with stones and pericholecystic fluid.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 5, 'Charcot triad consists of:', 'Fever, jaundice, RUQ pain', 'Nausea, vomiting, diarrhea', 'Jaundice, pruritus, pale stools', 'Fever, hypotension, confusion', 'Pain, vomiting, constipation', 'A', 'Charcot triad for acute cholangitis: fever/rigors, jaundice, and right upper quadrant pain.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 6, 'Reynolds pentad adds to Charcot triad:', 'Vomiting and diarrhea', 'Hypotension and confusion', 'Leukocytosis and anemia', 'Pruritus and dark urine', 'Weight loss and anorexia', 'B', 'Reynolds pentad = Charcot triad plus hypotension and altered mental status (severe cholangitis with sepsis).'),
('d2000042-0000-0000-0000-000000000042'::uuid, 7, 'Gold standard treatment for symptomatic gallstones is:', 'Medical dissolution therapy', 'Laparoscopic cholecystectomy', 'ERCP', 'Open cholecystectomy', 'Lithotripsy', 'B', 'Laparoscopic cholecystectomy is the gold standard for symptomatic gallstone disease.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 8, 'Critical View of Safety in cholecystectomy requires:', 'Visualizing the cystic duct only', 'Clearing hepatocystic triangle and seeing two structures entering gallbladder', 'Performing cholangiogram', 'Identifying CBD', 'Removing entire gallbladder wall', 'B', 'Critical View: hepatocystic triangle cleared, two structures (cystic duct and artery) entering gallbladder, lower GB separated from liver.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 9, 'Recommended timing for cholecystectomy in acute cholecystitis is:', 'Wait 6 weeks for inflammation to settle', 'Within 72 hours (early surgery)', 'Immediate same-day surgery', 'Only if antibiotics fail', 'After 2 weeks of antibiotics', 'B', 'Early laparoscopic cholecystectomy within 72 hours of presentation is recommended and safe.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 10, 'Treatment of choice for CBD stones is:', 'Open surgery', 'ERCP with stone extraction', 'Lithotripsy', 'Medical dissolution', 'Cholecystectomy alone', 'B', 'ERCP is the preferred method for extracting common bile duct stones, often followed by cholecystectomy.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 11, 'Emphysematous cholecystitis is characterized by:', 'Sterile inflammation', 'Gas-forming organisms requiring emergency surgery', 'Viral infection', 'Chronic inflammation', 'Parasitic infection', 'B', 'Emphysematous cholecystitis is caused by gas-forming organisms (Clostridium) and is a surgical emergency.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 12, 'Mirizzi syndrome is:', 'Gallbladder perforation', 'Stone in cystic duct compressing common bile duct', 'Cholangiocarcinoma', 'Primary biliary cirrhosis', 'Choledochal cyst', 'B', 'Mirizzi syndrome occurs when a stone impacted in cystic duct or Hartmann pouch compresses the CBD causing jaundice.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 13, 'Porcelain gallbladder is a risk factor for:', 'Cholangitis', 'Gallbladder carcinoma', 'Pancreatitis', 'Cirrhosis', 'Hepatitis', 'B', 'Porcelain gallbladder (calcified wall) is associated with increased risk of gallbladder carcinoma.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 14, 'Gallstone pancreatitis is caused by:', 'Stone obstructing cystic duct', 'Stone passing through ampulla of Vater', 'Stone in gallbladder fundus', 'Cholesterol deposits in pancreas', 'Bile reflux into stomach', 'B', 'Gallstone pancreatitis occurs when a stone passes through or obstructs the ampulla of Vater.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 15, 'After gallstone pancreatitis, cholecystectomy should be performed:', 'After 3 months', 'During same hospital admission', 'Only if recurrent', 'Never', 'After 6 weeks', 'B', 'Cholecystectomy during the same admission for mild pancreatitis reduces recurrence risk (30-50% within 6 weeks without surgery).'),
('d2000042-0000-0000-0000-000000000042'::uuid, 16, 'Normal CBD diameter on ultrasound is:', 'Less than 2 mm', 'Less than 6 mm', 'Less than 10 mm', 'Less than 15 mm', 'Any size is normal', 'B', 'Normal CBD is less than 6mm (or less than 10mm post-cholecystectomy). Dilation suggests obstruction.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 17, 'Most common organism in ascending cholangitis is:', 'Staphylococcus aureus', 'E. coli', 'Streptococcus', 'Pseudomonas', 'Candida', 'B', 'E. coli is the most common organism, followed by Klebsiella and Enterococcus in biliary infections.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 18, 'Conversion rate from laparoscopic to open cholecystectomy is approximately:', '1-2%', '5-10%', '20-25%', '30-40%', 'Less than 0.5%', 'B', 'Conversion rate is approximately 5-10%, higher in acute cholecystitis and complicated cases.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 19, 'Bile duct injury during cholecystectomy occurs in:', '5-10%', '1-2%', '0.1-0.6%', '0.01%', '15-20%', 'C', 'Bile duct injury rate is 0.1-0.6%, slightly higher in laparoscopic than open surgery.'),
('d2000042-0000-0000-0000-000000000042'::uuid, 20, 'The 5 Fs risk factors for gallstones are:', 'Fever, Fatigue, Flatulence, Fat, Fasting', 'Female, Forty, Fat, Fertile, Fair', 'Fast, Furious, Fat, Faint, Forgetful', 'Frequent, Fatty, Female, Feverish, Fatigued', 'None of the above', 'B', 'Classic 5 Fs: Female, Forty (age), Fat (obesity), Fertile (multiparity), Fair (Caucasian).');
