-- Article 43: Dysphagia and Oesophageal Diseases
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d0000043-0000-0000-0000-000000000043'::uuid, 'introduction', 1, 'Introduction to Dysphagia', 'Dysphagia is difficulty swallowing and is a symptom requiring thorough investigation to exclude malignancy. It may be oropharyngeal (transfer dysphagia) or esophageal. Esophageal dysphagia may be due to mechanical obstruction (stricture, cancer) or motility disorders (achalasia, diffuse esophageal spasm). Progressive dysphagia to solids suggests mechanical obstruction; dysphagia to both solids and liquids from onset suggests motility disorder. Alarm symptoms requiring urgent investigation include weight loss, anemia, and age over 55.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 'content', 2, 'Causes and Investigation of Dysphagia', 'OROPHARYNGEAL DYSPHAGIA: Neurological (stroke, Parkinson, MND, myasthenia gravis), muscular (polymyositis, muscular dystrophy), structural (pharyngeal pouch, Zenker diverticulum). Presents with difficulty initiating swallow, nasal regurgitation, coughing, aspiration.

ESOPHAGEAL DYSPHAGIA - MECHANICAL: Benign stricture (peptic, caustic, post-radiation), malignant stricture (esophageal or gastric cardia cancer), esophageal web (Plummer-Vinson/Patterson-Kelly syndrome with iron deficiency), Schatzki ring (mucosal ring at GE junction), extrinsic compression.

ESOPHAGEAL DYSPHAGIA - MOTILITY: Achalasia, diffuse esophageal spasm, nutcracker esophagus, scleroderma. Dysphagia to both solids and liquids. Motility disorders diagnosed by esophageal manometry.

INVESTIGATIONS: Barium swallow (first-line for oropharyngeal, pharyngeal pouch, motility disorders). Upper GI endoscopy (visualization, biopsy, therapeutic). CT scan (staging for malignancy). Esophageal manometry (motility disorders). pH studies (GERD assessment).'),
('d0000043-0000-0000-0000-000000000043'::uuid, 'content', 3, 'Gastroesophageal Reflux Disease and Complications', 'GERD: Reflux of gastric contents causing symptoms or complications. Heartburn, regurgitation, waterbrash. Risk factors: obesity, hiatal hernia, pregnancy, smoking, certain foods.

COMPLICATIONS: Esophagitis (Los Angeles classification A-D), peptic stricture, Barrett esophagus (intestinal metaplasia - premalignant), adenocarcinoma.

BARRETT ESOPHAGUS: Columnar metaplasia replacing squamous epithelium. Risk of adenocarcinoma 0.5% per year. Surveillance endoscopy with quadrantic biopsies. Dysplasia management: low-grade - surveillance or endoscopic therapy; high-grade - endoscopic resection/ablation.

HIATAL HERNIA: Type I (sliding) - 95%, GE junction slides into chest. Type II (paraesophageal) - GE junction in normal position, fundus herniates. Type III (mixed) - both components. Type IV - other organs (colon, spleen) herniate. Paraesophageal hernias risk strangulation.

MANAGEMENT: Lifestyle modifications (weight loss, elevate head of bed, avoid triggers). PPIs (first-line medical). Surgery (Nissen fundoplication - laparoscopic) for refractory GERD, large hiatal hernia, complications. Anti-reflux procedures: complete (Nissen 360) or partial (Toupet 270 posterior, Dor 180 anterior).'),
('d0000043-0000-0000-0000-000000000043'::uuid, 'content', 4, 'Achalasia and Other Motility Disorders', 'ACHALASIA: Failure of LES relaxation due to degeneration of myenteric plexus ganglion cells. Progressive dysphagia to solids AND liquids, regurgitation of undigested food, weight loss, chest pain. Bird beak appearance on barium swallow. Absent peristalsis and incomplete LES relaxation on manometry.

TREATMENT: Pneumatic (balloon) dilation (70-80% effective), Heller myotomy (laparoscopic, combined with partial fundoplication), peroral endoscopic myotomy (POEM), botulinum toxin injection (temporary). Surgery most durable long-term.

DIFFUSE ESOPHAGEAL SPASM: Intermittent dysphagia and chest pain. Corkscrew esophagus on barium swallow. Simultaneous non-peristaltic contractions on manometry. Treat with calcium channel blockers, nitrates.

PHARYNGEAL POUCH (Zenker Diverticulum): Pulsion diverticulum through Killian dehiscence (between thyropharyngeal and cricopharyngeal parts of inferior constrictor). Presents with dysphagia, regurgitation of undigested food, halitosis, aspiration, neck swelling (gurgling). Treatment: endoscopic stapling or open surgery (diverticulectomy or diverticulopexy with cricopharyngeal myotomy).

ESOPHAGEAL PERFORATION: Boerhaave syndrome (spontaneous perforation after vomiting). Iatrogenic (endoscopy most common cause). Presents with chest pain, surgical emphysema, fever. Mackler triad: vomiting, chest pain, subcutaneous emphysema. CXR shows pneumomediastinum. CT with oral contrast confirms. Management: NPO, IV antibiotics, drainage. Small contained perforations may be managed conservatively or with stent. Surgical repair for larger perforations.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'Progressive dysphagia to solids suggests mechanical obstruction; solids and liquids from onset suggests motility disorder. Bird beak on barium swallow is achalasia. Corkscrew esophagus is diffuse esophageal spasm. Barrett esophagus is premalignant - requires surveillance. Pharyngeal pouch causes regurgitation of undigested food and halitosis. Boerhaave syndrome: spontaneous esophageal perforation after vomiting.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 'key_points', 6, 'Key Points Summary', 'Dysphagia requires investigation to exclude malignancy. Oropharyngeal dysphagia: difficulty initiating swallow. Esophageal dysphagia: food sticks after swallowing. GERD complications: stricture, Barrett, adenocarcinoma. Barrett esophagus: intestinal metaplasia, 0.5% annual cancer risk. Achalasia: LES fails to relax, bird beak on barium. Treatment: Heller myotomy or balloon dilation. Esophageal perforation (Boerhaave): emergency, Mackler triad.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d0000043-0000-0000-0000-000000000043'::uuid, 1, 'Progressive dysphagia to solids only suggests:', 'Motility disorder', 'Mechanical obstruction', 'Functional dysphagia', 'Oropharyngeal dysphagia', 'Psychological cause', 'B', 'Progressive dysphagia to solids then liquids suggests progressive mechanical obstruction like stricture or cancer.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 2, 'Dysphagia to both solids and liquids from onset suggests:', 'Cancer', 'Peptic stricture', 'Motility disorder', 'Esophageal web', 'Foreign body', 'C', 'Dysphagia to both solids and liquids from the beginning suggests esophageal motility disorder.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 3, 'Bird beak appearance on barium swallow is seen in:', 'Esophageal cancer', 'Achalasia', 'Diffuse esophageal spasm', 'Peptic stricture', 'Pharyngeal pouch', 'B', 'Bird beak or rat tail appearance is characteristic of achalasia due to failure of LES relaxation.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 4, 'Achalasia is diagnosed definitively by:', 'Barium swallow', 'Endoscopy', 'Esophageal manometry', 'CT scan', 'pH study', 'C', 'Esophageal manometry is definitive, showing absent peristalsis and incomplete LES relaxation.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 5, 'Barrett esophagus is:', 'Squamous cell carcinoma', 'Intestinal metaplasia of esophageal epithelium', 'Inflammatory stricture', 'Motility disorder', 'Hiatal hernia', 'B', 'Barrett esophagus is intestinal (columnar) metaplasia replacing normal squamous epithelium, premalignant for adenocarcinoma.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 6, 'Annual risk of adenocarcinoma in Barrett esophagus is approximately:', '0.1%', '0.5%', '5%', '10%', '25%', 'B', 'Barrett esophagus carries approximately 0.5% annual risk of progression to adenocarcinoma.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 7, 'Most common type of hiatal hernia is:', 'Sliding (Type I)', 'Paraesophageal (Type II)', 'Mixed (Type III)', 'Type IV', 'Rolling', 'A', 'Sliding (Type I) hiatal hernia accounts for about 95% of all hiatal hernias.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 8, 'Laparoscopic Nissen fundoplication is a:', '180-degree anterior wrap', '270-degree posterior wrap', '360-degree complete wrap', '90-degree wrap', 'Partial anterior and posterior wrap', 'C', 'Nissen fundoplication is a 360-degree (complete) wrap of the gastric fundus around the esophagus.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 9, 'Corkscrew esophagus on barium swallow indicates:', 'Achalasia', 'Diffuse esophageal spasm', 'Cancer', 'Stricture', 'Barrett esophagus', 'B', 'Corkscrew or rosary bead appearance is characteristic of diffuse esophageal spasm.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 10, 'Pharyngeal pouch (Zenker diverticulum) occurs through:', 'Esophageal muscle wall', 'Killian dehiscence', 'Lower esophageal sphincter', 'Gastric cardia', 'Cricoid cartilage', 'B', 'Zenker diverticulum is a pulsion diverticulum through Killian dehiscence in the posterior pharynx.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 11, 'Plummer-Vinson syndrome consists of:', 'Dysphagia, iron deficiency, esophageal web', 'Achalasia and stricture', 'GERD and Barrett', 'Cancer and weight loss', 'Motility disorder and chest pain', 'A', 'Plummer-Vinson (Patterson-Kelly) syndrome: dysphagia, iron deficiency anemia, and upper esophageal web.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 12, 'Boerhaave syndrome is:', 'Spontaneous esophageal perforation', 'Achalasia', 'Esophageal cancer', 'Stricture', 'Motility disorder', 'A', 'Boerhaave syndrome is spontaneous (postemetic) rupture of esophagus, usually left posterolateral distal esophagus.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 13, 'Mackler triad includes:', 'Fever, jaundice, RUQ pain', 'Vomiting, chest pain, subcutaneous emphysema', 'Dysphagia, weight loss, anemia', 'Heartburn, regurgitation, dysphagia', 'Cough, fever, dyspnea', 'B', 'Mackler triad for esophageal perforation: vomiting, lower thoracic pain, subcutaneous emphysema.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 14, 'Most common cause of esophageal perforation is:', 'Boerhaave syndrome', 'Iatrogenic (endoscopy)', 'Foreign body', 'Trauma', 'Malignancy', 'B', 'Iatrogenic perforation (during endoscopy) is the most common cause of esophageal perforation.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 15, 'Surgical treatment for achalasia is:', 'Esophagectomy', 'Heller myotomy', 'Nissen fundoplication', 'Stricturoplasty', 'Gastric bypass', 'B', 'Laparoscopic Heller myotomy (cardiomyotomy) with partial fundoplication is surgical treatment for achalasia.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 16, 'Paraesophageal hernia is concerning because of risk of:', 'Acid reflux', 'Gastric volvulus and strangulation', 'Esophageal cancer', 'Motility disorder', 'Bleeding', 'B', 'Type II (paraesophageal) hernias risk gastric volvulus, strangulation, and incarceration.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 17, 'First-line medical treatment for GERD is:', 'H2 blockers', 'Proton pump inhibitors', 'Antacids', 'Prokinetics', 'Sucralfate', 'B', 'Proton pump inhibitors (PPIs) are the most effective first-line medical treatment for GERD.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 18, 'Schatzki ring is located at:', 'Upper esophagus', 'Mid-esophagus', 'Gastroesophageal junction', 'Pylorus', 'Pharynx', 'C', 'Schatzki ring is a mucosal ring at the gastroesophageal junction causing intermittent dysphagia to solids.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 19, 'POEM procedure for achalasia stands for:', 'Partial oral endoscopic myotomy', 'Peroral endoscopic myotomy', 'Primary open esophageal myotomy', 'Posterior oral esophageal myectomy', 'Pneumatic oral endoscopic maneuver', 'B', 'POEM - Peroral Endoscopic Myotomy is a newer endoscopic technique for treating achalasia.'),
('d0000043-0000-0000-0000-000000000043'::uuid, 20, 'Los Angeles classification grades:', 'Barrett esophagus', 'Reflux esophagitis severity', 'Achalasia', 'Esophageal cancer staging', 'Hiatal hernia size', 'B', 'Los Angeles classification (A-D) grades severity of erosive reflux esophagitis on endoscopy.');
