-- Article 44: Urinary Tumours
-- Surgery 2 CME Content

-- Insert sections
INSERT INTO article_sections (article_id, section_type, section_order, title, content) VALUES
('d0000044-0000-0000-0000-000000000044'::uuid, 'introduction', 1, 'Introduction to Urinary Tumours', 'Urinary tract tumours include renal cell carcinoma (RCC), urothelial (transitional cell) carcinoma of the bladder, ureter and renal pelvis, and less commonly squamous cell and adenocarcinoma. Bladder cancer is the most common urological malignancy. Haematuria is the cardinal symptom requiring investigation. Early detection improves prognosis. Understanding risk factors, presentation, investigation and management is essential for urological surgical practice.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 'content', 2, 'Renal Cell Carcinoma', 'EPIDEMIOLOGY: 3% of adult malignancies. Male predominance (2:1). Peak age 60-70 years. Risk factors: smoking, obesity, hypertension, acquired cystic kidney disease (dialysis patients), VHL syndrome, hereditary papillary RCC.

CLASSIFICATION: Clear cell carcinoma (70-80%, worst prognosis), papillary (10-15%), chromophobe (5%), collecting duct carcinoma (rare, aggressive), oncocytoma (benign).

PRESENTATION: Classic triad (haematuria, flank pain, palpable mass) in less than 10%. Often incidental finding on imaging. Paraneoplastic syndromes: hypercalcemia, polycythemia (EPO), hypertension (renin), Stauffer syndrome (hepatic dysfunction).

LEFT-SIDED: Varicocele (left renal vein compression) is concerning for RCC in adult males.

STAGING: T1 (less than 7cm, confined to kidney), T2 (greater than 7cm, confined), T3 (extends into major veins or perinephric tissue), T4 (invades beyond Gerota fascia). Metastases to lung (most common), bone, liver, brain. Cannonball metastases on CXR.

TREATMENT: Partial nephrectomy for T1 tumors (nephron-sparing). Radical nephrectomy for larger or locally advanced. Cytoreductive nephrectomy in metastatic disease. Targeted therapy: tyrosine kinase inhibitors (sunitinib), mTOR inhibitors, immunotherapy (checkpoint inhibitors). RCC is classically chemo and radio-resistant.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 'content', 3, 'Bladder Cancer', 'EPIDEMIOLOGY: Most common urological cancer. Male to female 3:1. Peak age 65-70. Risk factors: smoking (most important, 50% of cases), occupational carcinogens (arylamines - dye workers, rubber industry), schistosomiasis (squamous cell carcinoma), chronic irritation, cyclophosphamide.

HISTOLOGY: Transitional cell carcinoma (TCC/urothelial) 90%, squamous cell carcinoma (SCC) 5%, adenocarcinoma 2%. SCC associated with chronic irritation and schistosomiasis.

PRESENTATION: Painless haematuria (most common - 85%), irritative voiding symptoms, recurrent UTI. Advanced disease: pelvic pain, lower extremity edema, hydronephrosis.

STAGING: Ta (papillary, non-invasive), Tis (CIS - flat, high grade), T1 (invades lamina propria), T2 (invades muscle - superficial T2a, deep T2b), T3 (perivesical tissue), T4 (adjacent organs, pelvic wall). Non-muscle invasive (NMIBC): Ta, Tis, T1. Muscle-invasive (MIBC): T2 and above.

INVESTIGATION: Cystoscopy with biopsy (gold standard), urine cytology (high-grade detection), CT urogram, bimanual examination under anesthesia.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 'content', 4, 'Bladder Cancer Management', 'NON-MUSCLE INVASIVE (NMIBC): TURBT (transurethral resection of bladder tumour) for diagnosis and treatment. Intravesical therapy for intermediate and high risk: BCG (Bacillus Calmette-Guerin) for CIS and high-grade Ta/T1, or mitomycin C. Surveillance cystoscopy essential due to high recurrence (50-70%).

MUSCLE-INVASIVE (MIBC): Radical cystectomy with pelvic lymph node dissection (gold standard). Urinary diversion: ileal conduit (Bricker), continent diversion, orthotopic neobladder. Neoadjuvant chemotherapy (cisplatin-based) improves survival. Bladder-sparing: chemoradiation for select patients.

UPPER TRACT UROTHELIAL CARCINOMA: TCC of renal pelvis or ureter. Presents with haematuria, flank pain. CT urogram, ureteroscopy for diagnosis. Treatment: nephroureterectomy with bladder cuff excision.

PROGNOSIS: NMIBC - good prognosis but high recurrence. MIBC - 5-year survival 50% with radical treatment. Metastatic disease has poor prognosis.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 'clinical_pearls', 5, 'Clinical Pearls', 'Painless haematuria is bladder cancer until proven otherwise. Smoking is main risk factor for both RCC and bladder cancer. RCC: classic triad seen in less than 10%. Left varicocele in adult male suggests left RCC. RCC is chemo and radio-resistant - use targeted therapy. BCG intravesical therapy for high-risk NMIBC. Cystoscopy surveillance essential for bladder cancer.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 'key_points', 6, 'Key Points Summary', 'RCC: clear cell most common, worst prognosis. Paraneoplastic syndromes common. Treatment: partial or radical nephrectomy, targeted therapy. Bladder cancer: TCC most common, smoking major risk factor. NMIBC: TURBT plus or minus intravesical BCG. MIBC: radical cystectomy with neoadjuvant chemotherapy. Upper tract TCC: nephroureterectomy with bladder cuff.');

-- Insert MCQs
INSERT INTO article_self_assessments (article_id, question_number, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation) VALUES
('d0000044-0000-0000-0000-000000000044'::uuid, 1, 'Most common histological type of renal cell carcinoma is:', 'Papillary', 'Chromophobe', 'Clear cell', 'Collecting duct', 'Oncocytoma', 'C', 'Clear cell carcinoma accounts for 70-80% of RCC cases and has the worst prognosis.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 2, 'Classic triad of renal cell carcinoma is seen in:', 'Less than 10% of cases', '50% of cases', '75% of cases', 'All cases', 'No cases', 'A', 'The classic triad (haematuria, flank pain, palpable mass) is seen in less than 10% of RCC cases.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 3, 'Left-sided varicocele in an adult male should raise suspicion for:', 'Testicular torsion', 'Left renal cell carcinoma', 'Bladder cancer', 'Prostate cancer', 'Epididymitis', 'B', 'Left RCC can compress the left renal vein causing left varicocele that does not decompress when supine.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 4, 'Most common metastatic site for RCC is:', 'Liver', 'Brain', 'Lung', 'Bone', 'Adrenal', 'C', 'Lung is the most common site of RCC metastasis. Cannonball metastases are characteristic.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 5, 'RCC is characteristically resistant to:', 'Surgery', 'Chemotherapy and radiotherapy', 'Immunotherapy', 'Targeted therapy', 'All treatments', 'B', 'RCC is classically resistant to conventional chemotherapy and radiotherapy. Treatment relies on surgery and targeted/immunotherapy.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 6, 'Most common histological type of bladder cancer is:', 'Squamous cell carcinoma', 'Adenocarcinoma', 'Transitional cell carcinoma', 'Small cell carcinoma', 'Sarcoma', 'C', 'Transitional cell carcinoma (urothelial carcinoma) accounts for 90% of bladder cancers.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 7, 'Most important risk factor for bladder cancer is:', 'Alcohol', 'Smoking', 'Age', 'Gender', 'Diet', 'B', 'Smoking is the most important risk factor, accounting for approximately 50% of bladder cancers.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 8, 'Schistosomiasis is associated with which bladder cancer type?', 'Transitional cell carcinoma', 'Squamous cell carcinoma', 'Adenocarcinoma', 'Small cell carcinoma', 'Sarcoma', 'B', 'Schistosoma haematobium infection is associated with squamous cell carcinoma of the bladder.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 9, 'Gold standard investigation for bladder cancer is:', 'CT scan', 'MRI', 'Cystoscopy with biopsy', 'Urine cytology', 'Ultrasound', 'C', 'Cystoscopy with biopsy is the gold standard for diagnosis, staging, and treatment of bladder tumors.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 10, 'Non-muscle invasive bladder cancer includes stages:', 'T2 and above', 'Ta, Tis, T1', 'T3 and T4 only', 'Any N positive', 'Metastatic only', 'B', 'NMIBC includes Ta (papillary non-invasive), Tis (CIS), and T1 (lamina propria invasion only).'),
('d0000044-0000-0000-0000-000000000044'::uuid, 11, 'BCG intravesical therapy is used for:', 'Muscle-invasive bladder cancer', 'High-risk non-muscle invasive bladder cancer', 'Renal cell carcinoma', 'Prostate cancer', 'Upper tract TCC only', 'B', 'BCG (Bacillus Calmette-Guerin) is used for high-risk NMIBC including CIS and high-grade Ta/T1 tumors.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 12, 'Treatment for muscle-invasive bladder cancer is:', 'TURBT alone', 'Intravesical chemotherapy', 'Radical cystectomy with neoadjuvant chemotherapy', 'Observation', 'BCG therapy', 'C', 'Radical cystectomy with pelvic lymph node dissection, preceded by neoadjuvant cisplatin-based chemotherapy is standard.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 13, 'Recurrence rate for non-muscle invasive bladder cancer is approximately:', '10-20%', '30-40%', '50-70%', '90-100%', 'Less than 5%', 'C', 'NMIBC has a high recurrence rate of 50-70%, necessitating regular surveillance cystoscopy.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 14, 'Upper tract urothelial carcinoma treatment is:', 'TURBT', 'Nephroureterectomy with bladder cuff excision', 'Partial nephrectomy', 'Chemotherapy alone', 'Radiotherapy alone', 'B', 'Nephroureterectomy with excision of bladder cuff is standard treatment for upper tract TCC.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 15, 'Paraneoplastic syndrome associated with RCC includes:', 'SIADH', 'Hypercalcemia', 'Hypoglycemia', 'Cushing syndrome', 'Carcinoid syndrome', 'B', 'RCC can cause hypercalcemia (PTHrP secretion), polycythemia (EPO), hypertension (renin), Stauffer syndrome.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 16, 'Von Hippel-Lindau syndrome is associated with:', 'Bladder cancer', 'Clear cell renal carcinoma', 'Prostate cancer', 'Testicular cancer', 'Wilms tumor', 'B', 'VHL syndrome is associated with bilateral, multifocal clear cell RCC, as well as cerebellar hemangioblastomas and pheochromocytomas.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 17, 'TURBT stands for:', 'Total urinary bladder therapy', 'Transurethral resection of bladder tumour', 'Targeted urologic bladder treatment', 'Trans-abdominal urologic bladder therapy', 'Total ureter and bladder treatment', 'B', 'TURBT - Transurethral Resection of Bladder Tumour - both diagnostic and therapeutic procedure.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 18, 'Ileal conduit urinary diversion is also known as:', 'Neobladder', 'Bricker procedure', 'Mitrofanoff procedure', 'Indiana pouch', 'Studer neobladder', 'B', 'Bricker procedure is an ileal conduit - incontinent urinary diversion with urostomy.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 19, 'Targeted therapy for metastatic RCC includes:', 'Cisplatin', 'Sunitinib (tyrosine kinase inhibitor)', 'Doxorubicin', 'Methotrexate', '5-Fluorouracil', 'B', 'Sunitinib and other TKIs (sorafenib, pazopanib) are used for metastatic RCC, along with checkpoint inhibitors.'),
('d0000044-0000-0000-0000-000000000044'::uuid, 20, 'CIS (carcinoma in situ) of bladder is characterized by:', 'Low grade, papillary', 'High grade, flat', 'Muscle invasive', 'Benign', 'Always metastatic', 'B', 'CIS (Tis) is flat, high-grade intraepithelial neoplasia with high progression risk, treated with BCG.');
