-- ============================================================================
-- BATCH 33: Nasogastric Intubation - Clinical Scenario Questions
-- Topic: Clinical scenarios for NG tube insertion, management and complications
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- INDICATIONS AND DECISION-MAKING
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old man presents with 3 days of absolute constipation, bilious vomiting, and abdominal distension. X-ray shows multiple air-fluid levels. What is the role of nasogastric tube in this case?',
'Contraindicated in bowel obstruction',
'Gastric decompression to relieve vomiting, reduce aspiration risk, and allow stabilization before surgery',
'For feeding purposes only',
'To give laxatives',
'Not helpful in this condition',
'B',
'NG tube in bowel obstruction: Essential for decompression of distended stomach, relieves vomiting, reduces aspiration risk. Wide-bore tube (16-18Fr) for thick aspirates. Keep on free drainage or low intermittent suction. Part of initial management with IV fluids, analgesia, and electrolyte correction.',
'easy', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A stroke patient cannot swallow safely due to aspiration on speech therapy assessment. He needs nutrition support. What type of NG tube is appropriate and for how long?',
'Wide-bore Ryle tube for long-term feeding',
'Fine-bore feeding tube (8-10Fr) for up to 4-6 weeks, then consider gastrostomy if prolonged need expected',
'No NG tube - only IV nutrition',
'Orogastric tube',
'Wait until swallow recovers',
'B',
'NG feeding in dysphagia: Fine-bore tubes (Flocare, Corpak - 8-10Fr) for feeding. Less irritation than wide-bore. Suitable for up to 4-6 weeks. If longer nutrition support needed, consider PEG/RIG (gastrostomy). Wide-bore tubes for decompression, not feeding. May need radiographic confirmation of position.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with severe facial injuries from RTA has base of skull fracture suspected (CSF rhinorrhea, periorbital hematoma). He needs gastric decompression. What is the safest approach?',
'Standard nasogastric tube insertion',
'Orogastric tube insertion - NG tube contraindicated with suspected base of skull fracture',
'Percutaneous gastrostomy',
'No tube placement',
'Surgical gastrostomy',
'B',
'Base of skull fracture: Cribriform plate disruption may allow NG tube to pass into cranial cavity. Signs: CSF leak (rhinorrhea/otorrhea), raccoon eyes, Battle''s sign. Use orogastric route if gastric decompression needed. If feeding required long-term, consider post-pyloric tube or gastrostomy.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing emergency laparotomy for perforated peptic ulcer has gastric contents aspirated via NG tube. Intraoperatively, should the NG tube be left in situ?',
'Remove before incision',
'Leave in situ for post-operative drainage and to protect the repair',
'Replace with smaller tube',
'Remove if perforation found',
'Exchange for feeding tube',
'B',
'NG tube post-peptic ulcer repair: Keep for gastric decompression, prevents distension of repair, allows monitoring of aspirate (blood suggests bleeding), facilitates later feeding trials. Usually kept for 48-72 hours depending on repair type. May need to adjust position intraoperatively.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old with known esophageal varices from liver cirrhosis is vomiting blood. Can a nasogastric tube be safely inserted?',
'Absolutely contraindicated',
'Can be inserted carefully using fine-bore tube - helps assess bleeding, gives lavage access, but avoid if recent banding',
'Only after endoscopy',
'Use orogastric only',
'NG tube will stop the bleeding',
'B',
'NG in variceal bleeding: NOT absolutely contraindicated but use with caution. Helps assess ongoing bleeding, allows lavage. Use soft fine-bore tube with gentle technique. Avoid immediately after band ligation (risk of dislodging bands). Resuscitate first. Some centers avoid routine NG placement.',
'hard', 'application'),

-- INSERTION TECHNIQUE AND TROUBLESHOOTING
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'You are inserting an NG tube and the patient starts coughing persistently and becomes cyanotic. What should you do?',
'Continue insertion quickly',
'Withdraw tube immediately - likely in trachea, allow recovery, reattempt with proper positioning',
'Push through the coughing',
'Leave tube and check X-ray',
'Give sedation and retry',
'B',
'Tracheal misplacement signs: Persistent coughing, choking, cyanosis, inability to speak. Withdraw immediately. Allow patient to recover. Reattempt with head slightly flexed (chin to chest), ask patient to swallow during advancement, use water sips if able. Never continue if distress.',
'easy', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'An NG tube has been inserted and you aspirate 50ml of green fluid. pH testing shows pH 3.5. What does this confirm?',
'Tube is in respiratory tract',
'Tube is in stomach - pH less than 5.5 confirms gastric placement',
'Tube is in small bowel',
'Inconclusive - need X-ray',
'Tube is in esophagus',
'B',
'pH testing for NG position: Gastric pH typically less than 5.5 (often 1-4). Respiratory or intestinal placement shows pH greater than 6. Green/clear bile-stained aspirate with pH less than 5.5 = gastric placement confirmed. If pH 5.5-6, inconclusive - may need X-ray. Never use auscultation alone.',
'easy', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A fine-bore feeding tube is inserted and aspirate cannot be obtained for pH testing. The patient is on PPI therapy. What is the safest next step?',
'Start feeding immediately',
'Obtain chest X-ray to confirm position before feeding',
'Inject air and auscultate',
'Withdraw and reinsert',
'Wait 24 hours for aspirate',
'C',
'Unable to aspirate: Common with fine-bore tubes. PPIs increase gastric pH making testing unreliable. X-ray confirmation mandatory before feeding through fine-bore tubes when aspirate unavailable or pH indeterminate. Tube tip should be below diaphragm, left of midline, not in bronchus.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'During NG insertion in a confused elderly patient, the tube keeps coiling in the mouth. What technique can help?',
'Use larger diameter tube',
'Stiffen tube by refrigerating, flex neck during insertion, use jaw thrust if needed, consider guidewire-assisted tube',
'Force tube through',
'Use sedation',
'Abandon the procedure',
'B',
'Coiling in mouth: Tube too flexible or patient not swallowing. Stiffen by refrigerating or using cold water. Flex neck (chin to chest) to direct tube posteriorly. Encourage swallowing with water sips if safe. Guide-wire assisted tubes (Cortrak) may help. May need two-person technique in confused patients.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'After inserting an NG tube, the CXR report states "NG tube tip projects over the left lower zone below the diaphragm." Is this position acceptable for feeding?',
'No - tube is in wrong position',
'Yes - position is acceptable for feeding (below diaphragm, left side suggests stomach)',
'Need repeat X-ray',
'Withdraw 10cm and recheck',
'Only acceptable for drainage',
'B',
'NG tube position on CXR: Tube should follow esophageal line, cross diaphragm in midline, tip below diaphragm, curving to left (stomach). Left lower zone below diaphragm = in stomach. Watch for tubes in bronchi (right lower zone common) or coiled in esophagus. Record length at nostril.',
'medium', 'application'),

-- MANAGEMENT AND COMPLICATIONS
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with NG tube on continuous drainage has been draining 1500ml/day of green fluid for 3 days. Electrolytes show K+ 2.8, Na+ 132, Cl- 88. What has developed?',
'Normal findings',
'Hypochloremic hypokalemic metabolic alkalosis from gastric losses - replace potassium and consider H2 blocker',
'Metabolic acidosis',
'Hyperkalemia',
'No electrolyte consequences expected',
'B',
'NG drainage losses: Gastric juice contains HCl, K+, Na+. Prolonged drainage causes hypochloremic hypokalemic metabolic alkalosis (loss of H+ and Cl-). Replace K+ (and Cl- as KCl), monitor electrolytes daily. H2 blockers/PPIs reduce gastric secretion volume. May need careful IV replacement.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient on NG feeding develops sudden respiratory distress, coughing, and SpO2 drops to 88%. Tube has been in place for 5 days. What complication should be suspected?',
'Pulmonary embolism',
'Tube displacement with feed aspiration - stop feeding, suction airway, check tube position, CXR',
'Pneumothorax',
'Heart failure',
'Normal feeding response',
'B',
'NG tube displacement: May occur with coughing, vomiting, or spontaneously. If feeding into lungs = aspiration pneumonitis/pneumonia. Symptoms: Sudden respiratory distress, coughing, fever, hypoxia. Stop feed, suction, check tube position (pH + X-ray), support respiration. Never restart until position confirmed.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with long-term NG tube complains of severe ear pain and sore throat. Examination shows inflamed nostril and otitis media. What is the complication and management?',
'Unrelated ENT infection',
'NG tube complications (nasal erosion, sinusitis, otitis media) - consider tube change to other nostril, may need removal',
'Normal tube irritation',
'Allergic reaction',
'Continue same tube',
'B',
'NG tube ENT complications: Nasal irritation/erosion, sinusitis (Eustachian tube blockage leading to otitis media), sore throat, parotitis. Long-term tubes higher risk. Management: Alternate nostrils if replacing, consider smaller tube, good nasal care, or switch to gastrostomy for prolonged feeding.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'An NG tube becomes blocked during feeding. What steps should be taken to unblock it?',
'Remove and replace immediately',
'Flush with warm water (30-50ml) using push-pause technique, consider carbonated water or enzyme flush for stubborn blocks',
'Use guidewire to clear',
'Increase feed rate',
'Use air to clear',
'B',
'Blocked NG tube: Prevention better than cure (regular flushing). To unblock: Warm water flush with 50ml syringe, push-pause technique. If unsuccessful, carbonated water or pancreatic enzyme flush may dissolve feed/medication residue. If still blocked, replace tube. Never use guide wire - may perforate.',
'easy', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A ventilated ICU patient with NG tube develops abdominal distension and high gastric residual volumes (400ml). What should be considered?',
'Normal for ICU patients',
'Gastric dysmotility/ileus - consider prokinetics (metoclopramide/erythromycin), switch to post-pyloric feeding if persistent',
'Start laxatives',
'Increase feed rate',
'Remove NG tube',
'B',
'High gastric residuals in ICU: Common due to ileus, opioids, sepsis, electrolyte imbalance. Prokinetics (metoclopramide 10mg TDS, erythromycin 250mg BD) may help. Consider post-pyloric (nasojejunal) feeding if persistent. Aspiration risk higher with high residuals. Threshold varies (200-500ml concerning).',
'medium', 'application'),

-- SPECIAL SITUATIONS
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient post total gastrectomy for cancer needs enteral feeding. Where should the feeding tube tip be positioned?',
'In the stomach',
'Post-pyloric (jejunal) position - no stomach reservoir exists',
'In the esophagus',
'Standard NG position',
'Not possible to feed enterally',
'B',
'Post-gastrectomy feeding: No stomach exists, so need nasojejunal or surgically placed jejunostomy feeding. Tube tip must be beyond anastomosis (usually 20-30cm distal). Requires slow continuous feeding (no bolus possible). Check position carefully as anatomy altered.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'An NG tube is needed in a patient with known esophageal stricture who has difficulty swallowing even liquids. What is the safest approach?',
'Force standard tube through stricture',
'Endoscopic placement under direct vision, or consider gastrostomy',
'Use smaller pediatric tube',
'Do not place any tube',
'Surgical placement only',
'B',
'NG in esophageal stricture: Risk of perforation or tube coiling above stricture. Options: Endoscopic placement (under vision with dilation if needed), guidewire-assisted placement under fluoroscopy, or bypass with gastrostomy/jejunostomy. Never force blind passage through stricture.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient with NG tube develops hiccups that are persistent and distressing. What may be causing this?',
'Unrelated to NG tube',
'NG tube irritating diaphragm or vagus nerve - try repositioning or withdrawing slightly',
'Normal post-operative finding',
'Sign of infection',
'Too much drainage',
'B',
'NG-induced hiccups: Tube may irritate diaphragm, phrenic nerve, or vagus nerve. Management: Check tube length (may be too far in), withdraw slightly (2-5cm) and reassess. Other hiccup treatments: chlorpromazine, baclofen, metoclopramide, or gabapentin for persistent cases.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'Before giving medications through a fine-bore NG tube, what considerations are important?',
'Crush all tablets and give together',
'Check drug suitability for tube administration, use liquid forms when available, flush before and after, never mix medications',
'No special considerations',
'Use IV formulations through tube',
'Give medications without flushing',
'B',
'Medication via NG tube: Check if suitable for enteral administration (some cannot be crushed - enteric-coated, slow-release). Use liquid forms when available. Flush with 30ml water before and after. Give medications separately (interactions, blocking). Some medications need to be held around feeds (e.g., phenytoin).',
'medium', 'application'),

-- FEEDING MANAGEMENT
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient is started on NG feeding after prolonged starvation (3 weeks NPO due to bowel obstruction). On day 2 of feeding, he develops confusion, weakness, and arrhythmia. Labs show very low phosphate. What has occurred?',
'Normal feeding response',
'Refeeding syndrome - reduce feeding rate, correct phosphate, monitor electrolytes and supplement as needed',
'Feed intolerance',
'Sepsis',
'Fluid overload',
'B',
'Refeeding syndrome: In malnourished patients, restarting nutrition causes insulin surge, driving phosphate/potassium/magnesium intracellularly. Causes arrhythmias, confusion, weakness, cardiac failure. Prevention: Start feeds slowly (10kcal/kg/day), supplement electrolytes, monitor daily. High-risk: greater than 10 days NPO, low BMI, alcoholism.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient on continuous NG feeding at 75ml/hr develops diarrhea with 6 loose stools daily. What adjustments should be considered?',
'Stop all feeding',
'Reduce rate, consider fiber-containing formula, check for C. diff, review medications (sorbitol content)',
'Increase rate to finish faster',
'Switch to IV nutrition immediately',
'Normal finding - continue',
'B',
'Feed-related diarrhea: Common and multifactorial. Management: Reduce rate and increase gradually. Consider fiber-containing formula. Check for C. difficile (especially if antibiotics). Review medications (many liquid meds contain sorbitol). Consider probiotics. Usually manages conservatively without stopping feeds.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'What is the correct nursing position for a patient receiving bolus NG feeding?',
'Flat position',
'Semi-recumbent (30-45 degrees head up) during feeding and for 30-60 minutes after',
'Trendelenburg position',
'Prone position',
'Position does not matter',
'B',
'Aspiration prevention: Semi-recumbent position (30-45 degree head elevation) mandatory during feeding and 30-60 minutes after. Reduces gastroesophageal reflux and aspiration risk. Also important for ventilated patients. Continuous feeds safer than bolus for aspiration-prone patients.',
'easy', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with NG tube for 4 weeks continues to need enteral feeding. Swallow assessment shows no improvement. What should be considered?',
'Continue NG indefinitely',
'Referral for gastrostomy (PEG) for long-term feeding - more comfortable, lower complication rate',
'Switch to IV nutrition',
'Withdraw feeding',
'Wait another month',
'B',
'NG to gastrostomy conversion: If feeding expected greater than 4-6 weeks, consider PEG (percutaneous endoscopic gastrostomy) or RIG (radiologically inserted gastrostomy). More comfortable for patient, lower ENT complication rate, easier to manage at home, better for long-term nutrition. NG can remain until PEG established.',
'medium', 'application');
