-- ============================================================================
-- BATCH 34: Sutures and Surgical Instruments - Clinical Scenario Questions
-- Topic: Clinical scenarios for suture selection and instrument use
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- SUTURE SELECTION SCENARIOS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon is closing a midline laparotomy incision in a 60-year-old diabetic patient with BMI 35. What suture choice would reduce wound dehiscence risk?',
'Rapidly absorbable suture (Vicryl Rapide)',
'Slowly absorbable monofilament looped suture (PDS Loop) with small bites technique',
'Non-absorbable braided silk',
'Staples only',
'Catgut sutures',
'B',
'Mass closure of laparotomy: Slowly absorbable (PDS, Maxon) preferred - maintains strength during healing. Small bites technique (5mm from edge, 5mm apart) with long:wound length ratio greater than 4:1 reduces dehiscence. Looped sutures stronger. Monofilament reduces infection risk. Avoid rapidly absorbable in high-risk patients.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A child falls and sustains a 4cm laceration on his forehead. After cleaning, what suture would give the best cosmetic result?',
'2-0 Vicryl interrupted',
'5-0 or 6-0 non-absorbable monofilament (Prolene/Nylon) with subcuticular or fine interrupted technique',
'3-0 Silk',
'Staples',
'1-0 PDS',
'B',
'Facial lacerations: Fine sutures (5-0 or 6-0), non-absorbable monofilament (less tissue reaction, better cosmesis). Subcuticular technique or very fine interrupted. Remove early (5-7 days) to avoid suture marks. Deep absorbable sutures (5-0 Monocryl) for dermis. Minimize tension, precise approximation.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A vascular surgeon is performing an aortic aneurysm repair and needs to anastomose a synthetic graft to the aorta. What suture is most appropriate?',
'Absorbable suture',
'Non-absorbable monofilament polypropylene (Prolene) 3-0 or 4-0',
'Silk suture',
'Rapidly absorbable suture',
'Chromic catgut',
'B',
'Vascular anastomosis: Non-absorbable (permanent), monofilament (smooth passage, less friction/trauma), polypropylene (inert, pliable, maintains strength). Size depends on vessel (3-0 to 5-0 for aorta, 6-0 to 7-0 for smaller vessels). PTFE (Gore-Tex) alternative. Continuous running suture technique.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoes bowel anastomosis for colon cancer. The surgeon uses a single-layer technique. What suture properties are most important?',
'Non-absorbable braided',
'Absorbable monofilament (PDS or Maxon) - maintains strength during healing, monofilament reduces bacterial wicking',
'Rapidly absorbable',
'Permanent multifilament',
'Steel wire',
'B',
'GI anastomosis: Absorbable (no permanent foreign body in lumen), monofilament (less infection/fistula - no bacterial wicking along braided fibers). PDS or Maxon maintain strength for 4-6 weeks during healing. 3-0 or 4-0 size. Interrupted or continuous techniques both acceptable.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During tendon repair of a flexor digitorum profundus laceration, what suture technique and material should be used?',
'Simple interrupted absorbable sutures',
'Core suture with non-absorbable braided suture (Ethibond) using modified Kessler or similar technique, plus epitendinous repair',
'Continuous absorbable suture',
'Skin staples through tendon',
'Rapidly absorbable monofilament',
'B',
'Tendon repair: Requires strong core suture (3-0 or 4-0 braided non-absorbable - Ethibond, Ticron). Modified Kessler, Tajima, or 4-strand technique. Additional epitendinous (circumferential) suture with fine (5-0 or 6-0) suture improves strength and gliding. Early mobilization protocols important.',
'hard', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A hernia mesh is being secured during inguinal hernia repair. What suture or fixation method is appropriate?',
'Rapidly absorbable sutures',
'Non-absorbable (Prolene) or slowly absorbable sutures, or fibrin glue/self-gripping mesh',
'Steel staples',
'No fixation needed',
'Absorbable braided sutures only',
'B',
'Mesh fixation: Non-absorbable (Prolene 2-0 or 3-0) for permanent fixation. Slowly absorbable (PDS) acceptable as mesh incorporates. Self-gripping mesh (Progrip) needs no sutures. Fibrin glue (less post-op pain). Tacks/staples for laparoscopic repairs. Avoid excessive tension.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'An infected abdominal wound has been debrided and needs delayed primary closure. The tissue is edematous and under tension. What suture technique would help?',
'Fine interrupted sutures under tension',
'Interrupted mattress sutures or tension-relieving techniques (near-far-far-near)',
'Continuous subcuticular',
'Staples with maximum tension',
'Tissue glue only',
'B',
'High-tension wound closure: Mattress sutures (vertical or horizontal) distribute tension. Near-far-far-near technique reduces tissue strangulation. Consider retention sutures for high-risk abdominal wounds. Avoid excessive tension - causes ischemia and dehiscence. May need VAC therapy or skin grafting.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A patient has a skin laceration repaired with 4-0 nylon interrupted sutures on the forearm. When should sutures be removed?',
'3 days',
'10-14 days for extremity (longer than face)',
'Leave indefinitely',
'21 days',
'1 day',
'B',
'Suture removal timing varies by location: Face 5-7 days (less scarring, good blood supply), scalp 7-10 days, trunk 10-14 days, extremities 10-14 days, joints/high tension areas 14 days. Early removal = less suture marks but risk dehiscence. Use steri-strips after removal for support.',
'easy', 'application'),

-- INSTRUMENT SELECTION AND USE
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During a laparotomy, the surgeon asks for an instrument to grasp bowel atraumatically. Which forceps should be handed?',
'Kocher forceps',
'Babcock forceps or Dennis Browne bowel-holding forceps',
'Allis forceps',
'Towel clips',
'Lane twin forceps',
'B',
'Atraumatic bowel grasping: Babcock forceps (broad, flat, fenestrated ends without teeth). Dennis Browne forceps for bowel mobilization. Allis forceps traumatic (teeth) - use on tissue to be excised. Never use Kocher (heavy, crushing) on bowel. Debakey forceps for vessel/delicate handling.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon needs to clamp a bleeding vessel during emergency surgery. What is the difference between artery forceps and what should be chosen for temporary vessel occlusion?',
'All hemostats are the same',
'Bulldog clamps or vascular clamps for temporary occlusion; Spencer Wells/mosquito for permanent ligation',
'Kocher forceps for all vessels',
'Allis forceps',
'Towel clips',
'B',
'Vascular clamping: Bulldog clamps or atraumatic vascular clamps (Satinsky, DeBakey) for temporary occlusion - designed not to damage vessel wall. Artery forceps (Spencer Wells, mosquito, Crile) are for clamping vessels before ligation - they crush and damage the vessel. Different purposes.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During thyroid surgery, the surgeon asks for a "right angle." What instrument is being requested and what is it used for?',
'A protractor',
'Right-angled (Lahey) dissecting forceps - for passing ligatures around vessels or dissecting behind structures',
'A set square',
'Retractor',
'Scissors',
'B',
'Right-angled forceps (Lahey, Mixter): Curved at 90 degrees near tip. Used to pass sutures or ligatures around vessels/ducts, dissect behind structures safely. Essential in thyroid, cholecystectomy, vessel ligation. The curve allows safe passage behind structures without blind dissection.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A scrub nurse sees a needle driver with very fine jaws being used for a vascular anastomosis. The surgeon struggles because the needle keeps rotating. What would improve needle control?',
'Use larger needle driver',
'Use a needle holder with carbide (tungsten) inserts - provides better grip without damaging fine needles',
'Apply more force',
'Use tissue forceps to hold needle',
'Bend the needle',
'B',
'Needle holder selection: Fine vascular needles require needle holders with tungsten carbide inserts (golden colored jaws) - superior grip. Castroviejo needle holders for microsurgery. Match holder to needle size. Larger holders damage fine needles. Never use hemostats as needle holders (damage needle and holder).',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During an appendectomy, the surgeon asks for a retractor to hold back the wound edges in a deep incision. Which self-retaining retractor would be appropriate?',
'Langenbeck retractor',
'Balfour retractor or Travers retractor',
'Deaver retractor',
'Army-Navy retractor',
'Cat''s paw retractor',
'B',
'Self-retaining abdominal retractors: Balfour (has central blade for bladder/lower abdominal viscera), Travers for smaller incisions. Self-retaining means they stay in place without assistant holding. Hand-held (Langenbeck, Deaver) need assistant. Choice depends on incision size and depth.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A trauma surgeon is operating on a liver laceration. What instrument would help with parenchymal division while controlling bleeding?',
'Standard Metzenbaum scissors',
'CUSA (ultrasonic dissector), Ligasure, harmonic scalpel, or finger fracture technique with clips',
'Kocher forceps',
'Regular monopolar diathermy only',
'Cold knife only',
'B',
'Liver parenchymal transection: CUSA (cavitron ultrasonic surgical aspirator) fragments and aspirates parenchyma while preserving vessels/ducts. Ligasure/harmonic scalpel seal vessels. Finger fracture technique (Kelly clamp crushing) allows identification and ligation of vessels. Modern energy devices improve hemostasis.',
'hard', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During laparoscopic cholecystectomy, what instrument is used to provide a critical view of safety before clipping the cystic duct?',
'Babcock forceps',
'Maryland dissector and grasping forceps for traction to expose Calot''s triangle',
'Veress needle',
'Hassan cannula',
'Clip applier first',
'B',
'Critical view of safety: Calot''s triangle dissection requires Maryland dissector (or hook) for blunt/sharp dissection, grasping forceps for fundal traction. Must see: hepatocystic triangle cleared, lower third of gallbladder separated from liver, only two structures (cystic duct and artery) entering gallbladder. Then clip.',
'medium', 'application'),

-- SPECIFIC SURGICAL SCENARIOS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A patient has a 2cm skin lesion excised. The pathologist needs to know orientation. How should the specimen be handled?',
'Send without marking',
'Mark with sutures (long stitch = lateral or 12 o''clock, short stitch = medial or 3 o''clock) and document orientation',
'Bisect before sending',
'Place in multiple containers',
'Photograph only',
'B',
'Specimen orientation: Allows pathologist to identify margins and guide re-excision if needed. Use suture marking system (agreed with lab - e.g., long lateral, short superior). Document the marking system on request form. For large specimens, may use different colored sutures or multiple stitches.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During an operation, a swab count is wrong - one swab missing. The surgeon cannot locate it in the wound. What should be done?',
'Close anyway and monitor',
'Systematic search, X-ray if not found, document thoroughly, never close with confirmed missing swab',
'Use metal detector',
'Assume counting error',
'Complete surgery next day',
'B',
'Missing swab: Never close with confirmed missing swab. Systematic search: empty wound, check drapes, floor, bin. X-ray with radiopaque marker if not found. Modern swabs have radiopaque strips. Retained swab = medicolegal issue, infection, granuloma. Document all counts and search in operative notes.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A plastic surgeon is closing a wound in multiple layers. She asks for absorbable sutures for the dermis that will provide long-lasting support. What would be best?',
'Plain catgut',
'Poliglecaprone (Monocryl) or Poliglytone (Caprosyn) for dermis - absorbable, monofilament, long-lasting support',
'Silk sutures',
'Nylon sutures',
'Staples',
'B',
'Dermal closure: Absorbable (no removal needed), monofilament (less reactive, smooth), maintains strength 2-3 weeks. Monocryl (poliglecaprone) excellent choice. Vicryl (braided) also used but slightly more reactive. Buried interrupted technique with knots deep. Reduces tension on skin sutures.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon notices that the needle keeps bending while suturing tough fascia. What needle point and body type would be more appropriate?',
'Cutting needle with round body',
'Reverse cutting needle with reinforced (tapered) body',
'Round bodied needle',
'Blunt needle',
'Straight needle only',
'B',
'Needle selection for tough tissue: Cutting or reverse cutting point (sharp, penetrates fibrous tissue). Reverse cutting preferred (cutting edge away from wound edge). Heavy or reinforced body resists bending. Larger needle may be needed. Round-bodied for soft/friable tissue (bowel, vessel).',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon uses monopolar diathermy near the patient''s pacemaker and the pacemaker malfunctions. What precautions should have been taken?',
'Diathermy is safe with pacemakers',
'Use bipolar diathermy when possible, keep diathermy away from generator, short bursts, have magnet available',
'Avoid all surgery in pacemaker patients',
'Remove pacemaker before surgery',
'Use maximum diathermy power',
'B',
'Diathermy and pacemakers: Monopolar current can interfere with pacemaker sensing/pacing. Precautions: Use bipolar when possible, grounding pad far from generator, short bursts, keep electrosurgery greater than 15cm from device. Have magnet/programming available. Pacemaker check pre and post-op.',
'hard', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During a laparoscopic procedure, the surgeon accidentally touches bowel with the active diathermy electrode. No thermal injury is visible. How should this be managed?',
'Ignore if no visible injury',
'Document, closely inspect area, consider marking the site, monitor post-op for signs of delayed perforation',
'Convert to open surgery immediately',
'Apply more diathermy to seal',
'End procedure immediately',
'B',
'Diathermy bowel injury: Thermal injury may be deeper than visible (delayed perforation in 3-7 days). Document incident, carefully inspect bowel, consider marking site with clip, close observation post-op. Low threshold for re-look if concerning symptoms develop. Delayed presentation is common feature.',
'hard', 'application'),

-- SUTURE COMPLICATIONS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'Three weeks after bowel surgery using braided absorbable sutures, a patient develops anastomotic leak. What suture-related factor may have contributed?',
'Sutures were too strong',
'Bacterial wicking along braided suture allowing infection to track to anastomosis',
'Suture was too small',
'Suture absorbed too slowly',
'Wrong needle type',
'B',
'Braided suture and infection: Interstices of braided sutures allow bacteria to track along the suture (wicking). Once infection established in suture, difficult to eradicate. Monofilament sutures preferred for contaminated fields and GI surgery. This is why PDS (monofilament) often preferred over Vicryl (braided) for bowel.',
'hard', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A patient who had a hernia repair with non-absorbable mesh and sutures presents 2 years later with chronic pain and a palpable mass. Imaging shows no recurrence. What may be the cause?',
'Hernia recurrence',
'Suture granuloma or chronic foreign body reaction to mesh/suture',
'Normal post-operative finding',
'New hernia at different site',
'Muscle strain',
'B',
'Chronic suture/mesh reaction: Non-absorbable materials can cause chronic foreign body reaction, granuloma formation, chronic pain. Diagnosis: Imaging, clinical correlation. Management: May need exploration and removal of offending material. Some advocate absorbable fixation to reduce this. Mesh inguinodynia complex issue.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A patient develops a sinus that discharges at an old surgical scar. The wound had been sutured with silk. What has likely happened?',
'Normal healing',
'Suture sinus - silk is acting as nidus for infection/foreign body reaction',
'Recurrent cancer',
'Incisional hernia',
'Skin condition',
'B',
'Suture sinus: Non-absorbable braided sutures (especially silk) can harbor bacteria and cause chronic infection/foreign body reaction, presenting as a discharging sinus. Management: Exploration and removal of suture material. Silk rarely used now due to this complication. Absorbable or monofilament preferred.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A wound closed with staples appears to have wound edge ischemia with purple discoloration at the staple sites. What is the likely cause?',
'Normal staple appearance',
'Staples too tight causing local ischemia - may need removal and replacement',
'Infection',
'Allergic reaction',
'Hematoma',
'B',
'Staple/suture ischemia: Excessive tension causes local ischemia (blanching then purple discoloration). Can lead to necrosis and dehiscence. Management: Remove every other staple/suture to release tension, may need to leave wound open if severely ischemic. Prevention: Appropriate tension during closure.',
'easy', 'application'),

-- SPECIALIZED PROCEDURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A cardiac surgeon is closing a sternotomy. What closure method provides the best stability for bone healing?',
'Absorbable sutures',
'Stainless steel wire cerclage (figure-of-8 or interrupted)',
'Staples',
'Silk sutures',
'No closure needed',
'B',
'Sternotomy closure: Stainless steel wires provide strong, stable fixation for bone healing. Figure-of-8 technique around sternum. 6-8 wires typically used. Alternatives include titanium plates for high-risk patients (obesity, osteoporosis, revision). Closure under tension as bone must appose for healing.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During microsurgical nerve repair, what suture size and technique should be used?',
'2-0 interrupted',
'8-0 to 10-0 monofilament nylon with epineural repair under microscope magnification',
'Rapidly absorbable sutures',
'Staples',
'Tissue glue only',
'B',
'Nerve repair: Microsurgical technique with operating microscope. Very fine sutures (8-0 to 10-0) non-absorbable monofilament (nylon). Epineural repair (suturing outer covering) without tension. May use fibrin glue as adjunct. Fascicular repair for larger nerves. Minimal tissue handling. Tension-free anastomosis essential.',
'hard', 'application');
