-- ============================================================================
-- BATCH 35: Mensuration and Physical Examination - Clinical Scenario Questions
-- Topic: Clinical scenarios for vital signs interpretation and assessment
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- BLOOD PRESSURE SCENARIOS
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old man has BP readings of 160/95 in right arm, 115/70 in left arm. He complains of sudden chest pain radiating to the back. What does this BP differential suggest?',
'Normal variation',
'Aortic dissection - the BP difference greater than 20mmHg is significant, needs urgent CT aortogram',
'Faulty equipment',
'Essential hypertension',
'Subclavian steal syndrome',
'B',
'Blood pressure differential greater than 20mmHg systolic between arms suggests vascular occlusion. With acute chest/back pain, aortic dissection must be excluded. Dissection involving subclavian artery causes reduced BP in affected arm. Urgent imaging (CT aortogram) required. Other causes: subclavian stenosis, coarctation.',
'hard', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient''s BP reads 160/100 with a standard adult cuff. Their mid-arm circumference is 42cm. How might this affect the reading?',
'Reading is accurate',
'BP is falsely elevated - need large adult or thigh cuff for accurate measurement',
'BP is falsely low',
'No effect on reading',
'Cannot measure BP in this patient',
'B',
'Cuff size affects BP accuracy: Too small cuff = falsely high reading. Arm circumference greater than 33cm needs large adult cuff; greater than 42cm needs thigh cuff. Bladder should cover 80% of arm circumference. Common error in obese patients - may lead to over-treatment of "hypertension."',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old on antihypertensives has BP 140/80 sitting, 105/60 standing with dizziness. What is this finding and its significance?',
'Normal response to standing',
'Orthostatic (postural) hypotension - drop greater than 20 systolic on standing, risk of falls, review medications',
'Equipment malfunction',
'Hypertensive urgency',
'Vasovagal syncope',
'B',
'Orthostatic hypotension: Drop greater than 20mmHg systolic or greater than 10mmHg diastolic within 3 minutes of standing. Common in elderly on antihypertensives. Causes: medications, autonomic dysfunction, dehydration. Management: review/reduce antihypertensives, hydration, compression stockings, rise slowly.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has BP 80/60 with HR 65. He is on beta-blockers for heart failure. What is important about interpreting these vitals?',
'Normal vitals',
'Tachycardic response is blunted by beta-blockers - degree of shock may be underestimated',
'Patient is not shocked',
'Beta-blockers are protective',
'HR is diagnostic of shock severity',
'B',
'Beta-blocker effect on shock: Normal compensatory tachycardia is blunted. Patients may be significantly hypovolemic without expected tachycardia. Cannot rely on HR to gauge shock severity. Use other parameters: lactate, base deficit, urine output, mental status. Elderly and athletes also have blunted HR response.',
'hard', 'application'),

-- PULSE ASSESSMENT
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient has an irregularly irregular pulse at 130 bpm. ECG confirms atrial fibrillation. Why is it important to measure both radial pulse rate and heart rate by auscultation?',
'No difference expected',
'Pulse deficit - some beats too weak to reach periphery; apical rate higher than radial rate indicates poor cardiac output',
'Radial is always more accurate',
'Heart rate cannot be measured by auscultation',
'They should be measured at different times',
'B',
'Pulse deficit: Difference between apical (auscultated) heart rate and peripheral (radial) pulse rate. In AF, some ventricular contractions too weak to generate palpable pulse. Large pulse deficit indicates poor ventricular filling and cardiac output. Indicates need for rate control.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A young patient presents with syncope. BP is 90/60, HR 45. The pulse feels full and slow. ECG shows complete heart block. What is the character of this pulse called?',
'Thready pulse',
'Slow-rising (pulsus tardus) or collapsing pulse - Corrigan''s sign',
'Collapsing pulse',
'Pulsus paradoxus',
'Waterhammer pulse',
'B',
'Slow-rising pulse (pulsus tardus): Pulse rises slowly and has reduced amplitude. Classic in aortic stenosis. In complete heart block with bradycardia, stroke volume is high but rate slow, giving slow, full pulse. Different from collapsing pulse (rapid rise and fall in aortic regurgitation).',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with tamponade has BP 95/70. On inspiration, systolic BP drops to 75mmHg. What is this sign called and what does it indicate?',
'Normal respiratory variation',
'Pulsus paradoxus - inspiratory systolic drop greater than 10mmHg, suggests cardiac tamponade, constrictive pericarditis, or severe asthma',
'Orthostatic hypotension',
'Aortic dissection',
'Shock',
'B',
'Pulsus paradoxus: Exaggerated fall in systolic BP (greater than 10mmHg) during inspiration. Mechanism in tamponade: Inspiration increases venous return to right heart, but pericardial constraint shifts septum leftward, reducing LV filling. Also seen in constrictive pericarditis, severe asthma, COPD.',
'hard', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old man with claudication has weak femoral pulses and absent popliteal and pedal pulses bilaterally. What level of arterial disease does this suggest?',
'Femoral artery disease',
'Aortoiliac disease (Leriche syndrome)',
'Popliteal artery disease',
'Small vessel disease',
'Venous disease',
'B',
'Pulse level indicates disease location: Weak femoral pulses suggest disease proximal to femoral artery - aortoiliac segment. Leriche syndrome: aortoiliac occlusive disease with claudication, absent/weak femoral pulses, and erectile dysfunction in men. Popliteal disease would have normal femoral but absent distal pulses.',
'medium', 'application'),

-- TEMPERATURE MEASUREMENT
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has axillary temperature 37.2°C but appears flushed and tachycardic. What should be considered about temperature measurement site?',
'Axillary temperature is most accurate',
'Axillary temperature is approximately 0.5-1°C lower than core - oral or tympanic measurement would be higher',
'No difference between sites',
'Axillary is higher than core',
'Rectal is lower than axillary',
'B',
'Temperature site accuracy: Rectal/pulmonary artery = gold standard core temperature. Oral approximately 0.3°C lower than rectal. Axillary approximately 0.5-1°C lower than oral (and affected by sweating, positioning). Tympanic close to core if technique correct. In suspected infection, use consistent site, consider core measurement.',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient being treated for sepsis has temperature 38.8°C, then suddenly drops to 35.5°C. He becomes hypotensive and confused. What does this temperature change indicate?',
'Recovery from infection',
'Hypothermia in sepsis indicates severe sepsis/septic shock with poor prognosis',
'Thermometer malfunction',
'Normal diurnal variation',
'Antipyretic overdose',
'B',
'Hypothermia in sepsis: Core temperature less than 36°C is a poor prognostic sign in sepsis. Indicates failure of thermoregulatory response, often seen in elderly, immunocompromised, or severe sepsis. Part of SIRS criteria (temperature greater than 38°C OR less than 36°C). Associated with higher mortality.',
'hard', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient has fever (39°C) on post-operative day 3. Using the 5 W''s of post-operative fever, what is the most likely cause at this timing?',
'Wind (atelectasis)',
'Water (UTI) or Walking (DVT)',
'Wound infection',
'Wonder drugs (drug fever)',
'Immediate reaction',
'B',
'Post-operative fever 5 W''s timing: Day 1-2: Wind (atelectasis). Day 3-5: Water (UTI, especially if catheterized) and Walking (DVT/PE). Day 5-7: Wound infection. Day 7+: Wonder drugs (drug fever), abscess. Day 3 suggests UTI (especially with catheter) or early DVT. Systematic evaluation needed.',
'medium', 'application'),

-- RESPIRATORY ASSESSMENT
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with abdominal pain is breathing rapidly at 28 breaths/min with deep breaths. ABG shows pH 7.28, PCO2 18mmHg, HCO3 10mEq/L. What is this breathing pattern?',
'Cheyne-Stokes respiration',
'Kussmaul respiration - deep, rapid breathing to compensate for metabolic acidosis',
'Biot''s respiration',
'Apneustic breathing',
'Normal tachypnea',
'B',
'Kussmaul respiration: Deep, regular, rapid breathing (air hunger). Respiratory compensation for metabolic acidosis. Classic in DKA. ABG shows metabolic acidosis (low pH, low HCO3) with respiratory compensation (low PCO2). Calculate anion gap if elevated - suggests DKA, lactic acidosis, uremia, toxins.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with head injury has a breathing pattern of progressively deeper and faster breathing, then slower and shallower, with periods of apnea. What does this indicate?',
'Normal sleep pattern',
'Cheyne-Stokes respiration - suggests bilateral cerebral or diencephalic lesion, or severe heart failure',
'Good prognosis',
'Kussmaul respiration',
'Biot breathing',
'B',
'Cheyne-Stokes respiration: Cyclical pattern - crescendo-decrescendo depth with apneic periods. Causes: Bilateral hemispheric damage, heart failure with prolonged circulation time, altitude, uremia. In head injury, suggests raised ICP or bilateral cerebral dysfunction. Poor prognostic sign.',
'hard', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old smoker with barrel chest has respiratory rate 22, using accessory muscles, pursed lip breathing. SpO2 is 89% on air. What is the likely diagnosis?',
'Normal aging',
'COPD with acute exacerbation - pursed lip breathing is compensatory mechanism',
'Asthma',
'Pulmonary embolism',
'Panic attack',
'B',
'COPD examination findings: Barrel chest (hyperinflation), accessory muscle use, pursed lip breathing (increases airway pressure, prevents small airway collapse), prolonged expiration. Pursed lip breathing is learned compensatory mechanism. SpO2 target in COPD 88-92% (avoid hypoxic drive suppression).',
'medium', 'application'),

-- CARDIOVASCULAR EXAMINATION
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'On examining a patient''s neck, JVP is elevated at 10cm above the sternal angle and rises further with inspiration. What is this sign called and what does it suggest?',
'Normal JVP',
'Kussmaul sign - suggests constrictive pericarditis, tamponade, or RV infarct',
'Hepatojugular reflux',
'Elevated CVP only',
'Cannon waves',
'B',
'Kussmaul sign: Paradoxical rise in JVP with inspiration (normally JVP falls). Indicates impaired right ventricular filling. Causes: Constrictive pericarditis (calcified pericardium), tamponade, RV infarction, severe RV failure, restrictive cardiomyopathy. May coexist with pulsus paradoxus in tamponade.',
'hard', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with heart failure has pitting edema to the knee bilaterally. How is peripheral edema graded and what grade would this be?',
'Cannot grade edema',
'Grade 3+ (pitting 6mm deep, lasting 1-2 minutes) if indent significant; knee-level suggests significant volume overload',
'Grade 1',
'Normal finding in elderly',
'Only assessed in ankles',
'B',
'Edema grading: 1+ (2mm pit, rebounds immediately), 2+ (4mm, rebounds in 15 seconds), 3+ (6mm, rebounds in 1-2 minutes), 4+ (8mm, rebounds greater than 2 minutes). Level indicates severity - ankle mild, knee moderate, thigh/sacrum severe. Assess sacrum in bedridden patients. Multiple causes (cardiac, renal, hepatic, venous).',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A 20-year-old with fever has bounding pulses, widened pulse pressure (BP 140/40), and a decrescendo diastolic murmur at the left sternal edge. What is the likely diagnosis?',
'Aortic stenosis',
'Aortic regurgitation with wide pulse pressure (likely infective endocarditis given fever)',
'Mitral regurgitation',
'Normal finding',
'Pulmonary embolism',
'B',
'Aortic regurgitation signs: Wide pulse pressure (high systolic from high stroke volume, low diastolic from regurgitation), bounding/collapsing pulse (waterhammer), early diastolic decrescendo murmur at left sternal edge. With fever, consider infective endocarditis. Austin Flint murmur, pistol shot femorals, Quincke sign.',
'medium', 'application'),

-- ABDOMINAL EXAMINATION
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with suspected appendicitis has maximal tenderness in the right iliac fossa. When you press the left iliac fossa, he feels pain in the right. What is this sign?',
'McBurney''s point tenderness',
'Rovsing''s sign - suggests peritoneal inflammation at the appendix',
'Murphy''s sign',
'Psoas sign',
'Obturator sign',
'B',
'Rovsing''s sign: Palpation of LIF causes RIF pain. Mechanism: Pressure wave across peritoneum irritates inflamed appendix. Helps localize appendicitis. Other signs: Psoas sign (pain on hip extension - retrocaecal appendix), obturator sign (pain on internal rotation of hip - pelvic appendix).',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with jaundice has a palpable, non-tender gallbladder. According to Courvoisier''s law, what does this suggest?',
'Gallstones',
'Periampullary carcinoma (pancreatic head, ampulla, CBD) - malignant obstruction more likely than stone',
'Cholecystitis',
'Hepatitis',
'Normal finding',
'B',
'Courvoisier law: If gallbladder is palpable and patient is jaundiced, unlikely to be stones (chronic stones cause fibrotic, contracted gallbladder). More likely malignant obstruction (pancreatic head cancer, cholangiocarcinoma, ampullary cancer). Not absolute - stones can cause palpable GB if acute obstruction.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with ascites has shifting dullness. You percuss dullness in the flanks which moves to the midline when patient turns to the side. How much fluid does this indicate?',
'Less than 500ml',
'At least 1-1.5L of ascites required for shifting dullness to be detectable',
'Exactly 500ml',
'No fluid',
'More than 10L',
'B',
'Ascites detection: Shifting dullness requires approximately 1-1.5L of fluid. Fluid thrill requires even more (3-4L). Ultrasound can detect as little as 100ml. Obese patients may have false positive shifting dullness. Confirm with ultrasound if uncertain. Determine cause (portal hypertension, malignancy, cardiac, renal).',
'medium', 'application'),

-- NEUROLOGICAL ASSESSMENT
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with head injury has GCS 8 (E2, V2, M4). He does not open eyes to voice but opens them to pain, makes incomprehensible sounds, and withdraws from pain. What does GCS 8 indicate?',
'Mild head injury',
'Severe head injury (GCS less than or equal to 8 = coma = indication for intubation)',
'Moderate head injury',
'Normal consciousness',
'Death',
'B',
'GCS interpretation: 14-15 = mild, 9-13 = moderate, less than or equal to 8 = severe/coma. GCS less than or equal to 8 indicates inability to protect airway and need for intubation. E2 = eyes to pain, V2 = incomprehensible sounds, M4 = withdrawal. Serial GCS monitoring important - drop of 2+ points significant.',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A head-injured patient initially had equal reactive pupils. Now the right pupil is 6mm and fixed, while the left is 3mm and reactive. What does this indicate?',
'Normal pupil difference',
'Right-sided third nerve compression from ipsilateral tentorial herniation (uncal herniation) - neurosurgical emergency',
'Left-sided brain injury',
'Normal finding after head injury',
'Opioid effect',
'B',
'Unilateral fixed dilated pupil in head injury: Indicates ipsilateral third nerve compression from tentorial (uncal) herniation. The uncus herniates through tentorium, compressing CN III which runs along free edge. Emergency - indicates critical raised ICP. Needs urgent CT and likely decompressive surgery.',
'hard', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient with sudden onset weakness has power grade 3/5 in right arm and 4/5 in right leg, with brisk reflexes and upgoing plantar on the right. What type of weakness is this?',
'Peripheral neuropathy',
'Upper motor neuron (UMN) lesion - likely left hemispheric stroke given right-sided signs',
'Lower motor neuron lesion',
'Myopathy',
'Normal examination',
'B',
'UMN signs: Weakness (pyramidal distribution - extensors in arm, flexors in leg), increased tone (spasticity), brisk reflexes, upgoing plantar (Babinski positive), no wasting/fasciculations. Suggests CNS lesion above anterior horn cell. Sudden onset = vascular (stroke). Left hemisphere lesion causes right-sided weakness.',
'medium', 'application'),

-- COMPREHENSIVE ASSESSMENT
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient in ED has HR 120, RR 26, BP 85/50, SpO2 91%, and temperature 39.2°C. Using NEWS (National Early Warning Score), this patient scores high. What does a high NEWS indicate?',
'Normal vital signs',
'Critical illness requiring urgent medical review and likely escalation to HDU/ICU',
'Mild illness',
'Ready for discharge',
'Artifact',
'B',
'NEWS (National Early Warning Score): Aggregate score from vital signs to identify clinical deterioration. Each parameter scores 0-3. Score 5-6 or single parameter score 3 = urgent response. Score 7+ = emergency response (likely ICU/outreach). This patient has multiple abnormal parameters = high score = critical.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient has concerning vital signs. The nurse pages you urgently using SBAR format. What does SBAR stand for and why is it important?',
'Symptoms, Background, Assessment, Response',
'Situation, Background, Assessment, Recommendation - standardized communication reduces errors and ensures key information is conveyed',
'Signs, Blood pressure, Airway, Respiration',
'Stable, Background, Analysis, Results',
'No specific meaning',
'B',
'SBAR: Situation (what is happening now), Background (relevant history), Assessment (what I think is wrong), Recommendation (what I think should happen). Standardized communication framework reduces errors in handoffs and urgent calls. Ensures critical information is not missed. WHO-endorsed tool.',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient arrives and you perform primary survey. According to ATLS, what is the correct order of assessment?',
'Circulation, Airway, Breathing, Disability, Exposure',
'Airway with C-spine control, Breathing, Circulation, Disability, Exposure (ABCDE)',
'Disability, Airway, Breathing, Circulation, Exposure',
'Exposure, Disability, Circulation, Breathing, Airway',
'Any order is acceptable',
'B',
'ATLS Primary Survey ABCDE: A = Airway with cervical spine protection. B = Breathing and ventilation. C = Circulation with hemorrhage control. D = Disability (neurological status - AVPU or GCS, pupils). E = Exposure/Environmental control (undress, prevent hypothermia). Systematic approach saves lives.',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'An unconscious patient cannot tell you if they are in pain. What observation-based assessment tool can be used for pain in non-verbal patients?',
'Verbal analog scale',
'Behavioral Pain Scale or CPOT (Critical Care Pain Observation Tool)',
'Numerical rating scale',
'Pain is not assessed if patient cannot communicate',
'McGill Pain Questionnaire',
'B',
'Pain assessment in non-verbal patients: Use behavioral/observational tools. BPS (Behavioral Pain Scale) for ventilated patients: facial expression, upper limb movement, ventilator compliance. CPOT: facial expression, body movements, muscle tension, vocalization/ventilator compliance. Score triggers intervention.',
'medium', 'application');
