-- ============================================================================
-- BATCH 37: Surgical Wounds and Wound Management - Clinical Scenario Questions
-- Topic: Clinical scenarios for wound assessment, healing and complications
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- WOUND CLASSIFICATION
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoes elective hernia repair through healthy skin with no break in sterile technique. Antibiotic prophylaxis was not given. What is the wound classification and expected infection rate?',
'Contaminated wound, 15% infection rate',
'Clean wound (Class I), expected infection rate less than 2%',
'Clean-contaminated, 5% rate',
'Dirty wound, 30% rate',
'Cannot classify without culture',
'B',
'Clean (Class I) wound: Elective surgery, no entry into respiratory/GI/GU tract, no inflammation, no breaks in technique. Infection rate less than 2%. Prophylactic antibiotics often not required for simple clean cases. Examples: hernia repair, breast surgery, thyroid surgery.',
'easy', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has elective cholecystectomy for biliary colic. There is no spillage of bile. What is the wound classification?',
'Clean',
'Clean-contaminated (Class II) - GI tract entered under controlled circumstances',
'Contaminated',
'Dirty',
'Cannot be classified',
'B',
'Clean-contaminated (Class II): Controlled entry into GI, respiratory, or GU tract without unusual contamination. Infection rate 5-10%. Examples: cholecystectomy, colonic surgery with bowel prep, uncomplicated appendectomy. Prophylactic antibiotics recommended.',
'easy', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'During appendectomy, the appendix is found to be gangrenous with pus in the peritoneal cavity. What is the wound classification?',
'Clean',
'Clean-contaminated',
'Contaminated (Class III) - gross spillage from GI tract, acute inflammation',
'Dirty (Class IV)',
'Special category',
'C',
'Contaminated (Class III): Major break in sterile technique, gross GI spillage, acute inflammation present, fresh traumatic wounds. Infection rate 10-20%. Gangrenous appendix with pus = contaminated. Therapeutic antibiotics required, consider delayed primary closure.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient presents with a 2-day-old stab wound to the abdomen with fecal peritonitis from bowel perforation. After laparotomy, how should the wound be classified and managed?',
'Clean wound - primary closure',
'Dirty/infected (Class IV) - leave wound open or delayed primary closure, therapeutic antibiotics',
'Clean-contaminated',
'Contaminated - primary closure',
'No classification applies',
'B',
'Dirty/Infected (Class IV): Old traumatic wounds, established infection, perforated viscus with fecal contamination. Infection rate greater than 30%. Management: Debride, leave open or delayed primary closure, VAC therapy may help, therapeutic antibiotics. Primary closure has high dehiscence/infection risk.',
'medium', 'application'),

-- WOUND HEALING PHASES
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has a healing surgical wound at day 3. The wound edges are red, there is serous exudate, and histology would show neutrophil infiltration. Which phase of wound healing is this?',
'Hemostasis phase',
'Inflammatory phase - peaks at days 2-3, characterized by neutrophil infiltration, vasodilation, exudate',
'Proliferative phase',
'Maturation phase',
'Epithelialization phase',
'B',
'Inflammatory phase (Days 1-5): Vasodilation, increased vascular permeability, neutrophil then macrophage infiltration. Signs: rubor (redness), calor (heat), tumor (swelling), dolor (pain). This is NORMAL inflammation, not infection. Peaks day 2-3. Macrophages predominate by day 3 and orchestrate repair.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'At day 10 post-surgery, the wound shows healthy red granulation tissue filling the defect. New blood vessels are visible. What phase is this and what cells are responsible?',
'Inflammatory phase',
'Proliferative phase - fibroblasts produce collagen, angiogenesis forms new vessels, granulation tissue forms',
'Maturation phase',
'Hemostasis',
'Delayed healing',
'B',
'Proliferative phase (Days 3-21): Granulation tissue formation, fibroblast proliferation, collagen deposition, angiogenesis (new blood vessels), wound contraction (myofibroblasts). Healthy granulation tissue is beefy red, granular, and bleeds easily. Pale granulation suggests poor vascularity or infection.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient''s 6-week-old surgical scar is red, raised, and firm. Over the following months it gradually flattens and becomes paler. What is occurring?',
'Hypertrophic scar formation',
'Normal maturation/remodeling phase - type III collagen replaced by type I, scar matures over months to years',
'Keloid formation',
'Wound infection',
'Dehiscence',
'B',
'Maturation/Remodeling phase (3 weeks to 2 years): Type III collagen replaced by type I (stronger). Wound contracts, becomes less vascular (pale), fibers realign along tension lines. Maximum tensile strength (80% of normal) reached by 3 months. Scar maturation continues for up to 2 years.',
'easy', 'application'),

-- WOUND COMPLICATIONS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'On post-operative day 7, a patient suddenly coughs and feels something "give" in their abdomen. Pink serous fluid leaks from the wound. Examination reveals a 5cm dehiscence with visible bowel. What is the immediate management?',
'Send home with antibiotics',
'Cover with saline-soaked sterile dressing, keep patient nil by mouth, urgent return to theatre for repair',
'Close with tape strips',
'Observation only',
'Discharge with outpatient follow-up',
'B',
'Wound dehiscence with evisceration: Surgical emergency. Cover exposed viscera with warm saline-soaked sterile towels (prevent desiccation and hypothermia). NBM, IV access, analgesia, catheter. Urgent theatre for abdominal wall repair. Risk factors: coughing, obesity, infection, poor nutrition, steroids.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A post-operative wound on day 5 develops increasing redness spreading beyond wound edges, warmth, tenderness, and the patient develops fever (38.5°C). What is the diagnosis and management?',
'Normal healing',
'Surgical site infection (SSI) - open wound if fluctuant, antibiotics, send swab for culture',
'Allergic reaction to dressings',
'Hematoma',
'Seroma',
'B',
'Surgical site infection: Infection within 30 days of surgery (or 1 year if implant). Signs: purulent discharge, spreading cellulitis, fever, raised inflammatory markers. Management: Open wound if collection present (pus must be drained), send culture, antibiotics (empiric then targeted), wound care. Superficial vs deep vs organ/space classification.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A laparotomy wound has a fluctuant swelling under the incision at day 3. There is no erythema or fever. Aspiration yields clear straw-colored fluid. What is this collection?',
'Abscess',
'Seroma - sterile collection of serum; may observe small ones, aspirate larger ones',
'Hematoma',
'CSF leak',
'Lymphocele',
'B',
'Seroma: Collection of serous fluid in dead space after surgery. Common after procedures with large flap dissection (mastectomy, groin dissection). Usually sterile, straw-colored. Small seromas may reabsorb; larger ones require aspiration (risk of infection if repeated). Compression dressings help prevent.',
'easy', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'Post groin surgery, a patient develops a firm, tender, bluish discoloration at the wound site within 24 hours. Aspiration yields old blood. What is this and how should it be managed?',
'Seroma',
'Hematoma - if large or expanding, may need surgical evacuation and hemostasis',
'Abscess',
'Venous thrombosis',
'Normal bruising only',
'B',
'Hematoma: Collection of blood in wound. Early sign is firm swelling, later bluish discoloration. May be managed conservatively if small and stable. Large or expanding hematomas need surgical exploration (identify bleeding source, evacuate, achieve hemostasis). Risk of secondary infection if not drained.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient has a chronic foot wound that has not healed for 3 months despite dressings. The wound bed has thick yellow slough and minimal granulation tissue. What is this wound type and what management is needed?',
'Acute wound healing normally',
'Chronic wound - needs debridement, optimization of diabetes, offloading, consider VAC therapy, exclude osteomyelitis',
'Clean surgical wound',
'Normal granulation',
'Ready for skin graft',
'B',
'Chronic wound: Failed to heal in expected timeframe (usually greater than 4-6 weeks). Causes: poor perfusion, infection, diabetes, pressure, malnutrition, foreign body. Management: treat underlying cause, debridement (remove slough/necrotic tissue), optimize nutrition/diabetes, offloading, advanced wound care (VAC, growth factors). Exclude osteomyelitis.',
'medium', 'application'),

-- WOUND MANAGEMENT DECISIONS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient sustains a dog bite to the forearm 2 hours ago. The wound is 4cm, through dermis, with tissue devitalization. How should this wound be closed?',
'Primary closure immediately',
'Debride, irrigate copiously, leave open or delayed primary closure, antibiotics, tetanus prophylaxis',
'Close with tissue glue',
'Skin graft immediately',
'No treatment needed',
'B',
'Animal bite wounds: High infection risk (polymicrobial including Pasteurella). Management: Copious irrigation (reduces bacterial load 10-fold), debridement of devitalized tissue, leave open or loose approximation only, antibiotics (co-amoxiclav), tetanus update, consider rabies if endemic. Primary closure increases infection risk.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has a large contaminated wound that has been debrided but cannot be closed primarily. It is left open with wet-to-dry dressings. After 4 days, the wound has healthy granulation tissue. What closure is now planned?',
'Continue wet-to-dry indefinitely',
'Delayed primary closure - now that wound is clean and granulating, can approximate edges',
'Skin graft today',
'Healing by secondary intention only',
'Vacuum dressing indefinitely',
'B',
'Delayed primary closure (tertiary intention): Wound left open initially (contaminated, traumatic, at risk). Managed with dressings, dressing changes. Once clean and granulating (typically 4-5 days), wound edges can be approximated. Combines benefits of debridement/observation with primary healing. Lower infection rate than immediate closure of contaminated wound.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A pressure ulcer on the sacrum has necrotic eschar covering the wound base. The surrounding skin is intact. How should the necrotic tissue be managed?',
'Leave eschar in place indefinitely',
'Debridement (sharp, enzymatic, or autolytic) to allow healing - except stable heel eschar which may be left',
'Apply antibiotic ointment only',
'Immediate skin grafting',
'No intervention needed',
'B',
'Necrotic tissue debridement: Necrotic tissue (eschar/slough) prevents healing, harbors bacteria, prevents wound assessment. Needs removal: sharp debridement (fastest, for healthy patients), enzymatic (collagenase), autolytic (hydrogels), larval therapy. Exception: stable heel eschar with dry gangrene - may protect, do not debride.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A large granulating wound is ready for coverage but cannot be closed primarily due to tissue loss. The wound bed is healthy but too large for direct closure. What options exist for coverage?',
'Continue dressings only',
'Split-thickness skin graft to granulating bed, or local/distant flaps if bone or tendon exposed',
'Primary closure under tension',
'Healing by secondary intention is the only option',
'Wait for spontaneous closure',
'B',
'Wound coverage options: Skin graft (split or full thickness) for granulating beds without exposed bone/tendon. Flaps (local or free) when need tissue bulk or for exposed bone/tendon/prosthesis. VAC therapy prepares bed for grafting. Cannot graft onto avascular structures (bare bone, tendon without paratenon).',
'hard', 'application'),

-- DRESSING SELECTION
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A sloughy leg ulcer with moderate exudate needs dressing selection. What type of dressing would be most appropriate?',
'Dry gauze',
'Hydrocolloid or alginate dressing - absorbs exudate, maintains moist environment, promotes autolytic debridement',
'Film dressing',
'Paraffin gauze only',
'Leave wound exposed',
'B',
'Dressing selection by wound type: Sloughy with moderate exudate needs absorptive dressing that maintains moisture for autolytic debridement. Hydrocolloid (for light-moderate exudate) or alginate/hydrofiber (moderate-heavy exudate). Moist wound healing promotes faster epithelialization than dry dressings.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has a heavily exudating infected wound that needs to be debrided. What dressing technology promotes healing while managing heavy exudate?',
'Dry gauze dressings',
'Negative pressure wound therapy (VAC) - removes exudate, reduces edema, promotes granulation',
'Film dressings',
'Hydrogel only',
'No dressing',
'B',
'Negative pressure wound therapy (VAC): Applies sub-atmospheric pressure via sealed dressing. Benefits: removes excess exudate, reduces edema, increases blood flow, promotes granulation, may reduce bacterial load. Indications: large or complex wounds, post-debridement, preparing bed for closure/grafting. Contraindicated: malignancy in wound, untreated osteomyelitis.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A dry, necrotic wound needs rehydration to promote autolytic debridement. Which dressing would add moisture to the wound?',
'Alginate',
'Hydrogel - adds moisture to dry wounds, promotes autolytic debridement',
'Absorbent foam',
'Film dressing only',
'Dry gauze',
'B',
'Hydrogels: Donate moisture to dry/necrotic wounds. Promote autolytic debridement by rehydrating eschar. Cooling, soothing effect. Not suitable for exudating wounds (no absorptive capacity). Available as sheets or amorphous gel. Cover with secondary dressing. Good for dry, sloughy, or granulating wounds.',
'easy', 'application'),

-- SPECIFIC WOUND SCENARIOS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient develops crepitus around their wound with rapid spreading cellulitis, severe pain disproportionate to examination, and systemic toxicity. What is the diagnosis and urgent management?',
'Simple cellulitis',
'Necrotizing fasciitis - surgical emergency requiring immediate radical debridement, broad-spectrum antibiotics, ICU',
'Abscess',
'Gas gangrene is different',
'Allergic reaction',
'B',
'Necrotizing fasciitis: Rapidly progressive deep soft tissue infection. Signs: pain disproportionate to examination, crepitus, rapid spread, systemic toxicity, skin necrosis. HIGH MORTALITY. Immediate: IV antibiotics (broad spectrum including clindamycin for toxin), URGENT surgical debridement (often multiple), ICU support. Do not delay surgery for imaging.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with vascular disease has dry gangrene of the toes with clear line of demarcation. The toes are mummified and not infected. How should this be managed?',
'Immediate surgical debridement',
'Conservative management with dry dressings, await auto-amputation, or elective surgery once demarcated if vascularization not possible',
'Wet dressings to rehydrate',
'Aggressive debridement into bleeding tissue',
'No treatment',
'B',
'Dry gangrene management: Unlike wet gangrene (infected, surgical emergency), dry gangrene is mummified dead tissue without active infection. Management: Keep dry (wet dressings promote infection). May auto-amputate. Revascularization if possible. If not, await clear demarcation before elective amputation at appropriate level.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient''s scar from surgery 6 months ago has extended beyond the original wound borders and continues to grow. It is pruritic and has failed steroid injection. What is the diagnosis?',
'Hypertrophic scar',
'Keloid scar - extends beyond wound boundaries, continues to grow, may need multimodal therapy',
'Normal scar maturation',
'Wound recurrence',
'Skin cancer',
'B',
'Keloid vs hypertrophic scar: Keloids extend BEYOND original wound margins and continue growing. Hypertrophic scars stay within wound boundaries and typically regress. Keloids: genetic predisposition, more common in darker skin. Treatment: Pressure therapy, intralesional steroids, silicone sheets, radiotherapy, surgical excision (high recurrence alone).',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient develops fever, severe wound pain, and bronze discoloration of skin around a leg wound 24 hours after farm injury. Imaging shows gas in soft tissues. What organism is likely and what treatment is critical?',
'E. coli - antibiotics only',
'Clostridium perfringens (gas gangrene) - immediate surgical debridement, high-dose penicillin, hyperbaric oxygen if available',
'Staphylococcus - oral antibiotics',
'Pseudomonas - topical treatment',
'Normal post-injury appearance',
'B',
'Gas gangrene (Clostridial myonecrosis): Clostridium perfringens in contaminated wounds. Produces gas, toxins. Rapid progression, high mortality. Features: Pain, bronze skin, crepitus, systemic toxicity. Treatment: Immediate radical debridement, high-dose penicillin + clindamycin, hyperbaric oxygen may help. Farm injuries and crush injuries are high risk.',
'hard', 'application'),

-- FACTORS AFFECTING HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A malnourished patient with albumin of 18 g/L is not healing after surgery. What nutritional intervention is most important?',
'Vitamin C alone',
'Optimize protein intake (goal 1.5-2g/kg/day), ensure adequate calories, consider supplemental nutrition',
'Fat-free diet',
'Reduce calorie intake',
'Vitamin K only',
'B',
'Nutrition and wound healing: Protein critical for collagen synthesis (target 1.5-2g/kg/day in healing). Vitamin C essential for collagen cross-linking. Zinc for cell proliferation. Albumin less than 30 g/L associated with poor healing. Malnourished patients may need enteral or parenteral supplementation. Caloric needs increased in wound healing.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient on 20mg prednisolone for rheumatoid arthritis has poor wound healing. What effect do corticosteroids have on wound healing?',
'Improve healing',
'Impair healing - reduce inflammation, inhibit fibroblast proliferation, reduce collagen synthesis, increase infection risk',
'No effect on healing',
'Only affect very high doses',
'Improve collagen deposition',
'B',
'Corticosteroid effects on healing: Suppress inflammation (needed for normal healing), inhibit fibroblast and macrophage function, reduce collagen synthesis, impair epithelialization, increase infection risk. If possible, reduce dose peri-operatively. Vitamin A may partially reverse steroid effects on healing.',
'medium', 'application');
