-- ============================================================================
-- BATCH 39: Blood Conservation and Autotransfusion - Clinical Scenario Questions
-- Topic: Clinical scenarios for perioperative blood management
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- PREOPERATIVE BLOOD OPTIMIZATION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient scheduled for elective hip replacement has Hb 10.5 g/dL. Iron studies show low ferritin (12 μg/L) with low transferrin saturation (15%). Surgery is in 4 weeks. What preoperative intervention is most appropriate?',
'Proceed with surgery as planned',
'IV iron therapy (or oral iron if less urgent) to optimize Hb before surgery - part of patient blood management',
'Pre-operative transfusion',
'Cancel surgery',
'Increase dietary iron only',
'B',
'Preoperative anemia optimization: Iron deficiency anemia is common and correctable. IV iron (ferric carboxymaltose, iron sucrose) raises Hb faster than oral iron. 4 weeks allows improvement. Part of Patient Blood Management (PBM) pillars. Reduces need for perioperative transfusion. Also consider EPO in selected cases.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic kidney disease and Hb 9.0 g/dL is scheduled for major vascular surgery. EPO and iron have been discussed. What is the rationale for erythropoietin use?',
'EPO prevents blood loss',
'EPO stimulates RBC production, reduces transfusion requirement when started 2-4 weeks preoperatively with iron supplementation',
'EPO replaces transfusion during surgery',
'EPO is only for dialysis patients',
'EPO works immediately',
'B',
'Erythropoietin (EPO) in perioperative setting: Stimulates bone marrow RBC production. Most effective when combined with iron. Requires 2-4 weeks to increase Hb. Indications: Anemia of chronic disease/CKD, patients refusing transfusion, anticipated high blood loss. Side effects: Hypertension, thrombosis risk.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient on warfarin for AF needs elective surgery. INR is 2.8. Surgery is in 5 days. How should anticoagulation be managed?',
'Continue warfarin',
'Stop warfarin 5 days before surgery, consider bridging with LMWH if high thrombotic risk, check INR on day of surgery',
'Give vitamin K and operate tomorrow',
'Transfuse FFP preoperatively',
'Stop warfarin 24 hours before',
'B',
'Warfarin perioperative management: Stop 5 days before surgery (allows INR to normalize). Bridging with LMWH if high thrombotic risk (mechanical valve, recent VTE, high-risk AF). Check INR day before/morning of surgery (target less than 1.5 for most surgery). Resume warfarin when hemostasis secured.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient on clopidogrel after coronary stent placement 3 months ago needs semi-urgent surgery. What is the key consideration?',
'Stop clopidogrel immediately',
'Multidisciplinary discussion needed - balance stent thrombosis risk against bleeding; may need to delay if possible or continue clopidogrel',
'Continue clopidogrel without concern',
'Switch to warfarin',
'Transfuse platelets to overcome effect',
'B',
'Dual antiplatelet therapy (DAPT) perioperative management: Early cessation risks stent thrombosis (can be fatal). Usually continue aspirin, stop clopidogrel 5-7 days before if possible. Recent stent (less than 6 months BMS, less than 12 months DES) = high risk. MDT decision with cardiology. May need bridging or operative approach modification.',
'hard', 'application'),

-- CELL SALVAGE
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During a complex spine surgery with anticipated 2L blood loss, the anesthetist sets up cell salvage. How does intraoperative cell salvage work?',
'Saves whole blood directly',
'Blood is suctioned from wound, anticoagulated, washed, centrifuged to concentrate RBCs, then reinfused to patient',
'Blood is stored for later use',
'Only collects platelets',
'Requires no processing',
'B',
'Intraoperative cell salvage (cell saver): Shed blood collected via suction, anticoagulated (heparin/citrate), filtered, washed (removes debris, free Hb, anticoagulant), centrifuged to concentrate RBCs (Hct 50-80%), reinfused. Saves only RBCs - no platelets, clotting factors, or plasma proteins.',
'easy', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient with bowel perforation and contamination needs surgery. Cell salvage equipment is available. Is cell salvage appropriate?',
'Absolutely contraindicated',
'Relative contraindication - traditionally avoided in contaminated fields, but with leukodepletion filters may be used in emergency with informed consent',
'Ideal indication',
'Only for clean surgery',
'No restrictions apply',
'B',
'Cell salvage in contaminated fields: Historically contraindicated (bowel contamination, infection). However, with modern leukodepletion filters, bacterial contamination is largely removed. May be considered in massive hemorrhage where allogeneic blood is limited or patient refuses transfusion. Requires informed consent.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing cesarean section has significant bleeding. Cell salvage was historically avoided in obstetrics. What is current practice?',
'Still absolutely contraindicated',
'Now used in obstetrics with leukodepletion filter - amniotic fluid embolism risk mitigated by washing and filtering',
'Only allogeneic blood allowed',
'Wait for bleeding to stop',
'Cell salvage not effective in pregnancy',
'B',
'Cell salvage in obstetrics: Previously avoided due to amniotic fluid embolism (AFE) concern. Modern evidence shows washing and leukodepletion filters remove amniotic debris effectively. Now recommended in UK (NICE) for women at high risk of hemorrhage or those declining allogeneic blood. Use separate suction initially.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A Jehovah''s Witness patient needs major cardiac surgery. They refuse allogeneic transfusion. What blood conservation strategies can be offered?',
'Cannot offer any surgery',
'Preoperative optimization (EPO, iron), cell salvage in continuous circuit, acute normovolemic hemodilution, meticulous surgical hemostasis, tranexamic acid',
'Only observation',
'Standard surgery with forced transfusion',
'Must transfuse regardless of wishes',
'B',
'Blood management for Jehovah''s Witnesses: Many accept cell salvage if blood remains in continuous circuit with patient. Options: Preop EPO/iron optimization, intraoperative cell salvage, acute normovolemic hemodilution (if accepts), antifibrinolytics (TXA), controlled hypotension, meticulous hemostasis, accepting lower Hb threshold. Respect autonomy.',
'hard', 'application'),

-- ACUTE NORMOVOLEMIC HEMODILUTION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'Acute normovolemic hemodilution (ANH) is planned for a patient undergoing major vascular surgery. How is this technique performed?',
'Blood removed and discarded',
'Blood removed at anesthesia induction, replaced with crystalloid/colloid to maintain normovolemia, blood reinfused at end of surgery',
'Blood is frozen for later use',
'Patient is made hypovolemic',
'Performed weeks before surgery',
'B',
'Acute normovolemic hemodilution (ANH): 1-3 units removed at induction, replaced with crystalloid/colloid (3:1 for crystalloid). Blood stored at room temperature (maintains platelet and clotting factor function). Intraoperative bleeding is dilute blood. Stored units reinfused at end. Reduces allogeneic transfusion need.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What are the contraindications to acute normovolemic hemodilution?',
'Anticipated blood loss',
'Anemia (Hb less than 11-12), coronary artery disease, impaired cardiac function, coagulopathy',
'Young age',
'Large body habitus',
'Previous surgery',
'B',
'ANH contraindications: Pre-existing anemia (cannot tolerate further Hb reduction), significant cardiac disease (CAD, heart failure - depend on O2 delivery), coagulopathy, hypovolemia, renal impairment. Patient must tolerate hemodilution to Hct around 25-30% temporarily. Generally safe in otherwise healthy patients.',
'medium', 'application'),

-- PHARMACOLOGICAL AGENTS
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing cardiac surgery receives tranexamic acid. What is the mechanism of action and expected benefit?',
'Promotes clot breakdown',
'Inhibits plasmin activation (antifibrinolytic), reduces bleeding and transfusion requirement',
'Activates platelets',
'Reverses heparin',
'Provides clotting factors',
'B',
'Tranexamic acid (TXA): Antifibrinolytic - inhibits plasminogen activation to plasmin, preventing clot breakdown. Reduces blood loss by 30-40% and transfusion need in major surgery. CRASH-2 showed mortality benefit in trauma. Used in cardiac, orthopedic, obstetric surgery. Side effects: Rare seizure risk at high doses.',
'easy', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient on aspirin has persistent surgical bleeding despite adequate surgical hemostasis. What agent can improve platelet function?',
'Tranexamic acid',
'Desmopressin (DDAVP) - releases von Willebrand factor, may improve platelet adhesion',
'Vitamin K',
'Protamine',
'Fresh frozen plasma',
'B',
'Desmopressin (DDAVP): Releases von Willebrand factor and factor VIII from endothelial stores. Improves platelet adhesion. Used for: von Willebrand disease, uremia-related platelet dysfunction, mild hemophilia A, aspirin/antiplatelet reversal (limited evidence). Dose: 0.3 μg/kg IV. Side effect: Hyponatremia, tachyphylaxis.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'Topical hemostatic agents are applied to a bleeding hepatic surface. Which agents work by providing a matrix for clot formation?',
'Tranexamic acid',
'Absorbable gelatin sponge (Gelfoam), oxidized cellulose (Surgicel), microfibrillar collagen',
'Protamine',
'Vitamin K',
'Fresh frozen plasma',
'B',
'Topical hemostatic agents: Physical matrix agents - Gelfoam (gelatin, absorbs blood), Surgicel (oxidized cellulose, activates clotting), Collagen (activates platelets). Active agents - thrombin sprays, fibrin glues (thrombin + fibrinogen). Combination products available. Useful for diffuse oozing, parenchymal bleeding.',
'easy', 'application'),

-- INTRAOPERATIVE STRATEGIES
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During major surgery, the anesthetist maintains mean arterial pressure at 60-65 mmHg with careful fluid management. What technique is this?',
'Induced hypertension',
'Controlled hypotension - reduces bleeding in surgical field, decreases transfusion requirement',
'Normotensive anesthesia',
'Hypervolemic hemodilution',
'Cardiopulmonary bypass',
'B',
'Controlled (deliberate) hypotension: MAP 50-65 mmHg reduces capillary and venous bleeding. Used in spine, ENT, plastic surgery. Agents: Increased volatile anesthetic, remifentanil, beta-blockers, vasodilators. Contraindicated in cerebrovascular disease, CAD, uncontrolled hypertension. Requires adequate monitoring.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During liver resection, the surgeon applies intermittent inflow occlusion (Pringle maneuver). What does this involve?',
'Outflow occlusion only',
'Clamping hepatoduodenal ligament (portal vein and hepatic artery) to reduce hepatic blood flow during parenchymal transection',
'Continuous occlusion throughout surgery',
'Clamping hepatic veins only',
'No vascular control needed',
'B',
'Pringle maneuver: Occluding hepatoduodenal ligament (containing portal vein, hepatic artery, bile duct) to reduce hepatic inflow during liver transection. Reduces blood loss. Intermittent application (15-20 min on, 5 min off) preferred to continuous (reduces ischemia-reperfusion injury). Liver tolerates 60-90 min cumulative.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing hip replacement is positioned in lateral decubitus position. Beyond positioning, what other mechanical technique reduces blood loss in joint replacement?',
'Heating the room',
'Tourniquet application proximal to surgical site (in limb surgery)',
'Cooling the room',
'Elevating head of bed',
'Hyperventilation',
'B',
'Tourniquet use: Pneumatic tourniquet above surgical site in limb surgery creates bloodless field. Reduces blood loss during procedure. Ischemia time should be limited (generally less than 2 hours, release every 90-120 minutes). Concerns: Reperfusion syndrome, nerve injury, tissue damage. Widely used in knee replacement, foot/ankle surgery.',
'easy', 'application'),

-- RESTRICTIVE TRANSFUSION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A stable post-operative patient has Hb 7.5 g/dL without cardiac symptoms. According to current evidence, should they be transfused?',
'Yes - Hb less than 10 always requires transfusion',
'Not necessarily - restrictive threshold (Hb 7-8) is safe for most stable patients without cardiac disease',
'Yes - Hb less than 8 always requires transfusion',
'No - never transfuse post-operatively',
'Transfuse to Hb 12',
'B',
'Restrictive vs liberal transfusion: Multiple trials (TRICC, TRACS, FOCUS) show restrictive threshold (Hb 7-8 g/dL) is as safe or safer than liberal (Hb 9-10) for most patients. Reduces transfusion-related complications. Higher threshold (8-10) may be appropriate for acute coronary syndrome. Treat patient, not number.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient with acute coronary syndrome has Hb 8.2 g/dL after GI bleeding. What is the appropriate transfusion threshold for this patient?',
'Same as stable patients (Hb 7)',
'Higher threshold (Hb 8-10) may be appropriate in ACS - cardiac patients may benefit from higher Hb',
'Hb 12 mandatory',
'No transfusion indicated',
'Immediate transfusion regardless of Hb',
'B',
'Transfusion in cardiac patients: ACS patients may tolerate anemia less well due to limited coronary reserve. Higher threshold (Hb 8-9 or even 10) may be appropriate. MINT trial ongoing. Current guidance: Consider transfusion at Hb 8 for ACS/symptomatic cardiac disease vs Hb 7 for most other patients. Individualize decision.',
'medium', 'application'),

-- POINT OF CARE TESTING
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During massive hemorrhage, point-of-care testing with thromboelastography (TEG) or ROTEM is available. What information does this provide?',
'Hemoglobin level only',
'Real-time assessment of clot formation and lysis - guides targeted blood component therapy',
'Blood type only',
'Platelet count only',
'Nothing useful in acute setting',
'B',
'Viscoelastic testing (TEG/ROTEM): Measures whole blood clotting dynamics - clot formation, strength, and lysis in real time. Parameters indicate: need for FFP (prolonged clot time), cryoprecipitate (low clot strength), platelets (low clot amplitude), tranexamic acid (fibrinolysis). Reduces empiric transfusion, improves outcomes in trauma and cardiac surgery.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A ROTEM trace shows prolonged clot formation time (CFT) but normal maximum clot firmness (MCF). What component replacement is indicated?',
'Platelets',
'Fresh frozen plasma (FFP) - prolonged CFT with normal MCF suggests coagulation factor deficiency',
'Cryoprecipitate',
'Red blood cells',
'No replacement needed',
'B',
'ROTEM interpretation: Prolonged CFT (clot formation time) indicates reduced thrombin generation - give FFP. Low MCF (maximum clot firmness) on FIBTEM indicates low fibrinogen - give cryoprecipitate or fibrinogen concentrate. Low MCF on EXTEM but normal FIBTEM indicates platelet dysfunction - give platelets. Guides targeted therapy.',
'hard', 'application'),

-- POSTOPERATIVE CONSIDERATIONS
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient 3 days post-surgery has Hb dropped from 10 to 8 g/dL without obvious bleeding. What should be considered?',
'Immediate transfusion',
'Occult bleeding, hemodilution, ongoing hemolysis; investigate before transfusing if stable',
'Normal post-operative finding - no action',
'Bone marrow failure',
'Laboratory error',
'B',
'Post-operative Hb drop: Consider occult bleeding (wound, drain, GI), hemodilution (IV fluids), hemolysis (if transfused), phlebotomy losses. Examine patient, check drains/wound, review fluid balance. May need imaging if bleeding suspected. If stable and explained by hemodilution, may not need transfusion.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient has moderate post-operative anemia (Hb 9.5 g/dL) with confirmed iron deficiency. Surgery was 2 weeks ago. What is the most appropriate management?',
'Blood transfusion',
'Oral or IV iron therapy to rebuild stores and hemoglobin without transfusion risks',
'No treatment needed',
'EPO therapy',
'Vitamin B12',
'B',
'Post-operative anemia management: If stable and iron deficient, iron replacement is preferred over transfusion. IV iron provides faster repletion than oral. Avoids transfusion risks (infection, TACO, TRALI, alloimmunization). Transfusion only if symptomatic or very low Hb. Oral iron for mild deficiency, IV iron for moderate-severe or malabsorption.',
'easy', 'application');
