-- ============================================================================
-- BATCH 40: Additional Clinical Scenarios - Mixed Topics (Lower Coverage)
-- Topic: Additional clinical scenarios to balance topic distribution
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- ADDITIONAL ABDOMINAL INCISIONS SCENARIOS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient needs emergency splenectomy for traumatic rupture. Which incision provides optimal access to the left upper quadrant?',
'Right paramedian',
'Upper midline or left subcostal incision - both provide access to spleen',
'Pfannenstiel',
'McBurney',
'Right Kocher',
'B',
'Splenectomy incisions: Upper midline (most common in emergency - fast, extensible) or left subcostal (better exposure in elective cases, lower hernia rate). Left subcostal may be extended across midline if needed. Upper midline allows access to other abdominal organs for associated injuries.',
'medium', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A morbidly obese patient (BMI 55) requires laparotomy. What modifications should be considered for incision and closure?',
'Standard technique, no modifications',
'Transverse incision if possible, prophylactic mesh, meticulous closure with small bites technique, consider negative pressure wound therapy',
'Only subcostal approach allowed',
'Larger sutures only needed',
'Staples preferred',
'B',
'Obese patient laparotomy: High hernia risk (up to 25%). Transverse incisions have lower hernia rate. Prophylactic mesh reduces incisional hernia significantly. Small bites technique mandatory. Consider subcutaneous drainage or NPWT for wound. Panniculectomy may improve access. Longer retractors needed.',
'hard', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'During closure of an upper midline incision, the surgeon notes the xiphoid process is in the way of the superior extent. What can be done?',
'Leave upper 2cm open',
'Excise the xiphoid (xiphoidectomy) or suture around it',
'Convert to transverse incision',
'Close from bottom only',
'Leave gap at top',
'B',
'Xiphoid in upper midline incision: May interfere with closure. Options: Suture around xiphoid, or excise xiphoid (xiphoidectomy) if preventing adequate closure. Xiphoid excision is safe and often done. Not a major structural component. Occasionally xiphoid itself is pathological and requires excision.',
'easy', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient with multiple previous abdominal surgeries (midline, subcostal, appendectomy) needs another laparotomy. How should the surgeon approach this?',
'Completely new incision site',
'Extend through previous incision (adhesions are already there), careful entry avoiding bowel injury',
'Laparoscopy is contraindicated',
'Only emergency surgery allowed',
'Refer to plastic surgery',
'B',
'Reoperative laparotomy: Using previous incision avoids creating new scar and adhesions. However, bowel adhesions are common beneath old scars. Enter away from midline initially if possible, extend carefully. Adhesiolysis needed. Higher complication rate. Pre-op CT may show adhesion density.',
'medium', 'application'),

-- ADDITIONAL TPR CHART SCENARIOS
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A patient''s chart shows temperature 38.5°C with pulse 120 but blood pressure has been maintained at 110/70 for 12 hours. The nurse is concerned about sepsis. What stage of sepsis might this represent?',
'No sepsis present',
'Compensated SIRS/early sepsis - tachycardia but BP maintained by compensatory mechanisms',
'Septic shock',
'Cardiogenic shock',
'Normal response to fever',
'B',
'Sepsis stages: Early sepsis/SIRS - inflammatory response with fever, tachycardia but maintained BP. Sepsis - SIRS + infection. Severe sepsis - sepsis + organ dysfunction. Septic shock - sepsis + hypotension despite fluids. Normotensive with tachycardia = compensated. May progress if untreated.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'The observation chart shows a patient with respiratory rate persistently between 22-26/min for 24 hours despite treatment for pneumonia, but other vital signs are improving. What does persistent tachypnea indicate?',
'Patient is recovering normally',
'May indicate incomplete treatment, developing complication (empyema, abscess), or non-respiratory cause of tachypnea',
'Malingering',
'Measurement error',
'Pain only',
'B',
'Persistent tachypnea despite treatment: Respiratory rate is sensitive early warning sign. Causes: Incomplete infection treatment, developing empyema/abscess/ARDS, PE, metabolic acidosis (sepsis, DKA), anemia, cardiac failure. Investigate further - repeat imaging, blood gas, consider other causes.',
'hard', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient''s chart shows progressive decline in conscious level over several hours: GCS 15 to 14 to 12. Blood glucose is found to be 2.1 mmol/L. What does this case demonstrate?',
'Normal fluctuation',
'Importance of including blood glucose in observations for at-risk patients; hypoglycemia can present as altered consciousness',
'GCS not useful',
'Glucose not relevant',
'Patient is sleeping',
'B',
'Blood glucose monitoring: Essential in diabetics, patients on insulin/hypoglycemic agents, liver disease, sepsis, on total parenteral nutrition. Hypoglycemia causes altered consciousness, seizures, coma. Include glucose in routine observations for at-risk patients. Easily reversible if identified early.',
'easy', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A patient is on telemetry monitoring. The chart shows episodes of heart rate dropping to 35 bpm lasting 10-20 seconds, associated with dizziness. What is indicated?',
'Normal bradycardia in fit patient',
'Symptomatic bradycardia requiring urgent cardiology review - may need pacing',
'Electrode artifact',
'No intervention needed',
'Stop all medications and observe',
'B',
'Symptomatic bradycardia: Heart rate less than 50 with symptoms (dizziness, syncope, chest pain, hypotension) requires intervention. Causes: Sick sinus syndrome, AV block, medications. Immediate: Atropine if hemodynamically unstable. Urgent: Cardiology review, may need temporary or permanent pacing. Stop rate-limiting drugs.',
'medium', 'application'),

-- ADDITIONAL URETHRAL CATHETERIZATION SCENARIOS
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A male patient with a long-term catheter for neurogenic bladder asks about suprapubic catheter. What are the advantages of suprapubic over urethral catheterization?',
'No advantages',
'Avoids urethral complications (stricture, trauma), easier for patient/carer, better for sexual function, may have lower UTI rate',
'Suprapubic has more complications',
'Only for short-term use',
'Requires general anesthesia monthly',
'B',
'Suprapubic catheter advantages: Avoids urethral trauma/stricture/erosion, easier self-care, less interference with sexuality, lower urethral meatus free for spontaneous voiding trials, may have lower UTI rate (controversial). Disadvantages: Requires initial surgical placement, bladder perforation risk, tract complications.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A nurse performing catheter care notices the urine has become dark red with clots. The patient had a catheter change yesterday. What should be done?',
'Normal after catheter change',
'Assess for hematuria cause - may be traumatic from change, or new pathology; monitor, manual washout if blocking, increase fluids',
'Remove catheter immediately',
'Give antibiotics',
'Increase catheter size',
'B',
'Hematuria with catheter: Causes include traumatic insertion, UTI, bladder calculi, tumor, anticoagulation. Post-catheter change = likely traumatic, usually settles. Management: Monitor color and volume, ensure catheter draining (may need manual washout if clots blocking), increase fluids. If persists, investigate for pathology.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with indwelling catheter develops sudden fever, rigors, and flank pain. Blood pressure drops to 90/60. What is the likely diagnosis?',
'Simple CAUTI',
'Urosepsis - severe infection with systemic inflammatory response requiring urgent antibiotics and resuscitation',
'Normal catheter finding',
'Constipation',
'Dehydration',
'B',
'Urosepsis: CAUTI with systemic spread causing sepsis. Signs: Fever, rigors, flank pain, hypotension, altered consciousness. May progress to septic shock rapidly. Management: Resuscitation (fluids, may need vasopressors), blood cultures, change catheter, urgent broad-spectrum antibiotics (cover gram negatives + pseudomonas), source control.',
'hard', 'application'),

-- ADDITIONAL LEG ULCER SCENARIOS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a venous ulcer develops increased pain, surrounding erythema extending 5cm from wound edge, and fever. What complication has occurred?',
'Normal healing',
'Cellulitis - secondary bacterial infection of surrounding tissue requiring antibiotics',
'Venous thrombosis',
'Critical limb ischemia',
'Contact dermatitis',
'B',
'Cellulitis complicating leg ulcer: Spreading erythema, warmth, pain, fever indicates bacterial invasion of surrounding tissue. Common organisms: Streptococcus, Staphylococcus. Treatment: Systemic antibiotics (flucloxacillin first line, add coverage for strep), elevate leg, may need hospital admission if severe. Mark erythema edge.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic venous ulcer has been treated with compression for 6 months without healing. What should be considered?',
'Continue same treatment indefinitely',
'Investigate for mixed etiology, malignancy (biopsy if non-healing greater than 6 months), consider advanced wound therapy, optimize nutrition, exclude osteomyelitis',
'Stop all treatment',
'Amputation',
'Only observation needed',
'B',
'Non-healing ulcer investigation: After 6 months without healing: Biopsy to exclude malignancy (Marjolin ulcer - SCC). Check for mixed arterial disease. Exclude osteomyelitis (probe to bone, MRI). Optimize nutrition. Consider advanced therapies (skin grafts, bioengineered skin, growth factors, VAC). Reassess patient compliance.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient has a 2cm ulcer on the plantar surface of the 1st metatarsal head. What is the most important intervention beyond wound care?',
'Antibiotics',
'Offloading - removing pressure from the ulcer site (total contact cast, removable walker, or offloading shoes)',
'Compression bandaging',
'Elevation only',
'Hot soaks',
'B',
'Diabetic foot ulcer offloading: Pressure is a major factor in plantar ulcer development and perpetuation. Offloading is essential for healing. Total contact cast (gold standard), removable cast walker, half shoes, or therapeutic footwear. Without offloading, healing is unlikely. Also optimize glucose, treat infection, vascular assessment.',
'medium', 'application'),

-- ADDITIONAL BLOOD CONSERVATION SCENARIOS
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient develops dilutional coagulopathy after massive hemorrhage and crystalloid resuscitation. INR is 2.1, fibrinogen is 1.2 g/L. What should be administered?',
'More crystalloid',
'Fresh frozen plasma and cryoprecipitate (or fibrinogen concentrate) to correct coagulopathy',
'Packed red blood cells only',
'Tranexamic acid only',
'Vitamin K',
'B',
'Dilutional coagulopathy in massive hemorrhage: Crystalloid resuscitation dilutes clotting factors. Replace with FFP (contains all factors), cryoprecipitate or fibrinogen concentrate (for low fibrinogen less than 1.5 g/L), platelets if count less than 75. Target: INR less than 1.5, fibrinogen greater than 1.5 g/L. Massive transfusion protocol guided by point-of-care testing.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has received 6 units of packed RBCs in 2 hours. The massive transfusion protocol is activated. What ratio of blood products is currently recommended?',
'10:1:1 (RBC:FFP:platelets)',
'1:1:1 or balanced ratio (RBC:FFP:platelets) to prevent dilutional coagulopathy',
'RBCs only, no other products',
'3:1:1 ratio',
'Crystalloid:blood 3:1',
'B',
'Massive transfusion protocol (MTP): Based on military data (PROPPR trial), balanced ratio 1:1:1 (PRBC:FFP:platelets in units) or similar reduces coagulopathy and mortality. Early use of plasma and platelets, not just RBCs. Point-of-care testing (TEG/ROTEM) can guide further. Include calcium replacement and TXA.',
'medium', 'application'),

-- ADDITIONAL SURGICAL WOUNDS SCENARIOS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A wound has been healing well but at week 3, patient notices the scar becoming firm, red, and raised but staying within wound margins. What is occurring?',
'Normal wound healing',
'Hypertrophic scar formation - elevated scar within wound boundaries, often improves over time',
'Keloid',
'Wound infection',
'Wound dehiscence',
'B',
'Hypertrophic scar: Raised, red, firm scar that stays WITHIN wound margins (unlike keloid which extends beyond). More common in areas of tension. Usually improves spontaneously over 6-12 months. Treatment if needed: Silicone sheets, massage, intralesional steroids. Prevention: Minimize tension, wound care, silicone.',
'easy', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A 75-year-old malnourished patient with diabetes has persistent wound breakdown despite adequate glucose control. Serum albumin is 22 g/L. What factor is most important to address?',
'Increase insulin dose',
'Nutritional optimization - particularly protein intake to support wound healing',
'Change dressings more frequently',
'Add more antibiotics',
'Surgical revision',
'B',
'Malnutrition and wound healing: Protein-calorie malnutrition impairs wound healing (reduced collagen synthesis, impaired immune function). Albumin less than 30 g/L associated with poor healing. Target protein 1.5-2g/kg/day, adequate calories. May need enteral or parenteral supplementation. Also ensure adequate zinc, vitamin C.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient on therapeutic warfarin (INR 2.5) has a minor surgical wound that continues to ooze despite adequate local pressure. What should be considered?',
'Stop all anticoagulation immediately',
'Local hemostatic measures (topical thrombin, oxidized cellulose), consider temporary anticoagulation reduction if safe, optimize local wound care',
'Massive transfusion',
'Emergency surgery',
'Nothing - expected with warfarin',
'B',
'Anticoagulation and wound healing: Anticoagulants may prolong bleeding but do not prevent healing. For persistent oozing: Local measures (topical hemostatics, pressure, suture if needed). Consider temporary anticoagulation reduction if safe (weigh thrombotic risk). Do not stop anticoagulation without assessing indication. Vitamin K only for serious bleeding.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A wound has healthy granulation tissue but epithelialization from wound edges has stalled for 2 weeks. What could help promote epithelialization?',
'Continue waiting',
'Ensure moist wound environment, consider skin graft if large, silicone dressings, or bioengineered skin substitutes',
'Allow wound to dry out',
'Add topical antibiotics',
'Increase debridement',
'B',
'Promoting epithelialization: Occurs from wound edges and skin appendages. Moist environment accelerates epithelialization (occlusive dressings). If stalled: Ensure no underlying infection, optimize nutrition, consider skin graft for larger wounds, bioengineered skin substitutes (Apligraf, Dermagraft), or growth factors.',
'medium', 'application'),

-- ADDITIONAL GENERAL CLINICAL SCENARIOS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient needs emergency surgery but has eaten a full meal 2 hours ago. What are the anesthetic considerations regarding aspiration risk?',
'No increased risk',
'Full stomach increases aspiration risk - rapid sequence induction with cricoid pressure indicated, NG decompression may help',
'Cancel surgery',
'Proceed with standard induction',
'Wait 12 hours',
'B',
'Aspiration risk: Full stomach increases risk of gastric content aspiration during induction. Emergency surgery: Rapid sequence induction (RSI) with cricoid pressure (Sellick maneuver). Pre-oxygenation, fast-acting induction agents (propofol/thiopentone), suxamethonium or rocuronium, immediate intubation. Consider NG decompression. Antacids (sodium citrate).',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing general anesthesia has history of malignant hyperthermia. What precautions must be taken?',
'Standard anesthesia is safe',
'Avoid triggering agents (volatiles, suxamethonium), use total IV anesthesia, have dantrolene available',
'Use halothane specifically',
'Succinylcholine is safe',
'No special precautions',
'B',
'Malignant hyperthermia precautions: Avoid ALL volatile anesthetics (sevoflurane, isoflurane, desflurane) and succinylcholine. Use clean anesthetic machine (vapors flushed). Total intravenous anesthesia (TIVA) with propofol, opioids, non-depolarizing relaxants. Dantrolene must be immediately available. Monitor temperature, EtCO2, muscle tone.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'An obese patient with OSA is at high risk of difficult airway. What preparations should be made?',
'Standard equipment only',
'Difficult airway trolley available, consider awake fiber-optic intubation, senior anesthetist, post-op HDU/ICU bed',
'Proceed without preparation',
'Cancel all surgery',
'Only local anesthesia ever',
'B',
'Difficult airway preparation: OSA + obesity = high-risk airway. Preparation: Difficult airway trolley (videolaryngoscope, bougie, supraglottic airways, surgical airway equipment), skilled senior anesthetist, consider awake fiber-optic intubation. Post-op: HDU/ICU bed, CPAP if uses at home, avoid excessive sedation, monitor closely.',
'medium', 'application');
