-- ============================================================================
-- BATCH 41: Advanced Clinical Scenarios - Surgical Emergencies
-- Topic: Complex decision-making scenarios across multiple surgical topics
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- TRAUMA AND SHOCK ADVANCED SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A motorcyclist presents after RTA with BP 90/70, HR 130, GCS 14. FAST shows free fluid. After 2L crystalloid, BP is now 85/60 and abdomen is distending. What is the management priority?',
'Give more crystalloid',
'Activate massive transfusion protocol and proceed directly to emergency laparotomy - damage control resuscitation',
'CT scan first',
'Wait for blood bank',
'Continue fluid resuscitation until BP normalizes',
'B',
'Unstable trauma with intra-abdominal bleeding: No response to initial fluid = ongoing hemorrhage. "Permissive hypotension" until surgical control. Massive transfusion protocol (1:1:1 ratio). Proceed to emergency laparotomy for damage control surgery - pack, control bleeding, temporary closure. Avoid hypothermia, acidosis, coagulopathy (lethal triad).',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in hemorrhagic shock has received 6 units PRBCs, 6 units FFP, 1 pool platelets. Temperature is 34.5°C and bleeding continues despite surgical hemostasis. Labs show pH 7.18, lactate 8. What is the priority?',
'Continue surgery until complete',
'Damage control surgery (pack and close), active rewarming, correct coagulopathy - avoid lethal triad',
'More blood products only',
'Imaging studies',
'Wait for lab results',
'B',
'Lethal triad: Hypothermia (less than 35°C), acidosis (pH less than 7.2), coagulopathy. Each worsens the others in a vicious cycle. Management: Damage control surgery (abbreviated surgery, pack, temporary closure), ICU resuscitation (rewarm, correct acidosis, replace blood products), return to theatre when stable for definitive repair.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with pelvic fracture is hypotensive (BP 80/50) despite aggressive resuscitation. CT shows large pelvic hematoma but no other injuries. FAST is negative. What is the source of hemorrhage and management?',
'Intra-abdominal bleeding',
'Pelvic venous plexus and/or arterial bleeding - pelvic binder, angioembolization, or packing may be needed',
'External bleeding only',
'Thoracic source',
'No significant bleeding',
'B',
'Pelvic fracture bleeding: Rich venous plexus and branches of internal iliac artery. Retroperitoneal, so FAST may be negative. Management: Pelvic binder (stabilization reduces venous bleeding), transfusion, angiography with embolization for arterial bleeding, preperitoneal pelvic packing if unstable. May need combination approach.',
'hard', 'application'),

-- CPR AND RESUSCITATION ADVANCED SCENARIOS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During CPR for VF arrest, ROSC is achieved after third shock. However, immediately after ROSC, the monitor shows VT at rate 200 with no pulse. What is the next action?',
'Continue chest compressions only',
'This is re-arrest in VT - immediate defibrillation as per shockable rhythm protocol',
'Give IV amiodarone first',
'Check for breathing',
'Wait 2 minutes before checking rhythm',
'B',
'Re-arrest in VT/VF: Pulseless VT is a shockable rhythm. If patient re-arrests into VT immediately after ROSC, treat as new shockable arrest - immediate defibrillation. Resume CPR while charging. Consider underlying cause (ongoing ischemia, electrolyte abnormality). May need recurrent shocks if refractory.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient has cardiac arrest from massive PE. Standard ACLS has been followed for 20 minutes without ROSC. What additional interventions may be considered?',
'Stop resuscitation',
'Consider thrombolysis during CPR, ECMO if available, or surgical/interventional embolectomy',
'Continue same protocol indefinitely',
'Only chest compressions',
'Call time of death immediately',
'B',
'Cardiac arrest from PE: Standard CPR often ineffective due to mechanical obstruction. Options: Thrombolysis during CPR (alteplase - extends CPR duration to 60-90 mins if given), ECMO/ECPR if available, surgical or catheter-directed embolectomy. Prolonged CPR may be appropriate if PE confirmed as cause with definitive treatment available.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient achieves ROSC after out-of-hospital cardiac arrest. Initial GCS is 6 (E1V2M3). What post-resuscitation care is indicated?',
'Standard ward care',
'Targeted temperature management (TTM), optimize oxygenation/ventilation, hemodynamic management, early coronary angiography if STEMI/suspected cardiac cause',
'Immediate extubation',
'No specific care needed',
'Therapeutic hypothermia to 30°C',
'B',
'Post-cardiac arrest care: 1) Targeted temperature management (32-36°C for 24h in comatose patients). 2) Optimize oxygenation (avoid hypoxia and hyperoxia). 3) Hemodynamic targets (MAP greater than 65, treat cause). 4) Early coronary angiography if STEMI or suspected cardiac etiology. 5) Neuroprognostication after 72h minimum. ICU care essential.',
'hard', 'application'),

-- FLUID AND ELECTROLYTE ADVANCED SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has Na+ 126 mEq/L, measured serum osmolality 270 mOsm/kg, urine osmolality 600 mOsm/kg, urine Na+ 45 mEq/L. What is the most likely diagnosis?',
'Diabetes insipidus',
'SIADH (syndrome of inappropriate ADH) - euvolemic hypoosmolar hyponatremia with concentrated urine',
'Salt wasting',
'Hyperglycemic hyponatremia',
'Primary polydipsia',
'B',
'SIADH diagnosis: Hypotonic hyponatremia (low serum osmolality), inappropriately concentrated urine (greater than 100 mOsm/kg), elevated urine sodium (greater than 40 mEq/L in presence of hyponatremia), clinically euvolemic. Causes: CNS disorders, pulmonary disease, malignancy, drugs, post-operative. Treatment: Fluid restriction, treat cause, consider demeclocycline or tolvaptan if severe.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with severe burns has ongoing fluid resuscitation. After 12 hours, serum K+ is 6.8 mEq/L, pH 7.25, creatinine rising. ECG shows peaked T waves and widened QRS. What is the immediate priority?',
'Continue standard resuscitation',
'Cardiac protection with IV calcium gluconate, then shift K+ with insulin-dextrose, treat underlying acidosis/renal failure',
'Oral kayexalate only',
'Check repeat potassium',
'Increase IV fluids',
'B',
'Severe hyperkalemia with ECG changes: Life-threatening. Immediate steps: 1) Calcium gluconate 10ml of 10% IV (cardioprotection - does NOT lower K+). 2) Insulin (10 units) + dextrose (25g) - shifts K+ into cells. 3) Salbutamol nebulizer (additional shift). 4) Calcium resonium/kayexalate (removes K+). 5) Dialysis if refractory. Treat cause (burns release intracellular K+).',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient on TPN develops tremor, confusion, and positive Chvostek sign despite normal calcium. What deficiency should be suspected?',
'Hypocalcemia',
'Hypomagnesemia - can cause hypocalcemia-like symptoms and refractory hypocalcemia/hypokalemia',
'Hypophosphatemia',
'Zinc deficiency',
'Vitamin deficiency',
'B',
'Hypomagnesemia: Causes neuromuscular excitability similar to hypocalcemia (tetany, Chvostek/Trousseau signs). Also causes refractory hypocalcemia (Mg needed for PTH secretion) and refractory hypokalemia (Mg needed for K+ retention). Common in TPN, alcoholism, GI losses, diuretics. Treatment: IV magnesium sulfate.',
'hard', 'application'),

-- BLOOD TRANSFUSION ADVANCED SCENARIOS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient develops acute respiratory distress during blood transfusion with bilateral pulmonary infiltrates on CXR, no signs of fluid overload, and normal BNP. SpO2 is 85% on 15L O2. What is the diagnosis?',
'Pulmonary embolism',
'Transfusion-related acute lung injury (TRALI) - non-cardiogenic pulmonary edema, stop transfusion, supportive care',
'TACO',
'Anaphylaxis',
'Bacterial contamination',
'B',
'TRALI: Acute respiratory distress within 6 hours of transfusion, bilateral infiltrates, no cardiac cause (normal BNP, no fluid overload evidence). Caused by donor anti-HLA or anti-neutrophil antibodies. Treatment: Stop transfusion, supportive care (O2, may need intubation), NO diuretics (not fluid overload). Usually resolves 48-96 hours. Report to blood bank.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient receiving platelet transfusion for chemotherapy-induced thrombocytopenia has had minimal response to three consecutive transfusions. Pre-transfusion count was 8, post-transfusion was 12 (expected greater than 30). What should be investigated?',
'Continue same platelets',
'Check for HLA antibodies (alloimmunization) - may need HLA-matched platelets',
'Stop all transfusions',
'Switch to FFP',
'Use more platelets',
'B',
'Platelet refractoriness: Poor increment after platelet transfusion. Causes: Immune (HLA alloimmunization from previous transfusions/pregnancy - 70%) or non-immune (sepsis, DIC, splenomegaly, drugs). Investigate: HLA antibody screen. If HLA antibodies present: Use HLA-matched platelets or crossmatched platelets. May respond to fresh platelets (less than 3 days old).',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with sickle cell disease requires transfusion for acute chest syndrome. Hb is 6.5 g/dL. What special transfusion considerations apply?',
'Standard uncrossmatched blood',
'Extended phenotype matching, exchange transfusion may be needed, aim to reduce HbS%, avoid over-transfusion',
'Any blood type acceptable',
'No special requirements',
'Whole blood preferred',
'B',
'Sickle cell transfusion: Extended phenotyping (Rh and Kell antigens) to prevent alloimmunization (common in SCD). For acute chest syndrome, exchange transfusion may be preferred (reduces HbS% while avoiding hyperviscosity). Target Hb less than 10-11 (avoid hyperviscosity). Crossmatch may be difficult due to antibodies. Leukodepleted blood.',
'hard', 'application'),

-- FRACTURE ADVANCED SCENARIOS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a closed tibial fracture develops increasing pain not relieved by splitting the cast, pain on passive stretch of toes, and paresthesias. Pulses are present. What is the diagnosis and urgent management?',
'Cast too tight only',
'Compartment syndrome - urgent fasciotomy required, do not wait for pressure measurements if clinical diagnosis clear',
'Nerve injury from fracture',
'DVT',
'Normal fracture pain',
'B',
'Compartment syndrome: Classic signs - Pain out of proportion, Pain on passive stretch, Paresthesias, Pulselessness (late sign), Paralysis (late sign). Pulses may be present until late stage. If clinical diagnosis clear, URGENT fasciotomy required. Waiting for compartment pressure measurement may delay treatment. Remove all circumferential dressings/cast immediately.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with femur fracture has sudden onset dyspnea, confusion, and petechial rash on chest 48 hours after injury. SpO2 is 88%. What is the likely diagnosis?',
'Pulmonary embolism',
'Fat embolism syndrome - triad of respiratory distress, neurological changes, and petechial rash after long bone fracture',
'Pneumonia',
'Aspiration',
'Cardiac failure',
'B',
'Fat embolism syndrome (FES): Occurs 24-72 hours after long bone/pelvic fractures. Triad: Respiratory distress (most common), neurological changes (confusion, agitation), petechial rash (pathognomonic, delayed, over chest/axillae). Diagnosis: Clinical + exclusion. Management: Supportive (O2, may need ventilation), early fracture fixation may prevent.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old on warfarin falls and has a minimally displaced intracapsular neck of femur fracture. What factors influence surgical decision-making?',
'All intracapsular fractures need hemiarthroplasty',
'Age, displacement, baseline mobility and cognition, fracture type (subcapital vs basicervical), ASA grade - determines fixation vs arthroplasty',
'All need total hip replacement',
'Conservative management preferred in elderly',
'Wait for anticoagulation reversal then decide',
'B',
'Intracapsular NOF decision: Displaced = hemiarthroplasty or THR (high AVN/nonunion with fixation). Undisplaced = may attempt fixation (cannulated screws) in younger patients. Consider: Age, baseline mobility (mobile = THR may be better), cognitive status (dementia = hemiarthroplasty), ASA grade, anticoagulation (reverse or surgery with elevated INR). Aim for surgery within 36 hours.',
'hard', 'application'),

-- SURGICAL WOUNDS ADVANCED SCENARIOS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A post-surgical wound develops foul-smelling thin discharge with gray necrotic tissue and pain disproportionate to examination findings at day 2. What is the likely diagnosis and immediate action?',
'Simple wound infection',
'Necrotizing soft tissue infection (NSTI) - urgent surgical debridement, broad spectrum antibiotics, ICU care',
'Normal healing',
'Seroma',
'Hematoma',
'B',
'Necrotizing soft tissue infection: Rapidly progressive, high mortality. Signs: Pain disproportionate to findings, thin dishwater discharge, crepitus, skin necrosis, systemic toxicity. May be clostridial (gas gangrene) or polymicrobial (Fournier''s, necrotizing fasciitis). Management: IMMEDIATE radical surgical debridement (often multiple operations needed), broad spectrum antibiotics (including clindamycin for toxin suppression), ICU.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with prosthetic mesh repair of incisional hernia develops late mesh infection 6 months post-surgery with a draining sinus. Conservative treatment has failed. What is definitive management?',
'Long-term antibiotics',
'Mesh explantation (removal) - infected synthetic mesh rarely clears without removal',
'Increase antibiotic strength',
'Local wound care only',
'Ignore if patient stable',
'B',
'Mesh infection: Synthetic mesh infection is difficult to eradicate with antibiotics alone (biofilm formation). May present early (wound infection) or late (sinus, mesh exposure). Definitive treatment usually requires mesh explantation. May need staged repair with biological mesh or autologous tissue. Prevention: Meticulous technique, prophylactic antibiotics.',
'hard', 'application'),

-- MONITORING AND CRITICAL CARE SCENARIOS
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient in ICU has cardiac output 7L/min (high), SVR 600 dynes (low), CVP 4mmHg, lactate 5mmol/L. What type of shock is this?',
'Cardiogenic shock',
'Distributive (likely septic) shock - hyperdynamic circulation with low SVR despite high cardiac output',
'Hypovolemic shock',
'Obstructive shock',
'Neurogenic shock',
'B',
'Hemodynamic patterns: Septic/distributive shock shows vasodilation (low SVR), hyperdynamic circulation (high CO initially), low CVP (relative hypovolemia from vasodilation), elevated lactate (tissue hypoperfusion despite high flow). Cardiogenic = low CO, high SVR, high CVP. Hypovolemic = low CO, high SVR, low CVP. Treatment: Fluids first, then vasopressors (norepinephrine), source control.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A ventilated patient suddenly develops hypotension, hypoxia, elevated airway pressures, absent breath sounds on one side, and tracheal deviation. What is the diagnosis and immediate action?',
'ETT displacement',
'Tension pneumothorax - immediate needle decompression followed by chest drain',
'Cardiac arrest',
'Bronchospasm',
'Ventilator malfunction',
'B',
'Tension pneumothorax: Clinical diagnosis - do NOT wait for CXR. Signs: Hypotension, hypoxia, absent breath sounds, tracheal deviation (late), distended neck veins. Immediate needle decompression (2nd intercostal space mid-clavicular or 5th space mid-axillary), followed by chest tube insertion. Remove any circumferential dressings, disconnect from ventilator briefly if needed.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A post-thyroidectomy patient 6 hours post-op develops stridor and increasing neck swelling. What is the emergency management?',
'Give oxygen and observe',
'Open the wound immediately at bedside to evacuate hematoma, prepare for emergency airway management',
'CT scan of neck',
'Start antibiotics',
'Reassure patient',
'B',
'Post-thyroidectomy hematoma: Expanding neck hematoma can cause airway compromise rapidly. Stridor = critical airway emergency. Management: Open wound at bedside immediately (removes sutures, evacuates hematoma, relieves pressure). Prepare for difficult intubation or surgical airway. Do NOT delay for imaging. Return to theatre for hemostasis after airway secured.',
'hard', 'application');
