-- ============================================================================
-- BATCH 43: Procedural and Practical Skills Clinical Scenarios
-- Topics: NG Intubation, Urethral Catheterization, Surgical Techniques
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- NASOGASTRIC INTUBATION CLINICAL SCENARIOS
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with head injury and base of skull fracture requires gastric decompression. What route should be used for tube insertion?',
'Nasogastric route standard',
'Orogastric route - nasogastric contraindicated in base of skull fracture due to risk of intracranial passage',
'Nasogastric is safe in all skull fractures',
'No decompression needed',
'Gastrostomy only option',
'B',
'Base of skull fracture: Signs include raccoon eyes, Battle sign, CSF rhinorrhea/otorrhea. NG tube contraindicated - risk of intracranial passage through cribriform plate fracture. Use orogastric tube instead. Other contraindications for NG: esophageal stricture/perforation, recent gastric surgery, caustic ingestion, severe coagulopathy.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A ventilated ICU patient has high NG aspirate volumes of 500ml every 4 hours for 5 days. What nutritional approach is appropriate?',
'Continue NG feeding',
'Consider post-pyloric feeding (NJ tube) or prokinetics, if gastric ileus persists may need parenteral nutrition',
'Stop all nutrition',
'Wait for normal aspirates',
'NG aspirate volume is irrelevant',
'B',
'High gastric residual in ICU: Indicates gastroparesis (common in critical illness). Options: 1) Prokinetics (metoclopramide, erythromycin). 2) Post-pyloric feeding (nasojejunal tube placed endoscopically or fluoroscopically). 3) Consider parenteral nutrition if enteral route fails. Do not starve ICU patients - increases mortality. Small bowel usually functions even when stomach does not.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with esophageal varices and active upper GI bleeding requires gastric decompression. Is NG tube insertion safe?',
'Absolutely contraindicated',
'Can be inserted carefully if clinically needed - risk of worsening bleeding exists but may be necessary; use small caliber, gentle technique',
'No risk at all',
'Only after bleeding stops',
'Always causes massive hemorrhage',
'B',
'NG tube in variceal bleeding: Controversial but not absolutely contraindicated. May be needed for: gastric decompression (prevent aspiration), prepare for endoscopy (clear stomach). Use small caliber tube, gentle technique, well-lubricated. Risk of mucosal trauma exists. Some units avoid NG, others use routinely. Clinical judgement based on aspiration risk versus bleeding risk.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A post-stroke patient with dysphagia has had NG tube feeding for 6 weeks. Speech and language therapy assessment suggests swallow may not recover. What is the next step?',
'Continue NG indefinitely',
'Plan for percutaneous endoscopic gastrostomy (PEG) - long-term enteral access preferred after 4-6 weeks of NG feeding',
'Stop feeding entirely',
'IV nutrition permanently',
'NG is suitable for years',
'B',
'Long-term enteral access: NG tube uncomfortable, prone to displacement, may increase aspiration and sinusitis risk. If enteral feeding needed greater than 4-6 weeks, consider gastrostomy (PEG or surgical). PEG: endoscopic placement, local anesthesia. Requires: able to transilluminate stomach, no ascites, acceptable coagulation. Contraindications: head and neck cancer with esophageal obstruction, portal hypertension.',
'medium', 'application'),

-- URETHRAL CATHETERIZATION CLINICAL SCENARIOS
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'An 82-year-old male with BPH has acute urinary retention. Urethral catheterization fails after three attempts with increasing resistance. What is the next management step?',
'Force the catheter through',
'Suprapubic catheterization or urology referral for flexible cystoscopy with guidewire placement',
'Continue urethral attempts',
'Discharge without drainage',
'IM injection for bladder',
'B',
'Failed urethral catheterization: Do NOT force catheter (risk of false passage, urethral injury). Options: 1) Suprapubic catheterization (if palpable bladder, no contraindications). 2) Urology referral for flexible cystoscopy and guidewire-assisted catheterization. 3) Consider coude-tip catheter if not already tried. Document attempts and reason for failure.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient on warfarin with INR 4.5 develops acute urinary retention. How should this be managed?',
'Wait until INR normal before catheterization',
'Catheterize promptly - urinary retention is emergency; use gentle technique, suprapubic may be safer if urethral anatomy difficult',
'Give vitamin K first',
'No drainage needed',
'Oral fluids to help void',
'B',
'Urinary retention with anticoagulation: Urinary retention is a medical emergency requiring prompt drainage regardless of anticoagulation status. Urethral catheterization is generally safe with elevated INR with careful technique. If anticipating difficulty (BPH, stricture), suprapubic catheterization may be safer as hemostasis easier to achieve. Do not delay decompression waiting for anticoagulation reversal.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A young male with pelvic trauma has blood at urethral meatus, perineal hematoma, and high-riding prostate on DRE. What is the management of his urinary retention?',
'Immediate urethral catheterization',
'Suprapubic catheterization - suspected urethral injury; retrograde urethrogram before any urethral instrumentation',
'Wait for spontaneous voiding',
'Gentle urethral catheterization acceptable',
'Cystoscopy first choice',
'B',
'Urethral injury signs: Blood at meatus, perineal hematoma (butterfly pattern), high-riding prostate, inability to void. Classic mechanism: Pelvic fracture with posterior urethral disruption. Management: Do NOT attempt urethral catheterization (may convert partial to complete injury). Insert suprapubic catheter. Retrograde urethrogram to confirm injury. Delayed urethral repair.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A catheterized patient develops blocked catheter 12 hours after transurethral resection of prostate (TURP). Irrigation attempts fail. What is the management?',
'Leave catheter and observe',
'Replace catheter with new larger bore catheter, may need cystoscopy for clot evacuation if obstruction persists',
'Remove catheter and observe',
'Oral medications only',
'Wait 24 hours before action',
'B',
'Blocked catheter post-TURP: Usually due to blood clots. Management: 1) Attempt irrigation with bladder syringe. 2) If fails, replace with new/larger three-way catheter (clots may have blocked lumen). 3) Continuous bladder irrigation (CBI) to prevent further clots. 4) If persistent clot retention, cystoscopy and clot evacuation. Maintain adequate hemostasis - check hemoglobin, coagulation.',
'medium', 'application'),

-- MENSURATION AND EXAMINATION CLINICAL SCENARIOS
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old patient has BP measured at 160/95 in clinic. Automated home readings average 135/82 over 2 weeks. What is the diagnosis?',
'Stage 2 hypertension requiring treatment',
'White coat hypertension - office BP elevated but ambulatory or home BP normal; may not need medication initially',
'Normal blood pressure',
'Equipment malfunction',
'Severe hypertension emergency',
'B',
'White coat hypertension: Office BP greater than 140/90 but daytime ambulatory or home BP less than 135/85. Occurs in 15-30% of patients with elevated clinic BP. Diagnosis: ABPM (gold standard) or home BP monitoring for 7+ days. Management: May not need medication but warrants monitoring as some progress to sustained hypertension. Lifestyle modification recommended. Annual reassessment.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient in septic shock has non-invasive BP reading of 85/50. The clinical team questions its accuracy in this low perfusion state. What is the gold standard for BP monitoring?',
'Non-invasive oscillometric BP',
'Invasive arterial line monitoring - more accurate in shock states with poor peripheral perfusion',
'Palpation of pulse only',
'Calculated from other vitals',
'Auscultatory only',
'B',
'BP monitoring in shock: Non-invasive BP may be inaccurate in: shock (poor pulse amplitude), arrhythmias, obesity, movement. Invasive arterial monitoring provides: continuous real-time BP, waveform analysis (pulse pressure variation, cardiac output estimation), accurate BP in low perfusion states, arterial access for blood gases. Gold standard for critically ill patients.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient has blood pressure of 180/65 mmHg. What does the wide pulse pressure suggest and what condition should be considered?',
'Normal variation',
'Wide pulse pressure suggests aortic regurgitation, hyperthyroidism, severe anemia, or arterial stiffness (elderly); examine for water-hammer pulse and diastolic murmur',
'Measurement error',
'Hypotension',
'Narrow pulse pressure',
'B',
'Wide pulse pressure (greater than 60 mmHg): Pulse pressure = systolic minus diastolic. Causes: Aortic regurgitation (collapsing pulse, diastolic murmur, wide PP), hyperthyroidism, severe anemia, arteriovenous fistula, elderly (stiff arteries). Clinical significance: Indicates high stroke volume and/or decreased peripheral resistance. Examine for specific signs of underlying cause.',
'medium', 'application'),

-- INTRAOPERATIVE MONITORING CLINICAL SCENARIOS
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, the pulse oximeter waveform becomes dampened and SpO2 reads 85% despite the patient appearing pink with good end-tidal CO2. What is the likely cause?',
'True hypoxemia',
'Artifact - poor signal due to peripheral vasoconstriction, probe malposition, nail polish, or movement; reposition probe, check patient clinically',
'Cardiac arrest imminent',
'Ventilator failure',
'Equipment completely accurate',
'B',
'Pulse oximetry artifact: Causes of false low readings: peripheral vasoconstriction (cold, shock), probe malposition, motion artifact, nail polish (especially blue/green), methylene blue administration, excessive ambient light. Check waveform quality - poor waveform = unreliable reading. Verify clinically: patient color, ETCO2 (if normal, likely adequate oxygenation). Reposition probe, warm extremity if cold.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient under general anesthesia develops sudden onset hypotension, elevated ETCO2, rising temperature (38.5°C), muscle rigidity, and tachycardia. What is the diagnosis and immediate action?',
'Simple hypoventilation',
'Malignant hyperthermia - stop triggering agents immediately, give IV dantrolene, hyperventilate with 100% O2, active cooling, treat hyperkalemia',
'Equipment malfunction',
'Normal anesthetic response',
'Allergic reaction only',
'B',
'Malignant hyperthermia: Hypermetabolic crisis triggered by volatile anesthetics or succinylcholine. Signs: Rising ETCO2 (often first sign), hyperthermia, tachycardia, rigidity, hypoxia, hyperkalemia, acidosis. EMERGENCY management: 1) Stop triggers, switch to clean circuit. 2) Dantrolene 2.5mg/kg IV (repeat until symptoms resolve). 3) 100% O2, hyperventilate. 4) Active cooling. 5) Treat hyperkalemia, acidosis. 6) Monitor CK (rhabdomyolysis).',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During laparoscopic surgery, the patient develops increased airway pressure, decreased ETCO2, hypotension, and decreased SpO2. Breath sounds are diminished on the left. What has likely occurred?',
'Hypoventilation',
'CO2 insufflation complication - possible capnothorax (pneumothorax from CO2 extravasation); release pneumoperitoneum, consider chest decompression',
'Bronchospasm',
'Circuit disconnection',
'Normal laparoscopy finding',
'B',
'Laparoscopy complications: Capnothorax (pneumothorax from CO2 tracking through diaphragmatic defects or subcutaneous emphysema). Signs: Increased airway pressure, hypoxia, hypotension, decreased breath sounds. Management: Immediately release pneumoperitoneum (open all ports). If tension features: needle decompression or chest drain. CO2 absorbs quickly - may resolve rapidly once source stopped. Subcutaneous emphysema can cause similar presentation.',
'hard', 'application'),

-- GENERAL SURGERY PRINCIPLES CLINICAL SCENARIOS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient is scheduled for elective hernia repair. They take aspirin for primary prevention and clopidogrel for coronary stent inserted 3 months ago. How should antiplatelet therapy be managed?',
'Stop both medications 7 days before',
'Cardiology consultation essential - clopidogrel generally continued for 6-12 months after DES; may need to delay elective surgery or perform with cardiology guidance',
'Continue both during surgery',
'Stop clopidogrel only 1 day before',
'No modification needed',
'B',
'Antiplatelet management perioperatively: Drug-eluting stent (DES) requires dual antiplatelet therapy (DAPT) for 6-12 months. Stopping clopidogrel early risks stent thrombosis (high mortality). Options: Delay elective surgery until DAPT complete, continue aspirin and operate, or cardiology consultation for bridging strategies. Primary prevention aspirin may be stopped. Multidisciplinary decision required.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient on metformin is scheduled for CT with IV contrast. Creatinine is 150 μmol/L (eGFR 35). What precautions are needed?',
'No precautions for contrast or metformin',
'Withhold metformin 48 hours post-contrast, adequate hydration pre and post contrast, minimize contrast volume, reassess renal function before restarting metformin',
'Metformin contraindicated permanently',
'Contrast absolutely contraindicated',
'Continue metformin unchanged',
'B',
'Metformin and contrast: Risk of contrast-induced nephropathy (CIN) especially with eGFR less than 45. If CIN occurs and metformin continued, risk of lactic acidosis. Management: Withhold metformin from time of contrast, recheck renal function 48 hours post-contrast, restart only if function stable. IV hydration before and after contrast. Use minimum contrast volume. Consider iso-osmolar contrast.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with liver cirrhosis and ascites (Child-Pugh B) requires umbilical hernia repair for pain. What specific perioperative considerations apply?',
'No special considerations',
'High surgical risk - optimize liver function, drain ascites, correct coagulopathy, may need concomitant TIPS; discuss with hepatology',
'Standard hernia repair approach',
'Surgery contraindicated in all cirrhosis',
'Immediate emergency surgery',
'B',
'Surgery in liver cirrhosis: High risk of: bleeding (coagulopathy, portal hypertension), infection, hepatic decompensation, ascites leak, poor wound healing. Preoperative: Optimize nutrition, correct coagulopathy (vitamin K, FFP, platelets), drain ascites, consider TIPS for portal decompression, hepatology input for Child-Pugh C. Mesh use controversial (infection risk with ascites). MELD score helps predict mortality.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient develops high-output stoma 2 weeks after ileostomy formation. Output is 2.5L per day. What is the management?',
'Encourage oral fluids',
'Restrict oral hypotonic fluids, use oral rehydration solution, consider loperamide and codeine, IV fluids if dehydrated, review for cause',
'Increase fiber intake',
'Normal ileostomy output',
'Immediate stoma reversal',
'B',
'High-output stoma (greater than 1.5-2L/day): Causes: Adaptation period, infection, obstruction, short bowel, withdrawal of steroids. Management: 1) Restrict oral hypotonic fluids (worsen output). 2) Oral rehydration solution (sipped throughout day). 3) Loperamide (high doses may be needed - up to 16mg/day). 4) Codeine phosphate. 5) Consider PPIs (reduce gastric secretion). 6) IV fluids if dehydrated. 7) Monitor electrolytes (Mg, K).',
'hard', 'application'),

-- FRACTURE MANAGEMENT CLINICAL SCENARIOS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a tibial plateau fracture is being treated conservatively. At 6-week follow-up, there is valgus deformity of 8 degrees with progressive displacement. What is the management?',
'Continue conservative management',
'Consider operative intervention - progressive displacement or unacceptable alignment may require ORIF or conversion to arthroplasty',
'Normal healing pattern',
'Apply cast only',
'No further intervention possible',
'B',
'Failed conservative fracture management: Indications for late operative intervention: progressive displacement, unacceptable alignment (greater than 5-10 degrees valgus/varus for tibial plateau), articular step-off greater than 2-3mm. Options: ORIF if bone quality adequate, external fixation, or in elderly with osteoporosis may consider primary total knee replacement for complex tibial plateau fractures.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient with distal radius fracture has had closed reduction and cast application. X-rays at 1 week show fracture has re-displaced. What options should be considered?',
'Accept displacement in all elderly',
'Assess functional demands - may accept some malunion in low-demand elderly, but consider operative fixation if unacceptable alignment or high functional demands',
'Immediate amputation',
'Repeat closed reduction only',
'No intervention available',
'B',
'Distal radius re-displacement: Common after closed reduction. Decision factors: Patient functional demands (dominant hand, occupation), degree of displacement, age. In low-demand elderly, may accept some malunion (adapts well). In active elderly or younger patients, consider operative fixation (volar locking plate, K-wires, external fixation). Re-manipulation may be attempted but often re-displaces.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with open tibial fracture (Gustilo IIIB) has had debridement and external fixation. There is a 6cm soft tissue defect. What is the reconstructive plan?',
'Primary wound closure',
'Early soft tissue coverage essential - requires plastic surgery for flap coverage (free or local); delay increases infection risk',
'Leave wound open indefinitely',
'Skin grafting only',
'Wait for granulation then graft',
'B',
'Gustilo IIIB open fracture: Soft tissue defect that cannot be closed primarily, often with periosteal stripping. Requires: 1) Serial debridement until clean wound. 2) Early soft tissue coverage (ideally within 72 hours). 3) Options: local muscle flaps (gastrocnemius, soleus) or free flaps (latissimus, gracilis). Skin graft alone inadequate (no vascularized coverage over bone). Delay in coverage increases deep infection/osteomyelitis.',
'hard', 'application');
