-- ============================================================================
-- BATCH 45: Emergency Surgery and Critical Decision Scenarios
-- Topics: Acute surgical presentations with complex management decisions
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- ACUTE ABDOMEN AND SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 72-year-old with atrial fibrillation presents with sudden severe abdominal pain, bloody diarrhea, and minimal tenderness. Lactate is 7.8 mmol/L. What is the likely diagnosis and immediate priority?',
'Gastroenteritis',
'Acute mesenteric ischemia - high mortality emergency; urgent CT angiography and surgical/interventional consultation for revascularization',
'Simple bowel obstruction',
'Pancreatitis',
'Inflammatory bowel disease',
'B',
'Acute mesenteric ischemia (AMI): Classic triad - severe pain out of proportion to examination, AF (embolic source), elevated lactate. Mortality 60-80% without early treatment. Diagnosis: CT angiography. Management: Aggressive resuscitation, IV heparin, urgent intervention (endovascular if early, surgery if peritonitis/bowel necrosis), second-look laparotomy at 24-48h. Time is bowel.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A young patient is brought in after an assault with multiple stab wounds to the abdomen. He is combative with BP 100/60 and HR 120. FAST shows free fluid. What is the management approach?',
'CT scan first for all patients',
'Emergency laparotomy - hemodynamically concerning patient with positive FAST after penetrating trauma needs operative exploration',
'Observe and repeat FAST',
'Local wound exploration only',
'Angiography first',
'B',
'Penetrating abdominal trauma with hemodynamic concern: Unstable or transiently-responding patient with positive FAST = emergency laparotomy. No role for CT in unstable patient. Combativeness may indicate shock (cerebral hypoperfusion). Principles: Damage control if unstable (pack, temporary closure), systematic exploration, repair or resect injured organs. Stable patients may have selective non-operative management with CT.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with Addison disease is admitted for emergency appendectomy. Current maintenance is hydrocortisone 10mg morning, 5mg evening. What perioperative steroid management is required?',
'Continue usual oral dose',
'IV hydrocortisone stress dosing: 100mg IV at induction, then 50mg q8h for 24-48h, then taper back to maintenance',
'Stop steroids for surgery',
'Only post-operative steroids',
'No change needed ever',
'B',
'Adrenal insufficiency and surgery: Patients on replacement cannot mount adequate cortisol response to surgical stress. Stress dosing protocol: Hydrocortisone 100mg IV at induction (some give 200mg for major surgery), then 50mg IV q6-8h for first 24-48h, then taper by halving dose each day until back on maintenance. Cover prevents adrenal crisis (hypotension, collapse).',
'medium', 'application'),

-- BLOOD PRODUCTS AND COAGULATION
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient on warfarin with INR 3.5 requires emergency laparotomy for perforated viscus. What is the reversal strategy for urgent surgery?',
'Wait for INR to normalize naturally',
'Prothrombin complex concentrate (PCC) plus vitamin K IV - rapid reversal for urgent surgery in warfarinized patients',
'FFP only (4-6 units)',
'Proceed without reversal',
'Oral vitamin K only',
'B',
'Warfarin reversal for emergency surgery: PCC (Octaplex, Beriplex) provides rapid, complete reversal in minutes. Dose based on INR and weight. Give with vitamin K 5-10mg IV (sustains reversal - PCC effect temporary). FFP is alternative if PCC unavailable (slower, volume load, infection risk). For life-threatening bleeding, use 4-factor PCC. Check INR 15-30 min after PCC, may need additional dose.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient on dabigatran (NOAC) for AF has intracranial hemorrhage. What specific reversal agent is available?',
'Vitamin K',
'Idarucizumab (Praxbind) - specific reversal agent for dabigatran; PCC for other NOACs if specific agent unavailable',
'Protamine sulfate',
'FFP only',
'No reversal agent exists',
'B',
'NOAC reversal: Dabigatran (direct thrombin inhibitor) - Idarucizumab (Praxbind) 5g IV, rapid complete reversal. Factor Xa inhibitors (rivaroxaban, apixaban, edoxaban) - Andexanet alfa (Ondexxya) if available, otherwise 4-factor PCC. TXA as adjunct. Dialysis can remove dabigatran (not Xa inhibitors). Activated charcoal if ingested within 2-4 hours.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During major hepatic surgery, fibrinogen level is reported as 0.9 g/L (low) with ongoing oozing despite normal platelet count and PT. What blood product is most appropriate?',
'More FFP',
'Cryoprecipitate or fibrinogen concentrate - targeted fibrinogen replacement for hypofibrinogenemia',
'Platelet transfusion',
'PRBCs only',
'No product needed',
'B',
'Hypofibrinogenemia treatment: Fibrinogen less than 1.5 g/L associated with bleeding. Treatment: Cryoprecipitate (pooled from multiple donors, contains fibrinogen, FVIII, vWF, FXIII) - typically 2 pools. Alternative: Fibrinogen concentrate (Riastap) - single donor equivalent, viral-inactivated, precise dosing. Target fibrinogen greater than 1.5-2 g/L in major hemorrhage. More effective than FFP for fibrinogen replacement.',
'medium', 'application'),

-- WOUND COMPLICATIONS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient develops wound dehiscence with evisceration on post-operative day 6 after laparotomy. On exploration in theatre, the fascial edges are necrotic and will not hold sutures. What closure technique should be used?',
'Primary closure with absorbable suture',
'Temporary abdominal closure (TAC) with negative pressure system; delayed definitive closure when tissues healthy',
'Close skin only',
'Mesh bridging immediately',
'Leave completely open',
'B',
'Fascial necrosis with dehiscence: Necrotic fascia will not hold sutures - primary closure will fail. Options: 1) Temporary abdominal closure (TAC) with negative pressure wound therapy - protects viscera, controls fluid, allows tissue recovery. 2) Progressive fascial advancement over days/weeks. 3) Later definitive closure (primary if edges approximate) or planned ventral hernia. Avoid tension closure of compromised tissue.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient 10 days post-mastectomy develops fluctuant swelling under the wound with minimal erythema and no fever. Aspiration yields 80ml of straw-colored fluid. What is the diagnosis and management?',
'Wound infection requiring antibiotics',
'Seroma - aspirate as needed; may require multiple aspirations or drain placement if recurrent',
'Hematoma requiring surgery',
'Abscess requiring I&D',
'Wound dehiscence',
'B',
'Post-mastectomy seroma: Very common (30-50%). Caused by lymphatic disruption and dead space. Presents as painless fluctuant swelling, straw-colored aspirate. Management: Serial aspiration (may need multiple), compression dressing, can place drain if very recurrent. Prevention: Closed suction drains, compression, sclerotherapy (controversial). Usually resolves but may take weeks.',
'medium', 'application'),

-- SURGICAL TECHNIQUES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon is performing a tension-free inguinal hernia repair with mesh. What is the most important principle to prevent mesh infection?',
'Prophylactic antibiotics for 7 days',
'Single dose prophylactic antibiotic within 60 minutes of incision, meticulous hemostasis, tissue handling, and sterile technique',
'No antibiotics needed',
'Post-operative antibiotics only',
'Antibiotic-soaked mesh',
'B',
'Mesh infection prevention: 1) Single dose prophylactic antibiotic (cefazolin) within 60 min of incision. 2) Meticulous hemostasis (hematoma = infection risk). 3) Careful tissue handling. 4) Proper skin preparation. 5) Avoid excessive mesh handling. 6) Adequate soft tissue coverage of mesh. Prolonged antibiotics do not reduce infection and increase resistance. Mesh infection is difficult to clear - prevention essential.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During laparoscopic surgery, the surgeon notices a small enterotomy created by the Veress needle during entry. The bowel appears otherwise healthy. What should be done?',
'Ignore if small',
'Repair the enterotomy - can be done laparoscopically if small and clean, or convert if needed; document in operative note',
'Always convert to open',
'Complete surgery then repair',
'No documentation needed',
'B',
'Iatrogenic enterotomy: Must be repaired to prevent peritonitis/fistula. Small clean injury: laparoscopic suture repair (intracorporeal or extracorporeal if mobile segment). Larger injury or multiple injuries: consider conversion. Use absorbable sutures, transverse closure. Thorough lavage. Document fully in operative note. Consider extended antibiotic coverage. Inform patient post-operatively.',
'medium', 'application'),

-- MONITORING AND ICU
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient in ICU is on mechanical ventilation with FiO2 0.6 and PaO2 70mmHg. What is the P/F ratio and what does it indicate?',
'P/F ratio 117 - normal oxygenation',
'P/F ratio 117 - indicates moderate ARDS if acute onset with bilateral infiltrates and not cardiogenic',
'P/F ratio 200 - mild hypoxemia',
'Cannot calculate',
'P/F ratio 300 - normal',
'B',
'P/F ratio (PaO2/FiO2): PaO2 70 / FiO2 0.6 = 116.7. Berlin definition of ARDS: Acute onset, bilateral infiltrates, not cardiogenic. Mild ARDS: P/F 200-300. Moderate ARDS: P/F 100-200. Severe ARDS: P/F less than 100. This patient has moderate ARDS. Management: Lung protective ventilation (low tidal volume 6ml/kg, limit plateau pressure less than 30), consider prone positioning if severe, treat underlying cause.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A ventilated patient has central venous catheter with CVP monitoring showing respiratory variation (swings with ventilation). The CVP reads 12 during inspiration and 8 during expiration on positive pressure ventilation. What is the "true" CVP?',
'The higher reading (12)',
'End-expiratory reading (8) - represents true intrathoracic pressure on positive pressure ventilation',
'The lower reading (8 but for wrong reason)',
'Average of readings (10)',
'Neither reading is valid',
'B',
'CVP interpretation: In positive pressure ventilation, intrathoracic pressure increases during inspiration, falsely elevating CVP reading. End-expiratory CVP (when ventilator not pushing) reflects true right atrial pressure. In spontaneous breathing, it is opposite - inspiration decreases intrathoracic pressure. Always read CVP at end-expiration for consistency and accuracy.',
'medium', 'application'),

-- NASOGASTRIC AND NUTRITION
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with prolonged ICU stay and failed NG feeding trials has been on TPN for 3 weeks. They now have return of bowel function. How should enteral feeding be reintroduced?',
'Stop TPN and start full enteral immediately',
'Gradually transition: start low-rate enteral, reduce TPN as enteral tolerated, monitor for refeeding syndrome',
'Continue TPN indefinitely',
'Oral diet immediately',
'No transition needed',
'B',
'TPN to enteral transition: Gradual transition reduces complications. Protocol: Start enteral at low rate (10-20ml/hr), advance as tolerated. Reduce TPN proportionally as enteral increases. Full transition may take 3-7 days. Monitor for refeeding syndrome (phosphate, potassium, magnesium - especially if malnourished). Monitor tolerance (aspirates, abdominal distension). Abrupt TPN cessation risks hypoglycemia.',
'medium', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'An ICU patient on enteral feeding via NG tube develops watery diarrhea with 8 bowel movements per day. C. difficile toxin is negative. What adjustments should be considered?',
'Stop enteral feeding completely',
'Review feed rate, consider continuous vs bolus, check for medications causing diarrhea (sorbitol-containing), consider fiber-containing formula',
'Only antidiarrheal medications',
'Switch to TPN immediately',
'Ignore and continue',
'B',
'Enteral feeding diarrhea: Common causes: Too rapid infusion, hyperosmolar feed, contaminated feed, medications (sorbitol-containing liquids, antibiotics, PPIs). Management: Slow rate, use continuous rather than bolus, fiber-containing formula, review medications, rule out C. diff and other infections. Antidiarrheals may be used. Do not stop enteral nutrition for diarrhea alone - gut atrophy worsens with fasting.',
'medium', 'application'),

-- LEG ULCERS AND VASCULAR
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old diabetic with toe gangrene has ABPI 0.45. The foot is mottled with rest pain. What is the classification and management priority?',
'Chronic venous insufficiency',
'Critical limb ischemia (CLI) - urgent vascular surgery referral for revascularization (endovascular or bypass) before amputation',
'Mild peripheral vascular disease',
'Neuropathic only',
'Conservative management only',
'B',
'Critical limb ischemia (CLI): Rest pain, ulceration, or gangrene with ABPI less than 0.5 or toe pressure less than 30mmHg. Life and limb threatening. Management: Urgent vascular referral (within 2 weeks, sooner if gangrene spreading). Revascularization (endovascular preferred if feasible, bypass if not). Amputation level minimized if revascularization successful. Pain management, infection control while awaiting. 1-year mortality 25%, amputation rate 30% without revascularization.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a venous leg ulcer has had adequate compression for 12 weeks without healing. Venous duplex shows saphenofemoral junction incompetence. What additional treatment should be offered?',
'Continue compression only',
'Superficial venous intervention (endovenous ablation or surgery) - treating superficial reflux improves ulcer healing and reduces recurrence',
'Deep venous surgery',
'No further treatment available',
'Amputation consideration',
'B',
'Venous ulcer with superficial incompetence: ESCHAR and other trials show: treating superficial venous reflux (ablation, stripping) in addition to compression improves healing rates and significantly reduces ulcer recurrence. Interventions: Endovenous laser or radiofrequency ablation, foam sclerotherapy, surgery. Performed once ulcer clean or healed. Deep venous disease alone is not surgically correctable usually.',
'medium', 'application'),

-- TPR AND VITAL SIGNS
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A post-thyroidectomy patient suddenly develops stridor with respiratory distress. Neck swelling is visible. SpO2 is falling. What is the emergency action?',
'CT scan of neck',
'Open the wound at bedside immediately to evacuate hematoma and relieve tracheal compression',
'Give nebulizers',
'Call ENT for fiberoptic assessment',
'Intubation attempt first',
'B',
'Post-thyroidectomy hematoma: Surgical emergency. Expanding hematoma causes tracheal compression. Stridor indicates critical airway compromise. ACTION: Open wound at bedside immediately - remove skin clips/sutures, evacuate hematoma, relieve pressure. Do NOT wait for theatre or imaging. Prepare for difficult intubation. After decompression, return to theatre for hemostasis under controlled conditions. Every second counts.',
'hard', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A patient''s NEWS2 score has risen from 3 to 7 over 4 hours. The individual parameters are all moderately deranged but none in the "3" category. What is the significance and required response?',
'Score of 7 is not concerning',
'Aggregate score of 7 requires urgent senior clinical review and consideration for higher level of care',
'Only individual 3-point scores matter',
'Wait for further deterioration',
'Routine observation adequate',
'B',
'NEWS2 aggregate scoring: Total score is as important as individual extreme scores. Aggregate 7+ indicates clinical emergency requiring immediate senior review and consideration for ICU/critical care. Score 5-6 requires urgent response. The aggregate captures overall trajectory - multiple moderate derangements may be as serious as one severe. Trend (rising score) adds urgency. Escalate early.',
'medium', 'application'),

-- URETHRAL AND UROLOGICAL
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with recent radical prostatectomy develops urinary incontinence after catheter removal. This is expected to improve. What is the mechanism and timeframe?',
'Permanent nerve damage',
'Sphincter weakness after catheter removal; gradual recovery expected over 3-12 months with pelvic floor exercises',
'Bladder overactivity only',
'Immediate continence expected',
'No recovery possible',
'B',
'Post-prostatectomy incontinence: Expected after radical prostatectomy (30-50% at 3 months, improves to 5-10% at 1 year). Mechanism: Sphincter disruption, urethral shortening, denervation. Management: Pelvic floor muscle training (Kegels) starting pre-operatively and continuing post-operatively. Most recover adequate continence by 12 months. Persistent severe incontinence may need artificial urinary sphincter.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient develops acute kidney injury after surgery. Post-renal cause is suspected. Bladder scan shows residual volume of 800ml. What is the diagnosis and management?',
'Pre-renal AKI',
'Post-renal (obstructive) AKI from urinary retention - urgent catheterization; monitor for post-obstructive diuresis',
'Intrinsic renal disease',
'Normal post-operative finding',
'No intervention needed',
'B',
'Post-renal AKI: Obstruction to urinary outflow causes back-pressure on kidneys. Bladder residual greater than 300ml significant. Causes: Retention (BPH, post-operative, drugs), bilateral ureteric obstruction, blocked catheter. Management: Urgent drainage (urethral or suprapubic catheter). Monitor for post-obstructive diuresis (can be massive). Creatinine should improve within 24-48 hours if obstruction relieved promptly.',
'medium', 'application');
