-- ============================================================================
-- BATCH 46: Perioperative Medicine Clinical Scenarios
-- Topics: Mixed surgical topics with emphasis on perioperative care
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- GENERAL SURGERY PRINCIPLES
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old patient with recent MI (4 weeks ago) requires semi-urgent cholecystectomy for recurrent biliary colic. What is the cardiac risk assessment approach?',
'Surgery can proceed immediately',
'High cardiac risk - delay elective surgery 6 months if possible; if semi-urgent, cardiology optimization, consider beta-blockade, close monitoring',
'Cardiac evaluation unnecessary',
'Proceed without modification',
'Only aspirin needed',
'B',
'Cardiac risk stratification: Recent MI (less than 60 days) is high-risk for non-cardiac surgery (MACE rate 5-15%). Guidelines: Delay elective surgery 6 months post-MI if possible. For semi-urgent: Cardiology consultation, optimize medical therapy (beta-blockers, statins, aspirin balance with bleeding), consider stress testing, invasive monitoring perioperatively. Emergency surgery proceeds with optimization.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with severe COPD (FEV1 35% predicted) requires abdominal surgery. What perioperative respiratory optimizations reduce pulmonary complications?',
'No modifications possible',
'Preoperative respiratory physiotherapy, smoking cessation, bronchodilator optimization, regional anesthesia if feasible, early mobilization post-op',
'Intubation not possible in severe COPD',
'Postpone indefinitely',
'Only post-operative care matters',
'B',
'COPD surgical optimization: Preoperative - smoking cessation (2-8 weeks), optimize bronchodilators (LABA/LAMA, ICS if indicated), treat infections, chest physiotherapy, inspiratory muscle training. Intraoperative - regional/neuraxial if possible (avoid GA), minimize opioids, lung protective ventilation. Post-operative - early mobilization, incentive spirometry, good analgesia (enables deep breathing), NIV if needed.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with obstructive sleep apnea (OSA) on home CPAP undergoes laparoscopic surgery. Post-operatively, what special monitoring is required?',
'Standard ward care',
'Enhanced monitoring with pulse oximetry, use of home CPAP post-op, judicious opioid use, consider step-down unit',
'No CPAP needed post-op',
'Immediate ICU for all OSA',
'Only if very obese',
'B',
'OSA perioperative care: Increased risk of respiratory depression from opioids, upper airway collapse. Management: Resume home CPAP immediately post-op, continuous pulse oximetry (especially night 1-3), cautious opioid dosing (consider multimodal analgesia, avoid long-acting opioids), semi-upright positioning, step-down monitoring if moderate-severe OSA. CPAP compliance documentation.',
'medium', 'application'),

-- FLUID AND ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with acute pancreatitis has received aggressive fluid resuscitation. After 48 hours, the patient is edematous, oliguric, and has pulmonary edema. What is the likely cause and management?',
'Insufficient fluid resuscitation',
'Fluid overload from aggressive resuscitation - diuresis if stable, may need renal replacement therapy if oliguric and volume overloaded',
'Continue aggressive fluids',
'Normal post-pancreatitis state',
'Only chest X-ray needed',
'B',
'Third space fluid shift and recovery: Early pancreatitis causes massive capillary leak (fluid into retroperitoneum and peritoneal cavity). Aggressive resuscitation fills third space. As capillary leak resolves (48-72h), fluid mobilizes back to intravascular space = volume overload, pulmonary edema. Management: Diurese when stable, may need RRT if oliguric renal failure with volume overload.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A malnourished patient begins enteral feeding after prolonged starvation. Within 3 days, they develop confusion, muscle weakness, and arrhythmias. Labs show phosphate 0.4 mmol/L. What syndrome is this?',
'Feeding intolerance',
'Refeeding syndrome - life-threatening electrolyte shifts (phosphate, potassium, magnesium) when feeding malnourished patients',
'Allergic reaction to feed',
'Normal adaptation',
'Infection',
'B',
'Refeeding syndrome: Occurs when malnourished patients (starvation, anorexia, alcoholism) begin feeding. Mechanism: Carbohydrate intake triggers insulin, driving phosphate, potassium, magnesium into cells. Risk factors: BMI less than 16, greater than 10% weight loss, minimal intake greater than 10 days. Prevention: Start feeding slowly (10 kcal/kg), give thiamine before feeding, monitor and replace electrolytes. Can cause cardiac failure, arrhythmias, death.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient has K+ 2.5 mEq/L and Mg+ 0.5 mmol/L. Despite IV potassium replacement, the potassium remains low. What is the underlying issue?',
'Need more potassium only',
'Hypomagnesemia causes refractory hypokalemia - must correct magnesium first for potassium replacement to be effective',
'Potassium measurement error',
'Increased potassium excretion normal',
'No intervention needed',
'B',
'Magnesium-potassium relationship: Magnesium is required for Na-K-ATPase function (pumps K into cells) and for renal potassium retention. Hypomagnesemia causes increased renal K wasting. Hypokalemia is refractory until magnesium corrected. Treatment: IV magnesium sulfate 2g over 20 min, then continue replacement. Once Mg normalized, K replacement becomes effective.',
'hard', 'application'),

-- BLOOD TRANSFUSION
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient requires emergency transfusion but there is no time for crossmatch. What blood should be given and what is the risk?',
'Wait for crossmatch always',
'O negative uncrossmatched blood initially; switch to type-specific or crossmatched when available; risk of minor antibody reactions but life-saving',
'Any available blood',
'Synthetic blood substitutes only',
'No transfusion possible without crossmatch',
'B',
'Emergency uncrossmatched transfusion: O negative = universal donor (no A, B, D antigens). Risk: Minor antibody reactions to other antigens (may have antibodies from pregnancy/previous transfusion). Switch to type-specific blood ASAP (reduces O negative wastage). If greater than 2 units O neg given to Rh-positive patient, continue O neg (to avoid mixed-field reactions). Document uncrossmatched use.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient transfused 2 weeks ago develops jaundice with falling hemoglobin. Direct Coombs test is positive. What is the diagnosis?',
'Transfusion reaction prevented',
'Delayed hemolytic transfusion reaction - anamnestic response to previously undetected antibodies causing hemolysis days to weeks later',
'Unrelated liver disease',
'Normal post-transfusion finding',
'Acute hemolytic reaction',
'B',
'Delayed hemolytic transfusion reaction (DHTR): Occurs 3-14 days post-transfusion. Mechanism: Patient has low-titer antibodies not detected on crossmatch (previous sensitization). Transfusion causes anamnestic (memory) response, antibody titer rises, hemolyzes transfused cells. Presents: Jaundice, falling Hb, positive DAT, LDH elevated. Usually milder than acute reactions. Report to blood bank for future crossmatch.',
'hard', 'application'),

-- SHOCK MANAGEMENT
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient develops distributive shock from anaphylaxis during surgery. What is the first-line treatment?',
'IV antihistamines first',
'IM adrenaline (epinephrine) 0.5mg - first-line for anaphylaxis; may need IV if severe/refractory; remove trigger, airway support',
'IV steroids first',
'Fluid resuscitation only',
'Wait for symptoms to progress',
'B',
'Anaphylaxis management: IM adrenaline is first-line (0.5mg for adults, 0.3mg for children, anterolateral thigh). IV adrenaline for refractory cases (50mcg boluses). Also: Remove trigger (stop drug, tourniquet above injection site), high-flow oxygen, IV fluid bolus (1-2L), IV antihistamines (chlorpheniramine), IV steroids (hydrocortisone - prevent biphasic reaction). Position: supine with legs elevated unless respiratory distress.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with spinal cord injury at C5 level develops hypotension (BP 75/50) with bradycardia (HR 50). Skin is warm and dry below the injury. What is the type of shock and management?',
'Hypovolemic shock',
'Neurogenic shock - loss of sympathetic tone causing vasodilation and bradycardia; treat with fluids and vasopressor (norepinephrine)',
'Cardiogenic shock',
'Septic shock',
'Obstructive shock',
'B',
'Neurogenic shock: Spinal cord injury above T6 disrupts sympathetic outflow. Features: Hypotension, bradycardia (unopposed vagal tone), warm/dry skin (vasodilation), no tachycardia response. Different from spinal shock (loss of reflexes below injury). Treatment: Judicious fluids (overload risk), vasopressors (norepinephrine preferred - alpha agonist), atropine for severe bradycardia, maintain MAP greater than 85 for cord perfusion.',
'hard', 'application'),

-- SURGICAL WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with a heavily contaminated abdominal wound is on negative pressure wound therapy (NPWT). The dressing is changed every 3-4 days. What signs indicate NPWT is effective?',
'Wound getting larger',
'Granulation tissue formation, reduction in wound size, decreased exudate, reduced bacterial burden, healthy wound bed appearance',
'No visible change expected',
'Increased wound depth',
'Continued high exudate normal',
'B',
'NPWT effectiveness markers: 1) Granulation tissue - healthy red appearance. 2) Wound contraction - gradual size reduction. 3) Exudate reduction - initially high, decreases over days. 4) Reduced bacterial burden - less odor, healthier appearance. 5) Stable or improving surrounding skin. If no improvement after 2-4 dressing changes, reassess: underlying osteomyelitis, malignancy, infection, inadequate debridement.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic wound has undergone split-thickness skin grafting. At day 5, the graft appears dusky with serous fluid collection beneath. What has likely occurred?',
'Normal graft appearance',
'Graft failure - hematoma or seroma beneath graft preventing revascularization; may need evacuation and re-grafting',
'Successful take',
'Expected color change',
'No intervention possible',
'B',
'Skin graft failure: Causes - hematoma/seroma (most common), infection, shear forces, inadequate bed. Signs: Dusky/pale graft, failure to become pink (plasmatic imbibition should occur day 1-2, revascularization day 3-5), fluid collection. Management: Aspirate collection, may need return to theatre for washout. Prevention: Meticulous hemostasis, quilting sutures, NPWT over graft, immobilization.',
'hard', 'application'),

-- FRACTURE MANAGEMENT
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a closed femoral shaft fracture develops increasing thigh swelling, pain requiring escalating analgesia, and the circumference has increased 5cm compared to admission. What is the concern?',
'Normal fracture swelling',
'Thigh compartment syndrome or significant ongoing bleeding - urgent reassessment, may need fasciotomy or operative stabilization',
'Expected post-injury swelling',
'No intervention needed',
'Apply ice only',
'B',
'Femoral shaft fracture complications: Thigh can accommodate significant blood (2-3L). Progressive swelling may indicate: ongoing bleeding (may need urgent fixation), or thigh compartment syndrome (rare but catastrophic). Assessment: Pain on passive stretch, tense compartments, circumference increase, hemodynamic status. Management: May need urgent operative fixation to control bleeding, rarely fasciotomy for compartment syndrome.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with ankle fracture has had cast application. 24 hours later, they report severe pain not relieved by elevation and analgesia, with paresthesias in the foot. What must be done immediately?',
'Continue current analgesia',
'Split cast down to skin immediately - suspected compartment syndrome or cast too tight; reassess after splitting',
'Apply more padding',
'Wait and observe',
'Increase opioid dose',
'B',
'Tight cast or compartment syndrome: Pain disproportionate, paresthesias = warning signs. IMMEDIATE action: Split cast completely down to skin on both sides (includes underlying padding). Elevate. Reassess in 30 minutes. If symptoms resolve = cast was too tight. If symptoms persist after complete cast removal = true compartment syndrome, needs urgent fasciotomy. Never ignore increasing pain in a casted limb.',
'medium', 'application'),

-- INTRAOPERATIVE MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During a long surgery, the patient develops hypothermia (35°C). What are the consequences and prevention strategies?',
'Hypothermia is beneficial during surgery',
'Increased bleeding (impaired coagulation), increased wound infection, prolonged recovery, cardiac events - prevent with forced air warming, warm fluids, increase ambient temperature',
'No significant consequences',
'Only comfort issue',
'Improves surgical conditions',
'B',
'Perioperative hypothermia: Consequences: Coagulopathy (platelet dysfunction, enzyme inhibition), increased wound infection (vasoconstriction, impaired immunity), prolonged drug metabolism, cardiac morbidity, shivering (increases O2 consumption), patient discomfort. Prevention: Pre-warming, forced air warming blankets, fluid warmers, increase theatre temperature, cover exposed areas, humidified warm gases.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient under general anesthesia has BIS (bispectral index) monitoring showing a value of 75. What does this indicate about anesthetic depth?',
'Adequate depth of anesthesia',
'Light anesthesia - risk of awareness; target BIS 40-60 for general anesthesia; deepen anesthesia',
'Too deep anesthesia',
'BIS values are irrelevant',
'Patient is awake',
'B',
'BIS monitoring: Processed EEG indicating depth of anesthesia. Range: 100 = fully awake, 0 = isoelectric EEG. Targets: General anesthesia 40-60. BIS 70-80 = light sedation. BIS greater than 60 during GA = risk of awareness. BIS less than 40 = very deep, may indicate burst suppression. Adjust anesthetic accordingly. Not a substitute for clinical signs but helps prevent awareness.',
'medium', 'application'),

-- CPR AND EMERGENCY
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient in the ward develops PEA arrest. ETCO2 during CPR is very low (less than 10 mmHg) despite good quality compressions. What should be considered?',
'ETCO2 not relevant in PEA',
'Consider massive PE, tension pneumothorax, or cardiac tamponade - obstructive causes have very low ETCO2 as minimal blood reaches lungs despite compressions',
'CPR technique is wrong',
'Equipment malfunction',
'Normal finding in PEA',
'B',
'Very low ETCO2 during CPR: ETCO2 reflects pulmonary blood flow. Adequate compressions on a viable heart should produce ETCO2 greater than 10-20. Persistently low ETCO2 suggests: Obstructive causes (PE, tamponade, tension pneumothorax) - blood cannot reach lungs despite compression. Also consider: Prolonged arrest with metabolic failure, very poor prognosis. Treat obstructive causes urgently - needle decompression, thrombolysis, pericardiocentesis.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During resuscitation, a patient has ROSC but remains deeply comatose (GCS 3). What neuroprognostication strategy should be followed?',
'Immediately assess prognosis',
'Defer neuroprognostication for minimum 72 hours after normothermia; use multimodal assessment; do not withdraw based on single test',
'Withdraw care if GCS 3 at ROSC',
'CT brain immediately determines prognosis',
'EEG alone is definitive',
'B',
'Post-cardiac arrest neuroprognostication: Do NOT prognosticate too early. Minimum 72 hours after achieving normothermia (longer if sedation, hypothermia). Use MULTIMODAL assessment: Clinical examination (pupils, motor response), EEG, somatosensory evoked potentials (SSEPs), neuroimaging (CT/MRI), serum biomarkers (NSE). No single test is 100% predictive. Confounders: sedation, hypothermia, organ failure.',
'hard', 'application'),

-- ABDOMINAL INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A surgeon is planning a laparotomy in a patient with multiple previous abdominal surgeries and a large ventral hernia. What approach minimizes complications?',
'Standard midline through hernia',
'Preoperative planning with CT, consider component separation, may need staged approach, enter through virgin tissue if possible, plastic surgery input for complex reconstruction',
'Avoid all surgery',
'Simple mesh repair only',
'Open approach never possible',
'B',
'Complex abdominal wall surgery: Preoperative CT for planning (hernia contents, defect size, loss of domain). Options: Enter through virgin territory if possible, component separation technique for large defects, may need biologic mesh if contaminated, consider staged approach (first operation for pathology, later for hernia). Multidisciplinary approach (general surgery, plastic surgery). Preoperative optimization (weight loss, smoking cessation).',
'hard', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient requires urgent laparotomy for bowel obstruction. They have a stoma (ileostomy) on the right side. What incision considerations apply?',
'Incision through stoma site',
'Avoid incision near stoma (contamination, disruption of stoma blood supply) - use midline or contralateral approach if possible',
'Any incision acceptable',
'Stoma irrelevant to incision choice',
'Must always go through stoma',
'B',
'Incision planning with existing stoma: Avoid incising near stoma - risk of contamination (especially if stoma needs revision), disruption of stoma blood supply, difficult stoma management post-op. Use midline (away from stoma) or contralateral approach. If stoma needs revision, plan for new site. Stoma marking by stoma nurse pre-operatively for any potential new stoma.',
'medium', 'application');
