-- ============================================================================
-- BATCH 47: Advanced Trauma and Surgical Emergencies
-- Topics: Trauma care, emergency surgery, critical decision-making
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- TRAUMA AND SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has a grade IV liver laceration with active bleeding seen on CT. Despite 4 units PRBCs and 4 units FFP, BP remains 85/55 and HR 125. What is the management approach?',
'Continue conservative management',
'Damage control laparotomy with hepatic packing - hemorrhage control is priority, definitive repair later when physiology corrected',
'Wait for angioembolization',
'More blood products only',
'CT-guided drainage',
'B',
'Damage control surgery for liver trauma: Unstable patient with ongoing hemorrhage requires surgical control. Technique: Pringle maneuver (occlude hepatoduodenal ligament), perihepatic packing (control venous bleeding), temporary closure. Return to ICU for resuscitation (correct coagulopathy, hypothermia, acidosis). Relook laparotomy 24-48h for pack removal and definitive repair. Angioembolization may be adjunct but not for hemodynamic instability.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with penetrating chest trauma has Beck triad: hypotension, distended neck veins, and muffled heart sounds. Pulse pressure is narrow. What is the diagnosis and urgent intervention?',
'Tension pneumothorax',
'Cardiac tamponade - emergency pericardiocentesis or thoracotomy for decompression',
'Hemothorax only',
'Cardiogenic shock from contusion',
'Pulmonary contusion',
'B',
'Cardiac tamponade: Beck triad (hypotension, JVD, muffled heart sounds), pulsus paradoxus (greater than 10mmHg BP drop on inspiration), narrow pulse pressure, electrical alternans on ECG. Pathophysiology: Blood in pericardium restricts diastolic filling. Management: EMERGENCY pericardiocentesis (subxiphoid approach, 15-20ml may be life-saving), or emergency thoracotomy. FAST shows pericardial fluid.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with blunt abdominal trauma has CT showing grade III splenic laceration with contained hematoma. Hemodynamics are stable (BP 110/70, HR 95). What is the management?',
'Immediate splenectomy',
'Non-operative management with close monitoring - serial hemoglobin, repeat imaging, ICU/HDU admission, interventional radiology on standby',
'Conservative management on ward',
'Discharge with follow-up',
'Laparotomy for all splenic injuries',
'B',
'Non-operative management (NOM) of splenic injury: Selected hemodynamically stable patients. Requirements: ICU/HDU monitoring, serial examination and hemoglobin, CT-defined injury (grade I-III most suitable), interventional radiology available for angioembolization if needed, operating theatre available. Success rate greater than 80% for low-grade injuries. Failure = hemodynamic instability, dropping Hb, peritonitis → laparotomy.',
'hard', 'application'),

-- BLOOD CONSERVATION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing coronary artery bypass surgery has cell salvage running. During CPB, heparin is given. How is the salvaged blood processed before reinfusion?',
'Reinfuse directly without processing',
'Wash and concentrate the blood - removes heparin, hemolyzed cells, activated clotting factors, and debris before reinfusion',
'Add more heparin before reinfusion',
'Discard all blood during CPB',
'No processing needed',
'B',
'Cell salvage processing: Collected blood is anticoagulated, then centrifuged to separate RBCs, which are washed with saline. Washing removes: free hemoglobin, activated clotting factors, heparin (important in cardiac surgery), debris, fat globules. Resulting product: concentrated RBCs (Hct 50-80%) in saline. Does not contain plasma proteins, clotting factors, or platelets - these need separate replacement if needed.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'An orthopedic surgeon uses intraoperative tranexamic acid during total hip replacement. At what timing is TXA most effective?',
'Post-operative only',
'Preoperative or at induction, with optional repeat dose during surgery - prevents fibrinolysis from surgical activation',
'Only when bleeding observed',
'Not effective for orthopedic surgery',
'Only topical application',
'B',
'Tranexamic acid timing: Most effective when given before surgical insult (at induction or before tourniquet release). TXA inhibits fibrinolysis (blocks plasmin). Evidence: Reduces transfusion by 30-40% in orthopedic surgery. Dosing: 1g IV at induction, may repeat at 3 hours or at wound closure. Topical application also effective (wound irrigation). Contraindications: active thromboembolism, seizure history.',
'medium', 'application'),

-- FLUID AND ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient post bowel resection has Na+ 131, K+ 3.0, Cl- 92, HCO3- 35. Urine chloride is less than 10 mEq/L. What is the acid-base disturbance and likely cause?',
'Metabolic acidosis from bowel loss',
'Metabolic alkalosis from NG suction or vomiting - chloride-responsive; treat with saline and potassium',
'Respiratory acidosis',
'Normal post-operative values',
'Mixed disorder',
'B',
'Metabolic alkalosis: Elevated HCO3- with low Cl- and K+. Urine Cl- less than 20 = chloride-responsive (GI losses from NG suction, vomiting). Mechanism: HCl loss from stomach, volume contraction maintains alkalosis. Treatment: IV normal saline (chloride replacement), potassium replacement (hypokalemia maintains alkalosis), treat underlying cause (stop NG if possible, antiemetics). Correct over 24-48 hours.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient develops acute hyperkalemia (K+ 7.2) with ECG showing peaked T waves and widening QRS. Insulin and dextrose have been given. What additional treatment shifts potassium intracellularly?',
'IV calcium gluconate',
'Nebulized salbutamol (beta-2 agonist) - drives potassium into cells via Na-K-ATPase activation',
'IV bicarbonate only',
'Calcium resonium only',
'Loop diuretics only',
'B',
'Hyperkalemia treatment - K+ shifting: 1) Calcium gluconate = cardiac protection, NOT shift. 2) Insulin/dextrose = shifts K+ into cells (onset 15-30 min, lasts 4-6h). 3) Salbutamol (10-20mg nebulized) = shifts K+ via beta-2 stimulation (onset 15-30 min). 4) Bicarbonate = shifts K+ in acidosis setting. These are temporizing; potassium elimination needs: dialysis, kayexalate, loop diuretics. Use multiple shifting agents for severe hyperkalemia.',
'medium', 'application'),

-- BLOOD TRANSFUSION
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient receives platelet transfusion but develops rigors and fever 30 minutes later. There is no hemodynamic instability. What is the likely reaction and management?',
'Acute hemolytic reaction',
'Febrile non-hemolytic transfusion reaction (FNHTR) - stop transfusion, exclude hemolysis, give antipyretics; may resume different product',
'Anaphylaxis',
'Bacterial contamination confirmed',
'Normal response',
'B',
'Febrile non-hemolytic transfusion reaction: Most common transfusion reaction. Caused by cytokines in product or recipient antibodies to donor leukocytes. Features: Fever (greater than 1°C rise), rigors, no hemodynamic instability. Management: Stop transfusion, exclude hemolytic reaction (visual check, DAT), antipyretics. Prevention: Leukodepleted products (now routine), pre-medication for recurrent FNHTR.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has massive hemorrhage requiring more than 10 units PRBCs. What is the recommended ratio of blood products in massive transfusion protocols?',
'PRBCs only until labs available',
'Balanced transfusion: 1:1:1 ratio of PRBCs:FFP:Platelets - mimics whole blood, prevents dilutional coagulopathy',
'FFP only after specific tests',
'Platelets never needed',
'2:1:1 PRBCs to FFP to platelets',
'B',
'Massive transfusion protocol: Balanced resuscitation with 1:1:1 ratio (PRBCs:FFP:Platelets) shown to improve survival (PROPPR trial). Rationale: Avoids dilutional coagulopathy that occurs with crystalloid and PRBCs alone. Mimic whole blood replacement. Also includes: TXA, calcium (citrate toxicity), fibrinogen/cryoprecipitate if needed, warm products. Goal-directed with TEG/ROTEM if available.',
'medium', 'application'),

-- WOUNDS AND HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with a large abdominal wound is ready for definitive closure after serial debridements. The wound edges can be approximated with moderate tension. What technique reduces tension?',
'Close under maximum tension acceptable',
'Component separation technique (CST) - release of lateral abdominal wall muscles to medialize fascia and allow tension-free closure',
'Skin closure only',
'Permanent mesh bridging',
'Leave open indefinitely',
'B',
'Component separation technique: Allows advancement of abdominal wall fascia to close large defects. Technique: Release external oblique aponeurosis lateral to rectus sheath, allows 3-10cm advancement per side. Anterior or posterior approach. Used for: ventral hernia repair, abdominal wall reconstruction after trauma/sepsis. May combine with mesh reinforcement. Alternative: mesh bridging, but risks mesh exposure if skin cannot cover.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient has a clean but chronic foot wound that has stalled in healing. Granulation tissue is present but epithelialization is not progressing. What advanced therapy may stimulate healing?',
'Continue current dressings indefinitely',
'Consider negative pressure wound therapy, growth factors (PDGF), or bioengineered skin substitutes to stimulate healing',
'Surgical closure of chronic wound',
'No further options available',
'Amputation is only option',
'B',
'Stalled chronic wound management: When wound has granulation but fails to epithelialize: 1) NPWT - stimulates angiogenesis and granulation. 2) Growth factors (becaplermin/PDGF - for diabetic foot ulcers). 3) Bioengineered skin substitutes (Apligraf, Dermagraft). 4) Hyperbaric oxygen (improves tissue oxygenation). 5) Ensure offloading, glycemic control, vascular status optimized. Consider biopsy to exclude malignancy in chronic non-healing wounds.',
'hard', 'application'),

-- SUTURES AND INSTRUMENTS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon needs to anastomose small bowel in a patient with peritonitis. What suture technique and material are preferred for contaminated bowel anastomosis?',
'Single layer interrupted absorbable',
'Single or two-layer interrupted or continuous with absorbable suture (PDS, Vicryl) - interrupted may be safer in contaminated field',
'Permanent suture for all bowel',
'Stapled only',
'No anastomosis possible if contaminated',
'B',
'Bowel anastomosis in contamination: Hand-sewn often preferred over stapled in contaminated field (edematous bowel may not staple well). Technique: Single layer (simple, adequate) or two-layer (outer seromuscular, inner full-thickness). Interrupted sutures allow tissue to swell without ischemia. Material: Absorbable (Vicryl, PDS, Monocryl). Avoid permanent sutures (erosion, sinus formation).',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During surgery, the surgeon notices the diathermy is causing unintended burns away from the surgical site. What is the likely cause and solution?',
'Normal diathermy function',
'Faulty patient return electrode (grounding pad) - check pad adhesion, contact area, and positioning; replace if compromised',
'Increase diathermy power',
'Equipment is fine',
'Continue surgery regardless',
'B',
'Diathermy burns: Unintended burns suggest current finding alternative path to ground. Causes: Poor return electrode contact (dried gel, partial detachment, small contact area), patient touching metal, capacitive coupling. Prevention: Ensure full pad adhesion, place pad close to surgical site over large muscle mass, avoid bony prominences, check equipment before use. Stop and investigate any unusual burns.',
'medium', 'application'),

-- ABDOMINAL INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient has a high-output enterocutaneous fistula (ECF) draining 1500ml/day. Conservative management is planned initially. What nutritional route is preferred?',
'Enteral feeding through fistula',
'Parenteral nutrition initially to rest the bowel - may transition to enteral feeding distal to fistula if possible',
'Oral feeding as normal',
'No nutrition needed',
'Enteral feeding always contraindicated',
'B',
'ECF nutritional management: High-output fistula (greater than 500ml/day) usually requires TPN initially (bowel rest, reduce output). Assess if enteral feeding possible: tube feeding distal to fistula (if anatomically feasible), fistuloclysis (feeding into distal limb via fistula). As fistula output decreases and patient stabilizes, transition to enteral. Elemental/semi-elemental formulas may be better tolerated.',
'hard', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient with midline laparotomy develops incisional hernia 1 year post-operatively. They are asymptomatic with a reducible hernia. What are the options?',
'Emergency surgery required',
'Options include watchful waiting, abdominal binder, or elective surgical repair - discuss risk vs benefit with patient',
'Must repair all incisional hernias',
'No treatment available',
'Mesh is contraindicated',
'B',
'Asymptomatic incisional hernia: Not all require repair. Options: 1) Watchful waiting (if asymptomatic, low risk of complications). 2) Abdominal binder (symptomatic relief, does not prevent enlargement). 3) Elective repair (laparoscopic or open, usually with mesh). Decision factors: Symptoms, hernia size, patient comorbidities, surgical risk. Repair recommended if: symptomatic, enlarging, thin overlying skin, risk of incarceration.',
'medium', 'application'),

-- TPR AND MONITORING
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient develops fever of 38.5°C on day 1. They had an uncomplicated laparoscopic cholecystectomy. What is the most likely cause?',
'Wound infection',
'Inflammatory response to surgery (cytokine release) - fever in first 48 hours often non-infectious; evaluate but do not automatically treat with antibiotics',
'Anastomotic leak',
'UTI from catheterization',
'C. difficile colitis',
'B',
'Early post-operative fever: Day 0-2 fever usually inflammatory (surgical stress response, tissue trauma, blood transfusion reaction). Infectious causes become more common after day 3. Evaluation: Clinical assessment, wound inspection, urinalysis (if catheterized), chest exam. Do not reflexively give antibiotics for day 1 fever without source. Exception: Very high fever (greater than 39°C), hemodynamic instability, immunocompromised patient.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A patient in ICU has lactate of 5 mmol/L despite adequate MAP on vasopressors. What does persistent hyperlactatemia indicate in this context?',
'Adequate resuscitation achieved',
'Ongoing tissue hypoperfusion, mitochondrial dysfunction, or inadequate source control - need to address underlying cause, lactate clearance is prognostic',
'Normal ICU finding',
'Stop measuring lactate',
'Only liver dysfunction',
'B',
'Persistent hyperlactatemia: Lactate is product of anaerobic metabolism. Causes in ICU: Tissue hypoperfusion (most common), mitochondrial dysfunction (sepsis), regional ischemia (mesenteric), liver failure (reduced clearance), medications (metformin, linezolid). Lactate clearance (greater than 10% decrease per 2 hours) is prognostic marker. If not clearing: reassess perfusion, source control, regional ischemia.',
'hard', 'application'),

-- URETHRAL CATHETERIZATION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient develops catheter-associated UTI with sepsis. The catheter has been in place for 2 weeks. What is the management regarding the catheter?',
'Leave catheter and treat with antibiotics only',
'Remove or replace catheter as part of source control - infected catheter biofilm harbors bacteria; obtain cultures from new catheter',
'Catheter change makes no difference',
'Continuous bladder irrigation',
'Suprapubic always required',
'B',
'CAUTI with sepsis: Infected catheter acts as nidus. Biofilm on catheter protects bacteria from antibiotics. Management: Remove or replace catheter (source control). Obtain urine culture from new catheter. IV antibiotics (empiric then targeted). If catheter still needed, replace after 24-48h of antibiotics in severe infection. Prevention: Remove catheter as soon as not needed, aseptic insertion, daily review of necessity.',
'medium', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with chronic venous ulcer develops squamous cell carcinoma arising within the ulcer (Marjolin ulcer). What is the appropriate management?',
'Continue wound dressings',
'Wide local excision with adequate margins, lymph node assessment, may need skin grafting - Marjolin ulcers are aggressive',
'Topical chemotherapy only',
'Observation',
'Compression therapy will cure',
'B',
'Marjolin ulcer: SCC arising in chronic wound (usually greater than 10-20 years). Features: Raised edges, increased pain, change in appearance, failure to heal, bleeding. More aggressive than primary SCC (higher local recurrence, metastasis). Management: Biopsy to confirm, wide local excision (1-2cm margins), sentinel lymph node biopsy or lymph node dissection if indicated, reconstruction (graft or flap). May need amputation for extensive disease.',
'hard', 'application'),

-- NASOGASTRIC TUBES
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with small bowel obstruction has NG tube placed for decompression. Output is 1.5L on first day. The team questions whether a long intestinal tube would be more effective. What is the evidence?',
'Long tube always superior',
'Long intestinal tubes (e.g., Miller-Abbott) not proven superior to NG tubes for decompression; NG tubes are simpler and equally effective',
'NG tubes contraindicated in SBO',
'Must use long tube',
'Neither is effective',
'B',
'NG vs long intestinal tubes: Long tubes (Miller-Abbott, Cantor) were thought to decompress small bowel better than NG tubes. However, RCTs show no significant benefit of long tubes over NG tubes for resolution of obstruction or need for surgery. NG tubes are simpler to place, less patient discomfort. Long tubes rarely used now. Main role potentially for repeated obstruction without clear need for surgery.',
'medium', 'application'),

-- INTRAOPERATIVE MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, arterial blood gas shows pH 7.25, PaCO2 50, HCO3 21, base excess -5, lactate 4. What is the acid-base interpretation?',
'Pure metabolic acidosis',
'Mixed respiratory and metabolic acidosis - hypercarbia plus elevated lactate/low base excess indicate both components',
'Pure respiratory acidosis',
'Metabolic alkalosis',
'Normal values',
'B',
'Mixed acidosis interpretation: pH low (acidemia). PaCO2 50 (elevated - respiratory acidosis). HCO3 21 (low - metabolic acidosis). Base excess -5 (negative - metabolic acidosis). Lactate 4 (elevated - tissue hypoperfusion/anaerobic metabolism). This patient has both hypoventilation (respiratory component) and tissue hypoperfusion (metabolic component). Management: Improve ventilation, assess perfusion and resuscitate.',
'hard', 'application');
