-- ============================================================================
-- BATCH 49: Clinical Judgment and Management Scenarios
-- Topics: Integrated clinical decision-making across surgical specialties
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- SHOCK AND RESUSCITATION
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has ongoing hemorrhage. Lactate is 6 mmol/L, pH 7.15, base deficit -12. The surgical team is controlling bleeding. What resuscitation targets indicate adequate tissue perfusion?',
'MAP greater than 65 alone is adequate',
'Lactate clearance greater than 10% per 2 hours, normalizing pH and base deficit, urine output, improving mental status - multiparameter assessment',
'Lactate measurement not useful',
'Only blood pressure matters',
'Wait for bleeding to completely stop',
'B',
'Resuscitation endpoints: Single parameters inadequate. Targets: Lactate clearance greater than 10% per 2 hours (best predictor of survival), base deficit improving toward normal, urine output greater than 0.5ml/kg/hr, MAP greater than 65, resolving coagulopathy, improving mental status, decreasing vasopressor requirements. Persistent hyperlactatemia despite controlled bleeding = ongoing tissue hypoperfusion, inadequate resuscitation.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient with known heart failure develops septic shock from cholangitis. Central venous pressure is 16 mmHg (elevated). Should further fluid resuscitation be given?',
'Give large fluid bolus regardless',
'Assess fluid responsiveness with dynamic measures (PLR, PPV) rather than relying on static CVP - elevated CVP does not preclude fluid responsiveness',
'Stop all fluids immediately',
'CVP of 16 means well-resuscitated',
'Give vasopressors only',
'B',
'CVP limitations: Static measure, poor predictor of fluid responsiveness. Elevated CVP may occur with: RV failure, PE, tamponade, tricuspid disease, or simply well-filled circulation. Dynamic measures better: Passive leg raise with cardiac output monitoring (PLR - best if arrhythmia/spontaneously breathing), pulse pressure variation (PPV - if ventilated, regular rhythm), stroke volume variation (SVV). Give fluid if responsive, vasopressors if not.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient refuses blood transfusion on religious grounds. Hemoglobin drops to 5 g/dL after emergency surgery with ongoing minor oozing. What optimization strategies maximize oxygen delivery?',
'Nothing can be done',
'Maximize oxygen delivery: high FiO2, consider hyperbaric oxygen, optimize cardiac output, minimize oxygen consumption (sedation, paralysis, normothermia, pain control)',
'Transfuse without consent',
'Discharge patient',
'Standard care only',
'B',
'Profound anemia without transfusion: Maximize remaining O2 delivery. Strategies: 1) High FiO2 (dissolves more O2 in plasma). 2) Hyperbaric oxygen if available (increases dissolved O2). 3) Optimize cardiac output (fluid, inotropes). 4) Minimize O2 consumption (sedation, paralysis, control fever, pain). 5) EPO + IV iron (takes days but helps recovery). 6) Meticulous hemostasis for ongoing ooze. 7) Accept lower Hb thresholds. Human physiology tolerates profound anemia if compensated.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with sickle cell disease develops acute chest syndrome. Current Hb is 6.5 g/dL with HbS 65%. What transfusion strategy is indicated?',
'Simple transfusion to Hb 12 g/dL',
'Exchange transfusion to reduce HbS percentage below 30% while maintaining Hb less than 10-11 to avoid hyperviscosity',
'No transfusion in sickle cell',
'Only crystalloid resuscitation',
'Whole blood transfusion',
'B',
'Acute chest syndrome transfusion: Exchange transfusion preferred over simple transfusion. Goals: Reduce HbS less than 30%, increase HbA (normal Hb), keep total Hb less than 10-11 g/dL (avoid hyperviscosity). Exchange removes sickle cells while adding normal RBCs. Simple transfusion increases total Hb but also increases viscosity without removing sickle cells. Automated erythrocytapheresis most efficient.',
'hard', 'application'),

-- BLOOD CONSERVATION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A hospital is implementing a Patient Blood Management (PBM) program. What are the three pillars of PBM?',
'Transfuse more blood, use more products, faster transfusion',
'Optimize patient''s own blood (treat anemia preoperatively), minimize blood loss (surgical and iatrogenic), harness and optimize physiological reserve of anemia',
'Only use cell salvage',
'Eliminate all transfusion',
'Use autologous donation only',
'B',
'Patient Blood Management pillars: 1) Optimize patient''s own blood - diagnose and treat anemia preoperatively (IV iron, EPO), optimize hemostasis. 2) Minimize blood loss - meticulous surgery, TXA, cell salvage, avoid unnecessary phlebotomy. 3) Harness physiological reserve - tolerate lower Hb thresholds (7 g/dL in most patients), optimize O2 delivery (cardiac output, oxygenation). Evidence-based approach improves outcomes and reduces transfusion.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient with hemophilia A requires emergency appendectomy. Factor VIII level is 15% (low). What perioperative factor management is required?',
'Surgery contraindicated in hemophilia',
'Factor VIII replacement to achieve level greater than 80-100% for major surgery, maintain greater than 50% until wound healed, involve hematology',
'No factor replacement needed',
'Only FFP required',
'Platelets will compensate',
'B',
'Hemophilia A surgical management: Factor VIII deficiency. Target levels: Major surgery - factor level greater than 80-100% at time of surgery, maintain greater than 50% for 10-14 days. Minor surgery - greater than 50%. Give bolus pre-op then continuous infusion or regular boluses. Dose calculated based on weight and target level. Involve hematology early. Consider DDAVP for mild hemophilia A. Avoid IM injections, NSAIDs.',
'hard', 'application'),

-- FLUID AND ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has Na+ 155 mEq/L, urine output 50ml/hr, urine specific gravity 1.025 (concentrated). What is the likely cause of hypernatremia?',
'Diabetes insipidus',
'Inadequate free water administration - the concentrated urine shows intact ADH response; patient needs more free water intake/administration',
'Salt poisoning',
'Excess IV normal saline',
'No intervention needed',
'B',
'Hypernatremia with concentrated urine: Intact ADH response (kidneys concentrating urine appropriately) but insufficient free water to match losses. Common in: Post-operative patients with restricted oral intake, sedated/intubated patients without adequate free water in IV fluids, elderly with reduced thirst. Treatment: Free water replacement (D5W, or enteral water if feeding). Calculate free water deficit. Correct slowly (less than 10 mEq/L per 24 hours).',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient has hyperchloremic metabolic acidosis after receiving large volumes of normal saline. What is the mechanism and how can it be avoided?',
'Normal saline is neutral',
'Normal saline has supraphysiological chloride (154 mEq/L vs plasma 100 mEq/L) causing dilutional acidosis; use balanced crystalloids (Hartmann/PlasmaLyte) instead',
'Acidosis is beneficial',
'All IV fluids cause acidosis',
'Only occurs with blood transfusion',
'B',
'Hyperchloremic acidosis from NS: Normal saline contains 154 mEq/L chloride (plasma ~100). Large volume resuscitation causes hyperchloremia, dilutes bicarbonate, causes non-anion gap metabolic acidosis. Also associated with AKI (chloride causes renal vasoconstriction). Prevention: Use balanced crystalloids (Hartmann/Ringer Lactate, PlasmaLyte) with chloride ~100 mEq/L and buffer (lactate or acetate). Evidence (SPLIT, SMART trials) favors balanced crystalloids.',
'medium', 'application'),

-- SURGICAL WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with a large sacral pressure ulcer has exposed bone at the wound base. NPWT has achieved good granulation tissue. What is the next reconstructive step?',
'Skin graft directly over exposed bone',
'Flap coverage needed (muscle or fasciocutaneous flap) - skin graft will not take over bone without periosteum',
'Continue NPWT indefinitely',
'Primary closure',
'Leave to heal by secondary intention',
'B',
'Pressure ulcer reconstruction: Exposed bone without periosteum = no graft bed. Split-thickness skin graft will not take. Options: 1) Muscle flap (provides bulk, good blood supply, covers bone) - gluteus maximus, hamstring advancement. 2) Fasciocutaneous flaps (perforator-based). Principles: Debride to healthy tissue, manage infection, optimize nutrition, relieve pressure post-operatively (special mattress, positioning). Recurrence high if pressure not addressed.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has a large soft tissue defect over the tibia with exposed bone and no periosteum. The defect is 15 x 8 cm. What reconstructive approach is needed?',
'Skin graft adequate',
'Free tissue transfer (free flap) - large defect over exposed bone requires vascularized tissue coverage; gastrocnemius or free flap depending on defect size and location',
'Secondary intention healing',
'Local random flaps',
'Leave exposed bone',
'B',
'Tibial defect reconstruction: Exposed bone without periosteum requires vascularized tissue. Reconstructive ladder: Proximal third tibia - gastrocnemius muscle flap. Middle third - soleus muscle flap. Distal third - free tissue transfer (no local muscle flaps available). Large defect (15cm) likely exceeds local flap coverage. Free flaps: ALT, latissimus, gracilis. Cover within 72 hours if possible to reduce infection/osteomyelitis.',
'hard', 'application'),

-- INSTRUMENTS AND TECHNIQUES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon is performing a bowel resection and needs to choose between stapled and hand-sewn anastomosis. What factors influence this decision?',
'Stapled always superior',
'Both comparable outcomes; stapled faster but more expensive; hand-sewn may be better for edematous/thickened bowel, small diameter lumen, or ischemic tissue',
'Hand-sewn always superior',
'Only stapled for large bowel',
'Only hand-sewn for small bowel',
'B',
'Stapled vs hand-sewn anastomosis: Meta-analyses show comparable leak rates. Stapled: Faster, standardized technique, good for deep pelvis (circular stapler). Hand-sewn: Cheaper, more adaptable, better for size discrepancy, edematous/inflamed bowel (staples may not fire properly), very small lumen, ischemic tissue margins. Surgeon experience important. Either technique acceptable if properly performed.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'During open surgery, the surgeon needs to rapidly control bleeding from a major vessel. What is the order of hemostasis attempts?',
'Clamp first, assess later',
'Apply direct pressure first, improve visualization, then precise control with clamps or sutures; avoid blind clamping',
'Use diathermy on major vessels',
'Tourniquet application first',
'Suture without pressure first',
'B',
'Hemorrhage control sequence: 1) Apply direct pressure immediately (buys time, controls bleeding). 2) Improve exposure and visualization (suction, assistance, better lighting). 3) Identify bleeding source precisely. 4) Controlled vascular clamp or finger occlusion. 5) Definitive repair (suture, ligation, patch). Avoid: Blind clamping (damages adjacent structures, especially ureters, nerves), panic-driven attempts. Pack if needed to temporize.',
'medium', 'application'),

-- ABDOMINAL INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient develops "burst abdomen" with complete fascial dehiscence and evisceration on day 7. After emergency repair, what factors predict future incisional hernia?',
'All patients develop hernia',
'Emergency closure, contamination, inadequate suture length to wound length ratio, patient factors (obesity, smoking, steroids, malnutrition) predict higher hernia rates',
'Suture material determines all outcomes',
'No factors predict hernia',
'Mesh prevents all hernias',
'B',
'Incisional hernia risk factors: Patient - obesity, smoking, malnutrition, steroids, COPD, diabetes, connective tissue disorders. Technical - emergency surgery, contamination, inadequate suture length (should be 4:1 ratio), wound infection, previous dehiscence. The burst abdomen itself indicates failed healing. Higher hernia rate expected even after repair. May benefit from prophylactic mesh in future if clean field.',
'medium', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient with a large incisional hernia has "loss of domain" - the herniated viscera will not reduce into the abdomen. What preoperative preparation may help?',
'Operate without preparation',
'Preoperative progressive pneumoperitoneum (PPP) or botulinum toxin to lateral abdominal muscles to increase abdominal capacity before repair',
'Nothing can be done',
'Delay indefinitely',
'Diet alone sufficient',
'B',
'Loss of domain management: Abdominal contents chronically outside abdomen, cavity has contracted. Replacing viscera can cause abdominal compartment syndrome. Preparation options: 1) Progressive pneumoperitoneum - insufflate air into peritoneum pre-op over weeks to expand cavity. 2) Botulinum toxin injection to lateral abdominal muscles (relaxes, allows elongation). 3) Component separation at surgery. May need staged repair or mesh bridging with planned ventral hernia.',
'hard', 'application'),

-- TPR CHART AND MONITORING
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has HR 105, RR 22, BP 125/80, temp 37.8°C, SpO2 94% on room air. Each parameter is only mildly abnormal. Should there be concern?',
'Each parameter normal so patient is fine',
'Pattern of multiple mild derangements suggests early deterioration - systemic inflammatory response or early sepsis; investigate and monitor closely',
'Wait for more obvious abnormality',
'Only single severely abnormal value matters',
'Discharge is appropriate',
'B',
'Subtle deterioration pattern: Individual parameters may be "borderline normal" but the combination suggests physiological stress. Tachycardia + tachypnea + low-grade fever + borderline hypoxia = concerning pattern. Could indicate: Developing sepsis, anastomotic leak, PE, hemorrhage. Early warning scores (NEWS) aggregate these findings. Trends are key - if progressing, investigate cause. Senior review, consider sepsis screen, imaging.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A patient''s urine output has been less than 20ml/hr for 4 hours despite adequate blood pressure. What should be considered and how should this be investigated?',
'Normal for post-operative patients',
'Oliguria requires investigation - check catheter patency, bladder scan if no catheter, assess volume status, check renal function; may indicate AKI',
'Increase IV fluids empirically',
'Diuretics immediately',
'Ignore if BP normal',
'B',
'Oliguria investigation: Urine output less than 0.5 ml/kg/hr for greater than 6 hours = AKI criteria. Causes: Pre-renal (hypovolemia, hypotension), renal (ATN, nephrotoxins), post-renal (obstruction). Investigation: 1) Check catheter patent/correctly positioned. 2) Bladder scan if no catheter. 3) Assess volume status. 4) Check creatinine and electrolytes. 5) Review medications (nephrotoxins). 6) Consider fluid challenge if hypovolemic. Do not give diuretics without cause identified.',
'medium', 'application'),

-- URETHRAL CATHETERIZATION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient has had a urethral catheter for 5 days post-operatively. Surgery was uncomplicated, they are mobilizing, and there is no ongoing indication for the catheter. What is the recommended action?',
'Remove when patient requests',
'Remove catheter promptly - each day of unnecessary catheterization increases UTI risk; trial without catheter (TWOC)',
'Wait until discharge',
'Keep for convenience',
'Long-term catheter indicated',
'B',
'Catheter duration: Risk of CAUTI increases approximately 5% per day of catheterization. Remove as soon as no longer indicated. Indications to continue: urinary retention, accurate output monitoring critical, immobility with incontinence care issues, open sacral/perineal wounds. TWOC: Remove catheter, monitor for voiding, check residual. If retention, reassess cause and consider clean intermittent catheterization.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A male patient with known urethral stricture requires catheterization for urinary retention. Standard catheter will not pass. What are the options?',
'Force the catheter through',
'Options include: smaller catheter, coude tip catheter, suprapubic catheterization, or urology referral for flexible cystoscopy with guidewire-assisted passage',
'No catheterization possible',
'Large catheter more likely to pass',
'Wait for retention to resolve',
'B',
'Urethral stricture catheterization: Do NOT force catheter (causes false passage, bleeding, more scarring). Options: 1) Smaller caliber catheter (may pass through stricture). 2) Coude tip (angled tip for prostatic curve, may help). 3) Suprapubic catheterization (if trained, palpable bladder, no contraindications). 4) Urology referral for flexible cystoscopy with direct visualization and guidewire-assisted passage, or dilation. 5) Urethral dilation/stenting for recurrent stricture.',
'medium', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with mixed arterial-venous leg ulcer has ABPI of 0.6. Full compression is contraindicated. What therapeutic approach is appropriate?',
'Full four-layer compression',
'Optimize arterial supply first (vascular referral for possible intervention), then modified compression if ABPI improves or under specialist supervision',
'No treatment available',
'High compression acceptable',
'Amputation only option',
'B',
'Mixed arterial-venous ulcer: ABPI 0.5-0.8 = significant arterial component. Full compression (40 mmHg) may compromise arterial flow. Approach: 1) Vascular referral for possible revascularization. 2) If ABPI greater than 0.8 after intervention, full compression. 3) If ABPI 0.5-0.8 and intervention not possible, modified compression (23-30 mmHg) under specialist supervision. 4) ABPI less than 0.5 = compression contraindicated, arterial treatment priority.',
'hard', 'application'),

-- NASOGASTRIC TUBES
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A patient with small bowel obstruction has been managed conservatively with NG decompression for 72 hours. Obstruction has not resolved. What clinical and radiological features suggest need for surgery?',
'Continue conservative management indefinitely',
'Features suggesting strangulation or failed conservative management: fever, tachycardia, peritonitis, closed-loop obstruction on CT, free fluid, lack of improvement after 48-72 hours',
'All SBO needs immediate surgery',
'Only operate if complete obstruction',
'Surgery never indicated for adhesive SBO',
'B',
'SBO surgical indications: Absolute - peritonitis, irreducible hernia, complete obstruction, closed-loop. Relative - failure to improve after 48-72h of conservative management, CT signs of ischemia (mesenteric edema, reduced bowel wall enhancement, free fluid), fever/tachycardia suggesting strangulation. Water-soluble contrast (Gastrografin) has diagnostic and therapeutic value - if not in colon by 24h, surgery likely needed.',
'hard', 'application');
