-- ============================================================================
-- BATCH 50: Comprehensive Clinical Reasoning Scenarios
-- Topics: Advanced clinical decision-making across all Surgery 1 topics
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- GENERAL SURGERY AND PERIOPERATIVE CARE
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient on chronic opioid therapy for back pain requires elective surgery. Post-operative pain control is challenging despite standard doses. What approach is recommended?',
'Use standard opioid doses only',
'Continue baseline opioid requirement plus additional analgesia for surgical pain; multimodal approach; consider acute pain service involvement',
'Stop all opioids pre-operatively',
'Avoid all opioids post-operatively',
'Double standard doses',
'B',
'Opioid-tolerant patient pain management: Tolerance means baseline opioids do not provide surgical pain relief - they just prevent withdrawal. Approach: Continue baseline opioid dose (or equivalent IV), ADD analgesia for surgical pain. Multimodal analgesia essential: acetaminophen, NSAIDs, regional anesthesia/nerve blocks, ketamine, gabapentinoids. Involve acute pain service. PCA may be helpful. Doses often higher than opioid-naive patients.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with BMI 52 requires laparoscopic cholecystectomy. What perioperative considerations are specific to morbid obesity?',
'No special considerations',
'Airway difficult, positioning challenges, VTE prophylaxis dosing, pharmacokinetics altered, equipment weight limits, cardiopulmonary reserve reduced',
'Obesity is protective in surgery',
'Standard doses adequate',
'Shorter surgery always required',
'B',
'Morbid obesity perioperative considerations: Airway - difficult mask ventilation/intubation. Positioning - pressure areas, appropriate tables/equipment. VTE - higher risk, may need higher LMWH doses. Pharmacology - drug dosing complex (ideal vs total body weight). Cardiopulmonary - reduced reserve, OSA common. Wound - higher infection rate. Post-op - early mobilization, respiratory support, vigilance for DVT/PE.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with well-controlled HIV (undetectable viral load, CD4 600) requires surgery. What specific precautions are needed?',
'Surgery contraindicated in HIV',
'Universal precautions apply; well-controlled HIV not significantly increased risk; continue antiretrovirals; standard prophylaxis',
'Extreme isolation required',
'All staff must know HIV status',
'Different surgical instruments needed',
'B',
'HIV and surgery: Well-controlled HIV (undetectable viral load, CD4 greater than 200) has similar surgical outcomes to general population. Precautions: Universal/standard precautions (same as all patients). Continue antiretrovirals (drug interactions with some anesthetics). Standard antibiotic prophylaxis. No need for special instruments or isolation. Wound healing normal if disease controlled. Confidentiality maintains.',
'medium', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in septic shock from necrotizing fasciitis is on maximal vasopressors. The surgical team is called for debridement. Is the patient "too sick" for surgery?',
'Wait for vasopressor weaning',
'Source control is essential for survival - surgery needed despite hemodynamic instability; mortality approaches 100% without debridement',
'Stabilize fully first',
'Surgery will kill the patient',
'Medical management alone adequate',
'B',
'Necrotizing fasciitis: Surgical emergency. Source control (debridement) is essential for survival - no amount of antibiotics or vasopressors will resolve without removing necrotic tissue. "Too sick for surgery" often means "too sick NOT to operate." Operative debridement proceeds despite instability. May need multiple debridements. Delay in source control = certain death. Resuscitate concurrently with surgery.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with hemorrhagic shock has received damage control surgery with abdominal packing. In ICU, what targets guide ongoing resuscitation before return to theatre?',
'Normal vital signs only',
'Correct lethal triad: Temperature greater than 35°C, pH greater than 7.25, lactate clearing, INR less than 1.5; plan return to theatre when optimized',
'Wait indefinitely for normalization',
'No specific targets',
'Return immediately regardless of status',
'B',
'Damage control resuscitation targets: Lethal triad = hypothermia, acidosis, coagulopathy. Goals before return to theatre: Temperature greater than 35°C (ideally greater than 36°C), pH greater than 7.25 (base excess improving), coagulopathy corrected (INR less than 1.5, platelets greater than 50), lactate trending down. Typically return 24-48h for pack removal and definitive repair. Avoid prolonged open abdomen.',
'hard', 'application'),

-- BLOOD PRODUCTS AND TRANSFUSION
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient with autoimmune hemolytic anemia (AIHA) requires urgent transfusion. The blood bank reports difficulty crossmatching - all units show reactivity. What should be done?',
'No transfusion possible',
'Transfuse least incompatible units if clinically indicated - in AIHA with pan-reactive antibodies, perfect match impossible but transfusion may be life-saving',
'Wait for perfect match',
'Use type O negative only',
'Autoantibodies contraindicate transfusion',
'B',
'AIHA transfusion challenge: Autoantibodies react with all RBCs (including patient''s own), making crossmatch impossible. Approach: 1) Confirm autoantibody (not alloantibody). 2) Check for underlying alloantibodies. 3) If clinically needed, transfuse "least incompatible" units. 4) Transfused cells may hemolyze but may provide temporary oxygen-carrying benefit. 5) Treat underlying AIHA (steroids, immunosuppression). Blood bank and hematology involvement essential.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient develops circulatory overload after two units of blood (TACO). They are in respiratory distress with elevated JVP and pulmonary edema. What is the management?',
'Continue transfusion',
'Stop transfusion, sit patient upright, give IV diuretics (furosemide), may need respiratory support (NIV, intubation if severe)',
'TACO is same as TRALI',
'Adrenaline required',
'TACO is not serious',
'B',
'TACO (Transfusion-associated circulatory overload): Volume overload, not immunological. Risk factors: Elderly, cardiac/renal disease, rapid transfusion. Features: Dyspnea, hypertension, elevated JVP, pulmonary edema, elevated BNP. Management: Stop transfusion, upright position, oxygen, diuretics (furosemide). Prevention: Slow transfusion rate (1ml/kg/hr for at-risk patients), pre-transfusion diuretic. Distinguish from TRALI (TRALI has hypotension, no fluid overload).',
'medium', 'application'),

-- BLOOD CONSERVATION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient undergoing major spine surgery has acute normovolemic hemodilution (ANH) performed. Blood is removed and stored in the OR. When should this blood be reinfused?',
'At the end of surgery',
'Reinfuse in reverse order of collection (last collected first) when surgical bleeding slows or at end of surgery',
'Discard unused blood',
'Give during maximum bleeding',
'Only if patient requests',
'B',
'Acute normovolemic hemodilution: Whole blood collected at start of surgery, replaced with crystalloid/colloid. Stored at room temperature (maintains platelet function). Benefits: Blood lost during surgery is dilute (lower Hb loss per ml), fresh autologous blood reinfused with functional platelets and coagulation factors. Reinfuse in reverse order (last collected first = highest Hct), typically when bleeding controlled or at surgery end.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient with iron deficiency anemia (Hb 9.5, ferritin 8) is scheduled for major cancer surgery in 3 weeks. Oral iron has been prescribed. What is likely to happen?',
'Oral iron will correct anemia in 3 weeks',
'Oral iron unlikely to adequately correct Hb in 3 weeks - IV iron works faster and should be preferred for surgical optimization',
'No treatment needed for Hb 9.5',
'Transfusion before surgery preferred',
'Wait 6 months for oral iron effect',
'B',
'Iron replacement timing: Oral iron takes 2-3 months to replete stores and increase Hb (also GI side effects, poor compliance). IV iron (ferric carboxymaltose, iron sucrose) works within days to weeks. For surgical optimization with 3-week window, IV iron preferred. Single dose ferric carboxymaltose 1000mg can increase Hb 1-2 g/dL within 2-3 weeks. Reduces transfusion requirements.',
'medium', 'application'),

-- FLUID AND ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient post thyroidectomy develops perioral tingling, Chvostek sign, and QT prolongation on ECG. Calcium level is awaited. What is the immediate management?',
'Wait for calcium level',
'Give IV calcium gluconate empirically - symptomatic hypocalcemia is emergency; do not wait for lab confirmation',
'Oral calcium only',
'Check magnesium first',
'ECG changes are not concerning',
'B',
'Symptomatic hypocalcemia: Post-thyroidectomy (parathyroid injury) or other causes. Symptoms: Perioral tingling, muscle cramps, tetany, Chvostek sign, Trousseau sign, cardiac arrhythmias (QT prolongation). Management: IV calcium gluconate 10ml of 10% over 10 minutes (may repeat). Do NOT wait for lab confirmation if symptomatic. Continuous cardiac monitoring. Start oral calcium and calcitriol for maintenance. Check and replace magnesium.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient has Na+ 120 mEq/L, serum osmolality 250, urine osmolality 400, urine Na 55 mEq/L. They are clinically euvolemic. What is the diagnosis?',
'Hypovolemic hyponatremia',
'SIADH - euvolemic hypotonic hyponatremia with inappropriate urine concentration',
'Hypervolemic hyponatremia',
'Diabetes insipidus',
'Normal sodium for surgical patient',
'B',
'SIADH diagnosis: Low serum osmolality (hypotonic) + inappropriately concentrated urine (Osm greater than 100) + high urine sodium (greater than 40) + clinically euvolemic = SIADH. Causes: Post-operative (pain, nausea, drugs), CNS disorders, pulmonary disease, malignancy. Treatment: Fluid restriction (800-1000ml/day), treat cause. If severe/symptomatic: hypertonic saline carefully. Avoid rapid correction (ODS risk).',
'hard', 'application'),

-- SURGICAL WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with a venous leg ulcer treated with compression has healed. What is essential for preventing recurrence?',
'No further treatment needed',
'Long-term compression with stockings (Class 2), treat underlying venous disease if amenable, lifestyle modification',
'Compression only during active ulcer',
'Daily dressing changes indefinitely',
'Antibiotics permanently',
'B',
'Venous ulcer recurrence prevention: High recurrence rate (up to 70% at 5 years) without preventive measures. Essential: Long-term compression stockings (Class 2, 18-24 mmHg minimum), worn daily during waking hours, replace every 6 months. If superficial venous incompetence present, treat with ablation/surgery. Lifestyle: Elevation, exercise, weight management, skin care. Compliance with compression is key factor.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has a chronic wound being treated with silver dressings for 4 weeks. The wound is now clean but silver dressings are continued. Is this appropriate?',
'Silver should continue indefinitely',
'Prolonged silver use may delay healing (cytotoxic to healing cells) - transition to non-antimicrobial dressings once infection controlled',
'Silver has no adverse effects',
'Silver promotes epithelialization',
'Stop silver only when fully healed',
'B',
'Silver dressing duration: Silver is antimicrobial but also cytotoxic to keratinocytes and fibroblasts. Appropriate for infected wounds or high-risk colonized wounds. Once infection controlled and wound clean, transition to non-antimicrobial dressings (foams, hydrocolloids, etc.) to promote healing. Typically 2-4 weeks maximum. Reassess regularly for signs of infection requiring reinstitution of antimicrobials.',
'medium', 'application'),

-- SUTURES AND INSTRUMENTS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon is closing a clean-contaminated wound and must decide on closure technique. What evidence-based approach is recommended?',
'All clean-contaminated wounds should be left open',
'Most clean-contaminated wounds can be primarily closed; delayed primary closure or secondary intention for heavily contaminated wounds',
'Only staples for contaminated wounds',
'Drain all clean-contaminated wounds',
'No evidence guides this decision',
'B',
'Clean-contaminated wound closure: Definition - controlled entry into GI, respiratory, GU tract without significant contamination. SSI rate 3-11%. Can usually be primarily closed. Heavily contaminated or dirty wounds: Consider delayed primary closure (pack open, close day 4-5) or secondary intention. Evidence: Primary closure generally safe for appendectomy, bowel surgery if no gross spillage. Skin closure method (sutures vs staples) less important than wound classification.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A right-handed surgeon is suturing and notices their assistant consistently places instruments incorrectly in their hand. What is the proper technique for passing instruments?',
'Any passing technique acceptable',
'Pass instruments handle first, in correct orientation for use, with audible or visible cue; surgeon should be able to use without adjustment',
'Throw instruments on table',
'Sharp end first for quick use',
'Surgeon should pick up from table',
'B',
'Instrument passing technique: Safety and efficiency principles. Pass handle first (surgeon grasps working end). Correct orientation (needle holder with needle pointing appropriately). Audible cue (instrument snap) or visible cue (present to visual field). Surgeon receives without looking (keeps eyes on field). Scalpel passed handle first in neutral zone or via tray. Never pass sharp end first. Standardized practice reduces needlestick injuries.',
'easy', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient with osteoporotic vertebral compression fracture has failed conservative management. What minimally invasive options exist?',
'Only spinal fusion',
'Vertebroplasty or kyphoplasty - percutaneous cement injection to stabilize fracture and provide pain relief',
'No treatment available',
'Cast for vertebral fractures',
'Open surgery only',
'B',
'Vertebroplasty/kyphoplasty: Minimally invasive for painful vertebral compression fractures failing conservative treatment. Technique: Percutaneous needle into vertebral body, cement (PMMA) injection. Kyphoplasty: Balloon expansion before cement (may restore height). Evidence: Pain relief often rapid. Controversial - RCTs show mixed results vs sham. Risks: Cement leak, adjacent level fracture. Select patients with localized pain, recent fracture.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a tibial shaft fracture has definitive intramedullary nailing performed. At 6 months, there is no callus visible on X-ray and the fracture line persists. What is the classification and approach?',
'Normal healing at 6 months',
'Non-union (no progression over 3 months) - determine if hypertrophic (needs stability) or atrophic (needs biology); plan revision surgery',
'Wait another 6 months',
'Remove nail and cast',
'No intervention can help',
'B',
'Tibial non-union: No evidence of healing progression for 3+ months. Classification: Hypertrophic (elephant foot appearance - good biology, poor stability) - needs better fixation. Atrophic (no callus, sclerotic ends - poor biology) - needs bone graft. Management: Exchange nailing (reams canal, provides biology, new larger nail), dynamization (remove interlocking screws), bone grafting, plate fixation, BMP. Address risk factors (smoking, diabetes, infection).',
'hard', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient with known terminal malignancy with weeks prognosis develops cardiac arrest. CPR is started before anyone notes their DNAR status. What should happen?',
'Continue CPR indefinitely',
'Stop CPR when valid DNAR order confirmed - continuing is against patient wishes and potentially harmful',
'DNAR order can be ignored',
'Complete one cycle then stop',
'Continue until family arrives',
'B',
'DNAR and CPR: DNAR (Do Not Attempt Resuscitation) is patient or surrogate decision that CPR should not be performed. If CPR started before DNAR known, stop once valid order confirmed. Continuing CPR against known wishes violates autonomy and is futile/harmful in terminal disease. Verify order validity (documented, still applicable to current situation). Communication with family important but does not override valid DNAR.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During CPR for PEA arrest, ultrasound shows a dilated, hypokinetic right ventricle. What diagnosis is suggested and what intervention should be considered?',
'Normal finding in cardiac arrest',
'Massive pulmonary embolism likely - consider thrombolysis during CPR if PE suspected as cause of arrest',
'Left ventricular failure',
'Cardiac tamponade',
'No intervention for PEA',
'B',
'RV dilation in cardiac arrest: Point-of-care echo showing dilated RV suggests massive PE as cause. In PEA arrest with suspected PE, thrombolysis can be given during CPR. Alteplase 50mg IV bolus (some give 100mg). If thrombolysis given, continue CPR for 60-90 minutes (time for lysis to work). Contraindications to thrombolysis relative in cardiac arrest setting. Alternative: ECMO/ECPR if available, catheter-directed therapy if ROSC achieved.',
'hard', 'application'),

-- MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient''s arterial line waveform shows a tall, narrow pulse with rapid upstroke and early dicrotic notch. What cardiac condition does this suggest?',
'Hypovolemia',
'Aortic regurgitation - hyperdynamic pulse with wide pulse pressure, rapid runoff in diastole',
'Aortic stenosis',
'Cardiac tamponade',
'Normal waveform',
'B',
'Aortic regurgitation arterial waveform: Wide pulse pressure (high systolic due to increased stroke volume, low diastolic due to regurgitant runoff). Bisferiens pulse (double peak in systole - forward flow then reflected wave). Rapid upstroke. Early dicrotic notch. Collapsing/water-hammer quality. Contrast with aortic stenosis: Slow upstroke (pulsus parvus et tardus), narrow pulse pressure, anacrotic notch.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A ventilated patient has significant pulse pressure variation (PPV of 18%). What does this indicate and what action is suggested?',
'Poor cardiac function',
'Likely fluid responsive - PPV greater than 13% suggests preload reserve; trial fluid bolus and reassess',
'Needs vasopressors only',
'PPV is not clinically useful',
'Over-resuscitated state',
'B',
'Pulse pressure variation: Dynamic measure of fluid responsiveness in mechanically ventilated patients with regular cardiac rhythm. PPV = (PPmax - PPmin)/PPmean x 100. PPV greater than 13% = likely fluid responsive. Mechanism: Positive pressure ventilation decreases preload during inspiration; if patient is preload-dependent, stroke volume varies significantly. Give fluid bolus and reassess. PPV less than 9% = unlikely to respond to fluids.',
'hard', 'application');
