-- ============================================================================
-- BATCH 51: Surgical Complications and Management Scenarios
-- Topics: Recognition and management of post-operative complications
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- ANASTOMOTIC COMPLICATIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient post colorectal anastomosis develops fever, tachycardia, and increasing abdominal pain on day 5. WBC is 18, CRP is 350. CT shows free air and fluid adjacent to the anastomosis. What is the diagnosis and management?',
'Post-operative ileus',
'Anastomotic leak - emergency return to theatre for exploration, washout, likely diversion (stoma); source control is essential',
'Normal post-operative inflammation',
'Conservative management adequate',
'Antibiotics alone',
'B',
'Anastomotic leak: Clinical signs (fever, tachycardia, pain, peritonitis), lab abnormalities (WBC, CRP elevated), imaging (free air, collection near anastomosis). Management: Resuscitation, antibiotics, emergency laparotomy. Intraoperatively: Confirm leak, washout, decision regarding anastomosis (takedown and stoma, or proximal diversion if minor leak). Some small contained leaks may be drained percutaneously, but peritonitis = surgery.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient develops superficial surgical site infection 5 days after hernia repair. The wound has erythema, purulent discharge, and fever 38°C. The mesh is not exposed. What is the management?',
'Remove mesh immediately',
'Open wound for drainage, wound care, antibiotics - superficial infection with unexposed mesh can often be managed without mesh removal',
'Oral antibiotics only',
'No treatment needed',
'Complete wound excision',
'B',
'Superficial SSI with mesh: If mesh not exposed and infection superficial, can often be managed conservatively. Management: Open wound (if collection), drain pus, wound care (packing, NPWT), antibiotics targeting skin flora. Monitor closely for deep infection. If mesh exposed, chronic drainage, or fails to improve = likely mesh removal needed. Prevention: Meticulous technique, prophylactic antibiotics, adequate soft tissue coverage.',
'medium', 'application'),

-- SURGICAL COMPLICATIONS - DVT/PE
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient 5 days post hip replacement suddenly develops pleuritic chest pain, dyspnea, and hypoxia. ECG shows S1Q3T3 pattern. What is the likely diagnosis and immediate management?',
'Pneumonia',
'Pulmonary embolism - anticoagulation if not contraindicated, consider CT-PA or V/Q scan, escalate if hemodynamically unstable',
'Cardiac ischemia',
'Anxiety',
'Pulmonary contusion',
'B',
'Post-operative pulmonary embolism: High risk after orthopedic surgery despite prophylaxis. Presentation: Sudden dyspnea, pleuritic pain, hypoxia, tachycardia. ECG: S1Q3T3 (not always present), right heart strain. Management: Anticoagulation (heparin or LMWH) if no contraindication to post-op bleeding. CT-PA for diagnosis. If massive PE with hypotension: thrombolysis, catheter intervention, or surgical embolectomy. Prevention: VTE prophylaxis, early mobilization.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient develops post-operative delirium on day 2 after major abdominal surgery. They are agitated and confused with fluctuating consciousness. What is the approach to management?',
'Sedate immediately with benzodiazepines',
'Identify and treat underlying cause (infection, hypoxia, pain, medications, electrolytes, urinary retention); non-pharmacological measures first; avoid benzodiazepines if possible',
'Delirium is expected post-operatively',
'Physical restraints are first-line',
'Ignore and observe',
'B',
'Post-operative delirium management: Common in elderly (10-50% of major surgery). Precipitants: Pain, infection, hypoxia, medications (opioids, anticholinergics), metabolic derangement, urinary retention, constipation, sleep deprivation. Approach: Identify and treat cause, non-pharmacological measures (orientation, lighting, mobilization, glasses/hearing aids), minimize sedating medications. Pharmacology if needed: low-dose haloperidol (not benzos - worsen delirium except in alcohol withdrawal).',
'medium', 'application'),

-- FLUID COMPLICATIONS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has received 5L of normal saline over 24 hours. They now have peripheral edema, elevated JVP, and crackles at lung bases. Sodium is 139 mEq/L. What complication has developed?',
'Dehydration',
'Iatrogenic fluid overload - excessive IV fluid administration; reduce fluids, may need diuresis',
'SIADH',
'Normal post-operative state',
'Hypernatremia',
'B',
'Iatrogenic fluid overload: Excessive IV fluid (especially crystalloid) causes interstitial edema, pulmonary edema, delayed return of bowel function, wound healing impairment. Risk factors: Elderly, cardiac/renal disease, aggressive resuscitation protocols. Prevention: Goal-directed fluid therapy, reassess daily requirements, transition to oral/enteral early. Management: Restrict fluids, diuresis if symptomatic, monitor intake/output and weight.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient post-gastrectomy develops dumping syndrome with sweating, palpitations, and diarrhea after meals. What is the pathophysiology and dietary management?',
'Unrelated to surgery',
'Rapid gastric emptying causes hyperosmolar load in small bowel (fluid shift, hormonal response); dietary modification with small frequent meals, low carbohydrate, avoid liquids with meals',
'Increase meal size',
'High carbohydrate diet helps',
'No management available',
'B',
'Dumping syndrome: Early (15-30 min postprandial) - hyperosmolar chyme causes fluid shift into bowel, distension, autonomic symptoms. Late (1-3 hours) - reactive hypoglycemia from insulin overshoot. Management: Dietary - small frequent meals, avoid simple carbohydrates, avoid liquids with meals, increase fiber/protein, lie down after eating. Medications: Octreotide if refractory. Most improve with dietary changes. Occurs after gastric surgery with pyloric bypass.',
'hard', 'application'),

-- BLOOD PRODUCT COMPLICATIONS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient develops urticaria and mild bronchospasm 30 minutes into platelet transfusion. Vitals are stable. What is the diagnosis and management?',
'Acute hemolytic reaction',
'Allergic transfusion reaction - stop transfusion, give antihistamines ± hydrocortisone, may restart cautiously if only urticaria; bronchospasm more concerning',
'Continue transfusion unchanged',
'TRALI',
'Febrile non-hemolytic reaction',
'B',
'Allergic transfusion reaction: IgE-mediated response to plasma proteins. Mild: Urticaria, pruritus - stop transfusion, antihistamines, may restart if resolves. Moderate: Bronchospasm, angioedema - stop transfusion, antihistamines, steroids, bronchodilators; do not restart. Severe: Anaphylaxis - stop transfusion, adrenaline, full anaphylaxis protocol. Prevention: Pre-medication for recurrent reactions, washed products for severe allergic patients.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'Cell salvage is being used during a ruptured AAA repair. The collected blood is noted to be very dark. What might this indicate and is processing still appropriate?',
'Blood is not usable',
'Dark blood indicates high oxygen extraction (patient hypoperfused) or hemolysis - processing will wash and concentrate RBCs; still appropriate to use if no contamination',
'Only bright red blood is usable',
'Discard all collected blood',
'Color is irrelevant to cell salvage',
'B',
'Cell salvage blood quality: Dark blood = deoxygenated (high extraction in hypovolemia) or hemolyzed. Processing (washing, concentrating) removes free hemoglobin from hemolysis. Washed product safe to reinfuse. Contraindications to cell salvage: Gross bacterial contamination, certain medications in field, amniotic fluid. Cancer surgery controversial but increasingly used with filters. Always process before reinfusion.',
'medium', 'application'),

-- WOUND COMPLICATIONS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A laparotomy wound develops seroma formation 10 days post-operatively. The fluid collection is fluctuant but there are no signs of infection. What is the management?',
'Immediate surgical drainage',
'Observation initially - small seromas often resolve; aspirate if large/symptomatic; avoid repeated aspiration (infection risk); drain if recurrent',
'IV antibiotics required',
'Re-operate to close dead space',
'Seromas always need surgery',
'B',
'Seroma management: Collection of serous fluid in surgical dead space. Common after breast, hernia, abdominoplasty surgery. Management: Small/asymptomatic - observe, often resolve. Large/symptomatic - needle aspiration (sterile technique). Avoid repeated aspiration (introduces bacteria). Persistent/recurrent - may need drain placement. Prevention: Minimize dead space, use of drains (controversial), compression dressings, quilting sutures.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient develops incisional hernia 6 months after laparotomy. They have no symptoms but are anxious about enlargement. What is the natural history if untreated?',
'Hernias always remain stable',
'Incisional hernias typically enlarge over time; risk of incarceration/strangulation; repair recommended for most symptomatic hernias and growing asymptomatic hernias',
'Spontaneous resolution expected',
'All require emergency surgery',
'No risk from observation',
'B',
'Incisional hernia natural history: Most enlarge progressively if untreated. Enlargement causes: Pain, cosmetic concern, difficulty with clothing, skin breakdown over thinned tissue. Complications: Incarceration (8% per year), strangulation (emergency, bowel compromise). Small asymptomatic hernias may be observed in high-risk surgical patients. Elective repair recommended for: Symptomatic, enlarging, overlying skin compromise.',
'medium', 'application'),

-- MONITORING COMPLICATIONS
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A central venous catheter is inserted for TPN in a thin patient. Post-procedure CXR shows catheter tip in good position but a small apical opacity. What complication should be suspected?',
'Normal appearance',
'Pneumothorax - small apical opacity may be subtle PTX; confirm with expiratory film or CT if concerned; clinical monitoring essential',
'Hemothorax',
'Line malposition',
'No significance',
'B',
'Post-CVC pneumothorax: Complication of subclavian (highest risk) or internal jugular approach. May be small and asymptomatic initially. Detection: Post-procedure CXR mandatory, look at apices carefully. Small PTX may be seen as subtle apical lucency or visible visceral pleural line. Management: Small (less than 2cm), asymptomatic - may observe with repeat imaging. Larger or symptomatic - chest drain. Always exclude before positive pressure ventilation.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'An arterial line is inserted for hemodynamic monitoring. The waveform shows an overdamped appearance with slow upstroke and absent dicrotic notch. What is the cause and solution?',
'Normal arterial waveform',
'Air bubbles, kinking, clot, or overly compliant tubing causing damping - flush line, check for obstruction, replace tubing if needed',
'Patient is hypotensive',
'Aortic stenosis',
'Arrhythmia artifact',
'B',
'Overdamped arterial waveform: Causes - air bubbles in tubing, partial clot at catheter tip, kinking, overly compliant tubing, catheter against vessel wall. Appearance: Slurred upstroke, diminished pulse pressure, absent dicrotic notch. Consequence: Underestimates systolic, overestimates diastolic. Solution: Flush system (careful with air emboli), check for kinks, reposition, replace tubing, may need line rewire/replacement.',
'medium', 'application'),

-- CPR COMPLICATIONS
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During prolonged CPR, there is noted to be crepitus over the chest wall. What complication has likely occurred and what is the management?',
'Normal finding during CPR',
'Rib fractures with possible subcutaneous emphysema - continue CPR (benefit outweighs risk of rib fractures); be alert for tension pneumothorax',
'Stop CPR immediately',
'Rib fractures mean CPR is too aggressive',
'Switch to abdominal compressions only',
'B',
'CPR-related injuries: Rib fractures occur in 30-80% of patients receiving CPR (higher in elderly). Sternal fractures also common. Subcutaneous emphysema may occur from rib/sternal injury ± pneumothorax. Management: Continue CPR - survival benefit outweighs injury risk. Do not reduce compression depth due to crepitus. Be alert for tension pneumothorax (may be relieved by needle decompression). Document injuries post-ROSC.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient achieves ROSC but develops post-cardiac arrest syndrome with cardiogenic shock and multi-organ dysfunction. What components characterize this syndrome?',
'Just normal recovery process',
'Four components: Brain injury (hypoxic-ischemic), myocardial dysfunction (stunning), systemic ischemia-reperfusion response, persistent precipitating pathology',
'Only neurological damage',
'Syndrome does not exist',
'Only cardiac dysfunction',
'B',
'Post-cardiac arrest syndrome: 1) Brain injury - hypoxic-ischemic encephalopathy, may be comatose. 2) Myocardial dysfunction - stunning (reversible), may need inotropes. 3) Systemic ischemia-reperfusion - similar to sepsis (vasodilation, capillary leak, coagulopathy). 4) Persistent precipitating pathology (treat underlying cause). Management: TTM 32-36°C, coronary angiography if cardiac cause, hemodynamic optimization, neuroprognostication (defer 72h).',
'hard', 'application'),

-- FRACTURE COMPLICATIONS
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a tibial fracture in a cast develops increasing pain, swelling of toes, and paresthesias despite the cast being split. The limb is tense. What has developed?',
'Cast too tight resolved by splitting',
'Compartment syndrome - cast splitting alone insufficient; may need fasciotomy if compartment syndrome confirmed',
'Normal fracture swelling',
'Nerve injury from fracture',
'DVT',
'B',
'Compartment syndrome despite cast removal: If symptoms persist after complete cast removal (split down to skin including padding), true compartment syndrome likely. Diagnosis: Clinical (pain on passive stretch, tense compartments, paresthesia), or compartment pressure measurement (greater than 30 mmHg or within 30 mmHg of diastolic). Treatment: Emergency fasciotomy - all compartments of leg (4 compartments). Delay causes irreversible muscle necrosis, Volkmann contracture.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient 3 months after tibial nailing has persistent pain at the fracture site with localized tenderness and elevated inflammatory markers. X-ray shows lucency around screws. What is the likely diagnosis?',
'Normal healing',
'Hardware infection (implant-associated osteomyelitis) - may need hardware removal if fracture healed, or exchange if not healed; IV antibiotics',
'Delayed union only',
'Screw prominence',
'No intervention needed',
'B',
'Hardware infection: Presents with: Persistent/recurrent pain, drainage from incision, elevated inflammatory markers (CRP, ESR), radiographic changes (lucency around hardware, periosteal reaction). Management: Confirm with culture (ideally intraoperative). If fracture healed: Remove hardware, debride, IV antibiotics. If fracture not healed: May need hardware exchange, debride, antibiotic-impregnated cement, suppressive antibiotics. Biofilm makes eradication difficult without hardware removal.',
'hard', 'application'),

-- UROLOGICAL COMPLICATIONS
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient develops paraphimosis after urethral catheterization - the foreskin is stuck in retracted position with a tight band behind the glans. What is the emergency management?',
'Leave and observe',
'Reduce paraphimosis urgently - manual reduction with compression to reduce edema, may need dorsal slit if manual reduction fails; emergency to prevent glans ischemia',
'Circumcision immediately',
'Wait for urology in morning',
'Apply warm compresses only',
'B',
'Paraphimosis emergency: Foreskin trapped behind glans causes venous congestion, edema, and if untreated, arterial compromise with glans necrosis. Management: 1) Manual reduction - Apply pressure to glans (compress edema) for 5-10 minutes, then push glans back through foreskin ring. 2) If fails: Puncture edematous tissue with needle (release fluid). 3) If still fails: Dorsal slit (surgical incision of tight band). Always reduce foreskin after catheterization.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A catheterized patient develops severe bladder spasms despite the catheter draining well. This is causing significant discomfort. What is the management?',
'Larger catheter',
'Anticholinergic medication (oxybutynin, solifenacin) to reduce detrusor overactivity; check for catheter irritation, stones, or infection',
'Remove catheter immediately',
'Bladder irrigation',
'Pain is expected with catheters',
'B',
'Catheter-associated bladder spasms: Caused by: Catheter irritation triggering detrusor contractions, catheter balloon on trigone, infection, blood clots, encrustation. Management: Ensure catheter draining well (not blocked), smaller balloon (10ml not 30ml), treat infection if present, anticholinergics (oxybutynin, tolterodine). Belladonna suppositories may help. Consider different catheter type (silicone may be less irritating).',
'medium', 'application');
