-- ============================================================================
-- BATCH 52: High-Yield Clinical Scenarios - Board-Style Questions
-- Topics: Integration of all Surgery 1 topics with clinical reasoning
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- TRAUMA SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A 25-year-old restrained driver in a head-on collision has a seatbelt mark across the abdomen. Vital signs are normal. CT shows free fluid in the pelvis and a jejunal wall hematoma. How should this be managed?',
'Discharge with follow-up',
'Admit for observation and serial examinations - seatbelt sign with bowel wall hematoma has high risk of delayed perforation; surgery if peritonitis develops',
'Immediate laparotomy for all',
'CT adequate to rule out injury',
'MRI for better visualization',
'B',
'Seatbelt sign management: Seatbelt mark = high association with intra-abdominal injury (20-30%). Bowel wall hematoma = possible full-thickness injury or delayed perforation. Initial CT may miss hollow viscus injury. Management: Admission, serial abdominal examination q4-6h, repeat imaging if concerned, laparotomy if peritonitis. Cannot be discharged even with stable vitals due to high risk of missed injury.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has a widened mediastinum on chest X-ray after deceleration injury. They are hemodynamically stable. What is the next diagnostic step?',
'Immediate thoracotomy',
'CT angiography of the chest to evaluate for traumatic aortic injury',
'Repeat chest X-ray',
'Transthoracic echocardiography',
'Observation only',
'B',
'Traumatic aortic injury workup: Widened mediastinum after deceleration suggests aortic injury (at ligamentum arteriosum). Stable patient: CT angiography (CTA) is diagnostic test of choice - high sensitivity and specificity. Unstable patient: May need operative exploration. If aortic injury confirmed: Permissive hypotension (SBP less than 100), beta-blockade (reduce shear stress), urgent endovascular or open repair. Other mediastinal causes: Venous bleeding, thymic fat, technique.',
'hard', 'application'),

-- GENERAL SURGERY
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 60-year-old with acute cholecystitis undergoes laparoscopic cholecystectomy. Intraoperatively, the surgeon notes the gallbladder wall is gangrenous with local perforation. What classification is this wound?',
'Clean wound',
'Dirty/Infected wound - gross contamination from gangrenous, perforated viscus elevates SSI risk significantly',
'Clean-contaminated wound',
'Contaminated wound',
'Cannot classify intraoperatively',
'B',
'Wound classification: Clean - no inflammation, no hollow viscus entry. Clean-contaminated - controlled hollow viscus entry without spillage. Contaminated - gross spillage, acute inflammation without pus, traumatic wound. Dirty/Infected - established infection, pus, perforated viscus, devitalized tissue. Gangrenous perforated gallbladder = dirty/infected (established infection + perforation). SSI risk: Clean less than 2%, Clean-contaminated 3-11%, Contaminated 10-17%, Dirty greater than 25%.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with cirrhosis (Child-Pugh B) requires emergency umbilical hernia repair for incarceration. Which perioperative factors significantly increase mortality risk?',
'Hernia size alone',
'Emergent surgery, ascites, coagulopathy, and encephalopathy - Child-Pugh/MELD scores predict surgical mortality in cirrhosis',
'Patient age only',
'Type of anesthesia only',
'Laparoscopic approach',
'B',
'Cirrhosis surgical risk: MELD score and Child-Pugh class predict mortality. Risk factors: Emergency surgery (10x higher mortality vs elective), uncontrolled ascites (infection, wound dehiscence), coagulopathy (INR greater than 1.5), hypoalbuminemia, encephalopathy, renal dysfunction. Optimize: Control ascites, correct coagulopathy, treat infections, nutritional support. Consider TIPS for portal decompression in select cases. Avoid surgery if possible in Child-Pugh C.',
'hard', 'application'),

-- FLUIDS AND ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient is on IV maintenance fluids. What is the typical daily fluid and electrolyte requirement for an adult patient who is nil by mouth?',
'5L water, no electrolytes',
'Approximately 25-30 ml/kg water, 1 mmol/kg sodium, 1 mmol/kg potassium, with glucose to prevent ketosis',
'1L water with no additives',
'Same as oral intake only',
'No standard requirements exist',
'B',
'Maintenance fluid requirements (adult): Water 25-30 ml/kg/day (or 1ml/kg/hr). Sodium 1 mmol/kg/day. Potassium 1 mmol/kg/day. Glucose ~50-100g/day (prevents ketosis, provides 200-400 kcal). Example (70kg patient): ~2100-2500ml water, 70 mmol Na+, 70 mmol K+. This is maintenance only - additional replacement needed for abnormal losses. Avoid excessive 0.9% saline (hyperchloremia). NICE guidelines recommend balanced approach.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with bowel obstruction has Na+ 128, K+ 2.8, Cl- 82, HCO3- 38. What is the acid-base disturbance and likely cause?',
'Metabolic acidosis',
'Hypochloremic hypokalemic metabolic alkalosis from GI losses (vomiting/NG suction)',
'Respiratory acidosis',
'Normal electrolytes',
'Respiratory alkalosis',
'B',
'Metabolic alkalosis from GI losses: Vomiting or NG suction causes loss of H+, Cl-, K+, Na+. Creates hypochloremic, hypokalemic metabolic alkalosis. Mechanism: H+ loss directly raises HCO3-. Volume contraction maintains alkalosis (kidneys retain Na+ at expense of H+). Hypokalemia perpetuates alkalosis (K+-H+ exchange). Treatment: Volume replacement (0.9% saline provides Cl-), potassium replacement, treat underlying obstruction.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient has repeated positive antibody screens making crossmatch difficult. They have been transfused multiple times in the past. What has likely developed?',
'ABO incompatibility',
'Alloimmunization - development of antibodies to foreign red cell antigens from previous transfusions; need extended phenotype matching',
'Autoantibodies only',
'False positive screens',
'HIV antibodies',
'B',
'Transfusion alloimmunization: Previous transfusion exposes recipient to foreign RBC antigens. Immune response creates alloantibodies (1-3% per unit transfused). Common antigens: Kell, Rh (E, c), Kidd, Duffy. Consequences: Difficult crossmatch, delayed hemolytic reactions. Prevention: Extended phenotype matching (match beyond ABO/Rh), leukodepletion. Management: Identify all antibodies, find compatible units (may take time), involve blood bank early for complex patients.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'During massive transfusion, the patient''s temperature drops to 34°C. What is the most effective method to prevent and treat transfusion-associated hypothermia?',
'Room temperature blood is adequate',
'Use blood warmers to warm products to 37-42°C before infusion; also use forced air warming blankets and warmed IV fluids',
'Rapid infusion warms blood',
'Hypothermia is not related to transfusion',
'Microwave blood products',
'B',
'Transfusion hypothermia prevention: Refrigerated blood (4°C) and frozen products cause heat loss. Each unit of cold blood can drop core temperature 0.25°C. Consequences: Coagulopathy (enzymes work poorly at low temps), cardiac arrhythmias, increased oxygen consumption. Prevention: Approved blood warmers (NOT microwave - causes hemolysis), forced air warming, warm IV fluids. Target normothermia (greater than 36°C).',
'medium', 'application'),

-- BLOOD CONSERVATION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is the mechanism of action of tranexamic acid (TXA) in reducing surgical blood loss?',
'Increases clot formation',
'Antifibrinolytic - inhibits plasminogen activation, preventing premature clot breakdown',
'Vasoconstriction',
'Platelet aggregation enhancement',
'Factor replacement',
'B',
'Tranexamic acid mechanism: Competitive inhibitor of plasminogen activation. Binds lysine-binding sites on plasminogen, preventing it from binding fibrin and being activated to plasmin. Result: Clots formed are more stable, not prematurely lysed. Does NOT form new clots or replace factors - preserves clots already formed. Evidence: CRASH-2 (trauma), WOMAN (PPH), ortho surgery trials show reduced bleeding and transfusion with TXA.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient is scheduled for elective hip replacement and wants to donate their own blood preoperatively (autologous predonation). What are the considerations?',
'Always beneficial and should be done',
'Evidence limited; may cause preoperative anemia; wastage rate high; largely replaced by other blood conservation strategies',
'Eliminates all transfusion risks',
'No drawbacks to predonation',
'Mandatory for all elective surgery',
'B',
'Autologous preoperative donation (APD): Patient donates blood weeks before surgery for their own use. Concerns: Creates preoperative anemia (often needs more transfusion), high wastage rate (30-50% units not used), not risk-free (clerical errors, bacterial contamination), costly. Current role limited - largely replaced by: preoperative anemia treatment, TXA, cell salvage, restrictive transfusion thresholds. May have role for rare blood types.',
'medium', 'application'),

-- WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has a pressure ulcer over the sacrum with a black eschar covering. The tissue is dry and firmly adherent. What is the wound classification and initial management?',
'Stage 1 pressure ulcer',
'Unstageable - depth cannot be determined under eschar; management depends on clinical situation (stable dry eschar may be observed vs debridement if infected)',
'Stage 4 pressure ulcer',
'Superficial wound only',
'Healed wound',
'B',
'Unstageable pressure ulcer: Eschar obscures wound bed, making depth assessment impossible. Management: Stable, dry, intact eschar on heel or elsewhere without signs of infection may be left as natural biological cover (do not debride). If signs of infection (erythema, fluctuance, drainage, odor, fever): Debride to assess depth and treat infection. After debridement, can stage wound properly. Always address underlying pressure.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A chronic wound has excessive slough (yellow necrotic tissue). What debridement method is most appropriate for a painful wound in an outpatient setting?',
'Sharp debridement at bedside',
'Autolytic debridement with hydrogel or hydrocolloid - moist dressings allow body''s enzymes to soften and remove slough with less pain',
'Wet-to-dry dressings',
'No debridement needed',
'Mechanical scrubbing',
'B',
'Autolytic debridement: Uses body''s own enzymes and moisture to liquefy necrotic tissue. Dressings: Hydrogels (add moisture), hydrocolloids, films (maintain moisture). Advantages: Selective (only removes dead tissue), painless, easy to apply, can be done by patient. Disadvantages: Slower than sharp debridement, not for heavily necrotic or infected wounds. Best for: Sloughy wounds with minimal-moderate necrotic burden, painful wounds, outpatient management.',
'medium', 'application'),

-- SUTURES AND INSTRUMENTS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon needs to ligate a large vessel (10mm diameter). What ligature approach is safest?',
'Single tie close to aorta',
'Double ligation with transfixion suture (suture through vessel wall) on one tie to prevent slippage',
'Single clip',
'Energy device only',
'No ligation needed for large vessels',
'B',
'Large vessel ligation: Risk of ligature slipping off large vessel. Technique: Double ligation - proximal tie, then transfixion suture (needle through vessel, suture secured on both sides = cannot slip). Alternative: Suture ligation where vessel is oversewn. For very large vessels (aorta, vena cava): Vascular clamp and suture repair preferred over ligation. Energy devices alone may not seal vessels greater than 5-7mm diameter.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the appropriate needle type for closing bowel anastomosis?',
'Cutting needle',
'Taper (round-bodied) needle - atraumatic, pushes tissue apart rather than cutting, reduces bleeding and tissue damage',
'Reverse cutting needle',
'Blunt needle',
'Straight needle',
'B',
'Needle selection for bowel: Taper (round-body) needle ideal. Mechanism: Pushes tissue fibers apart rather than cutting them. Benefits: Less tissue trauma, less bleeding, holes seal around suture. Cutting needles: For tough tissue (skin, fascia) - actually cuts through tissue. Reverse cutting: Cutting edge on outer curve, reduces risk of suture cutting out of wound edge. Blunt: For friable tissue like liver.',
'easy', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient falls from standing and has a proximal humerus fracture. They have significant comorbidities. What is the usual management approach?',
'ORIF for all proximal humerus fractures',
'Most can be managed non-operatively with sling immobilization and physiotherapy - good functional outcomes in elderly even with malunion',
'Total shoulder replacement always',
'No treatment needed',
'Cast for all shoulder fractures',
'B',
'Proximal humerus fracture management: 85% minimally displaced and managed non-operatively. Treatment: Collar and cuff or sling for 2-3 weeks, then gentle ROM exercises. Even 2-3 part fractures in elderly often do well non-operatively (shoulder tolerates malunion). Indications for surgery: Severe displacement, head-splitting fractures, young active patients, associated dislocation. Options: ORIF, hemiarthroplasty, reverse total shoulder (elderly, poor bone quality).',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a fifth metatarsal base fracture (Jones fracture) is seen in clinic. This is a known non-union risk fracture. What is the management?',
'Walking boot and weight bearing immediately',
'Non-weight bearing with immobilization 6-8 weeks, or primary screw fixation especially in athletes; close follow-up due to non-union risk',
'Ignore and activity as tolerated',
'Amputation',
'No follow-up needed',
'B',
'Jones fracture: Proximal diaphyseal-metaphyseal junction of fifth metatarsal. High non-union rate (15-40%) due to watershed blood supply. Management: Conservative - NWB cast or CAM boot 6-8 weeks with close radiographic follow-up. Operative - intramedullary screw fixation, especially in athletes or delayed union. Differentiate from: Tuberosity avulsion (heals well) and stress fracture (different location). Must counsel patient about non-union risk.',
'hard', 'application'),

-- URETHRAL CATHETERIZATION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is the main advantage of using a three-way catheter over a two-way catheter?',
'Smaller diameter',
'Allows continuous bladder irrigation (CBI) - third lumen for irrigation inflow while still draining and maintaining balloon',
'Better for long-term use',
'Lower infection rate',
'Easier to insert',
'B',
'Three-way catheter: Three lumens - drainage (largest), balloon inflation, irrigation inflow. Used for continuous bladder irrigation (CBI) to prevent clot retention, typically after TURP or with hematuria. Technique: Irrigation fluid (saline) runs in through irrigation port, drains out through drainage lumen, washing out blood/clots. Two-way catheter: Two lumens - drainage and balloon (standard catheter). Cannot perform CBI.',
'easy', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What size catheter balloon should typically be inflated in the bladder?',
'30ml for all patients',
'10ml for standard use; 30ml balloons used for specific indications like post-TURP or when catheter traction needed',
'5ml always adequate',
'As much as balloon will hold',
'Balloon size does not matter',
'B',
'Catheter balloon size: Standard catheters have 10ml balloon (fill with 10ml sterile water). 30ml balloons used for: Post-prostatectomy (prevents catheter migration into prostatic fossa), when traction needed (secure catheter). Smaller balloons (5ml) for pediatric use. Never overinflate (causes pressure on bladder neck, spasm). Always use sterile water (saline can crystallize in balloon).',
'easy', 'application');
