-- ============================================================================
-- BATCH 53: Advanced Clinical Decision-Making Scenarios
-- Topics: Complex surgical cases requiring critical thinking
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- COMPLEX SURGICAL SCENARIOS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old man with morbid obesity (BMI 55) requires emergency appendectomy. What special considerations apply?',
'Standard approach works for all patients',
'Requires longer instruments, careful positioning to prevent nerve injury, higher infection risk, VTE prophylaxis, and awareness of altered pharmacokinetics',
'Operate without any modifications',
'Obesity has no surgical implications',
'Delay surgery for weight loss',
'B',
'Morbid obesity surgical considerations: Positioning - pressure point protection, securing to table, avoid lateral positions if possible. Equipment - longer instruments, specialized retractors. Airway - difficult intubation anticipated. Pharmacology - lipophilic drug sequestration, altered volumes of distribution. Wound - higher SSI rate, use prophylactic antibiotics at higher doses. VTE - high risk, appropriate thromboprophylaxis. Physiologic - cardiopulmonary limitations, restrictive lung disease.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient scheduled for elective surgery mentions they take herbal supplements including ginkgo, garlic, and fish oil. When should these be stopped preoperatively?',
'Continue through surgery',
'Stop 1-2 weeks preoperatively - these supplements inhibit platelet function and increase bleeding risk',
'Stop day before surgery',
'Herbal supplements have no effects',
'Only prescription medicines matter',
'B',
'Herbal supplement perioperative management: Many supplements affect coagulation, cardiovascular function, drug metabolism. Bleeding risk: Ginkgo (antiplatelet), garlic (antiplatelet), fish oil (antiplatelet), ginger, vitamin E. Stop 1-2 weeks before surgery. Anesthetic interactions: Ephedra (cardiac), St. John''s wort (induces CYP450), kava (hepatotoxic, potentiates sedatives), valerian (potentiates sedatives). Always ask about supplements in preoperative assessment.',
'medium', 'application'),

-- SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with cardiogenic shock from MI is started on vasopressors. Despite treatment, urine output remains low and lactate is rising. What additional monitoring would guide therapy?',
'Monitor blood pressure only',
'Invasive cardiac monitoring (PA catheter or echocardiography) to assess cardiac output, filling pressures, and guide inotrope/vasopressor selection',
'Chest X-ray daily',
'No additional monitoring needed',
'Finger stick glucose',
'B',
'Advanced hemodynamic monitoring in cardiogenic shock: Goals - optimize preload, afterload, and contractility while avoiding excessive filling. Tools: Pulmonary artery catheter - measures PCWP (filling pressure), CO, SVR. Point-of-care echo - LV/RV function, volume status, valve function. Interpretation guides therapy: High PCWP + low CO = cardiogenic (may need inotropes + diuresis). Low PCWP + low CO = hypovolemia (needs volume). Mixed patterns common.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient with pelvic fracture has ongoing hemorrhage despite external fixation and angioembolization. Massive transfusion is ongoing. What is the next step?',
'Continue current management',
'Preperitoneal pelvic packing (PPP) - directly addresses retroperitoneal venous bleeding which angiography cannot control',
'CT scan for other injuries',
'Transition to comfort care',
'Exploratory laparotomy',
'B',
'Pelvic fracture hemorrhage algorithm: External compression/binder - stabilizes pelvis, reduces venous bleeding. Angiography/embolization - controls arterial bleeding (10-15% of pelvic bleeding). Preperitoneal pelvic packing - directly compresses retroperitoneal venous plexus (majority of bleeding). Combined approach increasingly used. REBOA (resuscitative balloon occlusion) - temporizing measure in extremis. Laparotomy alone doesn''t address retroperitoneal pelvic bleeding.',
'hard', 'application'),

-- ELECTROLYTE SCENARIOS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient on chronic diuretics presents with weakness. K+ is 2.2, Mg2+ is 1.0. You give IV potassium but levels remain low. Why?',
'Potassium dose inadequate',
'Magnesium depletion prevents potassium repletion - magnesium is required for normal potassium handling; must correct hypomagnesemia first or concurrently',
'Measurement error',
'GI losses ongoing',
'Renal failure developing',
'B',
'Hypokalemia and hypomagnesemia: Magnesium depletion causes renal potassium wasting (affects Na-K-ATPase and ROMK channels). Potassium replacement refractory until magnesium corrected. Common causes together: Diuretics (loop, thiazide), diarrhea, alcoholism, certain drugs. Treatment: Replace magnesium (IV MgSO4 if severe) BEFORE or WITH potassium replacement. Target Mg greater than 2.0 mg/dL. Severe hypokalemia less than 2.5 with cardiac monitoring.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient is receiving TPN. Labs show: glucose 250, K+ 3.0, phosphate 1.5 (low), Mg2+ 1.5 (low). What syndrome is occurring?',
'Hyperglycemia syndrome',
'Refeeding syndrome - intracellular shift of potassium, phosphorus, and magnesium due to insulin release with carbohydrate administration after starvation',
'TPN intolerance',
'Sepsis',
'Liver failure',
'B',
'Refeeding syndrome: Occurs when malnourished patients receive carbohydrates. Mechanism: Insulin released → drives glucose, K+, Mg2+, phosphate into cells → severe electrolyte depletion. Consequences: Hypophosphatemia (most dangerous) → respiratory failure, cardiac dysfunction, rhabdomyolysis. Risk factors: Anorexia, prolonged starvation, alcoholism, post-bariatric surgery. Prevention: Start TPN slowly (10-15 kcal/kg), monitor electrolytes closely, supplement before and during refeeding.',
'medium', 'application'),

-- BLOOD TRANSFUSION
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient in surgery has surgical bleeding that is mostly controlled. Current Hb is 7.2 g/dL. The patient has no cardiac history and is hemodynamically stable. Should they be transfused?',
'Transfuse to Hb >10',
'Not necessarily - restrictive threshold of 7-8 g/dL is safe in most patients; transfuse if ongoing bleeding, symptoms, or high-risk comorbidities',
'Must transfuse all Hb <10',
'Never transfuse in surgery',
'Transfuse to Hb >12',
'B',
'Transfusion thresholds: Evidence supports restrictive approach. TRICC, FOCUS trials: Threshold 7-8 g/dL safe in most patients. Liberal transfusion (Hb greater than 10) not shown to improve outcomes and carries risks. Exceptions (consider higher threshold): Active coronary syndrome, symptomatic anemia, ongoing hemorrhage, severe sepsis. Always: Consider symptoms, not just numbers. Transfusion triggers should be individualized.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A Jehovah''s Witness patient requires emergency surgery with expected significant blood loss. They refuse all blood products. What is the ethical and legal approach?',
'Transfuse if necessary to save life',
'Respect patient autonomy - documented competent refusal of blood is legally binding; use all blood conservation strategies and accept limitations',
'Refuse to operate',
'Transfuse while patient sedated',
'Obtain court order to transfuse',
'B',
'Jehovah''s Witness and blood: Competent adult refusal of blood is legally binding (patient autonomy). Cannot transfuse against will. Medical approach: Optimize preoperatively (iron, EPO), use blood conservation techniques (cell salvage may be acceptable to some, TXA, meticulous hemostasis, permissive anemia, controlled hypotension). Accept that outcome may be worse without blood. Document discussion thoroughly. Different considerations for children or incompetent patients.',
'hard', 'application'),

-- WOUND MANAGEMENT
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has a diabetic foot ulcer that has been present for 8 weeks despite offloading and dressings. What adjunctive therapies might be considered?',
'Continue current approach indefinitely',
'Consider advanced therapies - negative pressure wound therapy, bioengineered skin substitutes, growth factors, hyperbaric oxygen if ischemia and infection controlled',
'Amputation immediately',
'Stop all treatment',
'Oral antibiotics only',
'B',
'Non-healing diabetic foot ulcer: Definition - no improvement after 4 weeks of standard care. Reassess: Vascular status (revascularization may be needed), infection (deep cultures, bone scan for osteomyelitis), offloading adequacy, glycemic control, nutrition. Advanced therapies: NPWT (granulation tissue formation), skin substitutes (bioengineered, cellular products), HBOT (Wagner grade 3+, controls hypoxia), growth factors (becaplermin). Evidence mixed but consider when standard care fails.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with venous leg ulcer has had recurrent ulceration despite treatment. What intervention provides best evidence for preventing recurrence?',
'Topical antibiotics long-term',
'Lifelong compression therapy - maintains venous return and prevents the venous hypertension that causes ulceration',
'Annual skin grafting',
'Leg elevation only',
'No prevention possible',
'B',
'Venous ulcer recurrence prevention: After healing, venous disease persists - ulcer will recur without ongoing management. Compression: Most important intervention. Reduces venous hypertension, supports calf pump. Lifelong use needed. Options: Compression stockings (20-30 mmHg or 30-40 mmHg), velcro wraps. Recurrence rate 30% with compression vs 70% without at 1 year. Also: Treat underlying venous insufficiency (ablation, surgery if indicated), skin care, leg elevation, exercise.',
'medium', 'application'),

-- SUTURES AND INSTRUMENTS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon uses electrocautery on the skin extensively. What wound complication is more likely with electrocautery versus cold knife for skin incision?',
'Faster healing with cautery',
'Delayed wound healing and increased scarring - thermal damage to wound edges impairs epithelialization',
'No difference',
'Better cosmesis with cautery',
'Cautery is always preferred',
'B',
'Electrocautery skin effects: Lateral thermal spread damages adjacent tissue. Zone of coagulation necrosis at wound edges. Consequences: Delayed epithelialization, increased wound edge necrosis, potentially worse scar. Cold knife: Clean wound edges, minimal tissue damage. Best practice: Use cold knife for skin incision (cosmesis important), electrocautery acceptable for subcutaneous tissue and hemostasis deeper in wound. Balance hemostasis vs tissue damage.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the key difference between tissue forceps (toothed) and atraumatic forceps (smooth)?',
'Only cosmetic difference',
'Tissue forceps provide better grip but cause some tissue trauma; atraumatic forceps are gentler for delicate structures like bowel and vessels',
'Atraumatic forceps grip better',
'Both used identically',
'Size difference only',
'B',
'Forceps selection: Tissue forceps (Adson''s, toothed) - interdigitating teeth at tip provide excellent grip on fibrous tissue (skin, fascia). Cause puncture marks, not for delicate tissue. Atraumatic (DeBakey, smooth) - serrated jaws without teeth, gentler grip for bowel, vessels, nerves. Less grip on tough tissue. Ring forceps (Babcock) - atraumatic for tubular structures. Allis - more traumatic, for tissue to be excised.',
'easy', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient presents with a punched-out ulcer on the lateral malleolus with a pale, adherent base. ABI is 0.5. What is the likely diagnosis and key management?',
'Venous ulcer - compress',
'Arterial ulcer - requires vascular assessment and likely revascularization before ulcer will heal; compression contraindicated',
'Neuropathic ulcer',
'Malignant ulcer',
'Traumatic ulcer',
'B',
'Arterial ulcer features: Location - pressure points, lateral malleolus, tips of toes. Appearance - punched out, pale/necrotic base, may be painful (especially with elevation). Associated findings - absent pulses, cool limb, claudication, rest pain. ABI less than 0.5 = severe ischemia. Management: Vascular referral urgently, angiography, revascularization (angioplasty, bypass). DO NOT compress (worsens ischemia). Keep wound dry if severely ischemic until revascularized.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A diabetic patient has an ulcer on the plantar surface of the metatarsal heads. They have palpable pulses and sensation is decreased. What is most important for healing?',
'Antibiotics alone',
'Offloading - removing pressure from the ulcer site using total contact cast, removable cast walker, or specialized footwear',
'Debridement alone sufficient',
'Topical growth factors first',
'Tight glucose control only',
'B',
'Diabetic (neuropathic) foot ulcer: Location - pressure points (metatarsal heads, heel, tips of toes). Cause - repetitive mechanical stress on insensate foot. Key to healing: OFFLOADING. Methods: Total contact cast (gold standard - non-removable), removable cast walkers (compliance dependent), therapeutic footwear, felted foam. Also: Sharp debridement, moist wound environment, infection treatment when present, glucose optimization. Without offloading, healing is unlikely.',
'medium', 'application'),

-- ABDOMINAL INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'A patient with multiple previous abdominal surgeries requires reoperation. The previous incision is midline. What risks are increased?',
'No additional risks',
'Adhesions increase operating time and risk of inadvertent enterotomy; consider open technique for entry, careful adhesiolysis',
'Healing is better in reoperations',
'Infection risk is lower',
'Blood loss is minimal',
'B',
'Reoperative abdominal surgery risks: Adhesions - form after all abdominal surgery. Dense adhesions to previous incision are common. Risks: Inadvertent enterotomy (1-15%), bleeding, prolonged operating time, need for resection. Entry techniques: Open cut-down through previous scar avoiding bowel, alternative virgin area entry if possible. Adhesiolysis: Sharp dissection, careful technique, recognize serosal injuries. Consider preoperative counseling regarding conversion, stoma possibility.',
'medium', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'For open splenectomy, which incision provides best exposure?',
'McBurney incision',
'Left subcostal incision (Kocher) or upper midline - provides direct access to left upper quadrant',
'Pfannenstiel incision',
'Right subcostal incision',
'Transverse umbilical',
'B',
'Splenectomy incisions: Left subcostal (Kocher type) - follows costal margin, excellent access to left upper quadrant. Upper midline - versatile, can be extended, allows exploration of other areas. Choice depends on: Surgeon preference, patient body habitus, elective vs trauma (midline often preferred in trauma for exploration), splenic size. Laparoscopic approach now preferred for most elective cases.',
'medium', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient arrests in the radiology suite during a CT scan. What are the unique challenges and considerations for CPR in this location?',
'Standard CPR with no modifications',
'Limited access due to scanner gantry, potential equipment interference, need to move patient to floor or accessible location, minimize radiation exposure',
'CPR not possible in radiology',
'Defer to radiology staff only',
'Use CT table for compressions',
'B',
'Cardiac arrest in CT scanner: Challenges - patient in scanner bore with limited access, radiation if scanner running. Management: Stop scanning, remove patient from gantry, move to accessible location. CT table usually too narrow and high for effective CPR. Get patient to floor if needed. Standard BLS/ACLS once accessible. Consider causes related to contrast (anaphylaxis) or procedure. All staff should know location of crash cart and AED in radiology.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'During CPR for a patient with known massive PE, what specific intervention should be considered?',
'Standard ACLS only',
'Consider thrombolytic therapy (tPA) during CPR - may restore pulmonary blood flow; if given, continue CPR for longer period (60-90 minutes)',
'Immediate thoracotomy',
'Stop CPR after 10 minutes',
'Pace the heart',
'B',
'Thrombolysis in cardiac arrest: Consider when PE or MI suspected as cause. Mechanism: Lyses clot obstructing pulmonary circulation in PE or coronary arteries in MI. Evidence: Case reports and small series show survivors. If thrombolytic given during CPR, continue resuscitation efforts for 60-90 minutes (time for drug effect). Risks: Bleeding. Contraindicated: if bleeding cause of arrest. Alternatives: ECMO if available, surgical embolectomy, catheter-based intervention.',
'hard', 'application');
