-- ============================================================================
-- BATCH 54: Applied Surgical Pathophysiology Scenarios
-- Topics: Understanding disease mechanisms through clinical cases
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- PATHOPHYSIOLOGY-BASED SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in septic shock is given fluid boluses but blood pressure does not improve. What explains the vasoplegia (refractory vasodilation)?',
'Inadequate fluid volume',
'Pathologic vasodilation from nitric oxide, inflammatory cytokines, and loss of vascular responsiveness to catecholamines',
'Cardiac tamponade',
'Vasopressor overdose',
'Blood pressure cuff malfunction',
'B',
'Septic vasoplegia pathophysiology: Inflammatory mediators (TNF-alpha, IL-1, IL-6) cause: 1) Massive NO production (iNOS upregulation) → vasodilation. 2) Cytokine-mediated vascular smooth muscle dysfunction. 3) Downregulation/desensitization of adrenergic receptors. 4) Vasopressin depletion (used up in early shock). Result: Distributive shock refractory to fluids and sometimes catecholamines. Treatment: High-dose vasopressors, consider vasopressin, corticosteroids may help.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A burn patient develops hypotension 2 hours after injury. There is no bleeding. What causes hypotension in acute burns?',
'Blood loss',
'Capillary leak causing massive fluid shift from intravascular to interstitial space (third-spacing) leading to hypovolemic shock',
'Cardiac pump failure',
'Spinal shock',
'Anaphylaxis to medications',
'B',
'Burn shock pathophysiology: Injury releases inflammatory mediators (histamine, prostaglandins, leukotrienes). Increased capillary permeability throughout body (not just burn area). Massive fluid shifts: Intravascular → interstitial. Protein and electrolytes also leak. Hypovolemic shock develops rapidly without resuscitation. Burns greater than 20% BSA require IV fluid resuscitation. Parkland formula: 4ml/kg/% BSA crystalloid in first 24hrs.',
'medium', 'application'),

-- WOUND HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient''s surgical wound has not healed at 3 weeks despite no infection. Labs show albumin 2.0 g/dL. What is the relationship?',
'Albumin not related to healing',
'Hypoalbuminemia indicates protein malnutrition which impairs collagen synthesis and immune function needed for wound healing',
'High albumin delays healing',
'Albumin causes wound infection',
'No relationship exists',
'B',
'Protein malnutrition and wound healing: Albumin less than 3.0 g/dL indicates protein depletion. Impact on healing: Impaired collagen synthesis (amino acids needed), decreased fibroblast proliferation, impaired immune function (increased infection risk), reduced angiogenesis. Clinical: Delayed healing, weak wounds, higher dehiscence and infection rates. Management: Nutritional supplementation (oral or enteral preferred), high-protein diet, may need parenteral nutrition if GI nonfunctional.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with peripheral arterial disease has a foot wound that is not healing. Transcutaneous oxygen (TcPO2) is 25 mmHg. What does this indicate?',
'Adequate oxygenation',
'Critical tissue hypoxia - TcPO2 <40 mmHg indicates inadequate oxygen delivery for wound healing; revascularization likely needed',
'Oxygen toxicity',
'Excellent healing potential',
'Normal finding',
'B',
'TcPO2 and wound healing: Transcutaneous oxygen measurement reflects tissue oxygenation. TcPO2 greater than 40 mmHg: Good healing potential. TcPO2 30-40 mmHg: Borderline, may heal but slowly. TcPO2 less than 30 mmHg: Unlikely to heal without intervention. Critical ischemia often less than 20 mmHg. Oxygen is essential for: Collagen synthesis (hydroxylation), leukocyte bacterial killing, angiogenesis. Management: Revascularization if possible to improve tissue perfusion.',
'medium', 'application'),

-- FLUID PHYSIOLOGY
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has received 5L of 0.9% saline. Na+ is 139 but Cl- is 118 (normal 98-106) and HCO3- is 18. What has occurred?',
'Normal postoperative state',
'Hyperchloremic metabolic acidosis from excessive normal saline - the chloride load overcomes renal compensatory ability',
'Respiratory acidosis',
'Lactic acidosis',
'Saline is pH neutral',
'B',
'Normal saline and hyperchloremic acidosis: 0.9% saline contains Na+ 154, Cl- 154 mmol/L (supraphysiologic chloride). Large volumes → chloride load → displaces bicarbonate → metabolic acidosis. Strong ion difference (SID) decreases → acidosis. Effects: May impair renal blood flow, coagulopathy. Prevention: Use balanced crystalloids (Ringer''s lactate, Plasmalyte) which have lower chloride and buffer. SMART trial: Balanced fluids associated with less renal injury.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with small bowel obstruction has been vomiting for 3 days. They are hypokalemic. Where is the potassium going?',
'Stored in muscles',
'Lost in gastric secretions AND renally excreted due to secondary hyperaldosteronism from volume depletion',
'Converted to sodium',
'Destroyed by vomiting',
'Absorbed by bowel wall',
'B',
'Hypokalemia in GI losses: Direct losses: Gastric juice contains K+ (5-10 mmol/L) but this is modest contribution. Main mechanism: Secondary hyperaldosteronism. Volume depletion activates RAAS. Aldosterone → renal sodium retention BUT at cost of K+ and H+ excretion. Metabolic alkalosis perpetuates: Bicarbonaturia in alkalosis obligates K+ loss. Result: Profound hypokalemia. Treatment: Volume replacement (breaks aldosterone drive), potassium replacement.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient receiving multiple units of stored blood develops hypocalcemia. What is the mechanism?',
'Calcium removed from blood products',
'Citrate anticoagulant in stored blood binds ionized calcium, causing citrate toxicity, especially with rapid transfusion or liver dysfunction',
'Dilutional effect only',
'Calcium destroyed by storage',
'Unrelated to transfusion',
'B',
'Citrate toxicity: Blood products anticoagulated with citrate (chelates calcium). Normally liver metabolizes citrate rapidly. Citrate toxicity occurs with: Massive transfusion (exceeds liver capacity), liver dysfunction, hypothermia (slows metabolism), rapid infusion. Effects: Hypocalcemia (ionized calcium drops) → QT prolongation, hypotension, cardiac depression. Treatment: Calcium gluconate or chloride IV. Prevention: Monitor ionized calcium, give calcium after every 4 units in massive transfusion.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'Why does stored blood have reduced oxygen-carrying capacity despite adequate hemoglobin?',
'Hemoglobin degrades in storage',
'2,3-DPG levels decrease in stored blood, shifting the oxygen-hemoglobin dissociation curve left, impairing oxygen release to tissues',
'Storage increases oxygen binding',
'Bags block oxygen entry',
'Temperature effect only',
'B',
'Storage lesion and 2,3-DPG: During storage, red cell metabolism continues but is impaired. 2,3-DPG depletes within 2 weeks. Effect: Left shift of oxygen-hemoglobin dissociation curve. Hemoglobin binds oxygen more tightly, releases less to tissues. Clinical: Stored blood may not immediately improve oxygen delivery despite raising Hb. After transfusion, 2,3-DPG regenerates over 12-24 hours. Other storage changes: ATP depletion, membrane changes, potassium leak.',
'medium', 'application'),

-- SHOCK PATHOPHYSIOLOGY
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in prolonged shock has rising lactate despite resuscitation. The intensivist mentions "oxygen debt." What is the pathophysiology?',
'Lactate from infection only',
'Accumulated oxygen deficit from tissue hypoperfusion leads to persistent anaerobic metabolism; repayment requires adequate oxygen delivery over time',
'Lactate from ketosis',
'Normal metabolic byproduct',
'Due to dehydration only',
'B',
'Oxygen debt concept: During shock, tissue oxygen demand exceeds delivery. Cells switch to anaerobic metabolism → lactate accumulation. Oxygen debt = cumulative oxygen deficit. Even after blood pressure restored, this debt must be "repaid." Lactate clearance: Indicates adequate perfusion restored. Target lactate normalization within 6-8 hours. Persistent lactate despite resuscitation: Ongoing hypoperfusion, microvascular dysfunction, or mitochondrial dysfunction. Higher oxygen debt = worse prognosis.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient is resuscitated aggressively with crystalloid. Hours later, they develop abdominal compartment syndrome. What happened?',
'Undiagnosed abdominal injury',
'Massive fluid resuscitation causes tissue edema including bowel wall, mesentery, and retroperitoneum, increasing intra-abdominal pressure to pathologic levels',
'Hemorrhage recurred',
'Equipment malfunction',
'Unrelated to fluids',
'B',
'Resuscitation-related abdominal compartment syndrome: Crystalloid distributes to interstitium (only 20-25% stays intravascular). Large volume resuscitation → massive tissue edema. Abdominal cavity has limited compliance. Pressure rises: Greater than 20 mmHg with organ dysfunction = abdominal compartment syndrome. Effects: Decreased venous return (cardiovascular), renal vein compression (renal failure), diaphragm splinting (respiratory failure). Prevention: Damage control resuscitation, balanced products, avoid crystalloid excess.',
'hard', 'application'),

-- AUTOTRANSFUSION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During cell salvage for spine surgery, the blood collected is pink rather than red. What does this indicate?',
'Normal processing',
'Hemolysis - red cells have been damaged during collection or processing; hemolyzed blood should not be reinfused',
'High oxygen saturation',
'Dilution with saline',
'Arterial blood collected',
'B',
'Hemolysis in cell salvage: Pink/red supernatant or plasma indicates free hemoglobin from lysed cells. Causes: High suction pressure, contact with non-endothelial surfaces, improper handling, prolonged collection time. Consequences of infusing hemolyzed blood: Free hemoglobin causes renal toxicity, vasoconstriction, inflammatory response. Quality control: Processed blood should appear like normal packed RBCs. Discard if significant hemolysis. Reduce suction pressure to minimize.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What happens to clotting factors and platelets during cell salvage processing?',
'Preserved completely',
'Removed during washing - processed cell salvage blood contains only red cells, no clotting factors or functional platelets',
'Concentrated further',
'Unchanged from original',
'Enhanced by processing',
'B',
'Cell salvage blood composition: Washing process removes: Plasma proteins (including clotting factors), platelets (dysfunctional if present), white cells, debris, activated clotting factors, free hemoglobin, heparin (from anticoagulant). Result: Washed red cell concentrate in saline (Hct 50-80%). Clinical implication: Large volume cell salvage can cause dilutional coagulopathy - may need FFP and platelets concurrently. Not a complete blood replacement.',
'medium', 'application'),

-- CPR PATHOPHYSIOLOGY
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'Why does the quality of CPR decline significantly after about 2 minutes of compressions?',
'Arm strength adequate',
'Rescuer fatigue leads to decreased compression depth and rate; this is why 2-minute rotation intervals are recommended',
'Chest becomes more compliant',
'Patient''s chest stiffens',
'No decline occurs',
'B',
'CPR fatigue: Studies show compression quality declines at 1-2 minutes. Fatigue affects: Compression depth (should be 5-6 cm), compression rate (100-120/min), complete chest recoil. Decline often not perceived by rescuer. Consequences: Poor compression quality = poor coronary and cerebral perfusion = worse outcomes. Solution: Rotate compressors every 2 minutes (at rhythm check). Mechanical compression devices may maintain consistent quality.',
'easy', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the mechanism by which chest compressions generate cardiac output?',
'Direct cardiac massage',
'Combination of cardiac pump (direct heart compression) and thoracic pump (intrathoracic pressure changes) mechanisms',
'Stimulating heart to beat',
'Electrical activity generation',
'Heart restarts spontaneously',
'B',
'Chest compression mechanisms: Cardiac pump theory: Direct compression of heart between sternum and spine squeezes blood out; chest recoil allows filling. Thoracic pump theory: Compression increases intrathoracic pressure, driving blood from thorax to periphery; decompression creates venous return. Reality: Both mechanisms contribute. Optimal compressions: Deep (5-6 cm), fast (100-120/min), allow complete recoil (thoracic pump needs this), minimize interruptions. Generate about 25-30% of normal cardiac output.',
'medium', 'application'),

-- MENSURATION
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'A patient''s Glasgow Coma Scale improves from 7 to 13 after resuscitation. What does this change indicate pathophysiologically?',
'Random fluctuation',
'Improved cerebral perfusion - GCS improvement after resuscitation suggests hypoperfusion-related brain dysfunction that is reversible with adequate oxygen delivery',
'Worsening condition',
'Medication effect only',
'No clinical significance',
'B',
'GCS and perfusion: Initial low GCS in shock may be from cerebral hypoperfusion, not primary brain injury. Reversible with resuscitation. Improvement in GCS after fluid/blood: Indicates secondary (hypoperfusion) rather than primary (injury) cause. Important: Always reassess GCS after resuscitation before prognosticating or imaging decisions. If GCS does not improve: Consider primary brain injury, toxins, metabolic derangements, ongoing hypoperfusion.',
'medium', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'How do serial abdominal examinations help detect evolving intra-abdominal pathology in trauma patients?',
'One exam is always sufficient',
'Hollow viscus injuries may initially have minimal findings that evolve over hours as peritonitis develops; serial exams detect this progression',
'Serial exams delay treatment',
'Cannot detect any pathology',
'Only imaging matters',
'B',
'Serial abdominal examination: Hollow viscus injury (bowel perforation) may be initially subtle. Early: Minimal tenderness, no peritonitis. Evolution: Peritoneal contamination → inflammation → peritonitis develops over hours. Serial exam detects: Increasing tenderness, guarding, rebound, rigidity, absent bowel sounds. Timing: Typically q4-6 hours initially. Same experienced examiner preferred. Indications for urgent imaging/surgery: New peritoneal signs, hemodynamic changes, clinical deterioration.',
'medium', 'application'),

-- MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'Why does pulse oximetry give falsely normal readings in carbon monoxide poisoning?',
'Patient is actually well-oxygenated',
'Pulse oximetry cannot distinguish carboxyhemoglobin from oxyhemoglobin - both absorb light similarly at standard wavelengths',
'CO increases oxygen saturation',
'Equipment malfunction',
'No relationship exists',
'B',
'Pulse oximetry and CO poisoning: Standard pulse oximetry uses two wavelengths to distinguish oxyhemoglobin (oxygenated) from deoxyhemoglobin. Carboxyhemoglobin (CO-Hb) absorbs light similarly to oxyhemoglobin at these wavelengths. Result: Reads as "saturated" despite not carrying oxygen. Clinical: SpO2 may be 98% while actual oxygen content is critically low. Diagnosis: ABG with CO-oximetry measures true COHb. CO-oximetry uses multiple wavelengths.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'A patient on vasopressors has weak pulse oximetry signal. Why?',
'Oximeter broken',
'Peripheral vasoconstriction from vasopressors and shock reduces pulsatile blood flow to extremities, weakening or losing the photoplethysmograph signal',
'Patient has no oxygen',
'Nail polish effect only',
'Battery low',
'B',
'Pulse oximetry signal quality: Requires pulsatile arterial blood flow at sensor site. Poor signal causes: Peripheral vasoconstriction (vasopressors, hypothermia, shock), hypotension, poor perfusion, arrhythmias (irregular pulsations). Solutions: Ear probe (less affected by peripheral vasoconstriction), forehead sensor, warm extremity. Clinical: Weak signal = unreliable reading. Do not ignore poor signal quality. Consider alternative monitoring (ABG) in critically ill patients.',
'medium', 'application');
