-- ============================================================================
-- BATCH 55: Comprehensive Case-Based Assessments
-- Topics: Complex multi-system clinical scenarios
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- COMPREHENSIVE CASES
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old diabetic with heart failure (EF 25%) presents with acute cholecystitis. He has mild sepsis. What is the optimal surgical approach?',
'Open cholecystectomy under general anesthesia',
'Percutaneous cholecystostomy tube as bridge to surgery - allows source control while optimizing cardiac function for definitive surgery later',
'Laparoscopic cholecystectomy immediately',
'Observation without intervention',
'Total cholecystectomy with CBD exploration',
'B',
'Acute cholecystitis in high-risk patient: Goal - source control with minimal physiologic insult. Percutaneous cholecystostomy (PC): Minimally invasive, done under local anesthesia, drains infected gallbladder. Allows: Sepsis control, cardiac optimization, nutritional improvement. Definitive surgery: Interval cholecystectomy 6-8 weeks later when medically optimized. Consider: Some patients managed with PC alone if too high risk for any surgery. ACC/AHA guidelines for cardiac risk stratification.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'An 80-year-old with moderate dementia has acute appendicitis. Her family insists on surgery despite her poor baseline. What ethical principles apply?',
'Operate regardless of prognosis',
'Balance beneficence, non-maleficence, and respect for prior expressed wishes; consider whether surgery aligns with patient''s overall goals of care',
'Dementia excludes from surgery',
'Family decision is final',
'Refuse all treatment',
'B',
'Surgical decision-making with cognitive impairment: Principles: Beneficence (surgery treats disease), non-maleficence (surgery has risks), autonomy (prior wishes if known). Considerations: What were patient''s previously expressed wishes? What is her quality of life and functional status? What would she want? Is goal cure, comfort, or both? Family input valuable but should reflect patient''s values, not family''s. Document discussions. May involve ethics consultation for complex cases.',
'hard', 'application'),

-- SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient has both hemorrhagic shock from trauma AND cardiogenic shock from pre-existing severe cardiomyopathy. How does management differ from pure hemorrhagic shock?',
'Same management for all shock types',
'More conservative fluid resuscitation with earlier vasopressor support and careful monitoring for pulmonary edema; consider inotropes',
'More aggressive fluid resuscitation',
'Avoid all fluids',
'Use diuretics during resuscitation',
'B',
'Mixed shock management: Pure hemorrhagic shock: Aggressive volume replacement. With cardiogenic component: Heart cannot handle large volume loads. Risks: Pulmonary edema, worsening heart failure. Approach: Smaller fluid boluses with reassessment, earlier vasopressor initiation, consider inotropic support (dobutamine), invasive monitoring (PA catheter or echo) to guide therapy. May need balanced approach: Enough preload without overload. Challenging to manage.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A young woman has hypotension with warm skin and bounding pulses during late pregnancy. She is febrile. What type of shock is most likely and what is a specific concern?',
'Hypovolemic shock',
'Septic shock - distributive shock with warm peripheries; must consider obstetric sources (chorioamnionitis, pyelonephritis); fetal monitoring essential',
'Cardiogenic shock',
'Obstructive shock',
'Neurogenic shock',
'B',
'Septic shock in pregnancy: Presentation may be modified by physiologic changes of pregnancy. Warm shock presentation: Vasodilated, hyperdynamic, warm extremities. Obstetric sources: Chorioamnionitis, pyelonephritis (common), septic abortion, endometritis. Management considerations: Early antibiotics (pregnancy-safe), fluid resuscitation (avoid supine position - IVC compression), vasopressors if needed. Fetal monitoring essential. May need expedited delivery for source control or fetal distress.',
'hard', 'application'),

-- FLUID MANAGEMENT
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with severe traumatic brain injury has Na+ 125. The neurosurgery team requests urgent sodium correction. Why is this important for brain injury?',
'Sodium not relevant to brain',
'Hyponatremia causes water to shift into brain cells, worsening cerebral edema and intracranial pressure in already injured brain',
'High sodium protects brain',
'Osmolality not important',
'Correction can wait indefinitely',
'B',
'Hyponatremia and TBI: Serum hyponatremia creates osmotic gradient - water moves into cells (including brain cells). In TBI: Brain already at risk for edema. Additional cellular swelling worsens intracranial pressure (ICP). Can cause: Herniation, secondary brain injury, death. Management: Correct Na+ with hypertonic saline. Target slightly hypernatremic (145-155 in TBI) or eunatremic at minimum. Avoid rapid over-correction (osmotic demyelination syndrome) but TBI may require faster correction.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient on prolonged TPN develops elevated liver enzymes and bilirubin. What is the likely cause?',
'Unrelated to TPN',
'TPN-associated liver dysfunction - caused by lack of enteral feeding, excess calories, continuous infusion; may improve with cyclic TPN and starting enteral feeds',
'Hepatitis B infection',
'Medication reaction only',
'Normal finding',
'B',
'Parenteral nutrition-associated liver disease (PNALD): Occurs with prolonged TPN, especially without any enteral feeding. Mechanisms: Lack of enteral nutrients → gallbladder stasis, reduced cholecystokinin, altered bile flow. Excess calories/dextrose → hepatic steatosis. Continuous infusion → persistent hyperinsulinemia. Management: Start even minimal enteral feeding (trophic feeds), cycle TPN (off 8-12 hrs daily), reduce calories, omega-3 lipid emulsions may help.',
'medium', 'application'),

-- WOUND COMPLICATIONS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient has a chronic wound that has not changed in size for 6 months. Biopsy is performed. What is the primary concern prompting biopsy?',
'Routine wound care',
'Malignant transformation (Marjolin''s ulcer) - chronic non-healing wounds can undergo squamous cell carcinoma transformation; any suspicious or non-healing wound needs biopsy',
'Infection identification',
'Cosmetic assessment',
'Patient preference only',
'B',
'Marjolin''s ulcer: SCC arising in chronic wounds, burn scars, sinus tracts. Latency: Often years to decades after original injury. Risk factors: Long-standing wounds, burn scars, osteomyelitis sinuses, venous ulcers. Features prompting biopsy: Non-healing wound, changes in wound character, raised edges, increased pain, foul odor. Usually well-differentiated SCC but aggressive behavior with high metastatic potential. Treatment: Wide local excision, may need lymph node evaluation.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'Post-operative evisceration (abdominal contents protruding through wound) occurs on day 7. What is the immediate management?',
'Push contents back immediately',
'Cover with saline-moistened sterile dressing, keep patient nil by mouth, establish IV access, and arrange emergent return to OR for fascial closure',
'Apply pressure dressing tightly',
'Observe for improvement',
'Schedule elective repair',
'B',
'Evisceration management: Surgical emergency. Immediate: Cover exposed viscera with moist sterile saline gauze (prevents desiccation, contamination). Keep patient supine with knees flexed (reduces tension). NPO, IV access, fluid resuscitation if needed. Urgent OR: Exploration, assess bowel viability, fascial re-closure (may need mesh, VAC if contaminated). Risk factors: Obesity, malnutrition, wound infection, cough, increased IAP. Often preceded by serosanguinous discharge.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A massively transfused trauma patient has been resuscitated and stabilized. 24 hours later, they develop new hypoxemia and bilateral infiltrates on chest X-ray. What is the most likely cause?',
'Volume overload only',
'TRALI (Transfusion-Related Acute Lung Injury) - immune-mediated acute lung injury occurring within 6-72 hours of transfusion; diagnosis of exclusion',
'Hospital-acquired pneumonia',
'Pulmonary embolism',
'Aspiration pneumonia',
'B',
'TRALI: Acute lung injury within 6 hours of transfusion (may extend to 72 hrs). Mechanism: Donor antibodies (anti-HLA or anti-neutrophil) activate recipient neutrophils in pulmonary vasculature. Result: Capillary leak, non-cardiogenic pulmonary edema. Diagnosis: Acute lung injury criteria + temporal relationship to transfusion + exclusion of other causes. Treatment: Supportive (oxygen, ventilation). Prevention: Male-only plasma (lower antibody risk), high-risk donor exclusion.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient needs urgent surgery but has a positive antibody screen. The blood bank says crossmatch will take 2 hours. What is the safest approach if bleeding occurs before crossmatch is complete?',
'Wait for crossmatch regardless',
'Use O-negative or type-specific uncrossmatched blood - acceptable in emergencies; less safe than crossmatched but saves lives when blood urgently needed',
'Use any available blood type',
'Avoid all transfusion',
'Proceed without blood products',
'B',
'Emergency blood release: When crossmatched blood unavailable and patient exsanguinating: O-negative RBCs - universal donor, safest uncrossmatched option. Type-specific uncrossmatched - ABO/Rh matched but not crossmatched (small risk of minor antigen incompatibility). Electronic crossmatch - if no antibody history, can be rapid. Full serologic crossmatch - if positive antibody screen, needed but takes time. Risk vs benefit: Uncrossmatched blood may cause reaction, but death from bleeding is worse. Document emergency release.',
'hard', 'application'),

-- AUTOTRANSFUSION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During liver surgery with significant blood loss, the surgeon requests cell salvage. Unexpectedly, a small HCC is found. Should cell salvage continue?',
'Continue without modification',
'Cell salvage traditionally contraindicated with malignancy due to concern for tumor cell dissemination; however, with leukocyte depletion filters, may be considered in some settings',
'Malignancy has no effect',
'Cell salvage improves cancer outcomes',
'Never use cell salvage in liver surgery',
'B',
'Cell salvage and malignancy: Traditional teaching: Absolute contraindication (tumor cell dissemination). Current evidence: Uncertain - tumor cells can be found in salvaged blood, but metastatic potential unclear. Leukocyte depletion filters (LDF): Remove most tumor cells. Some centers use cell salvage + LDF in cancer surgery, especially if alternative is allogeneic transfusion (also has risks). Decision: Discuss with patient preoperatively if cancer suspected. No consensus.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A patient''s pre-operative hemoglobin is 9 g/dL. Surgery is scheduled in 4 weeks. What pre-operative interventions can reduce transfusion risk?',
'No intervention possible in 4 weeks',
'Iron supplementation (oral or IV), vitamin B12/folate if deficient, treat underlying cause; IV iron achieves faster response than oral',
'Delay surgery indefinitely',
'Transfuse preoperatively',
'Proceed without optimization',
'B',
'Preoperative anemia management: Anemia is strong transfusion predictor. 4 weeks allows meaningful intervention. Iron deficiency (most common): Oral iron (slow response, GI side effects), IV iron (faster, bypasses absorption issues). Check B12/folate and replace if deficient. Treat underlying cause: GI bleeding, menorrhagia, malignancy. EPO: Consider in select cases (renal failure, JW patients). Goal: Optimize hemoglobin to reduce intraoperative transfusion need. NATA guidelines recommend preoperative anemia screening.',
'medium', 'application'),

-- SUTURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A patient has had three incisional hernia repairs with recurrence. The surgeon plans mesh repair. What suture should be used to secure mesh to fascia?',
'Rapidly absorbable suture',
'Permanent or slowly absorbable suture - mesh needs to incorporate into tissue over weeks; rapidly absorbable suture loses strength before adequate healing occurs',
'No sutures needed for mesh',
'Staples only',
'Skin sutures are adequate',
'B',
'Mesh fixation sutures: Mesh hernia repair depends on tissue incorporation. Process takes weeks. Suture requirements: Maintain approximation until mesh fully incorporated. Options: Permanent sutures (polypropylene) or slowly absorbable (PDS, has 6 week strength retention). Rapidly absorbable (polyglycolic, catgut) lose strength at 2-3 weeks - too early. Alternatives: Tacks, tackers, fibrin glue, self-gripping mesh. Recurrence considerations: Previous failures require robust repair.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What knot security principle is most important when using monofilament sutures?',
'Single throw adequate',
'Additional throws needed because monofilament has more memory and is more slippery than braided sutures, requiring more throws to secure the knot',
'Fewer throws than braided',
'Knot security is identical',
'No knots needed',
'B',
'Monofilament knot security: Monofilament sutures (nylon, polypropylene, PDS) have: Higher memory (tendency to return to original shape), smoother surface (lower coefficient of friction). Result: Knots more likely to slip. Compensation: More throws required (typically 5-6 vs 3-4 for braided). Square knots essential. Consider knot-tying technique. Braided sutures: Better knot security but higher tissue drag and infection risk.',
'easy', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a tibial shaft fracture develops increasing pain despite adequate analgesia at 6 hours. Pulses are present. What must be excluded?',
'Normal postoperative pain',
'Compartment syndrome - pain out of proportion, pain with passive stretch, and pressure symptoms; palpable pulses do not exclude compartment syndrome',
'DVT',
'Fracture malreduction',
'Wound infection',
'B',
'Compartment syndrome clinical features: Hallmark: Pain out of proportion to injury, especially with passive stretch. Other signs: Pressure/tenseness of compartment, paresthesias (late), paralysis (late), pulselessness (very late). Critical: Pulses are preserved until late - compartment pressure less than arterial pressure. Perfusion compromised at the capillary level. High-risk fractures: Tibia, forearm. Diagnosis: Clinical suspicion + compartment pressure measurement if uncertain. Treatment: Emergent fasciotomy.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with bilateral calcaneal fractures after a fall from height should have what additional injury excluded?',
'No associated injuries likely',
'Lumbar spine fracture - axial loading injuries frequently cause concurrent calcaneal and thoracolumbar fractures; examine spine and consider imaging',
'Ankle sprain',
'Foot sprain only',
'Upper extremity fracture',
'B',
'Associated injury patterns: Calcaneal fractures = high-energy axial load (fall from height, MVA). This energy transmits up skeleton. Associated injuries: Thoracolumbar spine fracture (up to 10% of calcaneal fractures have spine injury). Mechanism: Same axial loading. Other associations: Tibial plateau, hip fractures. Always: Examine entire spine, maintain spinal precautions until cleared, low threshold for spinal imaging with calcaneal fractures.',
'medium', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A leg ulcer has rolled, everted edges and is growing despite treatment for 6 months. What investigation is essential?',
'Continue current treatment',
'Biopsy for histology - rolled edges and failure to heal despite treatment are suspicious for malignancy (SCC or BCC)',
'Change dressing type only',
'Increase compression',
'Start antibiotics',
'B',
'Warning signs in leg ulcers: Features suggesting malignancy: Rolled/everted edges, growth despite treatment, exophytic tissue, friability, bleeding, unusual location or appearance. Marjolin''s ulcer: SCC in chronic wounds. Other malignancies: BCC, melanoma, sarcoma. Investigation: Punch or incisional biopsy from ulcer edge (include normal tissue). Multiple biopsies if large ulcer. Treatment: Wide excision, may need skin graft/flap, lymph node assessment.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient with mixed arterial-venous leg ulcer has ABI 0.65. What is the safe compression pressure?',
'Full strength compression (40 mmHg)',
'Modified reduced compression (20-25 mmHg) - some compression beneficial for venous component but high compression dangerous with arterial disease',
'No compression ever',
'Compression does not matter',
'Maximum compression always',
'B',
'Mixed ulcer management: When both venous and arterial disease present. Full compression contraindicated with significant arterial disease. ABI thresholds: Greater than 0.8 - safe for standard compression. 0.6-0.8 - reduced compression (20-25 mmHg) with caution. Less than 0.6 - compression usually contraindicated until revascularized. Modified options: Reduced pressure bandaging, short-stretch bandages (lower resting pressure). Balance: Need some venous support without compromising arterial perfusion.',
'medium', 'application');
