-- ============================================================================
-- BATCH 56: Surgical Emergency Protocols and Rapid Decision Scenarios
-- Topics: Time-critical surgical emergencies requiring immediate action
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- TIME-CRITICAL EMERGENCIES
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient arrives in ED with eviscerated bowel after a stab wound. The bowel is pink and not contaminated with stool. What is the correct emergency room management?',
'Reduce bowel immediately at bedside',
'Cover with saline-moistened sterile gauze, avoid reduction, start IV access and antibiotics, prepare for emergent OR',
'Obtain CT scan first',
'Observe for spontaneous reduction',
'Apply pressure to push bowel in',
'B',
'Eviscerated bowel management: Emergency - risk of desiccation, contamination, strangulation. ED management: Cover immediately with warm saline-moistened sterile gauze (prevents drying). Do NOT attempt reduction in ED (may increase contamination, hide associated injuries). Large bore IV access, fluid resuscitation, broad-spectrum antibiotics. Urgent OR for exploration under controlled conditions. May have associated intra-abdominal injuries.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A child swallows a button battery 2 hours ago. X-ray confirms it is lodged in the esophagus. What is the time frame for intervention?',
'Elective removal next week',
'Emergent removal within 2 hours - esophageal button batteries cause rapid tissue necrosis and perforation within hours',
'Wait for spontaneous passage',
'Only remove if symptomatic',
'Observe for 24 hours first',
'B',
'Button battery esophageal impaction: Surgical emergency. Mechanism: Battery generates current at tissue interface causing: Electrolysis → hydroxide formation → liquefactive necrosis. Time course: Significant injury can occur within 2 hours. Complications: Perforation, fistula to trachea or great vessels (can be fatal). Management: Emergent endoscopic removal. Do not wait. If battery in stomach (past pylorus), usually can observe for passage. Esophageal = emergency.',
'hard', 'application'),

-- SHOCK EMERGENCIES
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with tension pneumothorax has tracheal deviation, absent breath sounds, and hypotension. What is the immediate intervention before chest X-ray?',
'Obtain chest X-ray first',
'Needle decompression followed by chest tube - tension pneumothorax is a clinical diagnosis requiring immediate decompression without waiting for imaging',
'Start IV fluids only',
'Emergency echocardiogram',
'Call thoracic surgery consult',
'B',
'Tension pneumothorax management: Clinical diagnosis - do not delay for imaging. Classic signs: Hypotension, distended neck veins, absent breath sounds, tracheal deviation (late). Mechanism: One-way valve → progressive air accumulation → mediastinal shift → impaired venous return → cardiac arrest. Immediate treatment: Needle decompression (2nd intercostal space midclavicular or 5th ICS anterior axillary line) followed by definitive chest tube. Life-saving intervention.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has pulseless electrical activity (PEA). Ultrasound shows cardiac motion but no blood in the ventricles. What reversible cause must be immediately addressed?',
'Hypoxia',
'Severe hypovolemia - heart is contracting but has no blood to pump (empty heart syndrome); immediate massive transfusion required',
'Hyperkalemia',
'Hypothermia',
'Acidosis',
'B',
'PEA with empty heart: Ultrasound during CPR can identify reversible causes. Empty ventricles = severe hypovolemia. Heart is contracting (excludes true asystole and VF) but has no preload. This is the mechanism of death in exsanguinating hemorrhage. Immediate massive transfusion essential. Other PEA causes (Hs and Ts): If full/distended heart - consider tamponade, massive PE. Continue resuscitation while addressing reversible cause.',
'hard', 'application'),

-- CRITICAL PROCEDURES
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'An NG tube is placed in a patient with decreased level of consciousness. After insufflation, epigastric gurgling is heard. The patient then coughs with tube manipulation. What should you do?',
'Tube is correctly placed, proceed',
'Obtain chest X-ray before using - clinical confirmation tests are not reliable in obtunded patients; must confirm radiographically',
'Begin feeding immediately',
'Remove tube and start again',
'Assume gastric placement',
'B',
'NG tube confirmation in altered consciousness: Clinical tests (auscultation, aspiration) have high false-positive rates. Coughing may indicate airway placement but may also be reflex. In obtunded/unconscious patients, cough reflex may be absent even with tracheal placement. MUST confirm with chest X-ray before using. X-ray criteria: Tube crosses midline at T10 and tip below diaphragm in stomach. Tracheal misplacement can cause: Aspiration, pneumonia, pneumothorax, death.',
'hard', 'application'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'A post-esophagectomy patient has a feeding jejunostomy tube. The tube becomes blocked. What is the safest approach to clear it?',
'Remove and replace tube surgically',
'Flush with warm water using pulsatile technique; if unsuccessful, try pancreatic enzyme solution or commercial declogging agent',
'Force feed through blockage',
'Abandon tube and use TPN',
'Use guidewire to force through',
'B',
'Feeding tube declogging: Common problem with enteral feeding. First step: Warm water flush with pulsatile (push-pause) technique. If unsuccessful: Pancreatic enzyme solution (dissolves formula precipitate), commercial declogging agents, sodium bicarbonate solution. Avoid: High pressure forcing (risk of tube rupture), sharp guidewires (can perforate tube and bowel). Prevention: Regular flushing, avoid mixing medications in formula, flush before and after medication administration.',
'medium', 'application'),

-- FLUID EMERGENCIES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient on spironolactone for cirrhotic ascites presents confused with peaked T waves on ECG. K+ is 7.2 mmol/L. What is the priority intervention?',
'Oral potassium binders',
'IV calcium gluconate to stabilize cardiac membrane, followed by insulin/glucose and other potassium-lowering measures',
'Dialysis first always',
'Increase spironolactone dose',
'Observe for improvement',
'B',
'Severe hyperkalemia emergency: K+ greater than 6.5 with ECG changes = medical emergency. Cardiac effects: Peaked T waves → flattened P waves → widened QRS → sine wave → VF/asystole. Treatment priority: 1) Calcium gluconate IV - stabilizes cardiac membrane (does not lower K+, works in minutes, lasts 30-60 min). 2) Insulin + glucose - shifts K+ intracellularly. 3) Sodium bicarbonate if acidotic. 4) Beta-2 agonists. 5) Dialysis for definitive removal. Stop potassium-sparing diuretics.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with severe hyponatremia (Na+ 108) is seizing. What is the initial target for sodium correction?',
'Correct to normal immediately',
'Raise sodium by 4-6 mEq/L in first 1-2 hours to stop seizures, then limit to 10-12 mEq/L maximum in first 24 hours',
'No correction needed',
'Wait for seizures to stop naturally',
'Fluid restriction only',
'B',
'Symptomatic hyponatremia treatment: Life-threatening symptoms (seizures, coma) require urgent correction. Hypertonic saline (3% NaCl): 100ml bolus over 10 min, may repeat up to 3 times. Goal: Raise Na+ by 4-6 mEq/L rapidly to stop symptoms. Then slow down: Maximum 10-12 mEq/L in first 24 hours. Risk of over-correction: Osmotic demyelination syndrome (central pontine myelinolysis). Higher risk: Chronic hyponatremia, alcoholism, malnutrition. Balance urgency vs safety.',
'hard', 'application'),

-- BLOOD EMERGENCIES
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient receiving blood develops rigors, back pain, and dark urine. BP drops to 80/50. What is happening and what is the immediate action?',
'Allergic reaction - give antihistamines',
'Acute hemolytic transfusion reaction - stop transfusion immediately, maintain IV access, send blood for repeat crossmatch, support circulation',
'Volume overload - give diuretics',
'TRALI - continue transfusion slowly',
'Febrile reaction - slow transfusion',
'B',
'Acute hemolytic transfusion reaction: Usually ABO incompatibility (clerical error). Symptoms: Fever/chills, flank/back pain, chest tightness, dark urine (hemoglobinuria), hypotension, DIC. Mechanism: Recipient antibodies destroy donor RBCs → free hemoglobin → renal failure, shock, DIC. Immediate action: STOP transfusion, maintain IV access (new line), send blood bag + patient blood to blood bank, support BP, monitor for DIC and renal failure. Often fatal if not recognized.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'During massive transfusion, the patient becomes progressively hypothermic. Core temperature is now 33°C. What coagulation problem is developing?',
'No coagulation effect',
'Hypothermia-induced coagulopathy - clotting enzymes are temperature-dependent and function poorly below 35°C',
'Hyperthermia improves clotting',
'Only DIC causes coagulopathy',
'Platelets function better cold',
'B',
'Hypothermia and coagulation: Clotting cascade is enzymatic - temperature dependent. Below 35°C, clotting factors function poorly. Below 33°C, significant impairment. Lab paradox: Coagulation tests run at 37°C may be normal despite in vivo coagulopathy. Clinical: Continued bleeding despite "normal" labs. Part of lethal triad: Hypothermia + acidosis + coagulopathy. Management: Aggressive warming (blood warmers, forced air warming, warmed fluids). Target normothermia.',
'medium', 'application'),

-- WOUND EMERGENCIES
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with a 24-hour-old wound presents with rapidly spreading erythema, crepitus on palpation, and bronze discoloration. What is the diagnosis and treatment?',
'Cellulitis - oral antibiotics',
'Necrotizing fasciitis - emergent surgical debridement, IV broad-spectrum antibiotics, ICU admission',
'Abscess - I&D only',
'Allergic reaction - antihistamines',
'Chronic wound - dressings',
'B',
'Necrotizing fasciitis: Life-threatening soft tissue infection spreading along fascial planes. Features: Rapid spread, pain out of proportion, crepitus (gas-forming organisms), dusky/bronze skin, bullae, systemic toxicity. Types: Type 1 (polymicrobial), Type 2 (Group A strep). Treatment: EMERGENT wide surgical debridement (often multiple returns to OR), IV antibiotics (broad-spectrum until cultures), ICU support. Delay in surgery = increased mortality. Mortality 20-40% even with treatment.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has sanguineous discharge from the wound on day 5. No bowel is visible. What does this often herald?',
'Normal wound drainage',
'Impending wound dehiscence - serosanguineous "salmon-colored" discharge often precedes fascial breakdown and should prompt urgent evaluation',
'Sign of healing',
'Hematoma only',
'Infection resolved',
'B',
'Wound dehiscence warning: Serosanguineous ("salmon-colored") discharge from abdominal wound at day 5-10 is classic warning sign. Mechanism: Peritoneal fluid leaking through disrupted fascial closure. Next step: Fascial disruption may be imminent. Examine wound carefully (probe for fascial integrity), consider imaging, plan for urgent return to OR if fascial disruption confirmed. Risk factors: Obesity, infection, malnutrition, increased IAP (coughing), technical issues.',
'medium', 'application'),

-- CPR EMERGENCIES
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient arrests in the OR during surgery with an open abdomen. How should CPR be performed?',
'Standard external chest compressions',
'Internal cardiac massage - direct compression of the heart through the open abdomen/thorax is more effective than external compressions',
'CPR not possible with open abdomen',
'Defibrillation only',
'Abandon resuscitation',
'B',
'Internal cardiac massage: Indications - cardiac arrest with open chest/abdomen, penetrating chest trauma, chest deformity preventing external compressions, cardiac tamponade. Technique: Through thoracotomy or subdiaphragmatic approach. Two-hand technique compressing heart against sternum. More effective: Generates 2-3x the cardiac output of external compressions. Continue until ROSC or decision to terminate. OR setting ideal - sterile field, direct visualization.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A patient with VF receives three shocks without conversion. What drug is given next according to ACLS algorithms?',
'Lidocaine only',
'Epinephrine 1mg IV/IO - given after first shock cycle for shockable rhythms, then every 3-5 minutes during resuscitation',
'Atropine',
'Sodium bicarbonate first',
'Calcium chloride',
'B',
'VF/pVT ACLS algorithm: Shock → CPR 2 min → Rhythm check → Shock if still VF → CPR 2 min → Epinephrine 1mg. Then amiodarone (or lidocaine) if VF persists after 2-3 shocks. Epinephrine: Alpha effects (vasoconstriction) improve coronary perfusion pressure during CPR. Given every 3-5 minutes. No survival benefit proven but standard of care. Consider reversible causes (Hs and Ts) throughout.',
'medium', 'application'),

-- TRAUMA EMERGENCIES
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with penetrating neck trauma in zone I (below cricoid) has an expanding hematoma. What is the management priority?',
'Observation and serial exams',
'Secure airway immediately and prepare for operative exploration - expanding hematoma in neck is surgical emergency',
'CT angiography first always',
'Compress the hematoma',
'Discharge with follow-up',
'B',
'Penetrating neck trauma with expanding hematoma: Surgical emergency. Priorities: Airway - may need emergent intubation before airway compromised by hematoma. Early intubation is easier than late. Zone I (below cricoid): Thoracic inlet - risk to great vessels, thoracic duct, apex of lung. Management: May need thoracotomy for proximal control. Expanding hematoma = hard sign requiring operative exploration without delay for imaging.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with blunt abdominal trauma has free fluid on FAST but is hemodynamically stable. CT shows a grade III splenic laceration without active extravasation. What is the appropriate management?',
'Emergent splenectomy',
'Non-operative management with ICU monitoring, serial hematocrits, bed rest - most blunt splenic injuries in stable patients can be managed without surgery',
'Observation on ward',
'Immediate discharge',
'Splenic artery embolization for all',
'B',
'Non-operative management of splenic injury: Revolution in trauma care. Criteria: Hemodynamic stability, no peritonitis, no other indications for laparotomy, able to monitor closely. Protocol: ICU admission, serial hemoglobin/hematocrit, bed rest, NPO initially, SCD/DVT prophylaxis. Success rate: Greater than 85% for blunt injuries in properly selected patients. Failure: Hemodynamic instability, dropping Hct, transfusion requirements. Role of angiography: Consider embolization for contrast blush or high-grade injuries.',
'hard', 'application'),

-- MONITORING EMERGENCIES
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, ETCO2 suddenly drops from 35 to 10 mmHg while SpO2 and BP are falling. What is the most likely cause?',
'Ventilator malfunction',
'Massive pulmonary embolism or cardiac arrest - sudden ETCO2 drop indicates loss of pulmonary blood flow, not just ventilation problem',
'Bronchospasm',
'Extubation occurred',
'Normal ETCO2 variation',
'B',
'Sudden ETCO2 drop: ETCO2 reflects pulmonary blood flow AND ventilation. Sudden drop to near-zero with maintained ventilation = loss of cardiac output. Causes: Cardiac arrest, massive PE, severe hypovolemia, air embolism. Immediate assessment: Check pulse, blood pressure. If pulseless: Start CPR. ETCO2 during CPR: Less than 10 mmHg suggests poor chest compressions or non-survivable state. Greater than 20 mmHg associated with better outcomes.',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'An arterial line shows blood pressure 180/120 mmHg during surgery, but the patient appears poorly perfused. What could explain this discrepancy?',
'Accurate measurement - treat hypertension',
'Arterial catheter is kinked or against vessel wall causing overdamping or whip artifact; flush and reposition, compare with cuff pressure',
'Monitor always accurate',
'Patient is hypertensive',
'No action needed',
'B',
'Arterial line artifacts: Technology can give false readings. Overdamping: Kink, clot, air, loose connections → underestimates systolic, overestimates diastolic. Underdamping (catheter whip): Resonance → overestimates systolic. Troubleshooting: Flush line (square wave test), check connections, reposition catheter. Validate: Compare with non-invasive cuff pressure. Clinical correlation essential - if numbers don''t match clinical picture, verify the measurement.',
'medium', 'application');
