-- ============================================================================
-- BATCH 57: Integrated Surgical Care and Systems-Based Scenarios
-- Topics: Healthcare system, quality, safety, and communication
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- SURGICAL SAFETY
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'Before incision, the WHO Surgical Safety Checklist requires confirmation of what key elements?',
'Patient name only',
'Team member introduction, patient identity, site marking, consent, allergies, anticipated critical events, antibiotic prophylaxis, DVT prophylaxis, imaging',
'Surgeon name only',
'Time of day only',
'Equipment list only',
'B',
'WHO Surgical Safety Checklist elements: Three phases - Sign In (before anesthesia), Time Out (before incision), Sign Out (before leaving OR). Time Out confirms: Patient ID, procedure, site, consent, antibiotic prophylaxis (within 60 min), DVT prophylaxis, imaging available. Team introduction improves communication. Anticipated blood loss, critical steps discussed. Sign Out: Counts correct, specimens labeled, equipment issues documented. Implementation reduces surgical complications by 30%+.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A wrong-site surgery nearly occurs but is caught during timeout. This is classified as what type of safety event?',
'Sentinel event',
'Near miss - an error that could have caused patient harm but was intercepted before reaching the patient; should be reported and analyzed',
'Never event',
'Expected complication',
'Not reportable',
'B',
'Safety event classification: Near miss (good catch) - error occurred but did not reach patient (caught by safety barrier). No harm event - reached patient but no harm. Adverse event - reached patient and caused harm. Sentinel event - serious harm, death, or serious disability. Never events - should never happen (wrong site, retained foreign body). Near misses are valuable for learning - analyze to strengthen barriers. Encourage reporting without punitive response.',
'medium', 'application'),

-- COMMUNICATION
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A nurse calls you at night about a post-operative patient with low blood pressure. What structured communication tool helps ensure complete information transfer?',
'Unstructured conversation',
'SBAR - Situation, Background, Assessment, Recommendation - provides systematic framework for urgent clinical communication',
'Email communication',
'Text messaging only',
'Wait until morning rounds',
'B',
'SBAR communication: Structured handoff tool. Situation - what is happening now (patient X has BP 80/50). Background - relevant history (POD 1 from colectomy, was stable). Assessment - what I think is happening (possible bleeding or sepsis). Recommendation - what I think should be done (suggest fluid bolus, labs, evaluate patient). Benefits: Reduces communication errors, ensures key information transferred, empowers all team members. Used for handoffs, calls, escalation.',
'easy', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'Informed consent for surgery must include what key elements?',
'Only procedure name',
'Diagnosis, proposed procedure, risks, benefits, alternatives (including non-treatment), and opportunity to ask questions',
'Surgeon''s preference',
'Hospital policy only',
'Insurance coverage',
'B',
'Informed consent elements: Legal and ethical requirement. Must include: Diagnosis/condition, proposed procedure and how performed, expected benefits, material risks and complications, alternatives to procedure, risks of alternatives, risk of no treatment. Patient must: Have capacity to consent, receive information in understandable language, consent voluntarily without coercion, have opportunity to ask questions. Document: Signature, date, witness. Consent is a process, not just a signature.',
'easy', 'application'),

-- QUALITY IMPROVEMENT
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A surgeon notices an increase in surgical site infections in their practice. What is the first step in quality improvement methodology?',
'Immediately change technique',
'Define the problem with data - measure current infection rate, identify patterns, determine if increase is real or random variation',
'Blame other team members',
'Ignore the observation',
'Report to media',
'B',
'Quality improvement methodology: PDSA (Plan-Do-Study-Act) or DMAIC (Define-Measure-Analyze-Improve-Control). First step: Define and measure the problem. Questions: Is the increase statistically significant? What are the specifics (which operations, which organisms)? What are current processes? Only with data can you: Identify root causes, target interventions, measure improvement. Rushing to solutions without understanding problem often fails.',
'medium', 'application'),

-- SPECIFIC CLINICAL SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with acute mesenteric ischemia has bowel that looks dusky but not frankly necrotic. What is the appropriate approach?',
'Resect all questionable bowel',
'Perform revascularization if possible, assess bowel viability after reperfusion, consider second-look laparotomy in 24-48 hours',
'Close without intervention',
'Total colectomy for all',
'Stoma only',
'B',
'Acute mesenteric ischemia - borderline bowel: Bowel viability may improve after revascularization. Assessment after reperfusion: Color, peristalsis, arterial pulsation. Adjuncts: Doppler, fluorescein, indocyanine green. If uncertain: Resect only frankly necrotic bowel, leave questionable bowel, plan second-look laparotomy (scheduled return in 24-48 hours). Better to re-explore than resect viable bowel. Consider damage control principles.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient has urine output of 15 ml/hr for the past 4 hours. They received adequate intraoperative fluids. What is the differential diagnosis approach?',
'Oliguria is always normal post-op',
'Systematic approach: Pre-renal (hypovolemia, hypotension), renal (ATN, nephrotoxins), post-renal (obstruction); check catheter patency first',
'Start dialysis immediately',
'Ignore if BP normal',
'Fluid restrict',
'B',
'Post-operative oliguria: Normal urine output greater than 0.5 ml/kg/hr. Systematic approach: Post-renal (most easily fixed) - check catheter patency, flush or replace if blocked. Pre-renal (most common) - assess volume status, give fluid challenge if hypovolemic. Renal (intrinsic) - ATN from hypoperfusion, nephrotoxins (contrast, NSAIDs, aminoglycosides). Labs: BUN/Cr ratio, urine sodium, FENa help differentiate. Early intervention prevents progression.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A clean surgical wound is inspected on post-operative day 2. It appears well-approximated with no erythema or discharge. What is the appropriate dressing strategy?',
'Leave original dressing indefinitely',
'Dressing may be removed at 24-48 hours; keep wound clean and dry; no evidence that keeping wound covered beyond this improves outcomes',
'Change dressing every 4 hours',
'Leave wound open to air immediately',
'Apply antibiotic ointment heavily',
'B',
'Clean surgical wound dressing: Primary closure wounds epithelialize superficially within 24-48 hours. After this, external contamination risk minimal. Evidence: No benefit to prolonged dressings on clean, primarily closed wounds. Recommendations: Remove dressing at 24-48 hours, keep clean and dry. Patient can shower (avoid soaking). Watch for signs of infection. Draining wounds or wounds at high infection risk may need longer dressing.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon is closing the abdomen and the scrub nurse notes only 9 of 10 laparotomy sponges have been counted. What is the appropriate response?',
'Accept the count - one may be in trash',
'Stop, recount, search the field systematically, and if not found, obtain intraoperative X-ray before closing',
'Close anyway and X-ray later',
'Complete documentation and proceed',
'Ignore nursing concern',
'B',
'Retained surgical item prevention: Incorrect count = mandatory pause. Steps: Recount all sponges. Systematic wound search (all quadrants, behind viscera). Search drapes, floor, trash. If still not found: Intraoperative X-ray mandatory (sponges have radio-opaque markers). Do not close until resolved. Consequences of retained sponge: Abscess, fistula, obstruction, sepsis, reoperation, malpractice. All team members responsible for count.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient is being transfused and develops urticaria (hives) without fever or hemodynamic changes. What is the management?',
'Stop transfusion and discard blood',
'Pause transfusion, give antihistamine, observe; if symptoms resolve and no systemic features, may resume transfusion slowly',
'Give epinephrine immediately',
'Continue transfusion unchanged',
'Emergency intubation',
'B',
'Allergic transfusion reaction (mild): Urticaria, itching without systemic symptoms. Mechanism: Reaction to plasma proteins. Management: Pause transfusion (do not disconnect), give antihistamine (diphenhydramine). If symptoms resolve in 30 minutes and no fever, hypotension, or respiratory symptoms: May resume transfusion slowly. More severe allergic/anaphylactic: Stop transfusion, epinephrine, airway management. IgA deficiency patients have severe reactions to plasma products.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient''s X-ray shows an undisplaced radial head fracture. They have full range of motion with mild pain. What is the treatment?',
'ORIF for all radial head fractures',
'Conservative management with sling, early mobilization, and physiotherapy - undisplaced radial head fractures with preserved ROM do well without surgery',
'Cast in full extension',
'Radial head excision',
'No treatment needed',
'B',
'Undisplaced radial head fracture: Mason Type I. Management: Conservative - collar and cuff or sling for comfort (1-2 weeks maximum). Early mobilization essential (prevent stiffness). No immobilization beyond comfort care. Aspiration of joint hematoma may relieve pain and improve motion. Outcomes: Excellent with early mobilization. Surgery reserved for: Displaced fractures (Mason II with block), comminuted fractures (Mason III), associated instability.',
'easy', 'application'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'When examining a patient with abdominal pain, what finding most specifically suggests peritonitis?',
'Voluntary guarding',
'Involuntary guarding and rebound tenderness - these represent reflex muscle spasm and peritoneal irritation from inflammation',
'Normal bowel sounds',
'Mild tenderness only',
'Soft abdomen',
'B',
'Peritoneal signs: Involuntary guarding - reflex muscle contraction that patient cannot relax (vs voluntary guarding that relaxes with distraction). Rebound tenderness - pain on release of pressure (peritoneum stretches). Rigidity ("board-like" abdomen) - extreme involuntary guarding. Other signs: Absent bowel sounds, patient lies still (movement worsens pain). These findings indicate peritoneal inflammation requiring urgent evaluation/surgery.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'In the ICU, a patient''s central line appears to have migrated out partially. What is the concern and management?',
'Continue using the line',
'Stop infusions immediately - tip may be in subcutaneous tissue or smaller vein; risk of extravasation of caustic medications; replace the line',
'Push line back in',
'Increase infusion rate',
'Ignore position change',
'B',
'Catheter migration management: Central line tip should be in SVC or right atrium. Migration out: Tip may be in smaller vein or even subcutaneous tissue. Risks: Extravasation of caustic medications (vasopressors, TPN, chemo), thrombosis, line malfunction. Management: Stop infusions (especially vesicants), do not push line in (contaminated exposed portion), confirm position with CXR, replace line if position inadequate. Never advance a partially withdrawn catheter.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'How should post-resuscitation care be managed after successful ROSC (return of spontaneous circulation)?',
'No special care needed after ROSC',
'Targeted temperature management, optimize oxygenation and ventilation, hemodynamic support, identify and treat precipitating cause, neuroprognostication after 72 hours',
'Immediate discharge',
'Extubate immediately',
'No monitoring required',
'B',
'Post-cardiac arrest care: ROSC is not the end - post-arrest syndrome causes significant morbidity/mortality. Bundle: Targeted temperature management (TTM 32-36°C for comatose patients), optimize hemodynamics (MAP >65, avoid hypotension), controlled oxygenation (avoid hyperoxia), ventilation targets (normocapnia), seizure treatment, coronary angiography if suspected cardiac cause. Neuroprognostication: Wait 72+ hours, multimodal approach. ICU admission mandatory.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A patient with a chronic venous leg ulcer asks about their long-term prognosis. What should they understand?',
'Ulcer will cure permanently',
'Venous ulcers have high recurrence rate without lifelong compression; underlying venous disease is chronic and management is ongoing',
'No treatment helps',
'Recurrence is rare',
'Compression not important after healing',
'B',
'Venous ulcer prognosis: Healing rates 50-70% at 6 months with good care. Recurrence: 30-50% within 1 year, up to 70% long-term. Why: Underlying venous hypertension persists (valve damage, reflux). Prevention requires: Lifelong compression (knee-high stockings 20-30 or 30-40 mmHg), skin care, leg elevation, exercise. May benefit from: Venous ablation or surgery for superficial reflux. Chronic disease model - ongoing management essential.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'A patient''s TPR chart shows spiking fevers every 8 hours starting post-op day 3 with rigors. What pattern is this and what source should be suspected?',
'Normal post-operative fever',
'Hectic/septic fever pattern - suggests bacteremia, often from an abscess or infected line; blood cultures and source control needed',
'Drug fever only',
'Atelectasis',
'DVT',
'B',
'Fever patterns: Hectic/septic fever - high spiking fevers with intervals of normal or low temperature, often with rigors. Suggests: Bacteremia with intermittent seeding from a source (abscess, line infection, endocarditis). Sustained fever - suggests continuous source. Timing post-op: POD 3-5 for intra-abdominal abscess after GI surgery. Workup: Blood cultures (during spike if possible), source investigation (CT for abscess, line cultures). Treatment: Source control essential.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A patient with long-term indwelling urinary catheter develops new confusion and low-grade fever. Urinalysis shows bacteria. How should this be interpreted?',
'Always treat bacteriuria in catheterized patients',
'Catheter-associated asymptomatic bacteriuria is common; only treat if symptomatic CAUTI (catheter-associated UTI) with specific symptoms beyond just bacteria in urine',
'Change catheter only',
'Remove catheter permanently',
'Long-term antibiotics',
'B',
'Catheter-associated bacteriuria: Nearly all long-term catheterized patients develop bacteriuria (biofilm colonization). Asymptomatic bacteriuria: Should NOT be treated - treatment promotes resistance without benefit. CAUTI diagnosis: Requires symptoms attributable to UTI (fever, CVA tenderness, rigors) + bacteriuria, and exclusion of other sources. In confused/elderly, UTI often over-diagnosed. Confusion alone is not specific for UTI - investigate other causes before attributing to UTI.',
'medium', 'application');
