-- ============================================================================
-- BATCH 58: Perioperative Care Excellence Scenarios
-- Topics: Pre, intra, and post-operative management details
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- PRE-OPERATIVE CARE
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient scheduled for elective surgery has an upper respiratory infection with productive cough. When should surgery be postponed?',
'Never postpone for URI',
'Postpone 2-4 weeks if lower respiratory symptoms, fever, or if general anesthesia planned - airway reactivity increases perioperative respiratory complications',
'Postpone 6 months',
'Only postpone if hospitalized for URI',
'URI has no anesthetic implications',
'B',
'URI and surgery timing: Active URI increases: Bronchospasm, laryngospasm, hypoxemia, atelectasis, pneumonia. Risk highest in children, with ETT intubation, lower respiratory involvement. Recommendations: Mild URI without lower symptoms in adult - may proceed with caution. Productive cough, fever, lower respiratory symptoms - postpone 2-4 weeks until resolved. Airway reactivity persists for weeks after URI resolution.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the recommended fasting time before elective surgery for clear liquids versus solid food?',
'No fasting needed for minor surgery',
'Clear liquids 2 hours, light meal 6 hours, fatty/fried foods 8 hours before anesthesia to reduce aspiration risk',
'All patients fast 24 hours',
'Fasting only for general anesthesia',
'Same fasting time for all intake',
'B',
'NPO guidelines (ASA): Clear liquids (water, black coffee, pulp-free juice) - 2 hours. Breast milk - 4 hours. Infant formula, non-human milk - 6 hours. Light meal (toast and clear liquids) - 6 hours. Fried/fatty foods, meat - 8 hours. Rationale: Gastric emptying time varies. Aspiration risk from full stomach. Exception: Emergency surgery - cannot wait, take aspiration precautions. Enhanced recovery: Clear carb drinks 2 hours before reduce insulin resistance.',
'easy', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient on warfarin for atrial fibrillation needs elective surgery. CHA2DS2-VASc score is 4. How should anticoagulation be managed?',
'Stop warfarin, no bridging ever',
'Stop warfarin 5 days before, consider bridging with LMWH based on thrombotic risk, restart warfarin postoperatively when hemostasis adequate',
'Continue warfarin unchanged',
'Stop warfarin day of surgery',
'Permanent warfarin discontinuation',
'B',
'Perioperative warfarin management: Stop 5 days before surgery (allows INR to normalize). Bridging decision based on thrombotic risk: High risk (CHA2DS2-VASc ≥5, recent stroke, mechanical valve) - bridge with LMWH. Moderate risk - individualize. Low risk - no bridging. LMWH: Stop 24 hours before surgery. Post-op: Restart LMWH when hemostasis adequate (24-48 hrs), restart warfarin when tolerating oral intake. BRIDGE trial: Questions benefit of bridging in AF.',
'hard', 'application'),

-- INTRAOPERATIVE CARE
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During surgery, the patient develops sudden severe hypoxemia (SpO2 75%). What is the systematic approach to diagnose and treat?',
'Increase FiO2 only',
'ABC approach: Airway (ETT position, patency), Breathing (bilateral breath sounds, ventilation), Circulation (BP, oxygenation), then consider specific causes',
'Immediate blood transfusion',
'Wake patient up',
'Abort surgery immediately',
'B',
'Intraoperative hypoxemia algorithm: Immediate: Increase FiO2 to 100%, hand ventilate (assess compliance). Airway: ETT in trachea? (Esophageal or right mainstem?) Patent? (Kink, secretions, blood?). Breathing: Bilateral breath sounds? Pneumothorax? Bronchospasm? Equipment: Circuit disconnect? Ventilator failure? Specific causes: Aspiration, anaphylaxis, fat embolism, PE. While troubleshooting: Maintain oxygenation as priority. Consider surgical causes (retraction, positioning).',
'hard', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is the normal range for end-tidal CO2 (ETCO2) during controlled ventilation and what does it reflect?',
'Any value is acceptable',
'Normal 35-45 mmHg; reflects adequacy of ventilation and indirectly cardiac output; trends are often more important than absolute values',
'Should be zero',
'Only measured during CPR',
'Same as arterial CO2',
'B',
'ETCO2 interpretation: Normal range 35-45 mmHg (usually 2-5 mmHg less than arterial). Reflects: Ventilation adequacy (↑CO2 = hypoventilation), metabolic rate (↑CO2 = fever, MH), cardiac output (↓CO2 = low output, PE), circuit integrity. Trends: Sudden ↓ = disconnect, cardiac arrest, PE. Gradual ↑ = hypoventilation, ↑metabolism. Waveform: Plateau should be present. No plateau = incomplete expiration. Essential intraoperative monitor.',
'medium', 'application'),

-- POST-OPERATIVE CARE
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient has persistent nausea and vomiting 6 hours after laparoscopic cholecystectomy despite antiemetics. What risk factors and treatments are relevant?',
'PONV is rare',
'Risk factors: Female, non-smoker, history of PONV/motion sickness, use of volatile anesthetics and opioids; multimodal antiemetic therapy recommended',
'Only treat if dehydrated',
'PONV not a real condition',
'Unrelated to surgery or anesthesia',
'B',
'Post-operative nausea and vomiting (PONV): Common complication (30% without prophylaxis). Risk factors: Female, non-smoker, history PONV/motion sickness, volatile anesthetics, opioids, nitrous oxide. Surgery types: Laparoscopic, gynecologic, strabismus. Prevention: Identify high-risk patients, multimodal prophylaxis (ondansetron + dexamethasone +/- others), TIVA instead of volatile, opioid-sparing analgesia. Treatment: Different class antiemetic from prophylaxis used.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'Post-operative day 1 fever is very common. What is the most likely cause?',
'Urinary tract infection',
'Atelectasis or inflammatory response to surgery - infection is unlikely this early; deep breathing exercises and mobilization are appropriate',
'Wound infection',
'DVT',
'Anastomotic leak',
'B',
'POD 1 fever: Very common, usually non-infectious. Causes: Atelectasis (hypoventilation, splinting from pain), systemic inflammatory response to surgical stress. Management: Encourage deep breathing (incentive spirometry), early mobilization, adequate analgesia to allow breathing. Investigation: Usually not needed for low-grade POD 1 fever without other concerning features. "Wind, Water, Wound, Walking" mnemonic: Fever timing helps identify source.',
'easy', 'application'),

-- ENHANCED RECOVERY
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'Enhanced Recovery After Surgery (ERAS) protocols include what key elements?',
'Maximum bed rest post-op',
'Preoperative counseling, carbohydrate loading, multimodal analgesia, early feeding, early mobilization, minimizing tubes and drains',
'Prolonged fasting before and after',
'Maximum opioid use for comfort',
'Extended hospital stay',
'B',
'ERAS principles: Preoperative - patient education, nutritional optimization, carbohydrate drink 2-3 hours before. Intraoperative - goal-directed fluid therapy, normothermia, minimally invasive surgery when possible, multimodal opioid-sparing analgesia. Postoperative - early oral intake (same day), early mobilization (day of surgery), early catheter/drain removal, multimodal analgesia. Outcomes: Reduced length of stay, complications, and costs without increased readmission.',
'medium', 'application'),

-- SPECIFIC SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient in hypovolemic shock has improved blood pressure with fluids but urine output remains low at 20 ml/hr. What does this indicate?',
'Adequate resuscitation',
'May indicate ongoing hypovolemia, renal injury from hypoperfusion, or need for additional resuscitation targets beyond blood pressure alone',
'Normal finding',
'Require no intervention',
'Bladder catheter problem',
'B',
'Resuscitation endpoints: Blood pressure alone is insufficient marker. Low UOP despite BP improvement suggests: Ongoing hypovolemia (may need more fluid), renal injury from initial hypoperfusion (ATN developing), or redistribution of flow away from kidneys. Additional markers: Lactate clearance, base deficit improvement, mixed venous O2 saturation, urine output trend. Goal: Restore adequate tissue perfusion, not just blood pressure.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient receiving IV fluids develops peripheral edema and lung crackles but has low urine output. What condition may be developing?',
'Normal fluid distribution',
'Fluid overload with third-spacing - fluids are not staying intravascular, causing edema while intravascular volume may still be inadequate',
'Adequate hydration',
'Impossible scenario',
'Pulmonary embolism',
'B',
'Capillary leak and third-spacing: In inflammation/sepsis, capillary permeability increases. Fluids given IV leak into interstitium. Result: Peripheral edema, pulmonary edema (extravascular), BUT intravascular volume may remain low (explains low UOP). Clinical challenge: Need intravascular volume for perfusion, but fluids worsen edema. Approach: Judicious fluids, consider vasopressors earlier, colloids may stay intravascular better (debated), diuresis when resolving.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A surgical wound appears to be healing well at 2 weeks, but the patient asks about final scar appearance. When is scar remodeling complete?',
'By 2 weeks',
'Scar remodeling continues for 1-2 years; initial scars may be raised and red, gradually fading and flattening over months to years',
'By 1 month',
'Never changes after surgery',
'Complete by 3 days',
'B',
'Scar maturation: Wound healing phases - Inflammatory (days), Proliferative (weeks), Remodeling (months to years). Initial scar: May be raised, red, firm. Over time: Collagen remodeling (type III replaced by type I), vascularity decreases, scar softens and flattens, color fades. Timeline: 6-12 months for major improvement, up to 2 years for final appearance. Factors affecting scar: Genetics, wound tension, location, skin type, age. Scar therapies: Silicone sheets, compression, after complete healing.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What suture technique minimizes wound tension and is used for high-tension closures like fascia?',
'Simple interrupted sutures',
'Far-far-near-near or figure-of-eight sutures distribute tension and resist pull-through better than simple sutures',
'Subcuticular suture',
'Simple continuous suture',
'Mattress sutures are weaker',
'B',
'High-tension suture techniques: Far-far-near-near (mattress variants): Takes wide bites far from edge plus near bites, distributes tension. Figure-of-eight: Crosses tissue, locks in place. Retention sutures: Large through-and-through sutures for very high tension (obesity, infection risk). Principles: Wide bites hold better than superficial ones, more sutures distribute tension, non-absorbable or slowly absorbable for fascia. Prevent dehiscence by adequate technique.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient requires emergency surgery but has a congenital clotting disorder (hemophilia A). What factor must be replaced and to what level?',
'No replacement needed',
'Factor VIII to 80-100% before major surgery; maintain 50-80% for 7-10 days post-operatively for wound healing',
'Factor IX replacement',
'Platelet transfusion only',
'Vitamin K only',
'B',
'Hemophilia A surgical management: Factor VIII deficiency. Preoperative: Raise Factor VIII to 80-100% (of normal) before incision. Maintenance: 50-80% for 1 week (minor surgery shorter). Products: Recombinant Factor VIII, plasma-derived concentrates. Monitoring: Factor VIII levels, not just PTT. Calculate dose based on weight and desired rise. Involve hematology early. May need continuous infusion or q8-12h dosing. Watch for inhibitor development.',
'hard', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with a fracture asks about timeline for bone healing. What is the typical sequence and duration for fracture union?',
'Complete healing in 1 week',
'Hematoma formation, inflammation (days), soft callus (weeks 2-3), hard callus (weeks 3-12), remodeling (months to years); total time depends on fracture type and patient factors',
'Bone never fully heals',
'Healing complete by day 5',
'No predictable timeline',
'B',
'Fracture healing phases: 1) Hematoma/inflammation (days) - blood clot, inflammatory cells. 2) Soft callus (weeks 2-3) - fibrocartilaginous tissue bridges fracture. 3) Hard callus (weeks 3-12) - woven bone replaces soft callus. 4) Remodeling (months to years) - woven bone replaced by lamellar bone along stress lines. Timeline varies: Children faster, elderly slower. Shaft fractures 3-4 months, some fractures 6+ months. Factors affecting: Blood supply, stability, age, nutrition, comorbidities.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the minimum compression depth and rate for effective adult CPR according to current guidelines?',
'2 cm depth at any rate',
'At least 5-6 cm depth, rate 100-120 compressions per minute, with full chest recoil and minimal interruptions',
'1 cm depth is sufficient',
'50 compressions per minute',
'Depth does not matter',
'B',
'CPR quality metrics: Depth: At least 5 cm (2 inches), not more than 6 cm. Rate: 100-120 per minute. Full recoil: Allow chest to completely recoil between compressions (enables venous return). Minimize interruptions: CCF (chest compression fraction) should be >60%, ideally >80%. Feedback devices can help maintain quality. Rotate compressors every 2 minutes. Quality CPR is the foundation of resuscitation - medications and defibrillation are secondary.',
'easy', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of lipodermosclerosis in venous disease?',
'Sign of healing',
'Indicates severe chronic venous insufficiency with fibrosis of subcutaneous tissue; associated with high ulcer risk and poor healing potential',
'Normal aging change',
'Indicates arterial disease',
'Benign finding requiring no intervention',
'B',
'Lipodermatosclerosis: "Champagne bottle leg" or "inverted bowling pin" appearance. Pathology: Chronic venous hypertension → inflammation → fibrosis of subcutaneous fat and dermis. Features: Indurated, hyperpigmented skin, often above medial malleolus. Significance: Indicates severe, long-standing venous disease. Associates with: Higher ulcer risk, poor healing, difficult compression (fibrosis). Management: Aggressive compression, elevation, skin care. May need specialized compression for bound-down skin.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What blood conservation strategy is most effective for reducing allogeneic transfusion in elective major surgery?',
'Single intervention is sufficient',
'Multimodal patient blood management program - combining preoperative optimization, intraoperative techniques, and restrictive transfusion thresholds is more effective than single interventions',
'Only cell salvage matters',
'Autologous predonation alone',
'No intervention is effective',
'B',
'Patient Blood Management (PBM): Comprehensive, multimodal approach. Three pillars: 1) Optimize erythropoiesis (treat anemia preoperatively - iron, B12, folate, EPO). 2) Minimize blood loss (surgical technique, antifibrinolytics, cell salvage, normothermia, positioning). 3) Harness and optimize tolerance of anemia (restrictive transfusion thresholds). Evidence: Reduces transfusion, improves outcomes, cost-effective. Institutional programs with bundled interventions most effective.',
'medium', 'application');
