-- ============================================================================
-- BATCH 59: Clinical Mastery Scenarios - Advanced Integration
-- Topics: High-level clinical reasoning and decision-making
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- CLINICAL MASTERY
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 65-year-old with diabetes, hypertension, and previous MI needs emergent surgery for perforated diverticulitis. What preoperative cardiac workup is appropriate?',
'Full cardiac catheterization first',
'Proceed with surgery - emergent surgery should not be delayed for cardiac testing; perioperative beta-blockers and close monitoring are appropriate',
'Stress test before surgery',
'Cancel surgery for cardiac optimization',
'No cardiac considerations needed',
'B',
'Preoperative cardiac evaluation: ACC/AHA guidelines. Emergency surgery: Proceed without delay for testing - risk of delaying surgery exceeds cardiac risk. Manage with perioperative: Beta-blockers (continue if already taking), monitoring, avoid hypotension/tachycardia, statin continuation. Reserve cardiac testing for: Elective surgery with high-risk factors AND active cardiac conditions. Risk stratification (RCRI): Helps identify high-risk patients for postoperative monitoring.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient develops new-onset atrial fibrillation with rapid ventricular response (rate 150) immediately post-operatively. They are hemodynamically stable. What is the initial management?',
'Immediate cardioversion',
'Rate control with beta-blocker or diltiazem, correct underlying causes (pain, hypovolemia, electrolytes), anticoagulation consideration if persists',
'Amiodarone loading',
'Digoxin only',
'No treatment for new AF',
'B',
'Post-operative AF: Common after thoracic and major surgery (25-40% after cardiac surgery). Initial management if stable: Rate control first (beta-blocker, calcium channel blocker). Address precipitants: Pain, hypovolemia, hypoxia, electrolyte imbalance (K+, Mg2+). Often self-limited. Anticoagulation: Consider if persists >48 hours based on stroke risk. Cardioversion: If hemodynamically unstable or rate control fails. Rhythm control not superior to rate control acutely.',
'hard', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A post-operative patient develops hypotension, tachycardia, and fever on POD 3. Lactate is elevated. What type of shock and what is the priority?',
'Hypovolemic shock from NPO',
'Likely septic shock - source control is priority; obtain cultures, start broad-spectrum antibiotics, consider imaging for surgical complication (leak, abscess)',
'Cardiogenic from MI',
'Anaphylaxis from medications',
'Normal post-operative state',
'B',
'POD 3 septic shock: Timing suggests surgical complication. Common sources: Anastomotic leak, abscess, wound infection. Management: Sepsis bundle - cultures before antibiotics (but don''t delay abx), broad-spectrum antibiotics immediately, fluid resuscitation, vasopressors if needed. Source control: CT to identify collection, drainage or reoperation as needed. Source control essential - antibiotics alone will not cure abscess. Early intervention improves survival.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What clinical finding best distinguishes cardiogenic from hypovolemic shock?',
'Blood pressure alone',
'Jugular venous distension - elevated in cardiogenic (heart failure), flat in hypovolemic (volume depleted)',
'Heart rate alone',
'Respiratory rate',
'Temperature',
'B',
'Shock differentiation: JVD reflects right heart filling pressure. Hypovolemic: Low preload → flat neck veins, collapsed IVC on ultrasound. Cardiogenic: Elevated filling pressure (heart failing) → JVD, distended IVC. Other signs: Cardiogenic - lung crackles, S3, cold extremities. Hypovolemic - clear lungs, tachycardia. Mixed presentation possible. Bedside ultrasound valuable: IVC collapsibility, cardiac function, lung B-lines.',
'medium', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with prolonged high-output GI fistula has Na+ 155, and clinical signs of volume depletion. What type of dehydration and initial fluid choice?',
'Hypotonic dehydration',
'Hypernatremic (hypertonic) dehydration - initial resuscitation with isotonic fluid (0.9% saline), then slow correction of hypernatremia to avoid cerebral edema',
'Isotonic dehydration only',
'No dehydration present',
'Give hypotonic fluids rapidly',
'B',
'Hypernatremic dehydration: Free water lost in excess of sodium (or sodium given in excess). Causes: High-output fistula (losing hypotonic fluid), inadequate free water intake, osmotic diuresis. Management: First stabilize hemodynamics with isotonic crystalloid. Then correct hypernatremia slowly (0.5 mEq/L/hour, max 10-12 mEq/L/day) - rapid correction causes cerebral edema (brain cells adapted to hypertonicity). Use hypotonic fluids for correction phase.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is syndrome of inappropriate ADH secretion (SIADH) and how is it managed?',
'Excess sodium intake',
'Excess ADH causes water retention, dilutional hyponatremia; managed with fluid restriction, salt tablets, or in severe cases, vasopressin receptor antagonists',
'Sodium loss in urine',
'Kidney failure causing hyponatremia',
'Related to blood transfusion',
'B',
'SIADH: Inappropriate ADH secretion (regardless of osmolality) → water retention → dilutional hyponatremia → concentrated urine despite low serum osmolality. Causes: CNS disorders, pulmonary disease, medications, malignancy, post-surgical. Diagnosis: Hyponatremia + concentrated urine (>100 mOsm) + euvolemia + urine Na >40. Management: Fluid restriction (800-1000ml/day), salt tablets, demeclocycline, vaptans. Treat underlying cause. Avoid rapid overcorrection.',
'medium', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What are the indications for platelet transfusion in a surgical patient?',
'Any count below 150,000',
'Threshold depends on bleeding risk: <10,000 for prophylaxis, <50,000 for procedures, <100,000 for neurosurgery or active life-threatening bleeding',
'Never transfuse platelets',
'Only for counts below 5,000',
'Transfuse all patients before surgery',
'B',
'Platelet transfusion thresholds: Prophylactic (stable, no bleeding): <10,000/μL (some use <5,000). Minor procedures (lines, biopsy): <20,000. Major surgery: <50,000. Neurosurgery, ocular surgery, massive bleeding: <100,000. Each platelet unit raises count 5,000-10,000. Consider: Function vs count (uremia, drugs affect function). HIT: Avoid platelets if heparin-induced thrombocytopenia. ITP: May not respond well to transfusion.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'How does prothrombin complex concentrate (PCC) differ from FFP for warfarin reversal?',
'No difference between products',
'PCC provides concentrated factors II, VII, IX, X in smaller volume with faster reversal and lower TACO risk compared to FFP',
'FFP works faster than PCC',
'PCC contains only Factor VII',
'PCC cannot reverse warfarin',
'B',
'PCC vs FFP for warfarin reversal: FFP: Contains all factors but large volume (15 mL/kg needed), slow to thaw, slow to administer, risk of TACO. PCC: Concentrated factors (small volume), rapid administration, faster INR correction (minutes vs hours). Types: 3-factor (II, IX, X) or 4-factor (adds VII). 4-factor preferred. Guidelines recommend PCC + vitamin K for major bleeding on warfarin. FFP only if PCC unavailable.',
'medium', 'application'),

-- WOUND HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What systemic condition impairs wound healing most directly through its effect on microvascular disease?',
'Obesity',
'Diabetes mellitus - hyperglycemia impairs neutrophil function and microvascular disease compromises tissue perfusion',
'Hypertension',
'Hyperlipidemia',
'Anxiety',
'B',
'Diabetes and wound healing: Multiple mechanisms. Hyperglycemia: Impairs neutrophil chemotaxis, phagocytosis, bactericidal activity → increased infection. Glycosylation of proteins → abnormal collagen. Microvascular disease: Endothelial dysfunction, reduced tissue perfusion. Neuropathy: Unrecognized trauma, pressure injury. Management: Optimize glucose control (target HbA1c), ensure adequate perfusion, aggressive infection treatment, offloading for neuropathic ulcers. Diabetic wounds require more aggressive care.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What medication class commonly used in surgery impairs wound healing and how can this be mitigated?',
'Antibiotics impair healing',
'Corticosteroids impair healing by suppressing inflammation; can be mitigated by vitamin A supplementation and using lowest effective dose',
'Beta-blockers affect wounds',
'Antiemetics impair healing',
'Antihypertensives affect wounds',
'B',
'Corticosteroids and wound healing: Mechanism - suppress inflammatory phase of healing, reduce collagen synthesis, impair angiogenesis, increase infection risk. Effect: Delayed healing, reduced wound strength, higher dehiscence rates. Mitigation: Vitamin A (topical or systemic) partially reverses steroid effects on healing. Surgical planning: Lowest effective steroid dose, nutritional optimization, careful wound closure technique, extended suture retention.',
'medium', 'application'),

-- SUTURES AND INSTRUMENTS
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What factors determine appropriate suture size selection for wound closure?',
'Largest available suture for strength',
'Tissue type, wound tension, cosmetic considerations - use smallest suture that provides adequate strength to minimize tissue reaction',
'Same size for all wounds',
'Smallest available regardless of tension',
'Suture size does not matter',
'B',
'Suture size selection: Principles: Smallest suture providing adequate holding strength. Larger sutures: More tissue reaction, worse cosmesis, scar marks. Selection by tissue: Fascia - large (0, 1), subcutaneous - medium (2-0, 3-0), skin - small (4-0 to 6-0 face), vessels - fine (5-0 to 7-0). Consider: Wound tension (higher tension = stronger suture), tissue quality (friable tissue = larger bites, potentially larger suture), cosmetic area (smaller suture for face).',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the proper technique for instrument tie versus hand tie for suture knot?',
'Both identical technique',
'Instrument tie uses needle driver to wrap and pull suture; conserves suture length and useful when suture short; hand tie useful in deep cavities or with long suture',
'Hand tie always superior',
'Instrument tie not used in surgery',
'No technique difference matters',
'B',
'Tying techniques: Hand tie: Traditional two-hand technique, preferred when: Deep in cavity (hard to instrument), long suture ends, thick suture. Advantage: Tactile feedback, adjustable tension. Instrument tie: Use needle driver to wrap suture around and pull through. Advantages: Conserves suture (can use shorter lengths), better for surface/accessible wounds, fine sutures. Both require proper technique: Square knots, appropriate number of throws, no air knots.',
'easy', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'When should CPR be discontinued in an adult patient?',
'After 10 minutes in all cases',
'When ROSC achieved, when team agrees further efforts are futile (considering reversible causes, ETCO2, duration), or when resuscitator exhausted with no replacement',
'Never discontinue CPR',
'After 5 minutes always',
'Only physicians can stop CPR',
'B',
'Terminating CPR: Continue CPR when: ROSC achievable, reversible causes present and being treated. Consider terminating: Prolonged resuscitation without ROSC, ETCO2 consistently <10 mmHg (poor prognosis marker), all reversible causes addressed, team consensus. Duration: No absolute cutoff - depends on clinical situation (hypothermia = longer, witnessed VF = favorable, unwitnessed asystole = less favorable). Emotional support for team/family important.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the role of extracorporeal CPR (ECPR) in cardiac arrest?',
'Replacement for standard CPR',
'ECPR (emergent ECMO) can provide circulatory support during prolonged arrest for potentially reversible causes (MI, PE); requires specialized centers and appropriate patient selection',
'Available at all hospitals',
'Obsolete technique',
'Only for pediatric patients',
'B',
'ECPR: Extracorporeal membrane oxygenation initiated during cardiac arrest. Provides: Mechanical circulatory support, oxygenation, while treating underlying cause. Indications: Witnessed arrest, shockable rhythm, short no-flow time, potentially reversible cause (MI amenable to PCI, PE for thrombectomy, hypothermia). Requirements: Specialized center, trained team, rapid deployment. Not for: Unwitnessed arrest, prolonged downtime, terminal illness. Emerging evidence supports improved survival in selected patients.',
'hard', 'application'),

-- MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is the role of lactate monitoring in surgical patients?',
'Not useful in surgery',
'Lactate reflects tissue oxygenation; elevated lactate indicates hypoperfusion/anaerobic metabolism; serial trending helps assess resuscitation adequacy',
'Only measured in diabetics',
'Useful only during CPR',
'Should always be elevated post-op',
'B',
'Lactate in surgical patients: Normal <2 mmol/L. Elevation indicates: Tissue hypoperfusion (anaerobic metabolism), hypoxia, liver dysfunction (clearance). Uses: Diagnosis of occult hypoperfusion (may have normal BP), prognostication (higher lactate = worse outcome), resuscitation target (lactate clearance). Goal: Normalize lactate within 6-8 hours. Persistent elevation despite resuscitation: Poor prognosis, ongoing hypoperfusion, or source not controlled.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'How should vital sign trends be interpreted in the context of clinical deterioration?',
'Each vital sign assessed alone',
'Pattern recognition - combination of changes (rising HR, falling BP, rising RR, decreasing O2 sat, altered mental status) more concerning than isolated abnormality; triggers early warning systems',
'Only BP matters',
'Trends not important, only current values',
'Deterioration cannot be predicted',
'B',
'Early warning systems: Single vital sign abnormality may be compensated. Multiple abnormalities suggest decompensation. NEWS/MEWS: Aggregated early warning scores using: HR, RR, BP, O2 sat, temperature, consciousness. Higher scores correlate with adverse outcomes. Action: Escalating response based on score threshold. Trending: Compare to patient baseline, look for trajectories. Early recognition and intervention prevents cardiac arrest and ICU admission. "Worried" nursing assessment valid concern.',
'medium', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient has a high-energy tibial fracture with extensive soft tissue injury. Why might external fixation be chosen initially?',
'Always the definitive treatment',
'Damage control orthopedics - allows wound management, reduces inflammation, permits access for soft tissue care; can convert to internal fixation when soft tissue healed',
'External fixation is obsolete',
'Only for open fractures',
'Never used for tibia',
'B',
'Damage control orthopedics: Principles from damage control surgery applied to trauma. Initial external fixation for: Polytrauma patients (reduces second hit of major surgery), severe soft tissue injury (allows wound access), open fractures with contamination. Benefits: Rapid application, low physiologic burden, permits soft tissue healing. Staged treatment: Convert to internal fixation (plates, nails) when patient stable and soft tissue ready (7-14 days). Reduces complications.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is suprapubic catheterization and when is it preferred over urethral catheterization?',
'Never a valid option',
'Catheter placed through anterior abdominal wall into bladder; preferred for urethral injury, long-term catheterization, or when urethral catheter not possible',
'Only for female patients',
'Emergency procedure only',
'Identical to urethral catheter',
'B',
'Suprapubic catheterization: Direct bladder drainage through anterior abdominal wall. Indications: Urethral trauma (pelvic fracture, straddle injury - blood at meatus, high-riding prostate), urethral stricture, long-term catheterization (lower infection rate than urethral, easier patient care), failed urethral catheterization. Technique: Ultrasound guidance, percutaneous or open. Advantages for long-term: Lower UTI, less urethral damage, easier changes, better for sexual function.',
'medium', 'application');
