-- ============================================================================
-- BATCH 60: Final Integration - High-Stakes Clinical Scenarios
-- Topics: Critical decision points across all surgical domains
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- CRITICAL DECISIONS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient in the ED has acute abdomen. CT shows free air. The family requests comfort measures only based on advanced directive. What should the surgeon do?',
'Operate despite directive',
'Honor the patient''s documented wishes if valid; ensure patient capacity or validity of surrogate decision-making; provide comfort care as directed',
'Ignore family, call ethics',
'Perform surgery and address later',
'Refuse to provide any care',
'B',
'End-of-life decision making: Valid advance directive is legally binding. Verify: Directive is authentic, applicable to current situation, patient lacks capacity. Surrogate: If no directive, appropriate surrogate makes decisions based on patient''s known wishes or best interests. Comfort care: Pain management, symptom control, dignity. Surgeon role: Ensure informed decision-making, clarify prognosis, support family. Document discussions. Ethics consultation if conflict.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A surgeon discovers unexpected metastatic cancer during elective surgery. The family is in waiting room but was not prepared for this finding. How should this be handled?',
'Complete planned procedure regardless',
'Close safely, complete appropriate biopsy for diagnosis, then discuss findings with patient/family post-operatively with full information',
'Tell family immediately while operating',
'Perform extensive cancer surgery without consent',
'Abandon operation completely',
'B',
'Intraoperative unexpected findings: Complete operation safely, obtain tissue diagnosis if possible (biopsy metastatic deposit). Do not perform major unplanned resection without informed consent. Close, recover patient safely. Disclosure: Post-operatively, with compassion, in appropriate setting. Provide: What was found, what was done, what next (oncology referral, staging, treatment planning). Support family through unexpected news.',
'hard', 'application'),

-- SHOCK MASTERY
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'Despite maximum vasopressor support, a patient in refractory shock remains hypotensive. What rescue therapies might be considered?',
'No additional options exist',
'Consider stress-dose steroids for possible relative adrenal insufficiency; vasopressin for catecholamine-resistant shock; ECMO in select cases',
'Increase fluids indefinitely',
'Reduce vasopressor doses',
'Accept poor outcome',
'B',
'Refractory shock: Definition - persistent hypotension despite adequate fluids and high-dose vasopressors. Rescue therapies: Stress-dose steroids (hydrocortisone 200mg/day) - may restore vascular responsiveness in relative adrenal insufficiency. Vasopressin - works via non-catecholamine pathway. Methylene blue - for vasoplegia (inhibits NO pathway). Mechanical support (ECMO, IABP) - for cardiogenic component. Always ensure: Source control, reversible causes addressed, appropriate goals of care.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the pathophysiologic difference between warm and cold shock in sepsis?',
'No clinical difference exists',
'Early/warm shock has high cardiac output with vasodilation (warm extremities); late/cold shock has myocardial depression with low output (cold extremities)',
'Cold shock means hypothermia',
'Warm shock is not sepsis',
'Temperature determines classification',
'B',
'Septic shock hemodynamic phases: Early/hyperdynamic (warm): High cardiac output, low SVR (vasodilation), wide pulse pressure, warm extremities, bounding pulses. Later/hypodynamic (cold): Myocardial depression (septic cardiomyopathy), reduced cardiac output, vasoconstriction, cold mottled extremities, narrow pulse pressure. Transition indicates worsening. Cold shock more ominous. Management differs: Warm shock - vasopressors. Cold shock - may need inotropes (dobutamine) in addition.',
'hard', 'application'),

-- FLUIDS AND ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A surgical patient develops severe hyperkalemia (K+ 7.5) with ECG changes. After calcium, insulin, and glucose, what provides definitive potassium removal?',
'Repeat insulin and glucose',
'Dialysis - hemodialysis most effective for rapid potassium removal when medical management insufficient',
'Beta-agonists alone',
'Sodium bicarbonate only',
'Kayexalate is fastest',
'B',
'Hyperkalemia definitive treatment: Temporizing measures shift potassium into cells but don''t remove it. Calcium - stabilizes membrane. Insulin/glucose, beta-agonists, bicarbonate - shift K+ intracellularly. Removal: Dialysis - most efficient, removes 25-50 mEq/hour. Loop diuretics - if producing urine. Potassium binders (kayexalate, patiromer) - slow, for mild cases. Severe hyperkalemia with ECG changes and renal failure: Emergent dialysis needed after stabilization.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient is admitted with diabetic ketoacidosis requiring surgery. What specific fluid and electrolyte management is needed?',
'Normal saline alone',
'Aggressive IV fluids (initially NS, then half-normal when Na normalizes), insulin infusion, potassium replacement (despite high initial K+, total body K+ depleted)',
'Glucose infusion for energy',
'Restrict fluids',
'Avoid potassium replacement',
'B',
'DKA management: Profound dehydration (often 5-10L deficit). Initial fluids: NS 1-2L first hour, then based on Na+ and volume status. Insulin: IV infusion 0.1 units/kg/hour (after fluids started). Potassium: Despite high serum K+, total body K+ depleted. As insulin given, K+ shifts into cells → hypokalemia. Replace K+ when <5.3 and adequate UOP. Monitor K+ frequently. When glucose <200, add dextrose to fluids (continue insulin to clear ketones).',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient develops DIC (disseminated intravascular coagulation) post-operatively. What is the primary treatment approach?',
'Transfuse all blood products aggressively',
'Treat underlying cause; provide supportive transfusion of blood products for clinically significant bleeding or before invasive procedures',
'Anticoagulate immediately',
'No treatment is effective',
'Plasmapheresis for all DIC',
'B',
'DIC management: Primary: Treat underlying cause (sepsis, malignancy, trauma). DIC is secondary process - cannot resolve until trigger removed. Supportive: Transfuse for bleeding or high-risk procedure - platelets if <50,000 and bleeding, FFP/cryo for fibrinogen <100-150 and bleeding. Anticoagulation: Controversial - consider in DIC with thrombosis predominating (purpura fulminans, large vessel thrombosis). Monitor with serial coagulation studies.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What laboratory findings characterize DIC?',
'Normal coagulation studies',
'Elevated PT/PTT, low fibrinogen, low platelets, elevated D-dimer, and peripheral blood smear showing schistocytes',
'Elevated fibrinogen',
'Normal D-dimer',
'High platelet count',
'B',
'DIC laboratory findings: Pathophysiology - simultaneous activation of coagulation and fibrinolysis. Labs: PT/PTT prolonged (factor consumption), low platelets (consumption), low fibrinogen (consumed and broken down), high D-dimer/FDP (fibrinolysis products), schistocytes on smear (mechanical RBC fragmentation from microthrombi). ISTH DIC score combines: Platelets, PT, fibrinogen, D-dimer. Score ≥5 compatible with overt DIC.',
'medium', 'application'),

-- WOUND HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A patient with an abdominal wound has been on negative pressure wound therapy for 3 weeks. The wound bed now has healthy granulation tissue. What is the next step?',
'Continue NPWT indefinitely',
'Plan for closure - skin graft, flap, or secondary intention depending on wound characteristics; prolonged NPWT without closure plan delays healing',
'Remove NPWT, leave wound open',
'Switch to wet-to-dry dressing',
'Start hyperbaric oxygen',
'B',
'NPWT endpoint: Goal - prepare wound for closure, not maintain indefinitely. When wound bed healthy (granulation tissue, no infection, reduced size): Plan closure. Options: Primary closure if edges approximate, skin graft for large granulating wound, flap for exposed bone/tendon/vital structures. Secondary intention for small wounds in good location. Prolonged NPWT without closure plan increases cost, delays definitive healing.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the role of tissue oxygen levels in wound healing and infection prevention?',
'Oxygen is detrimental to healing',
'Adequate tissue oxygenation is essential - oxygen is required for collagen synthesis, bacterial killing by neutrophils, and angiogenesis',
'Wounds heal better in hypoxia',
'Only affects superficial wounds',
'Oxygen only important for burns',
'B',
'Oxygen in wound healing: Essential roles: Collagen synthesis (proline/lysine hydroxylation requires O2), neutrophil bacterial killing (oxidative burst requires O2), angiogenesis (VEGF responds to hypoxia but O2 needed for new vessels), epithelialization. Implications: Maintain tissue perfusion (adequate volume, avoid vasoconstrictors if possible), supplemental O2 may help, hyperbaric O2 for problem wounds with hypoxia as component. Don''t tolerate hypoxemia in wound patients.',
'medium', 'application'),

-- AUTOTRANSFUSION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is acute normovolemic hemodilution and when is it used?',
'Removing blood without replacement',
'Removing whole blood preoperatively with crystalloid/colloid replacement; blood stored at room temperature and returned after surgical bleeding; preserves clotting factors',
'Diluting blood with saline post-op',
'Not used in modern practice',
'Same as cell salvage',
'B',
'Acute normovolemic hemodilution (ANH): Technique: Before surgery, remove 1-3 units whole blood, replace with crystalloid (3:1) or colloid (1:1). Blood stored at room temperature in OR. Blood lost during surgery is diluted (lower Hct = less RBC lost). After surgical bleeding controlled: Return autologous blood. Advantages: Fresh whole blood with functional platelets and clotting factors (unlike stored blood). Uses: Major surgery with expected blood loss in healthy patients.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'A hospital is implementing a patient blood management program. What are the three pillars?',
'Education, protocols, auditing',
'Optimize erythropoiesis (treat anemia), minimize blood loss (surgical and non-surgical), harness and optimize tolerance of anemia (restrictive transfusion)',
'Blood typing, crossmatching, transfusion',
'Donation drives, storage, administration',
'Not evidence-based approach',
'B',
'PBM three pillars: 1) Optimize erythropoiesis - detect and treat anemia preoperatively (iron, B12, folate, EPO). Don''t operate on anemic patients electively. 2) Minimize blood loss - meticulous surgical technique, antifibrinolytics, cell salvage, controlled hypotension, normothermia. 3) Optimize anemia tolerance - restrictive transfusion thresholds, evidence-based triggers not routine transfusion. Multidisciplinary program involving surgery, anesthesia, hematology, blood bank.',
'medium', 'application'),

-- ABDOMINAL INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'What is the difference between mass closure and layered closure for abdominal wounds?',
'No clinical difference',
'Mass closure includes all layers (peritoneum, muscle, fascia) in one bite; may be faster and as effective as layered closure; running mass closure currently preferred',
'Layered closure always stronger',
'Mass closure outdated technique',
'Only used for emergency surgery',
'B',
'Abdominal closure techniques: Mass closure: Single layer incorporating peritoneum, muscle, posterior and anterior fascia. Faster, fewer knots, reduced suture material. Running suture common. Layered closure: Separate closure of peritoneum, posterior fascia, muscle, anterior fascia. More time, more suture material. Evidence: Mass closure with running slowly absorbable suture (4:1 suture:wound length ratio) - low dehiscence rates, comparable to layered. Currently preferred technique.',
'medium', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'What suture-to-wound-length ratio is recommended for fascial closure to prevent dehiscence?',
'1:1 ratio',
'At least 4:1 ratio - suture length should be 4 times wound length to allow adequate bites and spacing without excessive tension',
'2:1 ratio sufficient',
'Ratio does not matter',
'10:1 ratio required',
'B',
'Suture-to-wound-length ratio: Studies show: <4:1 ratio associated with higher dehiscence rates. Optimal: ≥4:1 ratio. Technique: Small bites (5-8mm from edge), small intervals (5-8mm apart), running suture. "Small bites" technique (STITCH trial): 5mm bites, 5mm apart, may be superior to large bites. Suture: Slowly absorbable monofilament (PDS). Tissue handling: No excessive tension, healthy tissue edges. Prevents fascial dehiscence and incisional hernia.',
'medium', 'application'),

-- CPR AND EMERGENCIES
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'A cardiac arrest occurs during a surgical procedure. The patient has an open abdomen. How does this modify the CPR approach?',
'Standard external CPR only',
'Internal cardiac massage through open abdomen or thoracotomy provides better cardiac output than external compressions in this setting',
'CPR not possible during surgery',
'Close abdomen before CPR',
'Abandon resuscitation',
'B',
'Intraoperative cardiac arrest: Advantages - already monitored, IV access, team present, open cavity if applicable. Internal cardiac massage: If abdomen or chest open, direct cardiac compression is more effective than external (2-3x cardiac output). Technique: Through diaphragm from open abdomen, or direct through thoracotomy. Address surgical causes immediately: Hemorrhage control, release clamps if vascular. Advantage: Rapid diagnosis and treatment of cause.',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What are the reversible causes of cardiac arrest (H''s and T''s)?',
'Only VF is treatable',
'Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/hyperkalemia, Hypothermia; Tension pneumothorax, Tamponade, Toxins, Thrombosis (PE/MI)',
'Unknown and cannot be identified',
'All arrests are reversible',
'Irreversible once pulseless',
'B',
'H''s and T''s reversible causes: H''s: Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/hyperkalemia, Hypothermia. T''s: Tension pneumothorax, Tamponade (cardiac), Toxins/tablets, Thrombosis pulmonary (PE), Thrombosis coronary (MI). During resuscitation: Systematically consider and treat each. Some require specific intervention beyond ACLS: Tension pneumo = decompression, tamponade = pericardiocentesis, PE = thrombolysis/ECMO. Survival depends on recognizing and treating these.',
'medium', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'A venous ulcer has been present for 2 years despite compression therapy. What additional intervention might be considered?',
'Continue compression alone forever',
'Superficial venous ablation or surgery - treating underlying superficial reflux can improve healing rates and reduce recurrence in patients with incompetent saphenous veins',
'No additional options exist',
'Amputation',
'Antibiotics long-term',
'B',
'Venous surgery for ulcers: If superficial venous reflux present (great or small saphenous incompetence), ablation or surgery may help. EVRA trial: Early venous ablation accelerated ulcer healing compared to compression alone. Options: Endovenous ablation (laser, radiofrequency), foam sclerotherapy, surgical stripping. Criteria: Duplex confirms superficial reflux, patient suitable candidate. Deep venous disease: Less amenable to intervention but stenting explored.',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What clinical features help differentiate vasculitic ulcers from other types?',
'Cannot be distinguished clinically',
'Vasculitic ulcers are often multiple, punched-out with violaceous borders, very painful, associated with systemic symptoms or known vasculitis; biopsy confirms',
'Always single large ulcer',
'Never painful',
'Only on feet',
'B',
'Vasculitic ulcers: Appearance: Punched-out, irregular, often multiple, violaceous/purpuric borders. Pain: Often very painful (out of proportion to size). Location: Can be anywhere, not typical venous or arterial distribution. Associated features: Systemic vasculitis symptoms, positive autoantibodies (ANA, ANCA), palpable purpura, other organ involvement. Diagnosis: Skin biopsy showing leukocytoclastic vasculitis. Treatment: Immunosuppression, not compression or revascularization.',
'hard', 'application');
