-- ============================================================================
-- BATCH 61: Clinical Vignette Scenarios - Comprehensive Review
-- Topics: Diverse clinical presentations across all topics
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- GENERAL SURGERY
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'An 80-year-old is found to have a 6cm asymptomatic abdominal aortic aneurysm. He has severe COPD (FEV1 35% predicted) and recent MI. What is the best management approach?',
'Open AAA repair immediately',
'Consider endovascular repair (EVAR) if anatomically suitable - lower perioperative risk than open surgery for high-risk patients; medical optimization essential',
'No treatment possible',
'Conservative management only',
'Watchful waiting with serial imaging',
'B',
'AAA in high-risk patient: 6cm AAA has significant rupture risk (~10-20%/year). Open repair: High morbidity in severe cardiopulmonary disease. EVAR: Less physiologic stress, may be feasible if anatomy suitable (adequate landing zones, access vessels). Decision: Balance rupture risk vs operative risk. EVAR extends treatment to patients previously deemed inoperable. Medical optimization: Beta-blockers, smoking cessation, cardiac evaluation. Shared decision-making essential.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 55-year-old with BMI 45 has gallstone pancreatitis. After resolution, when should cholecystectomy be performed?',
'Immediate during index hospitalization',
'Index admission cholecystectomy preferred if feasible - reduces recurrent biliary events; technical challenges of obesity should not delay appropriately timed surgery',
'Wait 6 months for weight loss',
'Never in obese patients',
'Cholecystectomy not indicated',
'B',
'Cholecystectomy after gallstone pancreatitis: Recurrence of biliary events 30-40% within 6 weeks if not done. Guidelines: Same-admission cholecystectomy after mild pancreatitis resolution. Obesity considerations: Higher technical difficulty, but not contraindication. May need experienced surgeon, specialized equipment. Delay for weight loss not evidence-based and risks recurrent pancreatitis. ERCP if CBD stones suspected before surgery.',
'hard', 'application'),

-- SHOCK SCENARIOS
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A patient with septic shock has received 30ml/kg crystalloid and is on norepinephrine. MAP is 60 mmHg. What is the next step?',
'More fluid boluses indefinitely',
'Add vasopressin as second vasopressor; continue fluid resuscitation judiciously based on dynamic measures; consider stress-dose steroids',
'Stop norepinephrine, try dopamine',
'Albumin infusion only',
'Accept MAP of 60',
'B',
'Septic shock escalation: After initial crystalloid (30ml/kg) and first vasopressor: Target MAP ≥65 mmHg. If not achieved: Add second vasopressor (vasopressin 0.03 U/min). Vasopressin: Works via V1 receptors (non-catecholamine pathway), may restore vascular tone. Steroids: Consider stress-dose hydrocortisone if refractory to fluids and vasopressors. Continue: Source control, antibiotics, reassess fluid status with dynamic measures. Avoid excessive crystalloid.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient is hypotensive with cold extremities and JVD. What is the most likely diagnosis?',
'Hypovolemic shock',
'Obstructive shock - JVD with hypotension suggests cardiac compression (tension pneumothorax or pericardial tamponade); differentiate by breath sounds',
'Septic shock',
'Neurogenic shock',
'Cardiogenic shock from contusion',
'B',
'JVD with hypotension in trauma: Obstructive shock pattern - impaired venous return. Causes: Tension pneumothorax (absent breath sounds on one side, tracheal deviation), cardiac tamponade (muffled heart sounds, pulsus paradoxus). Both emergencies. Diagnosis: Clinical + FAST (tamponade shows pericardial fluid). Treatment: Tension pneumo = immediate decompression. Tamponade = pericardiocentesis or thoracotomy. JVD absent in hypovolemic shock.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient receiving their third unit of blood develops fever, chills, and flank pain. Previous units were uneventful. What is the most likely diagnosis?',
'Febrile non-hemolytic reaction',
'Delayed hemolytic transfusion reaction - anamnestic antibody response to previously encountered antigen; occurs days to weeks after transfusion',
'Acute hemolytic reaction',
'TRALI',
'Volume overload',
'B',
'Delayed hemolytic transfusion reaction (DHTR): Occurs 3-14 days after transfusion. Mechanism: Anamnestic response - patient has antibodies from prior sensitization (transfusion, pregnancy) at levels too low to detect on current crossmatch. Re-exposure boosts antibody levels, destroying transfused cells. Presentation: Fever, dropping Hct, jaundice, hemoglobinuria. Labs: Positive DAT, elevated bilirubin, LDH. Usually self-limited but can be severe.',
'hard', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is the proper rate for administering packed red blood cells in a non-emergent situation?',
'As fast as possible',
'Over 2-4 hours per unit, not exceeding 4 hours to minimize bacterial growth risk; slower in patients at risk for TACO',
'Over 12 hours per unit',
'No rate restrictions',
'Same as crystalloid',
'B',
'RBC transfusion rate: Standard: Each unit over 2-4 hours. Maximum: 4 hours per unit (after this, bacterial growth risk increases as blood warms). High-risk patients (CHF, renal failure): Slower infusion, consider diuretic between units. Emergency: Rapid infusion through pressure bags if indicated. Use blood warmer for rapid transfusion. Monitor: VS before, during (15 min), after transfusion.',
'easy', 'application'),

-- AUTOTRANSFUSION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'During cardiac surgery, 1500ml of blood is collected in the cell salvage device. After processing, how much is typically returned?',
'1500ml of whole blood',
'Approximately 500-600ml of washed red cell concentrate - processing removes plasma, platelets, debris, resulting in concentrated RBCs',
'3000ml (doubled)',
'Processing destroys all blood',
'Return without any processing',
'B',
'Cell salvage yield: Collected blood is diluted with anticoagulant, contains debris, and is further diluted during washing. Typical: 50-60% of collected RBC mass recovered. 1500ml collected → approximately 500-600ml washed RBCs (Hct 50-80%). Efficiency varies with: Collection technique, processing machine, operator. Some RBC loss during centrifugation and washing. Despite losses, significant autologous blood saved.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What anticoagulant is used in cell salvage systems and why must it be removed during processing?',
'Warfarin',
'Heparin or citrate; must be removed during washing to prevent systemic anticoagulation when reinfused',
'No anticoagulant used',
'Aspirin added to blood',
'EDTA for all systems',
'B',
'Cell salvage anticoagulation: Purpose - prevent clotting in collection reservoir and tubing. Options: Heparin (added to collection tubing), citrate-based solutions. Washing: Essential step removes anticoagulant along with plasma proteins, platelets, and debris. Result: Washed RBCs in saline, minimal residual anticoagulant. If not washed: Reinfusing heparinized blood would cause systemic anticoagulation. Citrate: Also removed (would cause hypocalcemia in large amounts).',
'medium', 'application'),

-- WOUND HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A keloid forms at a surgical scar. What differentiates a keloid from a hypertrophic scar?',
'No clinical difference',
'Keloid extends beyond original wound boundaries; hypertrophic scar remains within original wound margins but is raised and red',
'Keloid is flat',
'Hypertrophic scar extends beyond wound',
'Only location differs',
'B',
'Keloid vs hypertrophic scar: Keloid: Extends beyond original wound boundaries, does not regress spontaneously, higher recurrence after excision, associated with darker skin types, genetic predisposition. Hypertrophic scar: Remains within wound boundaries, often regresses with time (6-12 months), less recurrence with treatment. Both: Raised, firm, red initially. Treatment: Silicone sheets, steroid injections, pressure therapy. Keloids often recur even after excision + adjuncts.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the function of matrix metalloproteinases (MMPs) in wound healing?',
'Cause wound infection',
'Remodel extracellular matrix - break down collagen and other ECM components to allow cell migration and tissue reorganization; imbalance causes chronic wounds',
'Strengthen collagen',
'Only important in bone healing',
'Have no role in healing',
'B',
'MMPs in wound healing: Family of enzymes that degrade ECM components. Physiologic role: Enable cell migration (clear path through ECM), remodel provisional matrix, restructure tissue architecture, regulate growth factor activity. Balance critical: Too little MMP → excessive scarring, fibrosis. Too much MMP → chronic wound (ECM degraded faster than deposited). Chronic wounds: Elevated MMP activity, reduced TIMP (tissue inhibitors). Some dressings target MMP reduction.',
'hard', 'application'),

-- SUTURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the main advantage of monofilament over braided sutures in contaminated wounds?',
'Better knot security',
'Lower infection risk - bacteria can lodge between braided filaments (capillarity) and are protected from host defenses; monofilament has no interstices',
'Easier handling',
'Stronger tensile strength',
'Better cosmetic result',
'B',
'Suture structure and infection: Braided sutures: Multiple filaments woven together. Interstices harbor bacteria (capillarity effect), protected from phagocytes and antibiotics. Biofilm formation easier. Monofilament: Single strand, no interstices. Bacteria cannot "hide." Preferred in: Contaminated wounds, implant surgery, high infection risk settings. Trade-off: Monofilament has more memory, less handling ease, requires more throws for secure knot.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'A surgeon uses 2-0 PDS for fascial closure. What is the tensile strength retention profile of this suture?',
'Complete loss in 1 week',
'Approximately 70% at 2 weeks, 50% at 4 weeks, complete absorption at 6-12 months',
'Permanent suture',
'Complete absorption in 2 weeks',
'No tensile strength initially',
'B',
'PDS (polydioxanone) properties: Monofilament absorbable suture. Tensile strength retention: 70% at 2 weeks, 50% at 4 weeks, 25% at 6 weeks. Complete absorption: 180-210 days. Indication: When prolonged support needed (fascia, tendons). Comparison: Vicryl loses strength faster (75% at 2 weeks, 50% at 3 weeks). PDS ideal for fascia because healing strength develops slowly and extended suture support reduces dehiscence.',
'medium', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A 70-year-old falls on outstretched hand and has a Colles fracture (distal radius). What is the typical deformity?',
'Volar displacement',
'Dorsal displacement and angulation creating "dinner fork" deformity',
'No displacement typically',
'Medial displacement',
'Rotation only',
'B',
'Colles fracture: Distal radius fracture within 2.5cm of wrist joint with dorsal displacement and angulation. Mechanism: Fall on outstretched hand (FOOSH), wrist in extension. Deformity: "Dinner fork" - dorsal angulation creates step-off. Common in osteoporotic bone (elderly). Treatment: Closed reduction and cast for stable fractures. ORIF for: Intra-articular involvement, unstable, significant shortening, young patients. Complications: Malunion, median nerve injury, complex regional pain syndrome.',
'easy', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A patient with femoral shaft fracture has an ipsilateral knee effusion without direct knee trauma. What should be considered?',
'Normal finding after femur fracture',
'Ipsilateral femoral neck fracture - femoral shaft fractures can be associated with femoral neck fractures (5-10%); dedicated imaging of hip essential',
'Ligament injury',
'Meniscal tear',
'No significance',
'B',
'Associated fractures: Femoral shaft fracture + knee effusion raises concern for: Ipsilateral femoral neck fracture (5-10% association) - often missed initially as attention focuses on obvious shaft fracture. Knee ligament injury. Protocol: Dedicated imaging of ipsilateral hip and knee in all femoral shaft fractures. Missed femoral neck fracture → AVN, nonunion if not treated. CT may be needed if X-ray equivocal.',
'hard', 'application'),

-- MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'During laparoscopic surgery, the ETCO2 suddenly rises from 35 to 55 mmHg. What is the likely cause?',
'Improved ventilation',
'CO2 absorption from insufflation - laparoscopic CO2 pneumoperitoneum leads to CO2 absorption; may need to increase minute ventilation',
'Pulmonary embolism',
'Circuit disconnect',
'Oxygen failure',
'B',
'Laparoscopic ETCO2 changes: CO2 pneumoperitoneum → absorption of CO2 into circulation → ↑ETCO2 and PaCO2. Management: Increase minute ventilation (rate or tidal volume), check airway pressures (Trendelenburg + pneumoperitoneum increase airway pressure). Other causes of rising ETCO2: Hypoventilation, malignant hyperthermia. Sudden drop in ETCO2 during laparoscopy: CO2 embolism (rare but serious) - causes cardiovascular collapse.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'What does a widened pulse pressure (e.g., 160/50 mmHg) suggest?',
'Normal variation',
'Aortic regurgitation, high output states (sepsis, anemia, thyrotoxicosis), or atherosclerotic stiffening of large vessels',
'Hypovolemia',
'Cardiac tamponade',
'Heart failure',
'B',
'Widened pulse pressure (>40 mmHg): Systolic elevated and/or diastolic low. Causes: Aortic regurgitation (blood regurgitates during diastole → low diastolic), high output states (sepsis, anemia, thyrotoxicosis, AV fistula - vigorous cardiac contraction), atherosclerotic aorta (stiff vessels don''t distend). Contrast: Narrow pulse pressure (<25 mmHg) suggests: Low cardiac output (shock, heart failure), cardiac tamponade, aortic stenosis.',
'medium', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'An ETCO2 of 8 mmHg during CPR has been persistent for 20 minutes despite high-quality compressions. What does this indicate?',
'Good prognosis',
'Very poor prognosis - persistently low ETCO2 (<10 mmHg) during CPR indicates inadequate cardiac output and is associated with very low survival',
'ROSC is imminent',
'Normal CPR value',
'Monitor malfunction',
'B',
'ETCO2 during CPR: Reflects pulmonary blood flow (cardiac output during CPR). Persistently <10 mmHg: Indicates very poor cardiac output from CPR, associated with mortality approaching 100%. >20 mmHg: Better prognosis. Sudden rise to 35-40+ mmHg: Suggests ROSC (cardiac output restored). Uses: Guide CPR quality, prognostication, detect ROSC without interrupting compressions. AHA: Consider ETCO2 in decisions about resuscitation duration.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'A male patient has urethral stricture from previous catheterization. What are the management options?',
'Repeat standard catheterization',
'Urethral dilation, urethrotomy, or urethroplasty depending on stricture characteristics; suprapubic catheter if bladder drainage needed urgently',
'No treatment available',
'Remove stricture with lysis',
'Oral medications',
'B',
'Urethral stricture management: Acute retention: Suprapubic catheter if urethral catheter cannot pass. Definitive treatment depends on stricture length and location: Short strictures (<2cm) - urethral dilation, direct vision internal urethrotomy (DVIU). Longer or recurrent - urethroplasty (surgical reconstruction). DVIU: Endoscopic incision of stricture, high recurrence (50%+). Urethroplasty: Excision and primary anastomosis or graft, lower recurrence but more invasive.',
'medium', 'application');
