-- ============================================================================
-- BATCH 63: Surgical Fundamentals Applied Scenarios
-- Topics: Core concepts in clinical practice
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- FUNDAMENTALS APPLIED
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of "source control" in surgical infections?',
'Antibiotic intensification',
'Physical removal or control of infected material (drainage, debridement, repair of perforation) - antibiotics alone cannot cure most surgical infections without addressing the source',
'Diagnostic workup',
'Patient isolation',
'Monitoring only',
'B',
'Source control: Fundamental surgical principle. Definition: Eliminating the cause of infection - draining pus, debriding necrotic tissue, repairing perforation. Importance: Antibiotics cannot penetrate abscess cavities well, cannot eradicate necrotic tissue infections. Examples: Drain appendiceal abscess, resect perforated colon, debride necrotizing fasciitis, remove infected prosthetic material. Timing: Earlier source control = better outcomes. Exceptions: Some abscesses too small for drainage, may resolve with antibiotics alone.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the importance of tissue handling during surgery?',
'No effect on outcomes',
'Gentle tissue handling minimizes trauma, preserves blood supply, and reduces inflammation; rough handling increases ischemia, infection risk, and poor healing',
'Only affects cosmesis',
'Relevant only for skin',
'Makes surgery slower unnecessarily',
'B',
'Tissue handling principles: Halsted principles still apply. Gentle handling: Minimizes tissue trauma, preserves microcirculation. Sharp dissection: Less tissue damage than blunt tearing. Meticulous hemostasis: Without excessive cautery (thermal damage). Avoid: Crushing with instruments, excessive retraction, desiccation. Benefits: Better healing, lower infection rates, less scarring. "Treat tissues as you would want your own tissues treated." Part of surgical craftsmanship.',
'easy', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of base deficit in trauma resuscitation?',
'No clinical utility',
'Reflects severity of metabolic acidosis from hypoperfusion; worse base deficit correlates with greater injury severity and transfusion requirements',
'Only measured in diabetics',
'Normal value is -20',
'Indicates oxygenation status',
'B',
'Base deficit: Amount of base (mmol/L) needed to return blood pH to 7.40. Normal: -2 to +2. In shock: Tissue hypoperfusion → anaerobic metabolism → lactic acidosis → base deficit becomes more negative. Clinical utility: Injury severity correlate, transfusion predictor, resuscitation endpoint (improving BD indicates successful resuscitation). Categories: Mild (-3 to -5), moderate (-6 to -9), severe (<-10). Severe BD: Expect massive transfusion, high mortality.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is permissive hypotension in trauma resuscitation?',
'Accepting any blood pressure',
'Targeting lower-than-normal blood pressure (SBP 80-90) in penetrating trauma until surgical control, avoiding aggressive crystalloid that dilutes clotting factors and raises BP to disrupt clots',
'Maximum fluid administration',
'No resuscitation until surgery',
'Hypotension is always harmful',
'B',
'Permissive hypotension: Also called "hypotensive resuscitation." Concept: In uncontrolled hemorrhage, raising BP before surgical control may: Disrupt forming clots, dilute clotting factors (with crystalloid), worsen bleeding. Target: SBP 80-90 mmHg (enough for perfusion, not so high as to dislodge clots). Applies to: Penetrating trauma, before surgical hemorrhage control. Caution: TBI may need higher targets (cerebral perfusion). Once bleeding controlled: Resuscitate to normal targets.',
'hard', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is the composition of 0.9% Normal Saline compared to plasma?',
'Identical to plasma',
'NS has higher chloride (154 vs 100 mmol/L), no potassium, no buffer; this explains hyperchloremic acidosis with large volumes',
'Lower sodium than plasma',
'Contains bicarbonate buffer',
'Contains glucose',
'B',
'0.9% Saline composition: Na+ 154, Cl- 154 mmol/L. Compare to plasma: Na+ 140, Cl- 100 mmol/L. Differences: Supraphysiologic chloride (explains hyperchloremic acidosis), no potassium (may need supplementation), no buffer (unlike balanced solutions with lactate or acetate). pH: Saline pH is about 5.5 (slightly acidic). Large volume NS: Hyperchloremia, normal anion gap acidosis, possibly worse renal outcomes. Balanced crystalloids preferred for most resuscitation.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'How is fluid balance calculated and what does a positive balance indicate?',
'Intake minus urine output only',
'Total intake (IV, oral, blood products) minus total output (urine, drains, NG, estimated insensible losses); positive balance means fluid accumulation',
'Cannot be calculated',
'Only IV fluids count',
'Random variation',
'B',
'Fluid balance: Calculation: All intake (IV crystalloid, colloid, blood products, enteral, medications in fluid) - all output (urine, drains, NG, stool, estimated insensible losses ~500-1000ml/day). Positive balance: More in than out = fluid accumulating (edema, weight gain). May be appropriate in resuscitation phase. Negative balance: Diuresis exceeding intake = drying out. May be goal in de-resuscitation phase. Cumulative balance important - daily and over admission.',
'easy', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is the purpose of leukoreduction of blood products?',
'Remove all white cells for anemia',
'Filter to remove donor WBCs; reduces febrile reactions, CMV transmission, alloimmunization, and possibly transfusion-related immunomodulation',
'Increase oxygen carrying capacity',
'Sterilize the blood',
'Remove platelets',
'B',
'Leukoreduction: Process: Filter blood products to remove donor leukocytes (<5 million/unit). Benefits: Reduces febrile non-hemolytic transfusion reactions (from cytokines), reduces CMV transmission (CMV in WBCs), reduces HLA alloimmunization (improves platelet refractoriness). May reduce: Transfusion-related immunomodulation (TRIM). Now universal in many countries. Leukoreduced products labeled as such. Especially important for: Immunocompromised, transplant candidates, multiply transfused patients.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'A patient had a massive transfusion yesterday and today is oliguric with rising creatinine. What transfusion complication might be occurring?',
'Normal post-transfusion finding',
'Acute kidney injury from hemolysis, hypoperfusion, or direct effects of massive transfusion - evaluate for hemolytic reaction and renal support',
'Only from blood type mismatch',
'Irreversible kidney failure',
'Transfusion cannot affect kidneys',
'B',
'Post-massive transfusion AKI: Multiple mechanisms: 1) Hemolysis (incompatible blood, mechanical damage) → free hemoglobin nephrotoxicity. 2) Hypoperfusion during shock/resuscitation. 3) Direct effects: Older stored blood, microaggregates, inflammatory response. 4) Compartment syndrome if severe extremity injury (myoglobinuria). Evaluation: Check for hemolysis (LDH, haptoglobin, DAT, urine hemoglobin). Management: Supportive, maintain renal perfusion, may need RRT if severe.',
'hard', 'application'),

-- AUTOTRANSFUSION
('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is the maximum storage time for processed cell salvage blood at room temperature?',
'Indefinite storage',
'4-6 hours - washed cells have no anticoagulant and limited viability; must be reinfused promptly or discarded',
'24 hours',
'Same as blood bank products',
'1 week',
'B',
'Cell salvage blood storage: Washed RBCs are in saline without: Anticoagulant, preservative solutions, nutrients. Result: Limited viability outside body. Generally should be: Reinfused within 4-6 hours of processing. Some guidelines: More restrictive (reinfuse within 4 hours). If stored at room temperature: Bacterial growth possible. If refrigerated: Not standard practice for cell salvage products. Always label with time of processing, track expiration.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'Can cell salvage be used in obstetric hemorrhage?',
'Absolutely contraindicated',
'Yes - with leukocyte depletion filter; amniotic fluid embolism risk is theoretical and rare; benefit in massive obstetric hemorrhage outweighs theoretical risk',
'Only with Rh-negative patients',
'Only after hysterectomy',
'Never in any gynecologic surgery',
'B',
'Obstetric cell salvage: Historical concern: Amniotic fluid embolism (AFE) from reinfusing blood contaminated with amniotic fluid. Current evidence: AFE is immunologic reaction, not embolic phenomenon; reinfused blood has no amniotic debris after washing. UK guidelines: Cell salvage acceptable in obstetrics with leukocyte depletion filter. Benefits: Reduces allogeneic transfusion in massive PPH. Jehovah''s Witness patients: May be particularly valuable. Standard practice in many high-volume units.',
'medium', 'application'),

-- WOUND CARE
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the "TIME" framework for wound bed preparation?',
'Temperature, Infection, Moisture, Edges',
'Tissue (debride non-viable), Infection/Inflammation (treat), Moisture balance (not too wet or dry), Edge advancement (non-healing edges)',
'Time spent on dressing',
'No standard framework exists',
'Temperature only matters',
'B',
'TIME framework: Systematic approach to chronic wound assessment and management. T = Tissue non-viable or deficient: Debridement method selection. I = Infection or Inflammation: Treat infection, manage inflammation. M = Moisture imbalance: Too wet (exudate management) or too dry (add moisture). E = Edge of wound not advancing: Address non-healing margins (biopsy for malignancy, consider advanced therapies). Each element assessed and addressed systematically. Guides dressing selection and treatment plan.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the difference between colonization and infection in a wound?',
'Same clinical entity',
'Colonization is presence of bacteria without tissue invasion or host response; infection involves tissue invasion, damage, and inflammatory response',
'Colonization is worse',
'Infection has no bacteria',
'Determined by bacterial count only',
'B',
'Colonization vs infection: Colonization: Bacteria present on wound surface, not invading tissue, no host inflammatory response. All chronic wounds are colonized. Infection: Bacteria invade tissue, cause damage, trigger host inflammatory response (pain, erythema, edema, purulent discharge, fever). Treatment: Colonized wounds - topical antiseptics may help, antibiotics not indicated. Infected wounds - require systemic antibiotics (for cellulitis/systemic signs), source control.',
'easy', 'application'),

-- SUTURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the purpose of subcuticular skin closure?',
'Strongest closure method',
'Provides cosmetic closure without suture marks; suture runs in dermis parallel to skin surface, approximating skin edges without piercing epidermis',
'Fastest method',
'Only for contaminated wounds',
'Required for all wounds',
'B',
'Subcuticular closure: Technique: Suture runs within dermis, parallel to skin, taking horizontal bites that approximate dermal edges. Epidermis never punctured. Benefits: No suture marks (tracks where suture pierces skin), excellent cosmesis, can use absorbable suture (no removal needed). Limitations: Takes longer, cannot use in high-tension closures, requires good dermal layer. Indications: Cosmetically important areas, elective surgery, well-approximated wound edges.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'When should skin sutures or staples be removed?',
'Same timing for all locations',
'Varies by location: Face 3-5 days, scalp 5-7 days, trunk 7-10 days, extremities 10-14 days, joints 14 days; high tension areas need longer support',
'After 1 day',
'Never removed',
'4 weeks for all',
'B',
'Suture removal timing: Based on: Blood supply of area (better supply = faster healing = earlier removal), tension on wound (high tension = longer retention). Face: 3-5 days (excellent blood supply, cosmetic priority). Scalp: 5-7 days. Trunk/abdomen: 7-10 days. Extremities: 10-14 days. Over joints: 14 days. Early removal: Reduces suture marks but risks dehiscence. Support: Steri-strips after suture removal reduce tension on healing wound.',
'easy', 'application'),

-- CATHETERIZATION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is CAUTI and how is it prevented?',
'Catheter allergy reaction',
'Catheter-Associated Urinary Tract Infection - prevented by avoiding unnecessary catheters, prompt removal, aseptic insertion, closed drainage systems, and hand hygiene',
'Normal catheter complication',
'Treated with longer catheterization',
'Cannot be prevented',
'B',
'CAUTI prevention: Most common hospital-acquired infection. Prevention bundle: Avoid unnecessary catheterization (strict indications), daily assessment for removal (nurse-driven protocols work), aseptic insertion technique, closed drainage system (don''t break circuit), keep bag below bladder, secure catheter to prevent traction, hand hygiene before handling. Duration: Strongest risk factor - remove as soon as not needed. Alternatives: Intermittent catheterization when possible.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What are the indications for urinary catheterization in surgical patients?',
'All hospitalized patients',
'Urinary retention, accurate UOP monitoring in critical illness, perioperative for long cases, incontinence with wounds, patient request with informed consent',
'Only for urologic surgery',
'Never indicated',
'Infection prevention',
'B',
'Urinary catheter indications (surgical): Operative: Prolonged surgery, pelvic/lower abdominal surgery (bladder protection), accurate fluid management. Critical care: Hourly UOP monitoring in shock/resuscitation. Retention: Acute urinary retention, neurogenic bladder. Wound management: Incontinence with perineal/sacral wounds. Comfort: End of life care. NOT indications: Nursing convenience, "routine" post-op, patient immobility alone. Always ask: Is this necessary today? Can it come out?',
'easy', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the role of defibrillation in cardiac arrest?',
'Treatment for all rhythms',
'Delivers electrical shock to terminate VF/VT and allow organized rhythm to resume; only effective for shockable rhythms (VF/pulseless VT)',
'Restarts the heart from asystole',
'Strengthens weak heartbeat',
'Always the first intervention',
'B',
'Defibrillation mechanism: Depolarizes entire myocardium simultaneously, terminating chaotic electrical activity (VF/VT). Allows sinus node (or other pacemaker) to resume organized rhythm. Only works for: VF, pulseless VT (shockable rhythms). Does not work for: Asystole (no electrical activity to terminate), PEA (organized rhythm already present). Priority: Immediate defibrillation for witnessed VF arrest (shock takes priority over CPR). Delays in defibrillation reduce survival.',
'easy', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the correct shock energy for defibrillation?',
'Same energy for all devices',
'Biphasic: Manufacturer-specific (typically 120-200J first shock); Monophasic: 360J; escalate energy if initial shock fails',
'Always start at maximum',
'10 Joules is sufficient',
'Energy does not matter',
'B',
'Defibrillation energy: Biphasic waveforms: More efficient than monophasic, require less energy. Manufacturer recommendations vary (typically 120-200J initial). If unknown: Use maximum available. Escalate if first shock fails. Monophasic: 360J for all shocks. Energy selection: Use device-specific recommendations. Key point: A slightly higher or lower energy is less important than minimizing time to first shock and ensuring good pad contact. Transthoracic impedance affects energy delivery.',
'medium', 'application');
