-- ============================================================================
-- BATCH 64: Clinical Knowledge Integration Scenarios
-- Topics: Essential clinical reasoning across surgery topics
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- INTEGRATED KNOWLEDGE
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient presents with right lower quadrant pain migrating from the periumbilical region. What is the pathophysiologic basis for this pain pattern?',
'Random pain distribution',
'Initial visceral pain from appendix distension (periumbilical/referred) followed by parietal peritoneum irritation causing localized somatic pain (RLQ)',
'All appendicitis starts in RLQ',
'Migration indicates perforation',
'Due to patient positioning',
'B',
'Appendicitis pain migration: Classic presentation reflects two pain types. Initial (visceral pain): Appendix distension activates visceral afferents → referred to periumbilical region (midgut embryologic origin). Later (parietal pain): Inflammation extends to parietal peritoneum → localized somatic pain in RLQ where appendix contacts abdominal wall. Migration: Key clinical feature distinguishing appendicitis from other causes. Atypical positions (retrocecal, pelvic) may alter presentation.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the value of clinical scoring systems (like Alvarado score) in surgical decision-making?',
'Replace clinical judgment',
'Standardize risk assessment, stratify patients for imaging/observation/surgery, and improve diagnostic accuracy when combined with clinical judgment',
'No clinical utility',
'Only useful for billing',
'Delay decision-making',
'B',
'Clinical scoring systems: Purpose: Objective, reproducible risk assessment. Examples: Alvarado (appendicitis), Ranson/APACHE (pancreatitis), RCRI (cardiac risk), Caprini (VTE risk). Benefits: Standardize assessment, identify high/low risk for appropriate workup, clinical decision support. Limitations: Should augment not replace clinical judgment, may not apply to all populations, should be validated for local use. Best used as one component of overall assessment.',
'easy', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the mechanism of organ dysfunction in prolonged shock?',
'Infection always develops',
'Cellular hypoxia leads to ATP depletion, loss of membrane integrity, calcium influx, cellular death, and eventually organ failure',
'Only affects heart',
'Organ dysfunction is reversible',
'No mechanism exists',
'B',
'Shock and organ dysfunction: Cellular level: Hypoperfusion → inadequate O2 delivery → mitochondrial dysfunction → ↓ATP production → ion pump failure (Na+/K+ ATPase) → cellular swelling, Ca2+ influx → enzyme activation, membrane damage → cell death. Organ level: Accumulated cellular injury → organ dysfunction. MODS: Multiple Organ Dysfunction Syndrome - sequential or simultaneous failure of 2+ organs. Kidney, lung, liver, GI, brain commonly affected. Early resuscitation prevents progression.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is SIRS and how does it relate to sepsis?',
'Identical conditions',
'SIRS is systemic inflammatory response with 2+ criteria (temp, HR, RR, WBC); sepsis is SIRS with documented or suspected infection source',
'SIRS only from trauma',
'No relationship',
'Sepsis causes SIRS',
'B',
'SIRS and sepsis: SIRS criteria (2+ of): Temp >38°C or <36°C, HR >90, RR >20 or PaCO2 <32, WBC >12K or <4K or >10% bands. SIRS causes: Infection (sepsis), trauma, burns, pancreatitis, post-surgical. Sepsis-3 definition: Life-threatening organ dysfunction caused by dysregulated host response to infection (uses SOFA criteria, not SIRS). Clinical: SIRS identifies inflammatory state; must determine cause. qSOFA for screening: ≥2 of altered mental status, RR ≥22, SBP ≤100.',
'medium', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'Why do surgical patients often develop hyponatremia post-operatively?',
'Random occurrence',
'ADH (vasopressin) release from surgical stress, pain, and hypovolemia promotes water retention; hypotonic fluid administration then causes dilutional hyponatremia',
'Sodium always lost in surgery',
'Related to blood type',
'No known cause',
'B',
'Post-operative hyponatremia: Mechanism: Surgical stress → non-osmotic ADH release. ADH → water retention (even if hyponatremia should suppress it). If hypotonic fluids given (5% dextrose, 0.45% saline): Water retained more than sodium → dilutional hyponatremia. Risk factors: Female, pain, PONV, certain drugs. Prevention: Use isotonic or balanced fluids, not hypotonic. Restrict free water. Symptomatic hyponatremia: Can cause cerebral edema, seizures, death.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What happens to potassium in metabolic acidosis?',
'Potassium unchanged',
'Potassium shifts from intracellular to extracellular space as H+ enters cells; serum K+ may appear normal or elevated despite total body depletion',
'Potassium decreases always',
'No relationship exists',
'Potassium shifts into cells',
'B',
'Potassium and acid-base: Acidosis: H+ buffered by entering cells in exchange for K+ leaving → hyperkalemia. Each 0.1 pH decrease raises serum K+ approximately 0.6 mEq/L. Trap: Serum K+ may be normal or high, but as acidosis corrected, K+ shifts back into cells → hypokalemia. Must anticipate: Replace potassium as acidosis corrected. Total body K+ may be depleted even if serum K+ normal. Monitor closely during treatment of DKA, lactic acidosis.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is the storage lesion in red blood cells?',
'Improved quality with storage',
'Progressive changes during storage: ATP and 2,3-DPG depletion, potassium leak, membrane changes, reduced deformability; may affect oxygen delivery and clinical outcomes',
'No changes during storage',
'Only affects platelets',
'Improves oxygen delivery',
'B',
'RBC storage lesion: Changes over 42-day storage: ↓ATP (↓cell viability), ↓2,3-DPG (left-shifted O2 dissociation), ↑potassium (leak from cells), membrane changes (loss of deformability, ↑fragility), microparticle formation, ↓NO availability. Clinical significance: Debated - some studies show worse outcomes with older blood, others show no difference. 2,3-DPG regenerates within 24 hours post-transfusion. Storage lesion may be more important in critically ill patients.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is the proper procedure for blood product administration safety?',
'Any nurse can administer',
'Two-person verification of patient ID, blood product, compatibility label, and expiration before transfusion; monitor vital signs throughout',
'No verification needed',
'Single check is sufficient',
'Only physicians administer',
'B',
'Blood transfusion safety: Pre-transfusion: Two qualified staff independently verify: Patient identification (ask patient to state name/DOB), blood product (unit number, product type, ABO/Rh), compatibility label (matches patient), expiration date/time. At bedside: Final verification with patient. During transfusion: Baseline vitals, repeat at 15 minutes, monitor for reactions. Post-transfusion: Document volume, any reactions. Most fatal transfusion errors: Clerical/identification mistakes.',
'easy', 'application'),

-- WOUND HEALING
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the "proliferative phase" of wound healing?',
'Immediate response to injury',
'Phase from day 3-4 to weeks where fibroblasts deposit collagen, angiogenesis occurs, and granulation tissue forms to fill the wound',
'Scar remodeling phase',
'Only in chronic wounds',
'No distinct phases exist',
'B',
'Proliferative phase: Timing: Day 3-4 to approximately 3 weeks. Key processes: Fibroblast migration and proliferation, collagen synthesis and deposition (initially type III), angiogenesis (new blood vessel formation), granulation tissue formation, wound contraction (myofibroblasts), epithelialization. Result: Wound defect filled with vascularized granulation tissue, covered with epithelium. Precedes: Remodeling phase (collagen reorganization, type III → type I, strength increases).',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What role does zinc play in wound healing?',
'No role in healing',
'Essential cofactor for collagen synthesis, protein synthesis, and immune function; deficiency impairs healing; supplement only if deficient',
'Harmful to wounds',
'Only important topically',
'Speeds all wound healing',
'B',
'Zinc and wound healing: Functions: Cofactor for 300+ enzymes including those for collagen synthesis, DNA/protein synthesis, cell division. Essential for: Inflammatory cell function, protein synthesis for matrix formation, epithelialization. Deficiency: Impairs healing, increases infection risk. Causes: Malnutrition, alcoholism, GI disease, high-output fistula. Treatment: Supplement if deficient. Note: Supplementation in zinc-replete patients does not improve healing. Excess zinc can be harmful.',
'medium', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of "open fracture" and how is it classified?',
'Same as closed fracture',
'Fracture communicating with external environment through skin wound; Gustilo-Anderson grades I-III based on wound size, energy, contamination; all require antibiotics and operative treatment',
'Only affects skin healing',
'Minor difference from closed',
'Does not require treatment',
'B',
'Open fracture: Definition: Bone communicating with outside through wound. Gustilo-Anderson classification: Grade I: <1cm wound, minimal contamination, low energy. Grade II: >1cm wound, moderate contamination, no flaps. Grade IIIA: Extensive soft tissue damage but adequate coverage. Grade IIIB: Extensive injury requiring flap coverage. Grade IIIC: Arterial injury requiring repair. Management: Antibiotics (cephalosporin +/- aminoglycoside), tetanus, wound irrigation and debridement, fracture stabilization.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What are the risk factors for fracture non-union?',
'Only patient age matters',
'Inadequate immobilization, poor blood supply, infection, bone loss, systemic factors (smoking, diabetes, malnutrition, NSAID use), and patient noncompliance',
'All fractures heal eventually',
'Bone type only',
'No predictable factors',
'B',
'Fracture non-union risk factors: Local: Poor blood supply (some anatomic locations), inadequate immobilization, bone loss/gap, infection, soft tissue interposition, excessive distraction. Systemic: Smoking (strongest modifiable risk factor), diabetes, malnutrition, immunosuppression, chronic illness. Medications: NSAIDs (controversial), steroids. Patient factors: Noncompliance with weight-bearing restrictions. Definition: Failure to heal by 6-9 months with no radiographic progress. Requires intervention.',
'medium', 'application'),

-- MONITORING
('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is the utility of central venous pressure (CVP) monitoring?',
'Accurately predicts fluid responsiveness',
'CVP reflects right heart filling pressure; poor predictor of fluid responsiveness but trends may be useful; extreme values informative',
'No clinical utility',
'Replaced by blood pressure',
'Predicts cardiac output',
'B',
'CVP interpretation: Normal: 2-8 mmHg. What it measures: Pressure at junction of SVC and right atrium (right heart filling pressure). Limitations: Poor predictor of fluid responsiveness (does not reliably identify who will respond to fluids). CVP affected by: Intravascular volume, RV compliance, intrathoracic pressure, tricuspid function. Uses: Extreme values informative (very low or very high), trend with intervention may be useful, guide CVC tip position. Dynamic measures (PPV, SVV) better for fluid responsiveness.',
'medium', 'application'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'What vital sign changes may indicate impending clinical deterioration?',
'Only blood pressure matters',
'Increasing heart rate, increasing respiratory rate, falling blood pressure, decreasing urine output, altered mental status - often appear hours before arrest',
'Only late changes are concerning',
'Random vital sign changes',
'Deterioration is unpredictable',
'B',
'Early warning signs: In-hospital deterioration usually not sudden - warning signs present hours before cardiac arrest. Markers: ↑HR (compensating), ↑RR (earliest sign in many conditions), ↓BP (late sign, decompensation), ↓UOP, altered mental status. Early Warning Scores: Aggregate vital signs into risk score, trigger response at thresholds. Importance: Early recognition allows intervention before arrest. Track trends, not just individual values. "Worried" clinical assessment valuable.',
'easy', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of "resuscitative thoracotomy" and when is it indicated?',
'Standard CPR technique',
'Emergency thoracotomy for penetrating chest/abdominal trauma with recent loss of vital signs; allows internal cardiac massage, cross-clamping of aorta, and direct control of thoracic hemorrhage',
'All trauma arrests',
'Only in OR setting',
'Never indicated',
'B',
'Resuscitative thoracotomy (EDT): Indications: Penetrating thoracic injury with witnessed arrest or recent vital signs (<15 min CPR for penetrating chest, <10 min for penetrating abdominal, <5 min for blunt trauma - controversial). Procedure: Left anterolateral thoracotomy, pericardiotomy (for tamponade), internal cardiac massage, aortic cross-clamp (redistributes blood to heart/brain), hemorrhage control. Survival: Best for isolated cardiac injury with tamponade (~35%). Blunt trauma survival very low (<2%).',
'hard', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is targeted temperature management (TTM) and who benefits?',
'Cooling all hospital patients',
'Maintaining target temperature (32-36°C) for 24+ hours in comatose survivors of cardiac arrest to reduce neurologic injury from ischemia-reperfusion',
'Warming after arrest',
'Only for drowning victims',
'No proven benefit',
'B',
'Targeted temperature management: Previously "therapeutic hypothermia." Current evidence: Maintain 32-36°C for ≥24 hours in comatose (not following commands) survivors of cardiac arrest. Mechanism: Reduces cerebral metabolic demand, decreases inflammatory response, reduces reperfusion injury. Fever prevention essential (fever worsens outcomes). Practical: Active temperature management required. Prognostication: Wait ≥72 hours (longer if sedated) before determining neurologic outcome. Part of post-arrest care bundle.',
'hard', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the pathophysiology of venous ulcer formation?',
'Direct venous injury',
'Venous hypertension from reflux or obstruction leads to capillary damage, fibrin cuff formation, white cell trapping, and tissue hypoxia causing skin breakdown',
'Arterial insufficiency',
'Bacterial infection primary',
'Unknown etiology',
'B',
'Venous ulcer pathophysiology: Primary problem: Venous hypertension (normally 20-30 mmHg, in venous disease 60-90 mmHg). Causes: Valvular incompetence (reflux), obstruction, calf pump failure. Effects: Capillary distension → increased permeability → fibrin deposition around capillaries (fibrin cuff) → diffusion barrier. WBC trapping and activation → chronic inflammation. Tissue hypoxia → cell death → ulceration. Location: Gaiter area (maximum ambulatory venous pressure).',
'hard', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of ankle-brachial index (ABI) in leg ulcer assessment?',
'Not useful for leg ulcers',
'ABI assesses arterial perfusion; determines if compression is safe (>0.8) and identifies arterial component requiring vascular referral (<0.5)',
'Only measures venous function',
'Should be done weekly',
'Replaced by clinical exam',
'B',
'ABI in leg ulcers: Purpose: Detect arterial disease which contraindicates or modifies treatment. Measurement: Highest ankle pressure (DP or PT) / highest brachial pressure. Normal: 0.9-1.3. Interpretation: >0.8: Safe for standard compression. 0.5-0.8: Modified compression, consider vascular referral. <0.5: Avoid compression, urgent vascular referral. >1.3: Calcified (incompressible) vessels - unreliable ABI, use toe pressures or TcPO2. Essential before starting compression therapy.',
'medium', 'application');
