-- ============================================================================
-- BATCH 65: Advanced Clinical Integration and Synthesis
-- Topics: Complex clinical scenarios requiring synthesis
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- CLINICAL SYNTHESIS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A 45-year-old woman has recurrent episodes of RUQ pain after fatty meals, with normal ultrasound. What is the likely diagnosis and next step?',
'No biliary disease possible',
'Functional biliary sphincter dysfunction (biliary dyskinesia); consider HIDA with CCK stimulation to assess gallbladder ejection fraction',
'Must be gastric ulcer',
'Requires immediate cholecystectomy',
'Dismiss symptoms as psychiatric',
'B',
'Biliary dyskinesia: Presentation: Classic biliary colic symptoms without stones on imaging. Pathophysiology: Abnormal gallbladder motility or sphincter dysfunction. Diagnosis: HIDA scan with CCK stimulation - ejection fraction <35% at 30 minutes suggestive. Treatment: Cholecystectomy if low EF and symptoms correlate - ~80% symptom relief. Differential: Also consider functional dyspepsia, peptic ulcer, IBS. Evaluation should exclude other causes before surgical intervention.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of "damage control surgery" in critically ill trauma patients?',
'Complete all repairs in first surgery',
'Abbreviated initial surgery to control hemorrhage and contamination, ICU resuscitation for physiologic recovery, then return to OR for definitive repair when stable',
'Surgery is never safe in unstable patients',
'Operate only when fully resuscitated',
'No damage control concept exists',
'B',
'Damage control surgery: Indications: Lethal triad (hypothermia, acidosis, coagulopathy), patients too unstable for prolonged surgery. Phase 1 (OR): Hemorrhage control, contamination control, temporary closure. Phase 2 (ICU): Resuscitation - correct coagulopathy, warm patient, restore perfusion. Phase 3 (OR): Definitive repair when physiologically optimized. Concept: Physiology before anatomy. Prolonged surgery in unstable patient causes more harm. Goal: Stop bleeding, control contamination, buy time to resuscitate.',
'hard', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is adrenal insufficiency in critical illness and when should it be suspected?',
'Never occurs in ICU patients',
'Stress-related relative adrenal insufficiency causing vasopressor-refractory hypotension; consider when hemodynamic instability persists despite adequate fluid resuscitation and vasopressors',
'Only in known Addison disease',
'Diagnosed by high cortisol',
'Always requires surgery',
'B',
'Critical illness-related corticosteroid insufficiency: Pathophysiology: Adrenal glands cannot meet increased cortisol demand during critical illness. Risk factors: Prolonged sepsis, prior steroids, pituitary/adrenal disease, etomidate (inhibits cortisol synthesis). Presentation: Vasopressor-refractory hypotension despite fluids. Diagnosis: Controversial - random cortisol <10 μg/dL, or cosyntropin stimulation test. Treatment: Stress-dose hydrocortisone (50mg IV q6h or 200mg/day continuous). Taper as vasopressors weaned.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'In septic shock, what is the rationale for the "Surviving Sepsis" bundle approach?',
'Random treatment steps',
'Evidence-based interventions implemented together improve outcomes more than individually; includes early antibiotics, lactate measurement, fluids, and vasopressors within time targets',
'No evidence supports bundles',
'Only one intervention matters',
'Bundles delay treatment',
'B',
'Sepsis bundles: Concept: Group of individually effective interventions that together produce greater benefit than sum of parts - "bundle of care." Current elements: Hour-1 bundle: Measure lactate, obtain blood cultures, administer broad-spectrum antibiotics, start IV crystalloid 30mL/kg for hypotension/lactate ≥4, begin vasopressors if hypotensive during/after fluids. Rationale: Time-sensitive interventions, process measure improves compliance. Evidence: Bundle compliance associated with improved survival.',
'medium', 'application'),

-- FLUIDS/ELECTROLYTES
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'How does the kidney respond to hypovolemia?',
'Increased urine output',
'Activates RAAS causing sodium and water retention, concentrates urine, and reduces output to preserve intravascular volume',
'No renal compensation',
'Excretes more sodium',
'Kidney not involved',
'B',
'Renal response to hypovolemia: Detection: Decreased renal perfusion sensed by juxtaglomerular apparatus. Response: Renin release → angiotensin II → aldosterone. Effects: ↓GFR, ↑sodium reabsorption, ↑water reabsorption (ADH also released). Urine: Low volume, concentrated (↑osmolality), low sodium (<20 mEq/L). Purpose: Preserve intravascular volume. Clinical: Low urine output with ↑specific gravity/osmolality, low UNa suggests prerenal state (hypovolemia) vs renal failure.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of anion gap in metabolic acidosis evaluation?',
'No clinical significance',
'Distinguishes gap acidosis (excess unmeasured anions like lactate, ketones) from non-gap acidosis (HCO3 loss or failure to excrete acid); guides differential diagnosis',
'Only measures bicarbonate',
'Replaced by pH alone',
'Only relevant in children',
'B',
'Anion gap: Calculation: AG = Na+ - (Cl- + HCO3-). Normal: 8-12 mEq/L. High anion gap acidosis: Unmeasured anions accumulating. MUDPILES: Methanol, Uremia, DKA, Propylene glycol, Isoniazid/Iron, Lactic acid, Ethylene glycol, Salicylates. Non-gap (hyperchloremic) acidosis: HCO3 replaced by Cl-. Causes: Diarrhea, RTA, early renal failure, normal saline infusion. Clinical: AG guides differential - different causes require different treatment.',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What laboratory tests guide blood product therapy in massive hemorrhage?',
'Hemoglobin only',
'PT/INR, PTT, fibrinogen, platelet count, and viscoelastic testing (TEG/ROTEM) if available guide component therapy; trend more important than single values',
'No testing during resuscitation',
'Blood type only',
'All products given empirically',
'B',
'Coagulation monitoring in hemorrhage: Conventional tests: PT/INR (extrinsic pathway, factor deficiency), PTT (intrinsic pathway), fibrinogen (<100-150 needs replacement), platelet count (<50K may need transfusion in bleeding). Point-of-care viscoelastic testing: TEG, ROTEM - assesses whole clot formation and breakdown in real-time. Advantages: Faster than conventional, identifies specific deficiency, guides targeted therapy. Limitations: Not universally available, requires training. Trend values during resuscitation.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What are the considerations for blood management in Jehovah''s Witness patients undergoing major surgery?',
'Refuse all surgical care',
'Detailed preoperative discussion of acceptable/unacceptable blood products, optimize hemoglobin preoperatively, use blood conservation techniques (cell salvage, acute normovolemic hemodilution), minimize blood loss',
'Only use synthetic blood',
'No special considerations',
'Always override patient wishes',
'B',
'Jehovah''s Witness surgery: Principles: Respect patient autonomy, document clearly. Variability: Some accept blood fractions (albumin, immunoglobulins, clotting factors), cell salvage with continuous circuit (blood never leaves body). Others refuse all. Pre-op: Detailed discussion, written documentation, optimize hemoglobin (EPO, iron). Intra-op: Meticulous hemostasis, cell salvage, ANH, hypotensive anesthesia, hemostatic agents. Post-op: Tolerate lower hemoglobin, minimize phlebotomy. Competent adult decision respected.',
'hard', 'application'),

-- WOUND CARE
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of biofilm in chronic wounds?',
'Easily treated with topical antibiotics',
'Organized bacterial communities encased in protective matrix attached to wound surface; resistant to antibiotics and host defenses; requires physical disruption (debridement) for management',
'Only in hospital wounds',
'Same as contamination',
'Not clinically relevant',
'B',
'Wound biofilm: Definition: Complex community of microorganisms enclosed in self-produced extracellular polymeric substance (EPS) matrix. Characteristics: Attached to wound surface, highly organized structure, metabolically different from planktonic bacteria. Resistance: 10-1000x more resistant to antibiotics, protected from host immune response. Management: Requires physical disruption - debridement. Then: Antimicrobial dressings, topical antiseptics. Systemic antibiotics alone ineffective against biofilm.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the role of hyperbaric oxygen therapy in wound healing?',
'First-line treatment for all wounds',
'Adjunct for select wounds with tissue hypoxia (radiation injury, refractory osteomyelitis, compromised flaps); increases tissue oxygen tension to support healing in otherwise non-healing wounds',
'No proven benefit',
'Contraindicated in wounds',
'Replaces standard wound care',
'B',
'Hyperbaric oxygen (HBO): Mechanism: Breathing 100% O2 at 2-3 atmospheres → plasma oxygen dramatically increased → supports tissue oxygenation even without hemoglobin. Indications: Radiation tissue injury (prophylaxis before surgery, treatment of osteoradionecrosis), refractory osteomyelitis, compromised skin grafts/flaps, gas gangrene, diabetic foot wounds. Limitations: Requires specialized facility, time-intensive (multiple sessions), not first-line therapy. Adjunct to surgical debridement and wound care.',
'medium', 'application'),

-- SUTURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What factors determine suture selection for deep tissue closure?',
'Random selection',
'Tissue type, healing time, strength requirements, infection risk, and reaction profile; absorbable for deep layers that heal before suture strength lost; appropriate tensile strength for tissue needs',
'Only cost considered',
'All sutures equivalent',
'Surgeon preference only',
'B',
'Deep tissue suture selection: Factors: Required duration of support, tissue healing rate, infection risk, tissue reactivity, suture handling. Fascia: Needs long-term strength (slowly absorbable like PDS, or non-absorbable like nylon). Muscle: Usually not sutured directly (falls apart), close fascia. Subcutaneous: Absorbable braided (Vicryl) or monofilament, reduce dead space. Infected field: Monofilament preferred (less bacterial adherence). Match suture absorption to tissue healing timeline.',
'medium', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the mechanism and purpose of antimicrobial-coated sutures?',
'No proven benefit',
'Sutures impregnated with triclosan or other antimicrobials reduce bacterial colonization on suture surface, decreasing surgical site infection rates',
'Treat active infection',
'Replace sterile technique',
'Faster wound healing',
'B',
'Antimicrobial sutures: Mechanism: Typically coated with triclosan - broad-spectrum antimicrobial. Purpose: Prevent bacterial colonization of suture material (sutures are foreign bodies, can harbor bacteria). Evidence: Meta-analyses show reduced SSI rates, particularly in high-risk cases. WHO recommendation: "Consider use of triclosan-coated sutures." Cost-effectiveness: Debated - may be beneficial in high-risk patients/procedures. Not treatment for infection. Adjunct to, not replacement for, sterile technique.',
'easy', 'application'),

-- INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'What is the purpose of laparoscopic port placement and how are sites selected?',
'Random abdominal locations',
'Strategic placement for optimal triangulation to target organ, avoiding major vessels and previous scars; camera port centrally with working ports positioned for ergonomic instrument handling',
'Only supraumbilical approach',
'No planning required',
'All in one location',
'B',
'Laparoscopic port placement: Principles: Optical access (usually periumbilical for camera), triangulation (instruments approach target from different angles), avoid vessels (epigastric vessels), consider previous scars (adhesions). Specific procedures: Ports positioned based on target organ. Cholecystectomy: Typically 4 ports including umbilical camera, epigastric working port. Ergonomics: Surgeon comfort, avoid instrument fighting. Planning: Essential for complex cases.',
'medium', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'What is a "trocar site hernia" and how is it prevented?',
'Hernia at appendectomy site',
'Hernia through laparoscopic port site from incomplete fascial closure; prevented by closing fascia for all ports ≥10mm, particularly midline and off-axis insertions',
'Cannot be prevented',
'Only occurs with camera port',
'Same as incisional hernia',
'B',
'Trocar site (port site) hernia: Definition: Hernia through fascial defect at laparoscopic port insertion site. Incidence: 1-6%, increased with larger ports (≥10mm), midline ports, stretching of port sites. Prevention: Close fascia for all ports ≥10mm, some advocate for all ≥5mm if extended. Higher risk: Umbilical ports (anatomic weakness), lateral ports at 90° angle. Techniques: Direct visualization during closure, fascial closure devices. Presentation: Bulge at port site, can present with obstruction.',
'medium', 'application'),

-- NASOGASTRIC
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'What are the indications for gastric decompression in small bowel obstruction?',
'Never indicated',
'Decompress stomach and proximal bowel to relieve distension, decrease aspiration risk, improve patient comfort, and allow resolution of partial obstruction',
'Only after surgery',
'Contraindicated in SBO',
'Replaces IV fluids',
'B',
'NG tube in SBO: Functions: Decompression of swallowed air and accumulated secretions, reduce nausea/vomiting, decrease aspiration risk, improve patient comfort, allow assessment of output volume. Role in management: Part of "drip and suck" - NPO, IV fluids, NG decompression. Partial SBO: May resolve with conservative management. Complete SBO: Decompression before surgery. Monitoring: Output volume/character helps guide management decisions.',
'easy', 'application'),

-- CATHETERIZATION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is the appropriate response to catheter-associated bacteriuria in asymptomatic patients?',
'Immediate IV antibiotics',
'Generally do not treat asymptomatic bacteriuria in catheterized patients; change catheter if symptomatic infection develops, obtain culture from new catheter, then treat if indicated',
'Remove catheter immediately',
'Prophylactic antibiotics for all',
'Ignore all positive cultures',
'B',
'Asymptomatic catheter bacteriuria: Prevalence: Very common - ~100% by 30 days of catheterization. Asymptomatic bacteriuria: Presence of bacteria without symptoms of UTI. Evidence: Treatment of asymptomatic bacteriuria does NOT prevent symptomatic UTI and promotes resistance. Exception: Before urologic procedures. If symptomatic (fever, suprapubic pain, CVA tenderness): Change catheter, culture from new catheter, treat based on culture. Most important: Remove catheter as soon as possible.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What are the complications of long-term urethral catheterization?',
'No complications after first week',
'Catheter-associated UTI, urethral erosion, urethral stricture, bladder spasms, stone formation on catheter, and decreased bladder capacity',
'Only minor discomfort',
'Self-limiting issues',
'Improved bladder function',
'B',
'Long-term catheter complications: Infectious: CAUTI (most common nosocomial infection). Mechanical: Urethral erosion/stricture (especially males), catheter blockage. Other: Bladder spasms/bypass leaking, bladder stones (form on catheter), reduced bladder capacity (disuse atrophy). Prevention: Minimize catheter use, consider suprapubic for long-term needs, adequate hydration, routine catheter changes. Long-term catheterization: Reconsider indication regularly, consider alternatives (intermittent catheterization, suprapubic).',
'medium', 'application');
