-- ============================================================================
-- BATCH 66: Critical Care and Surgical Emergencies
-- Topics: Time-sensitive conditions and critical decisions
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- CRITICAL SCENARIOS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A postoperative patient suddenly becomes anxious, tachypneic, with oxygen saturation dropping. ECG shows sinus tachycardia. What is the most likely diagnosis?',
'Myocardial infarction',
'Pulmonary embolism presenting with sudden dyspnea, tachycardia, and hypoxemia in postoperative patient',
'Simple anxiety attack',
'Pneumothorax',
'Opioid overdose',
'B',
'Pulmonary embolism presentation: Classic scenario: Postoperative patient with sudden dyspnea, tachycardia, hypoxemia. Risk factors: Surgery, immobility, malignancy, hypercoagulable states. Signs: Tachycardia (most common), tachypnea, hypoxemia, clear lungs (helps differentiate from pneumonia). ECG: Sinus tachycardia (most common), S1Q3T3 (specific but not sensitive). Workup: CT pulmonary angiography if stable, echocardiogram if unstable. Treatment: Anticoagulation, thrombolysis for massive PE.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient 5 days post-colonic surgery develops fever 39°C, tachycardia, and localized abdominal tenderness. What is the most concerning diagnosis?',
'Normal postoperative course',
'Anastomotic leak with peritonitis requiring urgent evaluation and likely return to OR',
'Urinary tract infection',
'Simple wound infection',
'Atelectasis',
'B',
'Anastomotic leak: Timing: Usually POD 5-7, but can occur earlier. Presentation: Fever, tachycardia, abdominal pain, ileus, leukocytosis. May be subtle initially. Severe: Sepsis, peritonitis. Diagnosis: CT with water-soluble contrast, clinical suspicion. Management: Small contained leak may be managed with drainage. Large leak, free spillage, peritonitis: OR for washout ± diversion. Outcomes: Significant morbidity/mortality. High index of suspicion critical.',
'hard', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of "occult hypoperfusion" and how is it detected?',
'Obvious hypotension always present',
'Tissue hypoperfusion despite normal vital signs; detected by elevated lactate, base deficit, or decreased central/mixed venous oxygen saturation',
'Cannot be detected',
'Only in elderly patients',
'No clinical significance',
'B',
'Occult hypoperfusion: Definition: Inadequate tissue perfusion despite "normal" vital signs (compensated shock). Detection: Lactate (>2 mmol/L concerning, >4 mmol/L abnormal), base deficit (>-6 indicates significant shock), ScvO2/SvO2 (low indicates tissues extracting more O2). Importance: Traditional vital signs may normalize before tissue perfusion adequate. Continued resuscitation guided by perfusion markers, not just BP/HR. Unrecognized occult hypoperfusion leads to organ dysfunction.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'In a trauma patient, what is the significance of responding to fluid resuscitation only transiently?',
'Adequate resuscitation achieved',
'Indicates ongoing hemorrhage requiring urgent source control; transient response suggests continued blood loss that fluids cannot compensate',
'Patient is fluid overloaded',
'Give more crystalloid',
'No significance',
'B',
'Transient responders: Definition: Initial improvement in vital signs with fluid bolus, followed by deterioration when fluids stopped. Interpretation: Ongoing hemorrhage - rate of blood loss exceeds resuscitation. Management: Need source control - OR for surgical bleeding, angioembolization for non-surgical. NOT more crystalloid - will only dilute and not address source. Blood products may temporize. Classification helpful: Responders (volume deficit), transient responders (ongoing bleed), non-responders (massive hemorrhage or non-hemorrhagic cause).',
'hard', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A patient with severe burns has urine output of 20 mL/hr despite aggressive fluid resuscitation. What is the next step?',
'Decrease fluids to avoid overload',
'Increase fluid rate to target urine output 0.5-1 mL/kg/hr; inadequate UOP indicates under-resuscitation in burns',
'Output is adequate',
'Add diuretics',
'Discontinue all fluids',
'B',
'Burn resuscitation monitoring: Goal: UOP 0.5-1 mL/kg/hr (30-50 mL/hr in adults). Low UOP: Under-resuscitation → increase fluid rate. High UOP (>1 mL/kg/hr): May be over-resuscitating → decrease rate. Parkland formula: Starting point, adjust based on response. Unique considerations: Massive insensible losses, third-spacing. Monitor for resuscitation failure: Consider escharotomy if compartment syndrome, check if formula underestimated needs (inhalation injury increases requirements). Avoid both under- and over-resuscitation.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'A critically ill patient develops hypernatremia (Na 158). What is the likely cause and treatment?',
'Give hypertonic saline',
'Likely free water deficit from inadequate intake or excessive losses; treat with hypotonic fluids (D5W, 0.45% NS), correct slowly to avoid cerebral edema',
'Normal finding in ICU',
'Salt restriction only',
'Diuretic therapy',
'B',
'ICU hypernatremia: Causes: Inadequate free water (intubated patients cannot drink), excessive losses (fever, diarrhea, diabetes insipidus, osmotic diuresis). Treatment: Free water replacement. Route: Enteral preferred if GI functioning. IV: D5W or 0.45% saline. Rate: Correct at 0.5 mEq/L/hr (10-12 mEq/L per 24 hrs) to avoid cerebral edema. Calculate free water deficit: 0.6 × weight × [(Na/140) - 1]. Address underlying cause.',
'medium', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'During massive transfusion, a patient develops hypotension and oozing from IV sites. What is the likely cause?',
'Transfusion reaction',
'Dilutional coagulopathy and hypocalcemia from massive transfusion; treat with FFP, platelets, cryoprecipitate, and calcium replacement',
'Citrate allergy',
'Need more RBCs only',
'Normal during resuscitation',
'B',
'Massive transfusion coagulopathy: Mechanism: Dilution of clotting factors and platelets with RBC transfusion. Citrate in blood products binds calcium → hypocalcemia (↓ionized Ca). Presentation: Oozing from wounds/IV sites, hypotension, tremor, prolonged QT. Management: Balanced resuscitation (FFP:RBC:platelets ratios), calcium replacement (monitor ionized Ca), fibrinogen replacement (cryo or concentrate), warm products. Prevention: MTP protocols with balanced ratios from start.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is the threshold for platelet transfusion in a patient undergoing emergency surgery?',
'Always transfuse to 150,000',
'Target platelets >50,000/μL for most surgery; >100,000/μL for neurosurgery or ocular surgery where bleeding is particularly dangerous',
'No minimum required',
'Only transfuse if <10,000',
'Platelets never needed for surgery',
'B',
'Platelet transfusion thresholds: Surgery: General surgery: >50,000/μL (adequate for hemostasis). Neurosurgery, ocular surgery: >100,000/μL (bleeding into confined space catastrophic). Central line placement: >20,000-50,000/μL. Prophylactic (non-bleeding): <10,000/μL in stable patients. One apheresis unit: Typically increases count 30,000-50,000/μL. Considerations: Platelet function matters too - uremia, medications may impair function even with normal count.',
'medium', 'application'),

-- WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'A surgical wound has purulent drainage on POD 4. What is the initial management?',
'Start broad-spectrum IV antibiotics',
'Open the wound to allow drainage, culture the fluid, pack wound open; antibiotics only if surrounding cellulitis or systemic signs',
'Continue observation',
'Re-close the wound',
'Apply antibiotic ointment',
'B',
'SSI management: Superficial SSI: Open wound, evacuate pus/debris, pack open for secondary intention healing. Cultures: Helpful but treatment based on clinical assessment. Antibiotics: NOT needed for localized wound infection without cellulitis or systemic signs. Indications for antibiotics: Surrounding cellulitis, systemic signs (fever, leukocytosis), immunocompromised, prosthetic material. Principle: Adequate drainage is treatment - "ubi pus, ibi evacua" (where there is pus, evacuate it).',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the "reconstructive ladder" in wound management?',
'Fixed sequence of treatment',
'Hierarchy of wound closure options from simple to complex: secondary intention, primary closure, skin grafts, local flaps, regional flaps, free tissue transfer',
'Only applies to burns',
'Surgeons choice only',
'No standard approach exists',
'B',
'Reconstructive ladder: Concept: Simplest method that achieves wound closure preferred. Rungs: Secondary intention (healing by granulation), primary closure, delayed primary closure, skin grafting (STSG, FTSG), local flaps, regional/pedicled flaps, free tissue transfer (microvascular). Modern evolution: "Reconstructive elevator" - may skip rungs based on wound characteristics and patient factors. Not rigid sequence - choose appropriate level based on wound needs. Complex wounds may need immediate advanced reconstruction.',
'medium', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has femur fracture with blood loss. How much blood can be lost into a closed femur fracture?',
'Minimal blood loss',
'1-2 liters of blood can accumulate in the thigh compartment from closed femur fracture; accounts for significant hemorrhage',
'Only open fractures bleed',
'Less than 100mL',
'Blood loss easily visible',
'B',
'Occult blood loss in fractures: Femur: 1-2 L (1000-2000 mL). Tibia: 0.5-1 L. Pelvis: Massive (life-threatening, can be entire blood volume). Humerus: Up to 750 mL. Radius/ulna: 150-250 mL. Clinical significance: Hemodynamically unstable patient may have "hidden" blood in fracture. Multiply with multiple fractures. Assessment: Consider fracture-related blood loss when evaluating shock. Stabilization reduces ongoing loss. Part of secondary survey but impact on primary resuscitation.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of fat embolism syndrome after long bone fracture?',
'Rare and benign',
'Serious complication occurring 24-72 hours after fracture with classic triad of respiratory distress, neurologic changes, and petechial rash; can be life-threatening',
'Only with open fractures',
'Easily treated with medication',
'Does not affect outcomes',
'B',
'Fat embolism syndrome (FES): Timing: 24-72 hours post-fracture (usually long bones, pelvis). Classic triad: Respiratory distress (most common, earliest), neurologic changes (confusion, decreased consciousness), petechial rash (classic but late, upper body). Pathophysiology: Fat globules from marrow enter circulation, cause mechanical obstruction and inflammatory response. Diagnosis: Clinical, exclusion of other causes. Treatment: Supportive care, oxygen, mechanical ventilation if needed. Prevention: Early fracture stabilization.',
'hard', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of end-tidal CO2 (ETCO2) during CPR?',
'No utility during resuscitation',
'ETCO2 reflects cardiac output during CPR; rising ETCO2 indicates effective compressions or ROSC; persistently low ETCO2 (<10 mmHg) suggests poor prognosis',
'Only for confirming intubation',
'Should be kept at zero',
'Monitors ventilation only',
'B',
'ETCO2 in cardiac arrest: Mechanism: CO2 delivery to lungs requires cardiac output. During CPR: ETCO2 reflects quality of compressions (blood flow to lungs). Normal CPR: ETCO2 typically 10-20 mmHg. ROSC: Sudden ETCO2 increase (often >40 mmHg). Prognostic: Persistently <10 mmHg after 20 min associated with poor outcome. Uses: Confirm tube placement, monitor compression quality, early detection of ROSC. Part of current resuscitation monitoring.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What are the reversible causes of cardiac arrest (H''s and T''s)?',
'Only cardiac causes',
'Hypovolemia, Hypoxia, Hydrogen ion (acidosis), Hypo/hyperkalemia, Hypothermia; Tension pneumothorax, Tamponade, Toxins, Thrombosis (pulmonary/coronary)',
'Random causes',
'Not clinically useful',
'Only treat heart directly',
'B',
'H''s and T''s: During CPR, actively seek reversible causes: H''s: Hypovolemia (fluids/blood), Hypoxia (oxygenate), Hydrogen ion/acidosis (ventilation, bicarb if indicated), Hypo/hyperkalemia (treat electrolyte), Hypothermia (warm). T''s: Tension pneumothorax (needle/finger thoracostomy), Tamponade (pericardiocentesis), Toxins (specific antidotes), Thrombosis PE (thrombolytics), Thrombosis coronary (PCI). Treatment of underlying cause essential for successful resuscitation.',
'easy', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What are the features that distinguish malignant transformation (Marjolin ulcer) in a chronic wound?',
'All chronic wounds become malignant',
'Non-healing edges, exuberant granulation tissue, bleeding, rapid change in long-standing wound; biopsy any suspicious chronic wound',
'Always obvious cancer appearance',
'Transformation takes only weeks',
'No clinical features exist',
'B',
'Marjolin ulcer: Definition: Squamous cell carcinoma arising in chronic wound/scar. Timeline: Usually >10 years of chronic wound (burn scar, venous ulcer, osteomyelitis sinus). Features: Change in chronic wound - heaped/everted edges, exuberant/friable granulation, bleeding, rapid growth, pain. Behavior: More aggressive than primary SCC, higher metastatic rate. Diagnosis: Biopsy (edge and center). Management: Wide excision, consider lymph node assessment. Prevention: Aggressive treatment of chronic wounds.',
'hard', 'application'),

-- MONITORING
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'What does a rapidly increasing heart rate with falling blood pressure indicate in a postoperative patient?',
'Normal postoperative recovery',
'Decompensating shock - likely hemorrhage, sepsis, or cardiac event requiring immediate evaluation and intervention',
'Medication effect only',
'Anxiety from hospitalization',
'Expected with ambulation',
'B',
'Hemodynamic deterioration: Tachycardia + hypotension: Heart rate increasing to maintain cardiac output, but BP falling indicates failing compensation. Differential: Hemorrhage (most common post-op), sepsis (especially later post-op), cardiac event (MI, tamponade), PE, medication effect (less likely with hypotension). Response: Immediate bedside evaluation, fluid resuscitation while investigating cause, prepare for intervention. Do not attribute to benign cause without evaluation.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What does worsening metabolic acidosis with increasing lactate indicate during surgery?',
'Normal surgical finding',
'Inadequate tissue perfusion despite apparent hemodynamic stability; indicates need for improved resuscitation or source control',
'Laboratory error',
'Expected with general anesthesia',
'No clinical significance',
'B',
'Intraoperative acidosis: Rising lactate: Indicates anaerobic metabolism from inadequate oxygen delivery. Causes: Hypovolemia (inadequate preload), poor cardiac output, regional hypoperfusion (mesenteric ischemia). Response: Check volume status, cardiac function, consider inotropes if cardiac dysfunction, source control if ischemic bowel. Trend matters: Lactate clearance with resuscitation favorable; rising lactate concerning. Cannot ignore "good" vital signs if lactate rising.',
'hard', 'application');
