-- ============================================================================
-- BATCH 67: Complex Case Management and Clinical Pearls
-- Topics: Essential knowledge for clinical practice
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- GENERAL SURGERY
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'An elderly patient is found to have asymptomatic abdominal aortic aneurysm measuring 4.5 cm. What is the appropriate management?',
'Immediate surgical repair',
'Surveillance with ultrasound every 6-12 months; intervene when reaches 5.5 cm or grows >1 cm/year or becomes symptomatic',
'No follow-up needed',
'Stent placement now',
'CT scan weekly',
'B',
'AAA surveillance: Rupture risk related to size. <4.0 cm: Very low risk, US every 2-3 years. 4.0-4.5 cm: US every 12 months. 4.5-5.4 cm: US every 6 months. ≥5.5 cm (men), ≥5.0 cm (women): Consider repair. Growth >1 cm/year or symptoms: Repair regardless of size. Repair options: Open surgical or EVAR (endovascular). Medical optimization: Blood pressure control, smoking cessation, statin therapy. Rupture: 85% mortality if not reaching OR.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the triad of symptoms for ruptured AAA?',
'Chest pain, dyspnea, cough',
'Sudden severe abdominal or back pain, hypotension, and pulsatile abdominal mass; classic triad present in only 25-50% of cases',
'Fever, rigors, jaundice',
'Nausea, vomiting, diarrhea',
'Headache, confusion, seizure',
'B',
'Ruptured AAA triad: Classic: Abdominal/back pain (sudden, severe), hypotension (from hemorrhage), pulsatile abdominal mass. Reality: Full triad present in only 25-50% of cases. May present with syncope, back pain only, misdiagnosed as renal colic. High-risk populations: Males >65, smokers, known AAA. Key point: Hypotensive elderly patient with abdominal/back pain = ruptured AAA until proven otherwise. Immediate surgical consultation. Bedside ultrasound can identify AAA (not rupture).',
'hard', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the relationship between mean arterial pressure (MAP) and organ perfusion?',
'MAP not clinically important',
'MAP is the driving pressure for organ perfusion; minimum MAP of 65 mmHg generally needed for adequate perfusion; some patients may need higher targets',
'Only systolic pressure matters',
'MAP should be maximized',
'Diastolic pressure alone sufficient',
'B',
'MAP and organ perfusion: Calculation: MAP = DBP + 1/3(SBP - DBP), or (SBP + 2×DBP)/3. Significance: True driving pressure for organ blood flow. Target: Generally ≥65 mmHg. Higher targets (75-80) may be needed for: Chronic hypertension, evidence of organ hypoperfusion despite MAP 65. Trade-off: Higher MAP requires more vasopressors → potential adverse effects. Individualize: Target MAP based on end-organ function (mental status, urine output, lactate clearance), not just number.',
'medium', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of skin mottling in a patient with shock?',
'Cosmetic finding only',
'Indicates peripheral vasoconstriction and poor microcirculatory perfusion; mottling score correlates with mortality in septic shock',
'Sign of allergic reaction',
'Normal during stress',
'Unrelated to perfusion',
'B',
'Skin mottling in shock: Pathophysiology: Peripheral vasoconstriction shunts blood centrally; heterogeneous perfusion creates mottled appearance. Location: Usually starts around knees, extends to thighs with worsening shock. Mottling score: Grades 0-5 based on extent; higher scores associated with increased mortality. Clinical value: Easy bedside assessment of microcirculation. Improvement: Mottling resolution with resuscitation suggests improving perfusion. Other signs of poor perfusion: Cool extremities, prolonged capillary refill, weak pulses.',
'medium', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is "third spacing" and what conditions cause it?',
'Normal fluid distribution',
'Fluid shift from intravascular space to non-functional compartments (tissue edema, bowel wall, peritoneum); occurs with inflammation, surgery, sepsis, pancreatitis',
'Fluid loss in urine',
'Increased blood volume',
'Medication side effect only',
'B',
'Third spacing: Definition: Fluid leaves intravascular space but not the body - accumulates in interstitium, body cavities. "Third space" = non-functional, neither intravascular nor intracellular. Causes: Surgical trauma, sepsis, pancreatitis, burns, bowel obstruction. Effect: Hypovolemia despite total body fluid excess (edematous but intravascularly depleted). Management: Replace intravascular volume initially, then mobilization phase (third-space fluid returns to circulation, requires diuresis). Can cause pulmonary edema during mobilization.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'Why is hypophosphatemia dangerous in critically ill patients?',
'No clinical significance',
'Phosphate essential for ATP production, oxygen delivery (2,3-DPG), and cell membrane integrity; severe deficiency causes muscle weakness, respiratory failure, cardiac dysfunction',
'Only affects bones',
'Easily tolerated',
'Self-correcting condition',
'B',
'Hypophosphatemia consequences: Cellular energy: Phosphate essential for ATP synthesis - deficiency → cellular energy failure. Oxygen delivery: 2,3-DPG requires phosphate; low levels → left shift, impaired O2 release. Muscle function: Diaphragm weakness → respiratory failure, cardiac dysfunction. RBC fragility: Hemolysis. CNS: Confusion, seizures. Risk populations: Refeeding syndrome, alcoholism, DKA treatment, TPN without adequate phosphate. Treatment: IV phosphate replacement (caution: can cause hypocalcemia).',
'hard', 'application'),

-- BLOOD PRODUCTS
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is the difference between type and screen and type and crossmatch?',
'Identical procedures',
'Type and screen: Determines ABO/Rh and screens for antibodies. Crossmatch: Additionally tests patient serum against specific donor unit for compatibility before transfusion',
'Only crossmatch is needed',
'Type alone is sufficient',
'No difference clinically',
'B',
'Blood testing: Type and Screen (T&S): ABO and Rh typing of patient, antibody screen (looks for unexpected antibodies). Takes 45-60 minutes. If negative screen, blood can be released quickly. Crossmatch: T&S plus mixing patient serum with actual donor unit to check for reaction. Takes additional time. Indications: Crossmatch for patients with positive antibody screen, previous transfusion reactions, or when multiple specific units needed. Emergency: Type-specific or O-negative can be released immediately.',
'easy', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is the role of erythropoietin (EPO) in preoperative blood management?',
'Only for dialysis patients',
'Stimulates RBC production; used preoperatively to optimize hemoglobin in planned surgery, especially when transfusion avoidance important or autologous donation planned',
'Replaces blood transfusion',
'No surgical application',
'Works immediately',
'B',
'EPO in surgery: Mechanism: Stimulates erythropoiesis in bone marrow. Onset: 2-4 weeks for significant Hgb increase. Uses: Optimize preoperative hemoglobin in elective surgery (cardiac, orthopedic), support autologous blood donation, Jehovah''s Witness patients, anemia of chronic disease. Dosing: Variable protocols, typically with iron supplementation. Limitations: Time required, cost, rare thrombotic complications, concern about tumor growth (cancer patients). Not for emergency or short-notice surgery.',
'medium', 'application'),

-- WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of undermining wound edges?',
'Always harmful',
'Reduces skin tension to allow wound edge approximation; enables closure of wounds with tissue loss; should preserve dermal blood supply',
'No surgical purpose',
'Increases infection risk only',
'Contraindicated in all wounds',
'B',
'Wound undermining: Purpose: Reduce tension on wound edges, allow approximation when tissue defect present. Technique: Separate skin/subcutaneous from deeper structures in plane that preserves dermal blood supply. Benefits: Enables primary closure of larger defects, reduces risk of wound dehiscence. Risks: Create dead space (need drainage or quilting sutures), damage blood supply if excessive. Level: Usually subdermal or above fascia. Used in: Skin cancer excision, traumatic wounds with tissue loss.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the pathophysiology of pressure injuries (decubitus ulcers)?',
'Infectious etiology',
'Sustained pressure exceeds capillary closing pressure (32 mmHg), causing tissue ischemia; friction and shear forces, moisture, and malnutrition contribute',
'Allergic reaction to bedding',
'Vascular occlusion disease',
'Medication side effect',
'B',
'Pressure injury pathophysiology: Primary mechanism: Sustained external pressure (>32 mmHg, capillary closing pressure) → tissue ischemia → cell death. Contributing factors: Friction (skin damage from movement), shear (deep tissue damage from sliding), moisture (maceration, increases friction), malnutrition (impaired healing). Time: Injury can occur in 2 hours. Locations: Bony prominences - sacrum, heels, trochanters, ischium. Prevention: Pressure redistribution (turning, specialized surfaces), moisture management, nutrition optimization.',
'medium', 'application'),

-- SUTURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the purpose of "buried" dermal sutures in skin closure?',
'No functional purpose',
'Approximate dermal layer to reduce tension on epidermis, eliminate dead space, and improve cosmetic outcome; knot buried to prevent spitting',
'Faster than superficial sutures',
'Only for large wounds',
'Contraindicated in skin',
'B',
'Buried dermal sutures: Purpose: Close deep dermis, reduce tension on skin edges. Benefits: Better wound edge eversion, reduced tension on epidermal closure → improved scar, eliminate dead space. Technique: Knot buried (deep) to prevent foreign body reaction, suture spitting. Materials: Absorbable (Vicryl, Monocryl, PDS). Configuration: Often inverted, knot at depth of wound. Result: Allows superficial closure with minimal tension → can use skin glue or tape instead of sutures for epidermis.',
'easy', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What determines optimal suture size for a given tissue?',
'Always use largest available',
'Match suture strength to tissue holding strength and required tension; use smallest suture that will hold the repair adequately',
'Only surgeon preference',
'Size does not matter',
'All tissues use same size',
'B',
'Suture sizing: Principle: Suture should be no stronger than tissue it approximates. Tissue considerations: Fascia (strong holding, larger sutures), skin (moderate), bowel (gentle, smaller sutures). General guidance: Use smallest suture that maintains adequate strength for healing period. Larger sutures: More tissue reaction, larger needle track, potential for tearing through tissue. Typical sizes: Fascial closure 0-1, subcutaneous 3-0 to 4-0, skin 4-0 to 6-0 depending on location.',
'easy', 'knowledge'),

-- INCISIONS
('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'What are the advantages of transverse abdominal incisions over vertical incisions?',
'No advantages, purely cosmetic',
'Follow Langer lines for better cosmesis, less postoperative pain, lower hernia rate; maintain some mechanical strength advantage from intact longitudinal muscle fibers',
'Vertical always preferred',
'Faster to perform',
'Better for all procedures',
'B',
'Transverse vs vertical incisions: Transverse advantages: Follow Langer lines (better scar), cross fibers of lateral abdominal muscles (stronger closure), studies suggest lower incisional hernia rate, less pulmonary compromise (less pain with breathing). Vertical advantages: Faster to open and close, better extensibility, better access to entire abdomen for unclear diagnosis. Choice: Depends on procedure, exposure needed, patient factors. Many procedures possible through either approach.',
'medium', 'application'),

-- MONITORING
('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of jugular venous distension (JVD) in clinical assessment?',
'Normal finding in all patients',
'Indicates elevated right atrial pressure; concerning for right heart failure, cardiac tamponade, tension pneumothorax, or fluid overload',
'Sign of dehydration',
'Only seen in neck trauma',
'Related to carotid disease',
'B',
'JVD interpretation: Normal: JVP visible 3-4 cm above sternal angle (equivalent to RA pressure ~8 cm H2O). Elevated JVD indicates: Right heart failure, volume overload, cardiac tamponade, tension pneumothorax, PE, constrictive pericarditis. Assessment: Position patient at 45°, measure height of venous pulsation above sternal angle. Absence of JVD: Does not rule out these conditions (may be present with hypovolemia). Combined with hypotension: Suggests obstructive shock (tamponade, tension PTX).',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is pulse pressure variation (PPV) and how is it used?',
'Random measurement variation',
'Cyclic variation in pulse pressure with mechanical ventilation; indicates fluid responsiveness when >12% - patients likely to increase cardiac output with fluid bolus',
'Used only for arrhythmia',
'Monitors oxygen saturation',
'Not useful clinically',
'B',
'Pulse pressure variation: Definition: Cyclic change in pulse pressure during mechanical ventilation. Calculation: (PPmax - PPmin) / PPmean × 100. Threshold: PPV >12-13% suggests fluid responsiveness. Mechanism: Positive pressure ventilation varies venous return; preload-dependent ventricle shows more variation. Advantages over CVP: Better predictor of fluid responsiveness. Limitations: Requires mechanical ventilation, sinus rhythm, adequate tidal volume (>8 mL/kg). Similar principles: Stroke volume variation (SVV).',
'hard', 'application'),

-- NG TUBE
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of "coffee ground" aspirate from nasogastric tube?',
'Normal gastric secretions',
'Indicates upper GI bleeding; blood altered by gastric acid appears dark and granular; requires evaluation for bleeding source',
'Bile-stained output',
'Medication residue',
'Sign of tube malposition',
'B',
'Coffee ground aspirate: Appearance: Dark, granular material resembling coffee grounds. Cause: Blood in stomach, partially digested by gastric acid → hematin formation. Significance: Upper GI bleeding (active or recent). Sources: Peptic ulcer, gastritis, Mallory-Weiss tear, varices, malignancy. Management: Confirm with testing (guaiac), volume resuscitation, PPI therapy, GI consultation for endoscopy. Note: Bright red blood indicates more brisk bleeding, not yet exposed to acid.',
'easy', 'application'),

-- CATHETERIZATION
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of hematuria after urethral catheterization?',
'Always requires imaging',
'Small amount of blood common after instrumentation; persistent or significant hematuria requires investigation for urethral injury, bladder pathology, or trauma',
'Never significant',
'Indicates UTI always',
'Normal and expected',
'B',
'Post-catheterization hematuria: Minor: Small amount of blood common, especially if difficult insertion, resolves quickly. Concerning: Persistent hematuria, significant volume, clots, pain. Causes: Urethral trauma/false passage, bladder pathology (incidental finding), prostatic bleeding. Evaluation: If significant or persistent - consider urology consultation, imaging (CT urogram), cystoscopy. Prevention: Adequate lubrication, gentle technique, appropriate catheter size. Document any difficulty and hematuria in chart.',
'easy', 'application');
