-- ============================================================================
-- BATCH 68: Essential Surgical Reasoning and Principles
-- Topics: Core knowledge integrated across surgery topics
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- PRINCIPLES
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A patient with known cirrhosis requires urgent abdominal surgery. What are key perioperative concerns?',
'No special considerations',
'Coagulopathy, ascites, portal hypertension, impaired drug metabolism, hepatorenal syndrome risk, increased bleeding and infection risk',
'Lower surgical risk than normal',
'Only concern is jaundice',
'Fast recovery expected',
'B',
'Cirrhosis and surgery: Coagulation: ↓clotting factors, ↓platelets (splenomegaly), may need FFP, platelets, vitamin K. Ascites: Wound healing impaired, leak risk, infection risk. Portal hypertension: Collaterals cause bleeding, avoid excessive manipulation. Hepatorenal risk: Avoid nephrotoxins, maintain renal perfusion. Drug metabolism: Impaired clearance of many drugs. MELD score: Predicts perioperative mortality - MELD >15 high risk. Approach: Optimize preoperatively, correct coagulopathy, minimize insult.',
'hard', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of "surgical judgment" and when is watchful waiting appropriate?',
'Always operate when pathology found',
'Balancing intervention risk versus observation risk based on diagnosis, disease course, patient factors, and available evidence; not all pathology requires surgery',
'Only junior surgeons observe',
'Evidence never supports waiting',
'Observation shows indecision',
'B',
'Surgical judgment: Definition: Clinical decision-making integrating diagnosis, natural history, operative risk, patient preferences. Watchful waiting appropriate: When operative risk exceeds observation risk. Examples: Small asymptomatic hernia, uncomplicated acute appendicitis (selected cases, controversial), small asymptomatic AAA, stable trauma patient without peritonitis. Key: Clear indications for intervention, serial examination if observing, patient understanding of warning signs. Judgment evolves with evidence and experience.',
'medium', 'application'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'How does preexisting hypertension affect blood pressure interpretation in shock?',
'No effect on interpretation',
'Chronically hypertensive patients may be hypoperfused at "normal" blood pressure; autoregulatory curves shifted, requiring higher MAP for organ perfusion',
'Makes hypotension more obvious',
'Hypertensives never develop shock',
'Blood pressure always reliable',
'B',
'Hypertension and shock interpretation: Autoregulation: Chronic hypertension shifts cerebral and renal autoregulation curves rightward. Effect: Organs accustomed to higher pressure; "normal" BP may represent hypoperfusion. Example: Patient with baseline BP 180/100 may be in shock at BP 100/60 even though "normal" range. Clinical: Use end-organ function (mental status, urine output, lactate) rather than absolute BP targets. May need higher MAP target in chronic hypertensives.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the initial management priority in a hypotensive patient with distended abdomen after trauma?',
'CT scan first',
'Hemorrhagic shock assumed until proven otherwise; volume resuscitation and preparation for emergency laparotomy; imaging only if patient stable enough',
'Antibiotics first',
'Serial abdominal exams',
'Wait for blood results',
'B',
'Abdominal trauma with hypotension: Principle: Hypotension + distended abdomen after trauma = bleeding until proven otherwise. Immediate: Large bore IV access, activate massive transfusion protocol, call surgery. FAST exam: Confirm intra-abdominal fluid (blood). Decision: Hemodynamically unstable → operating room without delay for imaging. CT: Only if patient responds to resuscitation and remains stable. Damage control principles apply. Source control is treatment for hemorrhagic shock.',
'hard', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is the clinical presentation of hypermagnesemia?',
'No clinical manifestations',
'Muscle weakness, decreased deep tendon reflexes, respiratory depression, hypotension, and cardiac arrest in severe cases',
'Hyperactive reflexes',
'Seizures and tremors',
'Same as hypomagnesemia',
'B',
'Hypermagnesemia: Causes: Usually iatrogenic (Mg treatment), renal failure with Mg intake. Clinical (by serum level): >4 mEq/L: Loss of deep tendon reflexes (first sign). >5 mEq/L: Muscle weakness, nausea. >7 mEq/L: Respiratory depression, hypotension. >12 mEq/L: Cardiac arrest. ECG: Prolonged PR and QRS, heart block. Treatment: Stop magnesium, IV calcium (antagonizes Mg at neuromuscular junction), dialysis if severe with renal failure. Most common in obstetric setting (eclampsia treatment).',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What determines the choice between crystalloid and colloid for volume resuscitation?',
'Colloids always preferred',
'Generally crystalloids preferred - equivalent outcomes, lower cost; colloids may be considered in massive resuscitation to limit volume but evidence for benefit is lacking',
'Crystalloids never effective',
'Random choice',
'Based on fluid color',
'B',
'Crystalloid vs colloid: Evidence: Large RCTs (SAFE, CHEST, CRISTAL) show no mortality benefit of colloids over crystalloids. Crystalloid advantages: Lower cost, widely available, no allergic reactions. Colloid considerations: May need less volume for same effect (higher oncotic pressure), theoretical advantages not proven clinically. Current recommendation: Crystalloids first-line. Specific colloids: Albumin reasonable in sepsis (not proven better), starches associated with harm in sepsis (avoid). Balanced crystalloids preferred over NS.',
'medium', 'application'),

-- BLOOD
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is irradiated blood and when is it indicated?',
'Blood exposed to radiation for sterility',
'Gamma-irradiated blood products to prevent transfusion-associated graft versus host disease; indicated for immunocompromised recipients, HLA-matched products, and blood from relatives',
'All blood is irradiated',
'Only for cancer patients',
'Increases infection risk',
'B',
'Irradiated blood products: Purpose: Prevent transfusion-associated GVHD (donor lymphocytes attack recipient tissues). Irradiation: 25-50 Gy gamma radiation inactivates donor lymphocytes. Indications: Severely immunocompromised (stem cell transplant, some chemotherapy), congenital immunodeficiency, HLA-matched/related donor products, intrauterine transfusions. Note: Does not prevent other transfusion reactions. Storage: Irradiation increases potassium leak, shorter shelf life for RBCs after irradiation.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is preoperative anemia and why is it important to address?',
'Minor finding before surgery',
'Independent risk factor for perioperative morbidity and mortality; should be identified and treated preoperatively to reduce transfusion requirement and improve outcomes',
'Only affects elderly patients',
'Transfusion will correct it',
'Not related to outcomes',
'B',
'Preoperative anemia: Prevalence: 20-40% of surgical patients. Impact: Independent risk factor for mortality, major complications, longer LOS, transfusion requirement. Mechanism: Reduced oxygen carrying capacity, less reserve for blood loss. Management: Identify early (preop visit 2-4 weeks before surgery), investigate cause (iron deficiency common), treat accordingly (iron supplementation, EPO if appropriate, treat underlying disease). Goal: Optimize hemoglobin before elective surgery to reduce transfusion need.',
'medium', 'application'),

-- WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is a "keloid" and how does it differ from hypertrophic scar?',
'Identical conditions',
'Keloid extends beyond original wound boundaries; hypertrophic scar stays within wound margins; keloids more difficult to treat with high recurrence rate',
'Keloid is normal healing',
'Only color differs',
'Treatment is the same',
'B',
'Keloid vs hypertrophic scar: Keloid: Extends BEYOND original wound margins, rarely regresses, high recurrence after excision (>50%), associated with certain genetic/ethnic factors. Hypertrophic scar: Stays WITHIN wound margins, often regresses over 1-2 years, lower recurrence after treatment. Both: Elevated, excessive collagen deposition. Treatment: Hypertrophic responds better to silicone, pressure, steroids. Keloids: Combination therapy needed (excision + radiation/steroids), high recurrence.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the concept of "moist wound healing" and when is it preferred?',
'Wounds should always be kept dry',
'Maintaining optimal moisture at wound surface promotes epithelialization and healing; moist dressings accelerate healing compared to dry dressings for most wounds',
'Only for burns',
'Increases infection',
'No difference in outcomes',
'B',
'Moist wound healing: Evidence: Winter (1962) - moist wounds epithelialize faster than dry. Mechanism: Cells migrate better in moist environment, growth factors concentrated at surface, autolytic debridement facilitated. Not wet: Goal is balanced moisture, not maceration. Dressings: Hydrocolloids, hydrogels, foam, alginates maintain appropriate moisture. Exceptions: Some infected wounds may need drying; highly exudative wounds need absorbent dressings. Most modern wound care based on moist healing principle.',
'easy', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of a fracture through metastatic bone tumor?',
'Same management as normal fracture',
'Pathologic fracture requiring oncologic workup if unknown primary; often requires internal fixation for pain control and function; may not heal without tumor treatment',
'Contraindication to surgery',
'Conservative treatment only',
'No special considerations',
'B',
'Pathologic fracture (metastatic): Presentation: Often with minimal trauma, may be first sign of malignancy. Evaluation: If unknown primary - staging workup (CT, PET, etc.). Common primaries: Breast, prostate, lung, kidney, thyroid. Management: Surgical stabilization usually indicated for pain control and function. Healing: May not heal if tumor not treated. Special considerations: Renal cell - very vascular, may need embolization pre-op. Prognosis: Part of overall cancer staging and planning.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What is the Ottawa Ankle Rules and why is it important?',
'Standard x-ray views of ankle',
'Clinical decision rule to determine need for ankle/foot x-rays after injury; reduces unnecessary radiographs in low-risk patients while maintaining sensitivity for significant fractures',
'Required before treatment',
'Confirms fracture diagnosis',
'Outdated clinical practice',
'B',
'Ottawa Ankle Rules: Purpose: Identify patients who need x-ray (high sensitivity for significant fracture, reduces unnecessary imaging by 30-40%). Ankle x-ray if: Bone tenderness at posterior edge/tip of malleoli (distal 6cm), OR inability to bear weight (4 steps) immediately and in ED. Foot x-ray if: Bone tenderness at base of 5th metatarsal, navicular, OR inability to bear weight. Performance: ~98% sensitivity for significant fracture. Exclusions: Age <18, intoxicated, distracting injury, decreased sensation.',
'easy', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the role of point-of-care ultrasound in cardiac arrest?',
'No role during CPR',
'Identifies reversible causes (tamponade, PE, hypovolemia), confirms asystole, may show organized cardiac activity; should not interrupt compressions',
'Replaces ECG monitoring',
'Only for diagnosis',
'Delays resuscitation',
'B',
'POCUS in cardiac arrest: Uses: Identify reversible causes (tamponade - pericardiocentesis; PE - may support thrombolytics; hypovolemia). Confirm rhythm: True asystole vs fine VF. Cardiac activity: Organized motion may indicate better prognosis, may persist briefly after PEA. Technique: Brief (10-second) looks during rhythm checks, subxiphoid view. Limitation: Should NOT interrupt compressions, requires skill. Emerging role in resuscitation algorithms.',
'medium', 'application'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'When should resuscitation efforts be terminated?',
'After fixed time period',
'Consider termination after adequate resuscitation attempt without ROSC; factors include duration, rhythm, witness status, resuscitation quality, reversible cause likelihood; no universal rule',
'Never terminate in hospital',
'After three shocks',
'Physician decision alone',
'B',
'Termination of resuscitation: Considerations: Duration of arrest (longer = worse outcome), asystole (worst prognosis rhythm), unwitnessed arrest, no reversible cause found, quality of CPR provided. Guidelines: No absolute time; BLS termination rules exist for prehospital. Special considerations: Hypothermia ("not dead until warm and dead"), drug overdose, pregnancy. Process: Team discussion, not unilateral; communication with family. Do not terminate if reversible cause untreated.',
'hard', 'application'),

-- MONITORING
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of a widening pulse pressure in a patient?',
'Normal variation',
'May indicate aortic regurgitation, hyperthyroidism, sepsis (early/warm), or increased intracranial pressure (Cushing response); requires clinical context for interpretation',
'Always indicates hypovolemia',
'Sign of cardiac arrest',
'Related to anxiety only',
'B',
'Widened pulse pressure: Definition: Systolic - diastolic >60 mmHg. Causes: Aortic regurgitation (diastolic runoff), hyperthyroidism (↑CO), early sepsis (vasodilation), increased ICP (Cushing response - with bradycardia), severe anemia, arteriovenous fistula, advanced age (stiff arteries). Context matters: Patient with trauma and widening pulse pressure + bradycardia = concerning for ↑ICP. Febrile patient = may suggest sepsis. Evaluate in clinical context.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is the purpose of intraoperative nerve monitoring?',
'Standard for all surgery',
'Real-time feedback during surgery near nerves (thyroid/parathyroid, spine, head and neck) to reduce injury risk by identifying nerve location and function',
'Replaces anatomic knowledge',
'No proven benefit',
'Only for neurosurgery',
'B',
'Intraoperative nerve monitoring (IONM): Purpose: Identify nerves, provide real-time feedback on function, detect impending injury. Common uses: Thyroidectomy (recurrent laryngeal nerve), spine surgery (motor evoked potentials, EMG), parotidectomy (facial nerve), acoustic neuroma. Techniques: EMG, motor/somatosensory evoked potentials. Limitations: Not substitute for anatomic knowledge, false positives/negatives occur, requires interpretation expertise. Evidence: Growing but not definitive for all applications.',
'medium', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the role of superficial venous surgery in chronic venous ulcer management?',
'No role in ulcer treatment',
'Correction of superficial venous reflux reduces recurrence rate of healed venous ulcers; consider after ulcer healed or as part of comprehensive management',
'Worsens ulcer healing',
'Only cosmetic benefit',
'Replaces compression therapy',
'B',
'Venous surgery for ulcers: Evidence: ESCHAR trial - superficial venous surgery + compression reduces ulcer recurrence compared to compression alone. Indications: Superficial venous incompetence on duplex, after/with ulcer healing. Procedures: Ablation (thermal, chemical), stripping, foam sclerotherapy. Note: Does not replace compression; adjunctive treatment. Timing: May be done with active ulcer (carefully) or after healing to prevent recurrence. Deep venous disease management more complex.',
'hard', 'application'),

-- CATHETER
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is suprapubic catheterization and when is it preferred over urethral catheterization?',
'Identical indication and technique',
'Bladder drainage via catheter inserted through abdominal wall; preferred for long-term catheterization, urethral injury/stricture, prostate surgery, and patient preference/sexuality concerns',
'Only for acute retention',
'More infection risk',
'Contraindicated long-term',
'B',
'Suprapubic catheter (SPC): Insertion: Through anterior abdominal wall directly into bladder. Advantages over urethral: Preserves urethral integrity, easier to manage/change, more comfortable long-term, allows sexual activity, lower stricture risk. Indications: Long-term catheterization (>4 weeks), urethral trauma/stricture, after some urologic procedures, patient preference. Contraindications: Bladder malignancy, unlocated bladder. Risks: Bowel injury during insertion, tract problems. Requires initial ultrasound guidance usually.',
'medium', 'application');
