-- ============================================================================
-- BATCH 70: Final Clinical Scenarios - Completing the Question Bank
-- Topics: Comprehensive clinical scenarios to reach 2000 questions
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- FINAL SCENARIOS
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'A trauma patient has Glasgow Coma Scale of 8 with intact gag reflex. What is the airway management priority?',
'Observe with oxygen only',
'GCS ≤8 indicates need for definitive airway protection regardless of gag reflex; prepare for rapid sequence intubation',
'Wait for CT scan first',
'NG tube placement',
'Oral airway is sufficient',
'B',
'GCS and airway: GCS ≤8: Cannot reliably protect airway. Gag reflex: Not reliable indicator of airway protection. Decision: GCS 8 or less = intubate. Technique: Rapid sequence intubation (RSI) with inline C-spine stabilization if trauma. Avoid: Nasal intubation if facial/base of skull fracture suspected. Principle: Airway protection prevents aspiration, allows oxygenation/ventilation, enables safe transport for imaging/procedures. "A" comes before all other interventions.',
'medium', 'application'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the "golden hour" concept in trauma care?',
'Time limit for surgery',
'Critical window from injury to definitive care where rapid intervention maximizes survival; emphasizes importance of prehospital care and rapid hospital response',
'Time to complete all imaging',
'One hour of observation',
'Time for family notification',
'B',
'Golden hour: Origin: Dr. R Adams Cowley, shock trauma pioneer. Concept: Severely injured patients have best outcomes when definitive care provided within 60 minutes of injury. Implications: Prehospital efficiency, trauma system organization, rapid assessment and intervention, damage control principles. Modern understanding: Time to treatment matters, but exact 60-minute threshold is conceptual rather than absolute. Goal: Minimize time from injury to definitive hemorrhage control and resuscitation.',
'easy', 'knowledge'),

-- SHOCK
('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of mixed venous oxygen saturation (SvO2)?',
'Only for research',
'Reflects balance between oxygen delivery and consumption; low SvO2 indicates inadequate delivery or excessive extraction; used to assess tissue oxygenation adequacy',
'Same as pulse oximetry',
'Replaced by lactate',
'Only measures lung function',
'B',
'SvO2 interpretation: Normal: 65-75%. Measurement: From pulmonary artery (PA) catheter - true mixed venous. Low SvO2: Increased extraction (tissues need more O2 than delivered) - causes: low CO, anemia, hypoxemia, increased demand. High SvO2: Decreased extraction (tissues unable to extract or low demand) - causes: sepsis (maldistribution), high FiO2, cell death. ScvO2 (from central line): Surrogate, slightly higher (~5%). Clinical: Trends useful in resuscitation.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the pathophysiology of post-cardiac arrest syndrome?',
'Simply recovery from arrest',
'Combination of post-arrest brain injury, myocardial dysfunction, systemic ischemia-reperfusion response, and precipitating cause; requires comprehensive ICU management',
'Only brain injury',
'Resolves immediately with ROSC',
'Not a recognized syndrome',
'B',
'Post-cardiac arrest syndrome: Components: 1. Brain injury (most common cause of death post-ROSC), 2. Myocardial dysfunction (stunned myocardium, usually transient), 3. Systemic ischemia-reperfusion (inflammatory response, organ dysfunction), 4. Persistent precipitating cause. Management: TTM (temperature control), hemodynamic support, treat cause, delayed prognostication, multimodal neuroprognostication. Comprehensive ICU care improves outcomes after ROSC.',
'hard', 'application'),

-- FLUIDS
('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What are the phases of fluid resuscitation in sepsis?',
'Single phase of aggressive fluids',
'Rescue (initial bolus), optimization (goal-directed), stabilization (maintain homeostasis), de-escalation (mobilize excess fluid); fluid management evolves through illness course',
'Always restrict fluids',
'No defined phases',
'Fluids only in first hour',
'B',
'Fluid therapy phases (Malbrain''s ROSE concept): Resuscitation: Initial aggressive bolus for life-threatening hypoperfusion. Optimization: Goal-directed to optimize perfusion (using dynamic parameters). Stabilization: Maintenance to preserve organ function. Evacuation (de-escalation): Actively remove accumulated excess fluid. Concept: Fluid therapy is a drug - right phase, right patient, right amount. Harm: Both too little (early) and too much (cumulative) are harmful.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is the management of symptomatic hyponatremia?',
'Rapid correction to normal',
'Hypertonic saline (3%) for severe symptoms; correct at 1-2 mEq/L/hr initially, max 8-10 mEq/L in 24 hours to prevent osmotic demyelination syndrome',
'Free water restriction only',
'Oral salt tablets',
'Diuretics to remove water',
'B',
'Symptomatic hyponatremia: Symptoms: Confusion, seizures, coma (cerebral edema). Treatment: 3% saline - goal is to stop symptoms, not normalize sodium. Rate: Raise 1-2 mEq/L per hour initially until symptoms improve. Limit: Max 8-10 mEq/L in first 24 hours, avoid >18 mEq/L in 48 hours. Risk of overcorrection: Osmotic demyelination syndrome (central pontine myelinolysis). If overcorrected: D5W or desmopressin to re-lower. Monitoring: Frequent sodium checks.',
'hard', 'application'),

-- BLOOD
('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is the transfusion threshold for critically ill patients?',
'Always maintain Hb >10 g/dL',
'Generally transfuse when Hb <7 g/dL in most critically ill patients; restrictive strategy equivalent to or better than liberal for outcomes',
'Never transfuse in ICU',
'Transfuse based on symptoms only',
'Threshold of 11 g/dL',
'B',
'Transfusion thresholds: Evidence: TRICC, TRISS, and other trials show restrictive (Hb 7 g/dL) equivalent or better than liberal strategy. Current recommendation: Hb <7 g/dL for most critically ill and post-operative patients. Exceptions: May use higher threshold (8-9 g/dL) for acute coronary syndrome. Principle: Transfusion is not benign - carries risks. Individualize: Consider ongoing blood loss, symptoms, cardiopulmonary reserve. One unit at a time, reassess.',
'medium', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is the role of tranexamic acid in trauma?',
'No benefit in trauma',
'Antifibrinolytic that reduces mortality if given within 3 hours of injury in bleeding trauma patients; inhibits plasminogen activation to reduce fibrinolysis',
'Only for surgical bleeding',
'Increases clotting complications',
'Replaces blood products',
'B',
'Tranexamic acid (TXA) in trauma: Evidence: CRASH-2 trial - TXA within 3 hours reduces mortality in bleeding trauma. Mechanism: Inhibits plasminogen activation → reduces fibrinolysis → stabilizes clot. Dose: 1g IV over 10 min, then 1g over 8 hours. Timing critical: Benefit diminishes after 3 hours; may be harmful if given late (>3 hours). Now standard of care in many trauma protocols. Also used in surgical bleeding (orthopedic, cardiac surgery).',
'medium', 'application'),

-- WOUNDS
('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the difference between healing by primary, secondary, and tertiary intention?',
'All produce same result',
'Primary: direct closure; secondary: left open to granulate and epithelialize; tertiary: initially open then closed after edema/contamination resolves (delayed primary closure)',
'Terms are interchangeable',
'Only primary intention is healing',
'No clinical difference',
'B',
'Wound healing intention: Primary: Edges approximated immediately (sutures, staples). Best cosmetic result, fastest healing. Secondary: Left open, heals by granulation, contraction, epithelialization. For contaminated wounds. Longer healing, more scarring. Tertiary (delayed primary): Initially open for drainage/debridement, closed in 3-5 days. For contaminated wounds needing closure. Balance: Risk of closure (infection, dehiscence) vs. benefits (faster healing, better cosmesis).',
'easy', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the role of prophylactic antibiotics in contaminated traumatic wounds?',
'No antibiotics ever needed',
'Short course (usually 24-48 hours) of appropriate antibiotics for significantly contaminated wounds, open fractures, and penetrating injuries; not substitute for wound care',
'Continue for 2 weeks minimum',
'Only topical antibiotics',
'Prophylaxis prevents all infections',
'B',
'Wound prophylaxis: Indications: Significantly contaminated wounds, open fractures, penetrating injuries, bites. Duration: Brief course (24-48 hours) - longer is not more effective and promotes resistance. Selection: Based on likely organisms - skin flora, soil organisms, specific exposures. Critical: Antibiotics supplement, not replace, wound care (irrigation, debridement). Tetanus: Update prophylaxis as indicated. Clean wounds: Do not require routine prophylaxis.',
'medium', 'application'),

-- SUTURES
('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the proper technique for tying surgical knots?',
'Pulled as tight as possible',
'Square knots with adequate throws for suture material; tension approximates tissue without strangulation; security depends on material, number of throws, and proper technique',
'Granny knots are equivalent',
'One throw is sufficient',
'Technique does not matter',
'B',
'Surgical knot tying: Square knot: Throws alternate direction (prevents slipping). Throws needed: Varies by material - monofilament needs more than braided. Tension: Approximate tissue edges without strangulating (ischemia causes necrosis). Knot security: Affected by material, number of throws, technique. Hand ties vs instrument ties: Both valid, situation determines choice. Practice: Essential surgical skill requiring repetition. Poor knots: Can slip leading to wound failure.',
'easy', 'application'),

-- MONITORING
('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of fever patterns in postoperative patients?',
'Fever indicates infection',
'Timing and pattern help identify cause; early fever (24-48h) often inflammatory/atelectasis; later fever suggests SSI, UTI, pneumonia, or DVT/PE ("wind, water, wound, walk, wonder drugs")',
'All fevers need antibiotics',
'Fever is always benign',
'Pattern has no significance',
'B',
'Postoperative fever: 5 W''s mnemonic: POD 1-2 Wind (atelectasis, pneumonia), POD 3-5 Water (UTI), POD 5-7 Wound (SSI), POD 5+ Walk (DVT/PE), Any day Wonder drugs (drug fever). Evaluation: Based on timing, exam, and risk factors. Not all fever = infection (inflammatory response common). Early mild fever (<38.5°C in first 48h): Often atelectasis, encourage incentive spirometry. Workup: Directed by clinical suspicion.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is goal-directed therapy in perioperative care?',
'Fixed fluid volumes for all',
'Using measured hemodynamic parameters to guide individualized therapy; titrating fluids, vasopressors, and inotropes to specific targets like stroke volume or cardiac output',
'Only based on blood pressure',
'No monitoring needed',
'Same as traditional fluid management',
'B',
'Goal-directed therapy (GDT): Concept: Individualize hemodynamic therapy to measured patient response rather than fixed protocols. Targets: Stroke volume optimization, cardiac output, tissue oxygenation markers. Tools: Arterial waveform analysis, esophageal Doppler, echocardiography. Evidence: Some studies show reduced complications, LOS. Principle: Right patient gets right amount of intervention - avoid under- and over-treatment. Requires appropriate monitoring and protocol.',
'hard', 'application'),

-- FRACTURES
('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What are the principles of fracture reduction?',
'Push bones together forcefully',
'Restore anatomic alignment by manipulating distal fragment to match proximal; traction to disengage, recreation of deformity to unlock, then reduction and immobilization',
'Only surgical treatment works',
'No specific technique exists',
'Alignment not important',
'B',
'Fracture reduction principles: Goal: Restore anatomic alignment (or acceptable position). Steps: 1. Traction (disengage overlapping fragments), 2. Recreation of deformity (unlock fragments), 3. Reduction (realign), 4. Immobilization (maintain position). Closed reduction: Manipulation without surgery. Open reduction: Surgical exposure and fixation. Acceptable alignment: Depends on fracture location, patient age, function. Imaging: Confirm reduction with X-ray.',
'medium', 'application'),

-- CPR
('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is post-ROSC care and why is it important?',
'Resuscitation complete at ROSC',
'Comprehensive care after return of spontaneous circulation: targeted temperature management, hemodynamic optimization, ventilation management, coronary intervention if indicated, neuroprognostication',
'Only observe after ROSC',
'Transfer home immediately',
'No further intervention needed',
'B',
'Post-ROSC care: Concept: ROSC is not end of resuscitation - many die from post-arrest syndrome. Components: Oxygenation (avoid hyperoxia), ventilation (normocapnia), hemodynamics (MAP >65, avoid hypotension), TTM (32-36°C × 24h), coronary intervention (if STEMI or suspected cardiac cause), seizure management, glucose control. Prognostication: Wait >72h, multimodal approach. Comprehensive bundle approach improves survival with good neurologic outcome.',
'hard', 'application'),

-- LEG ULCERS
('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the evidence basis for compression therapy in venous ulcers?',
'No evidence supports compression',
'Strong evidence that compression increases venous ulcer healing rates compared to no compression; higher compression more effective than lower; multicomponent preferred',
'Evidence shows harm',
'Only works on small ulcers',
'Alternative therapies better',
'B',
'Compression therapy evidence: Cochrane reviews: Compression vs no compression - clearly faster healing. Higher pressure (30-40 mmHg) more effective than lower. Multicomponent systems: More effective than single component. Elastic vs inelastic: Both effective, may have different advantages. Compliance: Key to success. Contraindications: Severe PAD (ABPI <0.5), uncompensated heart failure. Evidence base: One of the strongest in wound care.',
'medium', 'application'),

-- NG TUBE
('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'When should a nasogastric tube be removed postoperatively?',
'Keep until bowel movement',
'Remove when no longer serving therapeutic purpose - most patients do not require routine NG tube after surgery; early removal associated with faster recovery',
'Keep for 1 week minimum',
'Only remove if output zero',
'Never remove before discharge',
'B',
'NG tube removal: Evidence: Routine NG decompression after abdominal surgery not necessary for most patients. ERAS protocols: Avoid routine NG or remove POD1. Indications to keep: Persistent nausea/vomiting, gastric outlet obstruction, ileus with distension, high-output states requiring measurement. Removal: When indication resolved. Early removal: Associated with earlier return of bowel function, earlier feeding, shorter LOS. Patient comfort: NG tubes are uncomfortable.',
'easy', 'application'),

-- CATHETER
('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is a "trial without catheter" (TWOC) and when is it appropriate?',
'Never remove catheter',
'Planned catheter removal with monitoring for voiding; appropriate after acute retention treatment or postoperative catheter use to assess for spontaneous voiding ability',
'Only for chronic catheter users',
'Always succeeds',
'No preparation needed',
'B',
'TWOC protocol: Purpose: Assess if patient can void after catheter removal. Indications: After AUR treatment (usually 2-3 days with alpha-blocker), postoperative catheterization, nursing home assessment. Process: Remove catheter (often morning for monitoring), observe for voiding, measure PVR. Success: Adequate voiding with acceptable PVR. Failure: Re-catheterization, urology referral. Optimization: Alpha-blockers before trial in men with BPH, ensure adequate hydration.',
'easy', 'application');
