-- ============================================================================
-- BATCH 71: Final Questions - Completing 2000 Question Target
-- Topics: Essential clinical scenarios and knowledge
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- COMPLETING THE QUESTION BANK
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is informed consent and what are its essential elements?',
'Patient signature only',
'Process ensuring patient understands diagnosis, proposed treatment, risks, benefits, alternatives, and consequences of no treatment; must be voluntary and by competent patient',
'Verbal agreement sufficient',
'Only for major surgery',
'Doctor decides for patient',
'B',
'Informed consent: Elements: 1. Disclosure (diagnosis, treatment, risks, benefits, alternatives), 2. Understanding (patient comprehends), 3. Voluntariness (no coercion), 4. Competence (patient capable of decision), 5. Decision. Documentation: Written consent form documents process but is not the consent itself. Emergencies: Implied consent for life-saving treatment. Minors: Parent/guardian consent unless emancipated or emergency.',
'easy', 'knowledge'),

('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the WHO Surgical Safety Checklist and why is it important?',
'Administrative requirement only',
'Structured tool with 3 phases (sign in, time out, sign out) to ensure critical safety checks; reduces surgical complications and mortality when properly implemented',
'Optional for experienced surgeons',
'Delays surgery unnecessarily',
'No proven benefit',
'B',
'WHO Surgical Safety Checklist: Phases: Sign in (before anesthesia - patient confirmation, site marking, allergies, airway assessment), Time out (before incision - team introduction, procedure confirmation, anticipated events, antibiotic given), Sign out (before patient leaves OR - procedure confirmed, counts correct, specimens labeled, equipment issues, recovery concerns). Evidence: Reduces complications by 36%, mortality by 47% in original study. Now standard of care globally.',
'easy', 'knowledge'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is "permissive hypotension" in trauma resuscitation?',
'Dangerous practice to avoid',
'Accepting lower than normal blood pressure (SBP 80-90) in actively bleeding trauma patients to reduce ongoing hemorrhage until surgical control achieved',
'Goal blood pressure for all',
'Same as standard resuscitation',
'Only for elderly patients',
'B',
'Permissive hypotension: Concept: Aggressive fluid resuscitation before hemorrhage control may worsen bleeding (increased pressure, dilution of clotting factors, clot disruption). Target: SBP 80-90 mmHg or palpable radial pulse in penetrating torso trauma. Exceptions: Traumatic brain injury (needs higher perfusion), elderly (less tolerant of hypotension). Duration: Until surgical hemorrhage control. Balance: Enough perfusion to prevent organ failure, not so much as to promote bleeding.',
'hard', 'application'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the Surviving Sepsis Campaign Hour-1 bundle?',
'Optional recommendations',
'Time-sensitive interventions to initiate within first hour: measure lactate, blood cultures, broad-spectrum antibiotics, 30mL/kg crystalloid for hypotension/elevated lactate, vasopressors if hypotensive despite fluids',
'Only for ICU patients',
'Outdated guidelines',
'Single antibiotic dose only',
'B',
'Hour-1 bundle: Elements: 1. Measure lactate (remeasure if elevated), 2. Obtain blood cultures before antibiotics, 3. Administer broad-spectrum antibiotics, 4. Begin rapid infusion of 30mL/kg crystalloid for hypotension or lactate ≥4, 5. Apply vasopressors if hypotensive during or after fluids to maintain MAP ≥65. Purpose: Standardize early aggressive treatment of sepsis. Evidence: Earlier treatment = better outcomes. Bundle compliance improves survival.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What are the daily maintenance fluid requirements for an adult patient?',
'2000mL for everyone',
'Approximately 25-30 mL/kg/day of water, 1-2 mmol/kg/day each of sodium/potassium/chloride, and 50-100g glucose to minimize protein catabolism',
'Only drink when thirsty',
'No standard exists',
'Double oral intake',
'B',
'Maintenance fluids: Water requirement: ~25-30 mL/kg/day (higher with fever, lower with edema/fluid overload). Electrolytes: Na+ 1-2 mmol/kg/day, K+ 1-2 mmol/kg/day, Cl- 1-2 mmol/kg/day. Glucose: 50-100g/day prevents starvation ketosis. Example: 70kg adult needs ~2100mL water, ~100 mEq Na+, ~70 mEq K+. Adjustments: Increase for fever (+10-15% per degree >38°C), decrease for renal/cardiac failure.',
'medium', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is the composition and clinical use of albumin?',
'Red blood cell component',
'5% or 25% human albumin solution for volume expansion in specific situations; stays intravascular longer than crystalloids due to oncotic properties',
'Only for nutritional support',
'Replaces blood transfusion',
'Not used clinically',
'B',
'Albumin: Forms: 5% (iso-oncotic) and 25% (hyperoncotic). Properties: Major plasma protein, maintains oncotic pressure. Uses: Volume expansion (5%), mobilizing edema fluid (25%), some specific conditions (spontaneous bacterial peritonitis, post large-volume paracentesis, hepatorenal syndrome). Evidence: SAFE trial - equivalent to saline for resuscitation. Cost: Expensive compared to crystalloids. Not for: Routine resuscitation, nutritional supplementation (not efficiently used).',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is delayed hemolytic transfusion reaction?',
'Same as acute hemolysis',
'Hemolysis occurring 3-14 days post-transfusion from anamnestic antibody response to previously encountered RBC antigens; presents with unexplained hemoglobin drop and jaundice',
'Immediately after transfusion',
'Not a real phenomenon',
'Only with incompatible blood',
'B',
'Delayed hemolytic reaction: Mechanism: Patient previously sensitized to RBC antigens (pregnancy, prior transfusion), antibodies undetectable at crossmatch, anamnestic response after re-exposure. Timing: 3-14 days post-transfusion. Presentation: Unexplained drop in hemoglobin, mild jaundice, positive DAT. Severity: Usually milder than acute hemolysis. Management: Supportive, identify antibody for future transfusions. Prevention: Difficult - antibodies may be too low to detect.',
'hard', 'application'),

('b0000002-0000-0000-0000-000000000002', 'a0000001-0000-0000-0000-000000000001',
'What is the role of recombinant Factor VIIa in hemorrhage?',
'First-line hemostatic agent',
'Off-label use for refractory hemorrhage after conventional measures; promotes thrombin generation at injury sites but expensive with potential thrombotic risk',
'Replaces all clotting factors',
'Standard treatment for all bleeding',
'No hemostatic effect',
'B',
'Recombinant Factor VIIa (rFVIIa): Mechanism: Binds tissue factor at injury site, initiates coagulation locally. Licensed uses: Hemophilia with inhibitors, factor VII deficiency. Off-label: Refractory hemorrhage (trauma, surgery, intracranial) after conventional therapy fails. Considerations: Expensive, potential arterial thrombosis risk, not substitute for other products, must have adequate fibrinogen and platelets. Evidence: Limited for off-label use. Usually last resort.',
'hard', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the role of debridement in wound management?',
'Never beneficial',
'Removal of devitalized tissue, debris, and biofilm to create wound environment conducive to healing; essential step in management of chronic and contaminated wounds',
'Only for infected wounds',
'Delays healing',
'Replaced by antibiotics',
'B',
'Wound debridement: Purpose: Remove barriers to healing (necrotic tissue, debris, biofilm, excessive exudate). Methods: Sharp/surgical (fastest, most complete), autolytic (dressings that promote self-digestion), enzymatic (collagenase preparations), biological (maggot therapy), mechanical (wet-to-dry - now less favored). Frequency: May need serial debridement. Principle: Clean wound heals better than wound with devitalized tissue. Caution: Adequate blood supply needed for subsequent healing.',
'medium', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is the TIME framework in wound bed preparation?',
'Treatment timing schedule',
'Systematic approach to wound assessment: Tissue (remove non-viable), Infection/Inflammation (control), Moisture (balance), Edge (non-advancing edges need attention)',
'Temperature, Infection, Movement, Elevation',
'Only for acute wounds',
'Outdated concept',
'B',
'TIME framework: T - Tissue: Assess viability, debride necrotic tissue. I - Infection/Inflammation: Identify and treat infection, address chronic inflammation. M - Moisture: Balance - not too wet (maceration), not too dry. Select appropriate dressing. E - Edge: Non-advancing edges indicate stalled healing - may need intervention (debridement, grafting, correction of underlying problem). Purpose: Systematic approach to chronic wound assessment and management.',
'easy', 'knowledge'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is needle-stick injury protocol in the operating room?',
'Continue with surgery only',
'Remove gloves, clean wound, report injury, identify source patient, post-exposure evaluation for bloodborne pathogens, possible PEP for HIV, hepatitis evaluation',
'No action required',
'Only if patient has HIV',
'Cover and continue working',
'B',
'Needle-stick protocol: Immediate: Remove gloves, wash wound with soap and water (no scrubbing), report to occupational health. Investigation: Source patient testing (HIV, HBV, HCV with consent), healthcare worker baseline testing. PEP: HIV PEP within 72 hours if indicated (ideally within 2 hours). Hepatitis: HBV - check immunity, HBV immunoglobulin if needed. HCV - no prophylaxis, follow-up testing. Documentation: Essential for workers compensation, follow-up.',
'easy', 'application'),

('b0000008-0000-0000-0000-000000000008', 'a0000001-0000-0000-0000-000000000001',
'What is an incisional hernia and what are risk factors for its development?',
'Hernia present at birth',
'Hernia through previous surgical incision site; risk factors include wound infection, obesity, malnutrition, steroids, increased abdominal pressure, poor surgical technique',
'Only after appendectomy',
'Always requires emergency repair',
'Cannot be prevented',
'B',
'Incisional hernia: Definition: Hernia through previous surgical incision. Incidence: 5-20% after laparotomy. Risk factors: Wound infection (strongest), obesity, malnutrition, steroids/immunosuppression, COPD, smoking, emergency surgery, vertical incisions, poor fascial closure technique, mesh not used when indicated. Prevention: Meticulous technique, small bites (5mm) close together, appropriate suture material, prophylactic mesh in high-risk patients. Treatment: Mesh repair.',
'medium', 'application'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of fracture classification systems?',
'Only for academic purposes',
'Standardize communication, guide treatment decisions, predict outcomes, and enable comparison across studies; must know common classifications for clinical practice',
'All fractures treated the same',
'Outdated practice',
'No clinical utility',
'B',
'Fracture classification utility: Communication: Common language between providers. Treatment: Different grades may require different management. Prognosis: Higher grades often worse outcomes. Examples: AO/OTA (comprehensive), Gustilo-Anderson (open fractures), Neer (proximal humerus), Garden (femoral neck), Schatzker (tibial plateau). Limitations: Inter-observer variability, may oversimplify complex injuries. Clinical practice: Know common classifications for your specialty.',
'easy', 'knowledge'),

('b0000010-0000-0000-0000-000000000010', 'a0000001-0000-0000-0000-000000000001',
'What is the Glasgow Coma Scale and how is it scored?',
'Blood pressure measurement',
'Neurologic assessment scoring Eye opening (4), Verbal response (5), Motor response (6); total 3-15 with lower scores indicating more severe impairment',
'Only measures eye function',
'Heart rate scoring system',
'Not used in trauma',
'B',
'Glasgow Coma Scale: Eye opening: Spontaneous (4), to voice (3), to pain (2), none (1). Verbal: Oriented (5), confused (4), inappropriate (3), incomprehensible (2), none (1). Motor: Obeys commands (6), localizes pain (5), withdraws (4), abnormal flexion (3), extension (2), none (1). Total: 3-15. Interpretation: 13-15 mild, 9-12 moderate, ≤8 severe TBI/coma (intubation indicated). Limitations: Affected by sedation, intubation, alcohol. Components more informative than total.',
'easy', 'knowledge'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the chain of survival for out-of-hospital cardiac arrest?',
'Hospital treatment only',
'Early recognition and call for help, early CPR, early defibrillation, advanced care, and post-arrest care; each link critical for survival',
'Single intervention',
'Random sequence',
'Only EMS treatment',
'B',
'Chain of survival: Links: 1. Recognition and activation (early 911 call), 2. Early CPR (bystander CPR doubles/triples survival), 3. Rapid defibrillation (for VF/pVT), 4. Advanced resuscitation (ALS), 5. Post-arrest care. Concept: Each link vital - chain only as strong as weakest link. Public access defibrillation and bystander CPR are major survival determinants. Time-dependent: Each minute without CPR decreases survival 7-10%.',
'easy', 'knowledge'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the CEAP classification for chronic venous disease?',
'Cancer staging system',
'Clinical (C0-6), Etiologic (primary/secondary/congenital), Anatomic (superficial/deep/perforator), Pathophysiologic (reflux/obstruction); standardizes venous disease description',
'Wound healing stages',
'Arterial disease classification',
'Not clinically used',
'B',
'CEAP classification: C (Clinical): C0 (no signs), C1 (telangiectasias), C2 (varicose veins), C3 (edema), C4 (skin changes), C5 (healed ulcer), C6 (active ulcer). E (Etiology): Primary, Secondary, Congenital. A (Anatomy): Superficial, Deep, Perforators. P (Pathophysiology): Reflux, Obstruction, both. Use: Standardize communication, guide treatment, research comparison. Clinical practice: C class most commonly used.',
'medium', 'knowledge'),

('b0000015-0000-0000-0000-000000000015', 'a0000001-0000-0000-0000-000000000001',
'What vital signs should be monitored in immediate postoperative period?',
'Blood pressure only',
'Heart rate, blood pressure, respiratory rate, oxygen saturation, temperature, level of consciousness, pain level, and urine output',
'Temperature only',
'Only when patient reports symptoms',
'No monitoring needed',
'B',
'Post-op monitoring: Parameters: HR, BP, RR, SpO2, temperature, consciousness, pain, urine output. Frequency: Every 15 min initially, then hourly as stable. Purpose: Early detection of complications (hemorrhage, respiratory depression, hypoxia). Documentation: Trend is important - single normal value does not ensure stability. Additional: Drain output, wound assessment, specific procedure-related monitoring. Early Warning Scores: Aggregate data to identify deterioration.',
'easy', 'knowledge'),

('b0000011-0000-0000-0000-000000000011', 'a0000001-0000-0000-0000-000000000001',
'What is refeeding syndrome and which patients are at risk?',
'Overfeeding obese patients',
'Metabolic disturbances when feeding malnourished patients; insulin surge shifts electrolytes intracellularly causing hypophosphatemia, hypokalemia, hypomagnesemia; can cause cardiac and respiratory failure',
'Only with IV nutrition',
'Rare and not important',
'Occurs with high protein diet',
'B',
'Refeeding syndrome: Mechanism: Prolonged starvation → catabolic state. Refeeding → insulin release → glucose/K+/PO4/Mg shift into cells → serum electrolyte crash. Consequences: Cardiac failure, arrhythmias, respiratory failure, rhabdomyolysis, seizures. At-risk: BMI <16, >15% weight loss, minimal intake >10 days, low baseline electrolytes, alcoholism. Prevention: Start feeding slowly (10-15 kcal/kg/day), supplement thiamine before feeding, monitor and replace electrolytes aggressively.',
'hard', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is clean intermittent catheterization and what are its advantages?',
'Only done in hospital',
'Self-catheterization technique using clean (not sterile) technique at intervals throughout the day; lower UTI rate than indwelling catheter, preserves bladder function',
'Must be sterile technique',
'Only for short-term use',
'Higher infection rate than indwelling',
'B',
'Clean intermittent catheterization (CIC): Technique: Patient or caregiver inserts catheter to empty bladder, then removes. Frequency: Typically 4-6 times daily. Advantages: Lower UTI rate than indwelling, maintains bladder cycling (prevents fibrosis), preserves continence mechanism, independence. Indications: Neurogenic bladder, urinary retention when surgery not indicated. Training: Essential for success. Clean technique: As effective as sterile for most patients, more practical.',
'medium', 'application');
