-- ============================================================================
-- BATCH 72: Final 11 Questions - Reaching 2000 Target
-- Topics: Essential clinical knowledge completion
-- ============================================================================

INSERT INTO questions (topic_id, category_id, question_text, option_a, option_b, option_c, option_d, option_e, correct_option, explanation, difficulty, cognitive_level) VALUES

-- FINAL QUESTIONS TO REACH 2000
('b0000001-0000-0000-0000-000000000001', 'a0000001-0000-0000-0000-000000000001',
'What is the principle of surgical asepsis versus medical asepsis?',
'Identical concepts',
'Surgical asepsis aims to eliminate ALL microorganisms; medical asepsis aims to reduce and control microorganism numbers; surgical asepsis required in operating room',
'Medical asepsis is stricter',
'Neither is important today',
'Only used in developing countries',
'B',
'Asepsis principles: Medical asepsis (clean technique): Reduce number of microorganisms, prevent transmission. Used in general patient care. Surgical asepsis (sterile technique): Eliminate ALL microorganisms. Required for: Operating room, invasive procedures, sterile sites. Methods: Sterilization (heat, chemicals, radiation), sterile gowning/gloving, sterile field maintenance. Both important: Medical asepsis in routine care, surgical asepsis for procedures.',
'easy', 'knowledge'),

('b0000003-0000-0000-0000-000000000003', 'a0000001-0000-0000-0000-000000000001',
'What is the clinical significance of serum lactate clearance?',
'No prognostic value',
'Lactate clearance (decrease >10% in first 2-6 hours) indicates improving tissue perfusion and is associated with better survival; failure to clear suggests inadequate resuscitation',
'Only measures kidney function',
'Should increase with treatment',
'Static measurement preferred',
'B',
'Lactate clearance: Definition: Percentage decrease in lactate over time (usually 2-6 hours). Target: >10-20% clearance suggests improving perfusion. Significance: Lactate clearance is resuscitation target; failure to clear indicates ongoing hypoperfusion or impaired clearance. Prognosis: Clearance associated with improved survival in sepsis and trauma. Clinical use: Serial lactate measurements guide resuscitation more than single value. Normalize lactate = resuscitation goal achieved.',
'hard', 'application'),

('b0000004-0000-0000-0000-000000000004', 'a0000001-0000-0000-0000-000000000001',
'What is the significance of urinary sodium in evaluating oliguria?',
'Not clinically useful',
'Low urinary sodium (<20 mEq/L) suggests prerenal cause with intact tubular function; high urinary sodium (>40 mEq/L) suggests intrinsic renal failure with impaired sodium reabsorption',
'Always indicates dehydration',
'Only matters in chronic disease',
'Replaced by creatinine',
'B',
'Urinary sodium interpretation: Prerenal (hypovolemia): Kidneys retain sodium → UNa <20 mEq/L. Intrinsic renal failure (ATN): Tubules cannot reabsorb sodium → UNa >40 mEq/L. FeNa: Fractional excretion of sodium also useful (<1% prerenal, >2% ATN). Utility: Differentiates treatable prerenal AKI from intrinsic renal injury. Limitation: May be altered by diuretics, underlying kidney disease. Use early before treatment alters values.',
'medium', 'application'),

('b0000007-0000-0000-0000-000000000007', 'a0000001-0000-0000-0000-000000000001',
'What is bedside blood typing and when is it performed?',
'Replaces laboratory typing',
'Point-of-care confirmation of ABO type immediately before transfusion as final check against clerical errors; does not replace full laboratory crossmatch',
'Only for O negative blood',
'Not recommended',
'Optional safety measure',
'B',
'Bedside blood typing: Purpose: Final safety check before transfusion to catch clerical errors. Procedure: Simple ABO typing of patient blood sample at bedside immediately before transfusion. Comparison: Match to unit label and patient identification. Context: Most fatal transfusion reactions from clerical/identification errors, not serologic incompatibility. Role: Additional safety barrier, not substitute for laboratory crossmatch. Requirement: Varies by institution.',
'easy', 'application'),

('b0000005-0000-0000-0000-000000000005', 'a0000001-0000-0000-0000-000000000001',
'What is an enterocutaneous fistula and what are principles of management?',
'Always requires emergency surgery',
'Abnormal connection between GI tract and skin; managed with resuscitation, control of sepsis, nutrition support, wound care, and delayed surgical repair if spontaneous closure fails',
'Only occurs after surgery',
'Cannot be treated',
'Antibiotics cure all fistulas',
'B',
'Enterocutaneous fistula: Causes: Postoperative (anastomotic leak), Crohn disease, radiation, malignancy. Management (SNAP): Sepsis control (drain collections), Nutrition (often TPN to rest bowel), Anatomy (define fistula with imaging), Procedure (planned surgery if no closure). Spontaneous closure: More likely if low output, long tract, no obstruction/radiation/malignancy/IBD. Timeline: Give 4-6 weeks for spontaneous closure before surgery. Wound care: Protect skin, collect output.',
'hard', 'application'),

('b0000006-0000-0000-0000-000000000006', 'a0000001-0000-0000-0000-000000000001',
'What is the difference between monofilament and multifilament sutures?',
'No functional difference',
'Monofilament: single strand, less tissue drag, less infection risk, harder to handle; Multifilament: braided strands, better handling, more tissue drag, may harbor bacteria',
'Monofilament always preferred',
'Multifilament never used today',
'Only differ in color',
'B',
'Suture structure: Monofilament: Single continuous strand. Advantages: Smooth, less tissue drag, resistant to bacterial colonization, good for running closures. Disadvantages: Stiffer, memory, knot may slip (needs more throws). Examples: Nylon, prolene, PDS. Multifilament (braided): Multiple strands braided. Advantages: Supple, good handling, secure knots. Disadvantages: Capillarity (wicks fluid/bacteria), more tissue drag. Examples: Vicryl, silk. Choice: Based on clinical situation.',
'easy', 'knowledge'),

('b0000009-0000-0000-0000-000000000009', 'a0000001-0000-0000-0000-000000000001',
'What is external fixation and what are its indications?',
'Permanent fracture treatment',
'Stabilization of fractures using pins inserted through skin into bone connected to external frame; indicated for open fractures, temporary stabilization in damage control, complex periarticular fractures',
'Only for compound fractures',
'Obsolete technique',
'Alternative to casting only',
'B',
'External fixation: Technique: Pins through skin into bone proximal and distal to fracture, connected by external frame. Indications: Open fractures (soft tissue access for wound care), damage control orthopedics (temporize in polytrauma), periarticular fractures, infected non-union, bone transport, pelvis fractures (emergent stabilization). Advantages: Quick application, avoids implants in contaminated wounds, adjustable. Disadvantages: Pin site infection, patient inconvenience, often temporary.',
'medium', 'application'),

('b0000012-0000-0000-0000-000000000012', 'a0000001-0000-0000-0000-000000000001',
'What is Bispectral Index (BIS) monitoring?',
'Blood pressure monitoring device',
'Processed EEG signal monitoring depth of anesthesia; values 0-100 with 40-60 indicating adequate surgical anesthesia; reduces awareness risk',
'Only for research use',
'Measures oxygen saturation',
'Obsolete monitoring technique',
'B',
'BIS monitoring: Principle: Processes EEG signals to generate index of anesthetic depth. Scale: 0 (flat EEG) to 100 (fully awake). Target: 40-60 for general anesthesia. Benefits: May reduce intraoperative awareness, may reduce anesthetic use, objective assessment of depth. Limitations: Not perfect predictor of awareness, affected by muscle activity and artifacts. Use: Standard in many centers, especially for TIVA, high-risk awareness patients.',
'medium', 'knowledge'),

('b0000013-0000-0000-0000-000000000013', 'a0000001-0000-0000-0000-000000000001',
'What is the role of capnography in procedural sedation?',
'Not useful outside OR',
'Continuous CO2 monitoring detects respiratory depression early before oxygen desaturation; allows earlier intervention in sedation-related respiratory compromise',
'Only for intubated patients',
'Replaced by pulse oximetry',
'No safety benefit',
'B',
'Capnography in sedation: Principle: Exhaled CO2 monitoring reflects ventilation. Advantage: Detects hypoventilation before SpO2 drops (especially with supplemental O2). Waveform: Changes or absence indicates apnea/obstruction/disconnection. Evidence: Studies show capnography detects respiratory depression earlier, may reduce adverse events. Standard: Recommended for moderate and deep sedation by multiple societies. Complements, does not replace, pulse oximetry.',
'medium', 'application'),

('b0000014-0000-0000-0000-000000000014', 'a0000001-0000-0000-0000-000000000001',
'What is the mechanism of action of compression therapy in venous disease?',
'Simply covers the wound',
'Reduces venous hypertension by supporting venous return, decreases edema, improves tissue oxygenation, enhances fibrinolysis, and promotes ulcer healing',
'Prevents arterial flow',
'No physiologic effect',
'Works by warming the leg',
'B',
'Compression mechanism: Venous effects: External pressure reduces superficial vein diameter → improved flow velocity, reduced reflux, improved venous emptying. Tissue effects: Reduces edema (shifts fluid from interstitium), improves tissue oxygenation, decreases inflammatory markers. Fibrinolysis: Compression may enhance fibrinolytic activity. Result: Reduced venous hypertension at tissue level → healing environment created. Key: Adequate pressure (30-40 mmHg at ankle), sustained use, proper application.',
'medium', 'application'),

('b0000016-0000-0000-0000-000000000016', 'a0000001-0000-0000-0000-000000000001',
'What is post-operative urinary retention (POUR) and what are its risk factors?',
'Rare complication',
'Inability to void after surgery; risk factors include age, male sex, pelvic/anorectal surgery, spinal anesthesia, high fluid volumes, opioids, anticholinergic drugs',
'Only after urologic surgery',
'Resolves spontaneously always',
'Only affects women',
'B',
'Post-operative urinary retention: Definition: Inability to void within expected timeframe after surgery. Incidence: 5-70% depending on surgery type. Risk factors: Male gender, age >50, pelvic/anorectal/hernia surgery, spinal anesthesia, large fluid volumes, opioids, anticholinergics, history of urinary symptoms. Management: Catheterization if bladder distended (>400-500mL), may need alpha-blocker trial. Prevention: Minimize risk factors, early ambulation, prompt catheterization if distended. Usually transient.',
'easy', 'application');
